### ISSUE TITLE
add tab completeable chat replacements 

### ISSUE THREAD

**Issue by MiniDigger** [thelounge/thelounge#1025]
it would be nice if you would get a list in the settings where you can define custom commands that just send a message for you. 
to not confuse them with lounge commands we could use another prefix like '.' , eg '.bug'  should print 'please report bugs on the github issue tracker: link' 
we even could go all out and make it support arguments, eg '. bug MiniDigger' should print 'MiniDigger, please report bugs on the github issue tracker: link', we could define the arguments with simple placeholders like %0.

**Comment by Cldfire** [comment]
This sounds like something that should be implemented as a plugin when they are supported.

**Comment by MiniDigger** [comment]
Soon (tm)

**Comment by richrd** [comment]
Doesn't `thelounge-plugin-shortcuts` mostly take care of this feature?

**Comment by MiniDigger** [comment]
Totally.
