### ISSUE TITLE
[Request] log file with failed login attempts

### ISSUE THREAD

**Issue by notaduck** [thelounge/thelounge#1048]
It would be nice if we could get a log file where all failed and successful login attempts where shown.  
It would make it easier to locate where the intruder came from if the system gets compromised, and also make it easier to prevent it from happen, and also allowing us users to sue fail2ban or tools like that.

**Comment by bews** [comment]
It will be better to be able to exec any cmd you like when invalid password is entered. For example I prefer to send info to gitter instead of logging.

**Comment by notaduck** [comment]
That would also be nice. But in my opinion the best thing will be to do both, then you can use fail2ban to automaticly block the intrusion attempts, and still get it notifications through gitter.

**Comment by astorije** [comment]
I'm going to close this because we just merged #2247 which should provide this now.
