### ISSUE TITLE
Implement OTR end-to-end encryption

### ISSUE THREAD

**Issue by JocelynDelalande** [thelounge/thelounge#108]
From https://github.com/erming/shout/issues/464 :

> Just for the record, and to avoid spreading efforts, we are working with @astorije on a support of OTR over IRC to provide end-to-end encryption and contact authentication.
> 
> Our choice is to encrypt on shout server side, using https://github.com/arlolra/otr
> 
> We are thinking about the UI to make it neat and clear for end-user.
> 
> We will keep you posted and come up with a PR once the work will approach something mergeable.

Now reporting on that issue here, and targeting a merge into lounge.

**Comment by JocelynDelalande** [comment]
So, quick status.

I rebased on lounge and fixed some errors, "state of the art" is for now here : https://github.com/JocelynDelalande/lounge/tree/otr

Should almost work, but current shout master is not in a working state (at least for me), so have no time to debug it in order to check if basic OTR features that were working with shout are working with lounge.

Stay tuned

**Comment by JocelynDelalande** [comment]
@almet ok, i got the *otr* branch of https://github.com/JocelynDelalande/lounge/tree/otr working. Dare to test it @almet ? (issuing `/otr init` in a query with someone otr-enabled should get you into an OTR conversation, although, it's lacking UI for now).

Also, created a ticket that may interest you @almet , as you were offering help : https://github.com/astorije/shout/issues/16

**Comment by JocelynDelalande** [comment]
@socketubs I need time :-) 

Actually it just got a little harder, as lounge changed its underlying IRC library to irc-framework, see https://github.com/thelounge/lounge/commit/da425fefafb4efeca480723945c1787ec165bcde So… I'm going to need to do some rewrite first.

I'm afraid I'm not finding time for this soon :x

Happy to handover to you if you find time & motivation for this anyway @socketubs

**Comment by JacobEdelman** [comment]
(curious if anyone is looking at this still)

**Comment by astorije** [comment]
Hi @JacobEdelman, unfortunately, no one is at the moment.

I'm still hoping @JocelynDelalande, in an ultimate act of passion, would add this one feature for us :D
Or at least, push everything we got in a PR so other people can take it from here?

Pretty pleaaaase! :)

**Comment by Zarthus** [comment]
This research was done and will probably "eventually" see official standardization in IRCv3 at some point in the (optimistically) next couple of years: https://github.com/ircv3/ircv3-ideas/issues/29

It looks like it's already in kiwiirc, maybe it'll be part of irc-fw and we can borrow on it that way, but I haven't watched the subject with too much depth.

**Comment by xPaw** [comment]
I'm going to close this as we're unlikely to implement something like this in core. See the linked ircv3 issue if you want to discuss this.
