### ISSUE TITLE
Clicking somewhere outside of input/autocomplete still keeps the menu around

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge#1085]
*This will only be relevant when #787 gets merged as I don't expect it to fix this minor issue.*

If the autocomplete dropdown gets opened, and a right click is pressed on channel/network/user, the context menu opens but the autocomplete menu does not close.

**Comment by astorije** [comment]
@yashsriv, do you think you'd be able to take a look into that once your PR gets merged? It's not critical so don't try to fix it on your PR directly or that might delay the merging again, while your PR is essentially ready.

**Comment by richrd** [comment]
Is this actually a bug? I don't see it being much of a problem actually.

**Comment by xPaw** [comment]
I think the actual issue is that clicking somewhere outside of input/autocomplete still keeps the menu around.
