### ISSUE TITLE
Message search

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#109]
Would be a killer feature to have a log search (could be channel only, network only, or global).

**Comment by astorije** [comment]
This needs *a lot* of discussion and design... :-)
But definitely a great long-term goal!

**Comment by Dr-Horv** [comment]
Sounds like a great feature. Most IRC clients I have used have had implementation on channel-basis and have some grep-like interface. Might not be suitable for a more GUI-focused interface like thelounge though.

**Comment by dgw** [comment]
Would it be bad to override Ctrl/Cmd+F? My habitual desktop client, Textual, searches in the current channel that way, though it is not as-you-type like the browser's built-in search would be.

**Comment by bnvk** [comment]
This would be an ideal feature component to have, and if implemented correctly would solve performance / stability issues like #110

IMHO, this should be done with an "[database abstraction layer](https://en.wikipedia.org/wiki/Database_abstraction_layer)" as peoples views, familiarity, needs, and use cases are always a bit different and having a good DBAL would be a really attractive feature of The Lounge. Of course, this adds a bit of complexity to engineering... so prolly just pick "one" to implement and do minimal abstracting, but at least think about it.

Some nice datastore options to consider:

- [LevelDB](http://leveldb.org)
- [SQLite](https://www.sqlite.org)
- [ElasticSearch](https://www.elastic.co)

Some nice features for this would be allowing a user to *choose* what types of messages get saved in the DB... some ideas:

- All messages and notifications
- Only messages
- Only messages by and mentioning a given "user" (ideally with some leading / trailing buffer)
- Only certain channels and/or networks
- Only when a user is "active" within some timeframe (20 mins, etc...)
- User action choosing to "save" one or more selected messages

**Comment by xPaw** [comment]
@bnvk We talked about it briefly on IRC, and indeed a lightweight option is required (by default, something like sqlite). Filtering would be left for plugins though, not base implementation.

**Comment by richrd** [comment]
Hi and many thanks to all the work you guys put in thelounge, especially 2.0. Loving it! :heart: 

I would love a find option, and currently I just bash the "Show older messages " button and hit Ctrl+F. That's fine for me but it doesn't work on mobile when the app is added to the desktop (no chrome menu to access).

I'm against a mandatory database (as I mentioned here https://github.com/thelounge/lounge/pull/506#issuecomment-250759696). 
I hope RAM storage could be kept as an option. Say for instance if I'm discussing some stuff under an NDA with a team mate (that has also signed the NDA). I wouldn't want any persistent records just to be safe.

**Comment by richrd** [comment]
Hi and many thanks for all the work you guys put in thelounge, especially 2.0. Loving it! :heart: 

I would love a find option, and currently I just bash the "Show older messages " button and hit Ctrl+F to find what I need. That's fine for me but it doesn't work on mobile when the app is added to the desktop (no chrome menu to access).

> On top of that, database logging would mean we can get rid of log files for users.
Wait wut, we have disk logging already? I never noticed that :frowning: Is this the case?

I'm against a mandatory disk or database logging feature (as I mentioned here https://github.com/thelounge/lounge/pull/506#issuecomment-250759696). Say for instance if I'm discussing some stuff under an NDA with a team mate (that has also signed the NDA ofc). I wouldn't want any persistent records just to be safe. So I hope RAM storage could be kept as an option.

Any thoughts on this?

PS. I fully support an option for persistent logs, but I'd really hope it'd be toggleable.

**Comment by MaxLeiter** [comment]
I agree with @richrd - anything regarding logs, saving to disk, etc should be optional.  

@richrd : Logging is a per-user setting. Each user gets a directory in` lounge-home-folder/logs/<user>`, and each network gets a sub-directory under that. In the network directory, every channel and PM conversation has a log file. 

Here's an example of #test on freenode.

> [2016-09-30 15:43:52] * lounge-user join
[2016-09-30 15:43:52] * undefined topic Welcome to freenode's test channel | Note: This is NOT #flood! Be nice, do NOT spam and do NOT paste senseless crap here. Try to be nice and helpful. Test and develop your bot in channel #botwar.
[2016-09-30 15:43:52] *  topic_set_by
[2016-09-30 15:43:52] * ChanServ mode +v lounge-user
[2016-09-30 15:43:56] <lounge-user> test

**Comment by richrd** [comment]
I just started playing with xPaw's prototype for the search feature
Here are some thoughts that were discussed in IRC:
- The default could be, that only the current channel is searched.
- If the user is in a network window, or checks a checkbox, the entire network is searched.
- There could also be an option to search across all channels in all networks.
- The search button/icon could be located in the header, on the left side of the context menu button.
- The button could either reveal the search field within the header, or alternatively open a dropdown that contains the search field.

Any thoughts on this? What do you think would be an MVP version of this feature?

**Comment by MiniDigger** [comment]
> What do you think would be an MVP version of this feature?  

Text field to search user names and messages, list view that displays x results.

improvements after that could be:
* scroll down to load more results
* filter search (like discord does it, from:<user>, has:<content-type>, before:<date>, in:<channel>)
* show context in search (like discord)
* jump to message (this is kinda hard as you would need, with the current way how things work, load all messages after the message you jumped to. before this is doable, we need to be able to also load more messages when scrolling down to not have all messages in DOM)

some more thoughts: 
* I would always scope search to one network
* I would definitely want a way to search in the whole network, with easy filtering of channels
* I think I would put a search button in the lower left corner, next to the other buttons that opens a menu, just like the quick join menu. I first thought about having it in the upper right corner, but we also have the filter for users there and it would be confusing to users

discord help page on search with nice screenshots: https://support.discordapp.com/hc/en-us/articles/115000468588

**Comment by richrd** [comment]
> Text field to search user names and messages, list view that displays x results.

Cool, I'll go for that. The fancy stuff can come later. One thing that would be great to have quite early is the jump to message feature, but as you said it's not really possible to do yet.

> filter search (like discord does it, from:, has:, before:, in:)
That would be ultimate! It's a major undertaking though to make it work correctly and to give it proper autocomplete features  :-P

> I think I would put a search button in the lower left corner, next to the other buttons that opens a menu, just like the quick join menu. I first thought about having it in the upper right corner, but we also have the filter for users there and it would be confusing to users

On mobile the top  right is the perfect place for it IMHO as it's not confusing, but admittedly on desktop it is a bit weird. Also having it in the sidebar feels unintuitive to me, as the search is related to messages in channels, not stuff in the sidebar. Another place might be in the channel context menu, but I'm not sure where the search field should be then. 

I guess tooltips, titles, and the placeholder text for the input field should make it clear enough what it does, where ever it is placed. 

Anyway, the discord look is a good guideline, as it is quite beautiful.

**Comment by vvug** [comment]
Hi! Any news here? I think being able to search the logs is a killer feature for a cloud-based client, it would be great to have it implemented in thelounge.

**Comment by probonopd** [comment]
I'd also be very interested in this, along with a possibility to download the whole backlog as a txt file.

**Comment by dgw** [comment]
@vvug @probonopd Being worked on in #3664.

**Comment by sha1sum** [comment]
@richrd @MiniDigger -- I believe that static search fields may be a stepping-stone implementation between where we are now (with no searching) and where you are discussing going with the all-text based search with advanced parameters added. I say this for a few reasons:

### The "pros" gained from this intermediate step

- The search term and the "in" fields could be easily populated
- The "from" can also be easily populated -- _bonus feature for later: clicking on a nick in a buffer and having a search context menu item_
- we can use a date **range** (like "last 30 days" or choosing a custom from and to), and it would not be difficult to pull messages within that range

### The "cons" avoided by going this route for the time being

- Avoiding what happens if you have multiple of a certain search field keys
- Avoiding what happens if someone uses conflicting fields (`before:2021/01/01 after:2021/01/23`)
- Avoiding parsing out what is and is not a keyed search field
- Running syntax checks for the fully-text searches (`has: link`, _oops_)
- Trying to autocomplete fully-text search with keyed fields such as these

Hopefully this makes sense and my feedback has been valuable to you.
