### ISSUE TITLE
Add .self class to your nickname in userlist

### ISSUE THREAD

**Issue by bews** [thelounge/thelounge#1101]
Will be nice for themes and custom css.

**Comment by dgw** [comment]
I don't know if I see a use case for this, but one's own lines in chat are already given `.self`, so…

**Comment by richrd** [comment]
Do we want to do this or not, any opinions? I wouldn't mind simply adding the class without any default styles.

**Comment by MaxLeiter** [comment]
I know it doesn't apply generally for themes, but you can currently use the `data-name` attribute for styling yourself.

**Comment by richrd** [comment]
Yep. As @MaxLeiter said it's possible to set styles on a  specific nick in the userlist with custom CSS. For example:

```
#chat .userlist .user[data-name="richrd"] {
    text-decoration: underline;
}
```
