### ISSUE TITLE
Unable to scroll if messages appear to fast in channel

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#1103]
Test case: twitch lobby with raw logs enabled.

Pressing page up scrolls up and then stickyscroll forces back to bottom.

**Comment by richrd** [comment]
Maybe it's related to the 30px threshold here: https://github.com/thelounge/thelounge/blob/master/client/js/libs/jquery/stickyscroll.js#L53

**Comment by xPaw** [comment]
I think this was fixed (or at least improved) some time ago.
