### ISSUE TITLE
Add OS fallback fonts so that emoji can render

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#1128]
On Windows 7 with default theme, emoji do not render.

**Comment by MiniDigger** [comment]
which browser? can't reproduce on chrome (just cleanly install win10, so no theme)

**Comment by xPaw** [comment]
Looks like Windows 7 doesn't have updated fonts to render all emoji, so I don't think we can do anything about it. Unless we suggest downloading a full emoji font (like EmojiOne) and adding a fallback to that.

**Comment by MaxLeiter** [comment]
Is this fixed now/still valid?

**Comment by richrd** [comment]
I know this is closed, but I have the same "issue" on Chromium on Kubuntu. Is there something I can do locally to fix that?

**Comment by McInkay** [comment]
What version are you on, @richrd ? I believe Ubuntu added colour emoji for 18.04. Not sure whether that works in kubuntu or not.

**Comment by richrd** [comment]
Thx! I'm on 17.10, I'll try and upgrade when I have time.

**Comment by richrd** [comment]
Yeah, makes sense not to try and fix it in core. After all they are just unicode characters, and the browser should handle it. I found this extension and it kind of works. However it doesn't detect all emojis and they end up being a bit misaligned. Maybe I'll just wait for official support. https://chrome.google.com/webstore/detail/chromoji-emoji-for-google/cahedbegdkagmcjfolhdlechbkeaieki/related

**Comment by McInkay** [comment]
Try this one as well. https://chrome.google.com/webstore/detail/emoji-swap-by-emojione/laaoconppkgneoeccdehhabfiojpekoa
