### ISSUE TITLE
AppVeyor produces some mocha output bug

### ISSUE THREAD

**Issue by PolarizedIons** [thelounge/thelounge#1134]
Example: https://ci.appveyor.com/project/astorije/lounge/build/2422

    435   > thelounge@2.2.2 test:mocha C:\projects\lounge
    436   > mocha
    437   
    438   The system cannot find the path specified.

**Comment by astorije** [comment]
I went back as far as 2 months ago and this output appears everywhere (also, this did not show up 4 months ago but `mocha` was not run either way). That's quite bad we never noticed this.

2 things to fix:

- Why can `mocha` not be found?
- Why would it not fail the build?!

**Comment by astorije** [comment]
FYI, I just emailed their support in case it's a known bug or something they know how to trivially fix.

**Comment by astorije** [comment]
@xPaw noticed the tests actually get reported in the `Tests` tab, so it might be nothing to worry about, just odd to see this though.

**Comment by IlyaFinkelshteyn** [comment]
Not an expert in mocha by any means, but after playing with the issue in RDP,  I think that `mocha.cmd` itself is being called OK, but it does not know what test files to use. I believe that you need to set something like `"test:mocha": "mocha test/**/*Test.js",` instead of `"test:mocha": "mocha",` [here](https://github.com/thelounge/lounge/blob/master/package.json#L23)

**Comment by IlyaFinkelshteyn** [comment]
Also build is not failed because `npm test` returns happy error code 0

**Comment by xPaw** [comment]
@IlyaFinkelshteyn 
> By default, mocha looks for the glob ./test/*.js

It works fine for me on Windows, by the way.

https://mochajs.org/#the-test-directory
https://mochajs.org/#mochaopts

**Comment by astorije** [comment]
> Are we even sure `The system cannot find the path specified.` is produced by mocha? It could be something unrelated.

Not sure, I've never seen that one before.

> I believe that you need to set something like `"test:mocha": "mocha test/**/*Test.js"`, instead of `"test:mocha": "mocha"`

That would be problematic as not all our test files end with `*Test.js`. In practice, we don't need that, tests run OK per @xPaw's observation, and that message started appearing between 2 and 4 months ago. I'm starting to suspect this does not even come from mocha like what @xPaw said.

**Comment by IlyaFinkelshteyn** [comment]
When I debugged it in my fork with [RDP ](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/) with command line last week, it was pretty clear that error is produced by mocha. And change I proposed fixed that locally. Just tried to do this in my fork with AppVeyor build and it [works](https://ci.appveyor.com/project/IlyaFinkelshteyn/lounge/build/9#L435). Interesting that `"test:mocha": "mocha test/**/*.js"` without `Test` did not work...

**Comment by astorije** [comment]
> And change I proposed fixed that locally. Just tried to do this in my fork with AppVeyor build and it works.

Not really, because only 2 test files are run. That would mean the issue comes from a file that is not a `*Test.js` file, at least that reduces the list...

**Comment by xPaw** [comment]
This doesn't happen anymore.
