### ISSUE TITLE
Channel restrictions

### ISSUE THREAD

**Issue by ThoreKr** [thelounge/thelounge#1192]
We currently have the need to be able to restrict the client to join only channels matching a certain pattern.
To make to configuration as individual, and usable for others, as possible support for regular expressions would be cool.
I already asked for it on freenode, but maybe this is the better place for such a discussion.

**Comment by xPaw** [comment]
Closing for the same reason the PR was closed:

> I'll close this as we all agree that doing this in the client is not the right place. Channel restrictions should be done on the IRC server.
