### ISSUE TITLE
Invite 1 user to another user into channel doesn't show which channel

### ISSUE THREAD

**Issue by McInkay** [thelounge/thelounge#1209]
When you get a notice about a user (who is not you) inviting another user (who is also not you) into a channel, it doesn't show you which channel it is.

```
19:11 sirocco.tx.us.synirc.net user1 invited user2 into the channel.
```

Related to #1207, but possibly not exactly the same.

**Comment by xPaw** [comment]
I believe this got fixed some time ago.
