### ISSUE TITLE
Split windows

### ISSUE THREAD

**Issue by fnutt** [thelounge/thelounge#1222]
mIRC, IRSSI etc. IRC clients let you split windows/views to see multiple channels at once. This makes it far easier to keep track of the activity in more than one channel, moderate chat in channels or just join the conversation in more than one channel at a time.

I have been informed there are Google Chrome plugins to split browser windows, and I know you can do this manualy by opening up TheLounge in multiple tabs and sort them on your screen. However, this rely on third party plugins and plugins specific to some browsers. It will also not work on tablets, phones etc.

I hope TheLounge community can implement split windows, where you can right click on a channel and choose to show it below or next to the other active channel. If it can support a grid of windows it would be even better.

![mdi](https://user-images.githubusercontent.com/11909212/27038165-73662ac0-4f8a-11e7-89fd-b06c2b9128d4.png)

![irssi-split-3](https://user-images.githubusercontent.com/11909212/27038189-895009e6-4f8a-11e7-9086-9d6aa7adc0c7.png)

**Comment by YaManicKill** [comment]
So yeah, I think this is a good suggestion, but I have 1 thing I need to check what would be the best way to make it clear which window is active, and therefore which window the user list applies to (or do we have a userlist shown per split window?)

**Comment by astorije** [comment]
This most likely is a massive undertaking of both the client and the server. I don't believe we will get to the bottom of this anytime soon, unfortunately.

Also, I could swear someone opened a similar ticket in the past but couldn't find it...

**Comment by christer88** [comment]
@YaManicKill I think having just one userlist is good IF we allow splitting up in more than two times. Could possibly add a border around the active channel?

**Comment by YaManicKill** [comment]
@astorije Actually, I don't think we will need many (if any) server edits. But maybe I'm being naive. Also I don't expect it'll be **too** difficult client side, but it'll still be a good chunk of work.

**Comment by xPaw** [comment]
Userlist is inside the channel container, however the input bar is not. If we implement simple splitting, the user list would be kept per channel. If the input bar stays global, message will go into active channel (according to the server).

**Comment by astorije** [comment]
In terms of UX, Atom's drag and drop + split at will in a grid fashion is very clever and intuitive. It took them a few attempts to get it as intuitive though, they tried a bunch of solutions.

I cannot wait for a per-channel message input, probably one of the highest things on my wishlist, so that you can start typing in a window and change channels without posting (Telegram supports picking up on a different device, and slack has a different icon when you left an unsent message, both very smart ideas).
Do you see a single input whose content change, or one input per split window? The former could be hard to differentiate in which channel you're posting, the latter a bit messier on the eye. Thoughts?

**Comment by YaManicKill** [comment]
> Do you see a single input whose content change, or one input per split window? The former could be hard to differentiate in which channel you're posting, the latter a bit messier on the eye. Thoughts?

A single one, it's not hard to differentiate, because we have the placeholder which says the channel name :-)

**Comment by MaxLeiter** [comment]
GroupMe handles this in an interesting way, maybe worth keeping in mind - it automatically shows multiple chats if the screen is large enough

**Comment by xPaw** [comment]
Closing as this is highly unlikely to be implemented. There would be a lot of effort to fix activeChannel/scroll and other stuff.

**Comment by philipp-rs** [comment]
> Closing as this is highly unlikely to be implemented. There would be a lot of effort to fix activeChannel/scroll and other stuff.

Please reconsider. I've been looking all over the place for a nice linux IRC client with this feature and apparently its way to hard.

Maybe you can go the route that Quassel took with their "chat monitor". They let you split the window in two tiles. One is the current channel and the other one is the "chat monitor" where all messages from a user specified list of channels get merged into one. They are then presented like `<channelname:username> message`

https://quassel-irc.org/files/images/snapshot13.preview.png
