### ISSUE TITLE
Lazily load autolink images/previews

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#1270]
Intersection Observer API can be used for this. https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

**Comment by bews** [comment]
Terrible idea, especially for mobile with unstable connection. I really hate such stuff (on twitter for example), because you can't even properly read loaded messages without connection. Also, you need to wait for each image to load, instead of loading them in background. Strong :-1: for this.

**Comment by richrd** [comment]
This seems to work most of the time in vue but after loading a lot of history previews seem to stop loading.
