### ISSUE TITLE
URL parser does not stop on apostrophe, valid in certain parts of link?

### ISSUE THREAD

**Issue by kode54** [thelounge/thelounge#1302]
The following link:

```
https://www.google.com's
```

Parses to include the 's in the link, which of course won't resolve.

**Comment by xPaw** [comment]
This is a URI.js issue, can you create it there? https://github.com/medialize/URI.js

**Comment by astorije** [comment]
@xPaw, do we want to add a test case (not enabled or merged for now) even though this is an issue on their side? It would still be nice to "monitor" this.

**Comment by kode54** [comment]
Hope this is enough.

medialize/URI.js#339

**Comment by kode54** [comment]
See? It's not an issue upstream, it's an issue with how you're using the library.

**Comment by xPaw** [comment]
We are using the library precisely how he suggests, but he wants us to do filtering on our side.

**Comment by astorije** [comment]
I think his answers were fair though, no?
If my (probably shitty) suggestion of checking TLDs is not possible, do we want to use `URI.findUri.trim` like he suggests, at least for apostrophe (and maybe others?)?

**Comment by xPaw** [comment]
Fixed on master.
