### ISSUE TITLE
SOCKS proxy support over corporate network

### ISSUE THREAD

**Issue by leopck** [thelounge/thelounge#1375]
ref (https://github.com/erming/shout/issues/690)

Currently I'm behind corporate firewall and I would like to run Lounge IRC and connect to an external IRC outside the network. Is it possible to connect Lounge IRC over a SOCK proxy to the external IRC?

**Comment by keryja** [comment]
The library used for connecting to IRC [supports socks proxies](https://github.com/kiwiirc/irc-framework/blob/master/src/transports/net.js#L85), extending the [Network model](https://github.com/thelounge/thelounge/blob/master/src/models/network.js#L109) should make (at least part of this) fairly easy to implement.

**Comment by michael-thayer-vb** [comment]
Follow-up to my ticket which was marked a duplicate.  I am assuming that for HTTP proxy support, reading the http_proxy variable and handling the connection through the proxy would be best done in [websocket.js](https://github.com/kiwiirc/irc-framework/blob/master/src/transports/websocket.js).  Could someone confirm or correct me?

**Comment by astorije** [comment]
@xPaw, do you know the answer to this question?

**Comment by xPaw** [comment]
We would just need to pass `socks` object into irc-fw network object:

https://github.com/kiwiirc/irc-framework/blob/101ff9ae9d42f1b183588fcd03d4d76086d20f6f/src/transports/net.js#L91-L94

**Comment by michael-thayer-vb** [comment]
HTTP proxies and socks proxies are two different beasts though, and need separate handling.

**Comment by xPaw** [comment]
Well irc-fw only supports SOCKS, so that's out of our direct control.

**Comment by michael-thayer-vb** [comment]
If irc-fw read and used the http_proxy and friends environment variables this should just work.  Talking to the developer.

**Comment by paride** [comment]
A SOCKS proxy should also be configurable for the prefetch functions, ideally using a separate setting. In this way it would be possible to prefetch via Tor, allowing for increased privacy. It is also important to proxy the DNS queries.

**Comment by MaxLeiter** [comment]
Thanks a lot, @Mstrodl! 🎉

**Comment by Mstrodl** [comment]
Woop! :tada:

**Comment by leopck** [comment]
Amazing work, thanks! @Mstrodl 🎉

**Comment by stevenengler** [comment]
Is this proxy used for everything network-related, or is the proxy bypassed for external downloads (media preview, prefetch, etc)? If it is bypassed, should the settings page have a note about this?

**Comment by brunnre8** [comment]
It only affects the irc connection, it's not a security feature
