### ISSUE TITLE
Avoid emitting multiple events to the server when collapsing/expanding channel previews 

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge#1377]
With #1366, we are sending an event on the server when clicking on the preview toggles to store the visibility there so it is preserved on page refresh.
When using `/collapse`/`/expand`, as many clicks as there are previews to collapse or expand are made to the server, causing spam there.

Improvements ideas were discussed on the original PR, but decided as non-blocking.

**Comment by xPaw** [comment]
I have implemented this in the vue branch as we have proper state access there: https://github.com/thelounge/thelounge/commit/edae28f2b250b28ff3d8f900379106d026e5e6d3

It will now send a list of messages to toggle previews on.
