### ISSUE TITLE
Clicking on the bar between messages and input field should focus input

### ISSUE THREAD

**Issue by Marlamin** [thelounge/thelounge#1408]
Just switched to The Lounge, loving it but noticed one little thing that my muscle memory seems to be triggering a lot. Clicking between the messages and the text input doesn't select the input while I feel it should. 

![image](https://user-images.githubusercontent.com/50212/29243668-d24f1570-7fa4-11e7-9898-62a7f6a082d1.png)

(xPaw told me to add this issue, blame him for all the confusion)

**Comment by xPaw** [comment]
This can be tweaked in themes. But since typing anywhere without even having focus in input is a thing now, this doesn't matter.
