### ISSUE TITLE
Focus input when typing into "nothing"

### ISSUE THREAD

**Issue by dgw** [thelounge/thelounge#1428]
Actions like clicking a link in the chat can put the focus outside the input, after which sending another message requires clicking the input box again.

One of the things I love about my desktop client (Textual) is that it will focus the input if I start typing but the focus is not in the input. Would it be practical for The Lounge to do this? Would it conflict at all with accessibility concerns surrounding screenreaders, keyboard shortcuts (existing or future/planned), etc.?

**Comment by astorije** [comment]
I like this a lot!

It would solve an accessibility issue (https://github.com/thelounge/lounge/issues/935) on top of the usability issue you mentioned. We could essentially remove that focus trap that prevents leaving the message input.

This would need to be available only if:

- Focus is currently not on any other input
- Key pressed is only a printable one (i.e. not on <kbd>Enter</kbd>, <kbd>Up/Down/Left/Right</kbd>, <kbd>Esc</kbd>, etc.)
- No modifiers are currently pressed, except <kbd>Shift</kbd>
- Others?

It could conflict with things mentioned in [this comment](https://github.com/thelounge/lounge/issues/935#issuecomment-280948162) however. One less-than-ideal solution for this could be to have an opt-out option in the settings so that this doesn't hijack screen readers.
I am interested in @cptvitamin's opinion though: I am convinced this proposal would be less horrific than what we have currently, but I'm curious of what unforeseen implications that might have and how to address them.

**Comment by xPaw** [comment]
I honestly do not like this idea at all. I have not see any other software do it this way either.

Doing this we're most likely going to break some key binds (e.g. screen readers), and maybe people will unintentionally send messages.

We would have to introduce a lot of checking (is in other input, is key bind, is in other window like help, etc, etc) for a minor feature, imo.

> Actions like clicking a link in the chat can put the focus outside the input, after which sending another message requires clicking the input box again.

The input is focused is lounge window/tab gets focus, so what you are describing should not happen.

**Comment by dgw** [comment]
> The input is focused is lounge window/tab gets focus, so what you are describing should not happen.

It happens when middle-clicking links to open in a background tab, for example.

> I have not see any other software do it this way either.

This isn't a good reason to make any decision, IMO. Just because "nobody else is doing it" doesn't mean it's not an improvement (and I provided an example of software in the same domain that does precisely this). I'm aware there are potential conflicts with screen readers, etc., but that's why @astorije is seeking accessibility input. The possibility of improving the situation in #935 can't be ignored, either.

> This would need to be available only if:
> […]
> * No modifiers are currently pressed, except <kbd>Shift</kbd>

Actually, one of my favorite side effects of this feature in Textual is that it makes copying text from the chat log and pasting it into the input really easy. <kbd>Cmd</kbd>+<kbd>V</kbd> pastes the clipboard into the input box, and focuses it. Most keyboard shortcuts should be ignored, though, yes.

It's likely obvious that I'm woefully ignorant of how complex it is to filter key input in The Lounge's codebase (or, for that matter, in Textual's…I just know how the feature behaves for the user), so if being that specific about it is a maintenance nightmare or something, I understand not wanting to do it.

Ultimately this issue came from using The Lounge almost constantly for a full day—the most I've used it "in one sitting" so far, if memory serves. This was the only frustration I encountered over those 12 hours. (OK, there were one or two other occasional things, but they've long-standing open issues already.) I admit, it's a nitpick, but I tried to type a message "into nothing" often enough in one day that it became worth requesting this.

**Comment by xPaw** [comment]
> It happens when middle-clicking links to open in a background tab, for example.

Good one. That specific case (and common I imagine) case can most likely be fixed.

> Just because "nobody else is doing it" doesn't mean it's not an improvement

There are certain expectations a user will have, and I imagine entering a message while there is no focus in the input is not one of them.

**Comment by astorije** [comment]
> I have not see any other software do it this way either.

Telegram (native app on macOS) has a mix of what we have and what this issue proposes (but much closer to this proposal than our solution), and it works really nicely. It's super intuitive and doesn't mess the focus nor user intent.
I'll try to identify what exactly differs between us, them, and this proposal.

Actually, Slack has this too, and I didn't even realize it until now even though I am using it <img src="http://www.reactiongifs.com/wp-content/uploads/2013/10/tim-and-eric-mind-blown.gif" width=50>
That's how intuitive the behavior is 😅 

> Doing this we're most likely going to break some key binds (e.g. screen readers)

The fact of the matter is: our trapping of the user's focus/<kbd>Tab</kbd> is horrific. I curse at him very often, I'm surprised I haven't removed it yet. And it's really bad for accessibility, as #935 explains (and that was one of the first comments @cptvitamin gave me lol).

I believe that once we remove that trap and constant unintentional re-focus, this will seem much more appealing and intuitive.

> Actually, one of my favorite side effects of this feature in Textual is that it makes copying text from the chat log and pasting it into the input really easy. Cmd+V pastes the clipboard into the input box, and focuses it.

That's a very good point, and yes, I do realize now that I am often doing this on both Telegram and Slack.

There will be edge cases to consider indeed, but if both Telegram and Slack can do it successfully, I don't see how we couldn't. It's not like it would be the first thing we do as well or better than Slack :D
Also, I note that neither of those allow for an opting-out option, that means they're kinda confident it's solid enough. If we notice a lot of edge-cases, nothing would prevent us to add a option in the accessibility section!

This is my proposal: the atrocious focus trap needs to go, there is no disagreeing on that :) Once this is done, let's take a quick stab at this and see how it feels. I'm confident we can easily know if it's a "yes definitely", "maybe with improvements", "no way" situation once we start actually playing with it. It's an interesting idea, potentially huge improvement, so let's give it a shot, I think :)
Thoughts?
