### ISSUE TITLE
CTCP responses go to network lobby but do not increment message counter

### ISSUE THREAD

**Issue by dgw** [thelounge/thelounge#1455]
I would expect CTCP replies to be placed in the active window, but if they are going to the network lobby they should at least increment the message counter. The current behavior is quite confusing (it looks like nothing has happened, or the other client ignored the request).

**Comment by dgw** [comment]
Hmm, this smells like Hacktoberfest/Up-For-Grabs material, now that I think about it.

**Comment by xPaw** [comment]
This was fixed by #2510
