### ISSUE TITLE
No autocomplete for nicks in direct messages

### ISSUE THREAD

**Issue by ssk2** [thelounge/thelounge#1459]
I can autocomplete a user's name in channels without problems but this functionality does not appear to exist for direct messages. This is desirable because occasionally my colleagues will only have notifications turned on for direct mentions of their name (whether in DM or in a channel).

**Comment by dgw** [comment]
:+1:

Could have sworn there was an issue open for this already, but I must have been thinking of #64, the opposite of this.

**Comment by xPaw** [comment]
I guess autocompletion list should contain exactly 2 names in queries, yours and the user you're talking to? Should be relatively simple to do.

**Comment by MaxLeiter** [comment]
I don't see a need to have your nick be completable

**Comment by dgw** [comment]
Need? Maybe not, but it wouldn't be the first client to do so.

**Comment by astorije** [comment]
I agree with @MaxLeiter
