### ISSUE TITLE
Channel history lost when using /rejoin (/cycle) command

### ISSUE THREAD

**Issue by dgw** [thelounge/thelounge#1484]
Channels are removed on `part` events, which has the effect of clearing the scrollback and moving the `rejoin`ed/`cycle`d channel to the end of the list due to The Lounge internal behavior. I wasn't able to counter that in #1449, and didn't feel it so necessary as to block merging the channel-cycling command itself.

But in the interest of taking ownership—since I made a bit of a "mess" by implementing a feature that doesn't quite work as one might expect—I think this can be improved with a bit more work. @YaManicKill suggested:

> We could add a command (or an extra bit to the part command) that will part a channel, but not hide it or remove history.

Since it appears The Lounge already effectively does this if the user is `KICK`ed, it's likely just a matter of adapting that code for use with `PART` somehow. It'll be a bit more involved, since the `KICK` code is merely reactive, but `PART` will have to block normal handling of the ensuing `PART` event received from the server that causes the channel to be removed—the `rejoin` command handler specifically avoids sending any events to the client, but they are sent anyway by the server component when the IRC network confirms the `PART`.

**Comment by xPaw** [comment]
This is fixed by sqlite.
