### ISSUE TITLE
Allow files serving in custom themes

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge#1537]
Themes can now be loaded from npm packages (#1266), kinda being our first public API. One improvement we could make is serving arbitrary files said packages provide. For example, 2 use cases: custom fonts and images (for `background-image` for example).

Adding a `files` property to the `package.json` file would probably be an easy way to do so, but this  addition to the API needs to be thought of carefully. In particular, we need to make sure developing a theme locally would still load the files correctly.

This issue is to discuss the design/API.

**Comment by xPaw** [comment]
@McInkay Isn't this implemented now?

**Comment by McInkay** [comment]
Yeah, technically you can throw any file into that API and we will serve it, but that will create malformed HTML as we'll try to import that as a stylesheet in the client.

So not exactly ideal :-P

It would be really quick to add a second api for adding static files, and just allow it to be pulled down by the client. I should be able to find some time tonight to do that.
