### ISSUE TITLE
On iOS, the user list does not seem to be scrollable

### ISSUE THREAD

**Issue by Gilles123** [thelounge/thelounge#1548]
When running 2.4.0 and the master build as of this writing, the users list does not seem to be scrollable on iOS for me. It tries to scroll the entire page. The channel list works fine. This is not an issue on Safari for Mac and only affects iOS, so I'm not sure what's going on here and my initial troubleshooting did not turn up an answer. I know it affects at least iOS 10 and 11, and I think it used to work with an older version of The Lounge, but I have not yet had time to check that.

**Comment by dgw** [comment]
Hmm, #1520 might have affected this?

(This is the issue I meant to comment on when I did on 1547… I should stop trying to GitHub on my phone. 😂)

**Comment by Gilles123** [comment]
I don’t think so, as that was only committed a week ago, and this issue existed at least in 2.4.0.

**Comment by xPaw** [comment]
Can you test if removing this line helps?

https://github.com/thelounge/lounge/blob/8f275c6a5554d7b7fe921174313bb9fc67148702/client/css/style.css#L1289

**Comment by Gilles123** [comment]
That was the first thing I tried and it didn't work. I just tried removing all instances of it from the css file, and THAT worked. I'll have to see if there's a way to keep it and not have it break things when I have a bit more time later today.

**Comment by Gilles123** [comment]
I've been testing various things for a few hours and haven't come up with anything that works while keeping any instance of that in the css file, and most of the solutions I was finding online for this are pretty hacky. All instances have to be removed for it to work at all, which of course means you lose momentum scrolling on mobile WebKit.

**Comment by MaxLeiter** [comment]
Can you try adding `$('.names').on('touchstart', function(event){});` to `client/lounge.js`?

**Comment by Gilles123** [comment]
Unfortunately doesn't seem to have any effect.

**Comment by Gilles123** [comment]
When I tested yesterday, it wasn’t working and now it is. I think I know what changed, but won’t be able to test until later today. I’ll follow up then.

**Comment by Gilles123** [comment]
After a bunch of testing, it turns out it's not your line that did it after all. It just starts working the second time you click a channel (i.e. a channel has to be selected first, switched to another one, and then come back). I don't know enough about what events get triggered when you do that to understand what's happening there.

**Comment by xPaw** [comment]
@Gilles123 Is it related to #1556?

**Comment by Gilles123** [comment]
Nope, it's unrelated. That's just a thing I noticed/was annoyed by while testing this, but it's a separate issue. What I know right now is that most recent comment.

**Comment by MaxLeiter** [comment]
Seems to be fixed for me on master

**Comment by MaxLeiter** [comment]
Never mind - wasn’t the first channel i opened

**Comment by xPaw** [comment]
@Gilles123 Were you able to figure this out?

**Comment by MaxLeiter** [comment]
Can confirm this is still a problem

**Comment by astorije** [comment]
Same here.
