### ISSUE TITLE
Install themes without server restart

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/thelounge#1612]
Would it be the end of the world to have `lounge start` open a command-prompt or something? Could show usage stats, active users, 🤷‍♂️ .

**Comment by dgw** [comment]
I suspect having `lounge start` open a command-prompt _by default_ would be unexpected, and might mess up any logging that administrators currently have set up for running The Lounge as a service unit.

What about dropping into a console for managing themes (and whatever else the package system ends up handling in the future) with a separate command? Maybe `lounge cli`, `lounge console`, `lounge admin`, …?

With a release or two of advance notice, though, `lounge start` could be deprecated for use in init scripts/service units without a `--daemon` flag or similar to suppress the console behavior. But I think adding a new subcommand would be simpler and less problematic for existing administrators.

**Comment by YaManicKill** [comment]
> Install themes without server restart

Yes, this is a good thing to do, it shouldn't be too difficult, we are already watching some things so it should just be a case of watching the directory that packages are installed in and updating things

> Would it be the end of the world to have lounge start open a command-prompt or something? 

I'm not sure this is a great solution. I think having a way to drop into a lounge console might be an idea, but seems entirely unnecessary.

**Comment by xPaw** [comment]
This was done by #3579
