### ISSUE TITLE
Await existing link expander promises

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#1614]
Link previewer calls `fetch` for every url in every message, it may happen that one url is posted multiple times (in different channels), and before the response arrives for the first request, there is no real need to fire another request, something like
```
if (requests[link]) {
    requests[link].then()
}
```

https://github.com/thelounge/lounge/blob/f18d0193837cac829c26cfc90361752de91f9164/src/plugins/irc-events/link.js#L38-L46

**Comment by tkulpa** [comment]
Hey i have question, where information about currently active requests that are not yet fullfiled should be stored in app? Is client object valid option?

**Comment by xPaw** [comment]
It can be an object within the same file.
