### ISSUE TITLE
Previews do not work with unicode URLs 

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/thelounge#1644]
If someone posts an image hosted on a unicode domain, for example https://taytay.ıoı.com/pic.gif, no preview loads.

**Comment by xPaw** [comment]
Some work in this branch: https://github.com/thelounge/lounge/tree/xpaw/fix-unicode-urls

I also created https://github.com/request/request/issues/2797

**Comment by MiniDigger** [comment]
another url to test against:
https://😻🍕.ws/👡🐼🍻 (link shortener, redirects to google.com)
preview shows this error: 
Server returned an error: Invalid URI "https:///%F0%9F%98%BB%F0%9F%8D%95.ws/%F0%9F%91%A1%F0%9F%90%BC%F0%9F%8D%BB"
