### ISSUE TITLE
Fold channel list

### ISSUE THREAD

**Issue by rgarrigue** [thelounge/thelounge#17]
All's in the title, this is a feature request.

I can fold user list but not the left hand channel list. If I split my screen in half with something else, half of lounge is about channel names and message time. So I'ld like a button to fold it like user list.

**Comment by astorije** [comment]
If this becomes a thing (I personally would not use that feature), it would need some research/experiment on UX.
For example, the way we fold the user list is not very nice UX-wise, and the channel list appears at a different level (the user list is "nested" in the channel itself while the channel list is not, if that makes sense).

**Comment by McInkay** [comment]
It's not often you get to close a 2 year old issue. Good job @xPaw
