### ISSUE TITLE
Rename this repository to "thelounge"

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge#1735]
In an effort to remove inconsistencies and confusion, we are normalizing all usages of "lounge" into "thelounge" (we have both at the moment). This repo should be renamed as well.

All URLs, clones, remotes, etc. will still be working indefinitely as GitHub keeps redirects for everything 👌

**Comment by dgw** [comment]
I suggested this, and I am 110% behind the idea. Good on GitHub for keeping redirects forever, lol.

**Comment by YaManicKill** [comment]
I mean, yeah, if we are standardising around "thelounge" then we should change the repo. I'm still not a fan of using "thelounge" for things rather than "lounge", but it makes sense based on what we are doing.

**Comment by xPaw** [comment]
Done!
