### ISSUE TITLE
Update website URL for 3.0

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/thelounge#1762]
for tracking purposes

Places link exists:

- [x] GitHub org description
- [x] Repo description/link
- [ ] Rename website repo
- [x] Website repo description
- [x] [Twitter share button on the website](https://github.com/thelounge/thelounge.github.io/blob/f3092e1a8a7a22935995be1ed5085df128b507d3/_layouts/default.html#L49)
- [x] [References in the code](https://github.com/thelounge/lounge/search?utf8=%E2%9C%93&q=https%3A%2F%2Fthelounge.github.io&type=)
  - https://github.com/thelounge/lounge/pull/1980

**Comment by astorije** [comment]
[defaults](https://github.com/thelounge/lounge/blob/c9da29f2fcaffc01de779c8217a4a50f52cef28a/defaults/config.js#L328)

**Comment by xPaw** [comment]
Gonna close this as it was pretty much done. Website repo can't be renamed as that breaks redirects.
