### ISSUE TITLE
"Special channel" windows should not have date/unread markers

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge#1812]
See:

<img width="1018" alt="screen shot 2017-12-08 at 00 14 15" src="https://user-images.githubusercontent.com/113730/33752170-21487030-dbae-11e7-922c-e07c1c7d6531.png">
<img width="1020" alt="screen shot 2017-12-08 at 00 14 29" src="https://user-images.githubusercontent.com/113730/33752171-2153e3fc-dbae-11e7-999a-46035aea2cd0.png">
<img width="1022" alt="screen shot 2017-12-08 at 00 15 10" src="https://user-images.githubusercontent.com/113730/33752172-21643590-dbae-11e7-9fd9-d6a5958c81f2.png">

These make little sense there I think.
I wanted to do the 30-second solution of simply hiding in CSS, but I don't know if that's the right thing to do or if it should be handled by the server instead, which seems cleaner to me. @xPaw, thoughts?

**Comment by MaxLeiter** [comment]
What if you /list on multiple days?

**Comment by astorije** [comment]
Right now it clears the whole page (as it should IMO) so really the markers are useless right now. I think it's a niche use case to open a channel list on different days to compare, so I'm not too worried.

**Comment by xPaw** [comment]
I think this was fixed at some point?

**Comment by astorije** [comment]
Fixed in https://github.com/thelounge/thelounge/pull/1849 indeed, good catch!
