### ISSUE TITLE
Should we remove `thelounge config` CLI command?

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge#1819]
As I'm rewriting [the docs](https://thelounge.github.io/docs/getting_started/usage.html), I'm more and more questioning the usefulness of `thelounge config`.
In fact, I have just realized that I was already wondering about that exactly a year ago at https://github.com/thelounge/lounge/issues/419#issuecomment-267252569 😅

I'm just not sure it is useful to have that. On one hand, I understand that typing `thelounge config` is faster than finding the config path and then typing `vim path/to/config`. On the other hand, I personally do not know other software that offer that (I guess nginx is an example of a software that runs like ours).

But maybe I'm misguided and just don't use something because it's not useful for me (I'm deploying using Ansible so I never edit the config file myself on my server) and it's useful for others, so rather than just kill it, I'm opening this issue to let people give their experience :)

Thanks!

**Comment by MaxLeiter** [comment]
a lot of people using Lounge may not know how to use vim/vi/know to open config in an editor. I see no problem with `lounge config` staying

**Comment by astorije** [comment]
That's the thing though, [we don't do anything else than opening `vi` for you](https://github.com/thelounge/lounge/blob/a8fb892873721a9ac8eb138533c999180f333313/src/command-line/config.js#L21) (unless you set `$EDITOR` yourself, but I'd argue that if you know about that, you are not going to use `thelounge config`).
So if you don't know how to use `vi`/`vim`, well `thelounge config` is not of any help 😕

Just to be clear, I'm not pushing to remove it at this point, I'm just trying to make sure that we keep or remove it for the right reasons. At the moment, removing code we have to support and simplifying the user documentation makes for a strong case IMO :)

(Marking as v3 to point out that whatever we do, we won't do it before next major version)

**Comment by xPaw** [comment]
Yeah I never saw a use for this command, nor have I seen other software implement anything similar.

We print full config path when the server starts, so that's pretty much enough.

**Comment by astorije** [comment]
Alright then, opened a PR at #2196, let's see how this goes.

**Comment by astorije** [comment]
@xPaw, I feel like `thelounge edit <user>` should meet the same fate. What do you think?
