### ISSUE TITLE
Preprocess css files

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#1869]
We need to add compilation to our css files.

Features we absolutely need:
- [x] Minification
- [x] Autoprefixer
- [x] Resolving `@import` (both local files and npm modules)
   - So we can split css into smaller files
   - So we can import modules like `normalize` and `primer-tooltips`
 
I tried this with `postcss` in `webpack`, but it's a pain in the ass to get clean CSS back out (that isn't JS).

**Comment by astorije** [comment]
Also that would solve the fact that `npm run watch` doesn't rebuild on CSS changes.

**Comment by astorije** [comment]
Actually, sometimes it watches, sometimes it does not. Not sure why, I didn't look really hard...

**Comment by Kinsmir** [comment]
@astorije `--watch` depends on the filesystem for tracking changes, in some environments (virtual machines for example) this isn't returned properly.

For that reason you have the option to poll for file changes with `--watch --watch-poll`, this periodically checks (every 1000ms) for changes within your files.

**Comment by astorije** [comment]
@Kinsmir, I don't have a particular setup, just macOS (though some would argue it's a particular setup lol). Also, it's not consistently _not_ working, it usually works fine, except when it doesn't. And only for CSS.
That being said, I didn't look too well, and just restart my `npm run watch` when it does. I'll pay more attention next time.

**Comment by xPaw** [comment]
This was done by #3449
