### ISSUE TITLE
Autocomplete opens past the right boundary of the screen

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge#1890]
<img src=https://user-images.githubusercontent.com/113730/34323710-bb52c7ee-e823-11e7-9f41-24edc0e0d12e.gif width=400>

Before someone mentions it, note that this is not the same issue that causes the dropdown to expand too high on mobile. Or differently put, both issues will have different solutions.
For this one specifically, the autocomplete dropdown needs to be bound to the right side of the screen, just like the context menu.

**Comment by xPaw** [comment]
I think this should be reported to the textcomplete library.

**Comment by MaxLeiter** [comment]
https://github.com/yuku-t/textcomplete/issues/132

**Comment by xPaw** [comment]
PR: https://github.com/yuku-t/textcomplete/pull/140
