### ISSUE TITLE
Status messages radio button selection needs to be wrapped in <fieldset>

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#1909]
And have a `<legend>` element for screen readers. We also probably want to hide margin/border of the fieldset though.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset

**Comment by astorije** [comment]
Why do we need fieldset? I thought radios were already accessible as they were, though could use ARIA properties

**Comment by xPaw** [comment]
Looks like we can get away with `role=group` but fieldset should be safer/easier.

https://www.w3.org/WAI/tutorials/forms/grouping/
