### ISSUE TITLE
CLI does not output anything on invalid commands

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge#1967]
When typing an invalid option, the CLI outputs ``error: unknown option `--xyz'`` with exit status of 1, but on invalid commands, it doesn't output anything and exits with status of 0.

It tripped me when I was testing https://github.com/thelounge/lounge/pull/1963 as I was typing `thelounge help` multiple times in a row before realizing it's actually `thelounge --help` :grin:

At the very least, print something like ``error: unknown command `xyz'`` to match invalid options.
Alternatively, it's rather nice when an output suggests similar results, like `isntall` could suggest `did you mean "install" instead?`.

**Comment by Jay2k1** [comment]
It might be a good idea to have it spit out the usage screen, as --help would.

I just ran into the same problem. I ran `thelounge update`, didn't get any output, wasn't sure if it actually did anything (you know, if linux tools don't produce any output, it's usually a sign for "it worked") and then tried `thelounge upgrade` just to be sure.
