### ISSUE TITLE
Socket.io still fires event after disconnect

### ISSUE THREAD

**Issue by crosma** [thelounge/thelounge#1995]
https://github.com/socketio/socket.io/issues/3095

> <+xPaw> get socketio-wildcard, in disconnected event set disconnected[socketid] = true, with wildcard, add "*" event, check against disconnected array

Use this to log when disconnected sockets receive events and stop them. Also log if socketId ever existed or if it's somehow new.

**Comment by MaxLeiter** [comment]
Possibly related:
```
/root/lounge/src/client.js:465
        this.attachedClients[socketId].openChannel = target.chan.id;
                                                   ^

TypeError: Cannot set property 'openChannel' of undefined
    at Client.open (/root/lounge/src/client.js:465:45)
    at Socket.<anonymous> (/root/lounge/src/server.js:353:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at /root/lounge/node_modules/socket.io/lib/socket.js:513:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by xPaw** [comment]
You can most likely get more debug info without modifying the code, run lounge with `env DEBUG="*"`, that should give a lot of socket.io info leading to the crash.

**Comment by xPaw** [comment]
Does this still happen? Maybe this issue was related to `uws` module which we explicitly disabled.
