### ISSUE TITLE
Auto-Away feature not very accessible

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/thelounge#1996]
So I thought it would be great if TL could automatically set myself away when I detach all clients. Turns out someone already had the idea and it was already implemented in #775. It didn't work for me though.

I found out that [this block](https://github.com/thelounge/lounge/blob/b2eebfa65edd53d27fcb76e8004b6dd9bef452db/src/client.js#L548-L556) is never being executed because client.awayMessage is an empty string. Apparently it has to be set in the user config. Setting myself away on a network just changes the network's awayMessage item, not the one of the user itself.

So, if I understand correctly: **in order to get the auto away feature working, the user (or their admin) has to edit the user.json file and set an away message** - that is not very intuitive.

I suggest adding an input field for the `user.awayMessage` to the settings, so users could set their away message (without needing access to their config file) and by doing so, enable or disable the auto away feature.
It could have a placeholder text like "Set a message to enable auto away" or "leave empty to disable auto away" or something.

This way,

- it becomes clear that TL has an auto-away feature
- every user, even those without access to their user config file, is able to enable/disable that feature
- the feature works out of the box

**Comment by fuzzy76** [comment]
Just came here after searching both documentation and settings for a mention of this. Can confirm. :)

**Comment by MaxLeiter** [comment]
I actually think https://github.com/thelounge/thelounge/blob/b2eebfa65edd53d27fcb76e8004b6dd9bef452db/src/client.js#L548-L556 (block you reference) is a bug.

Sending an empty AWAY is really what `/back` does (it means the user is back), but only if the user has set themselves away in the first place.
I -think- it should be `if (client.awayMessage && _.size(client.attachedClients) > 0) {` but I may be wrong.

@xPaw?

**Comment by pcolmer** [comment]
Not only is having to edit the user.json file not intuitive but @McInkay said in https://github.com/thelounge/thelounge/issues/646#issuecomment-402517139 that "people have no reason to be editing the files directly anymore, we have a way for the user to edit everything in that file". That doesn't seem to be the case …

Apart from anything else, it still isn't clear to me if editing those files (as, say, an admin) causes TL to reload them straight away or if TL has to be stopped and started, which is *very* disruptive just for a small thing like the auto-away message.

**Comment by xPaw** [comment]
This will be trivial to add to client settings, since we have client settings syncing now.

I'll do this after the client has been ported to Vue.

**Comment by Jay2k1** [comment]
> Apart from anything else, it still isn't clear to me if editing those files (as, say, an admin) causes TL to reload them straight away or if TL has to be stopped and started, which is very disruptive just for a small thing like the auto-away message.

I believe it's not automatically reloaded. The way I solved it is rename `user.json` to `user.json.foo` and back. TL notices that you "remove" a config, and also that you "add" one afterwards, and acts accordingly.

**Comment by hijxf** [comment]
Any update on this?

**Comment by McInkay** [comment]
> Any update on this?

Nope.

**Comment by xPaw** [comment]
As promised: #3549
