### ISSUE TITLE
Away reply raws 305/306 not shown in the client

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/thelounge#1997]
Currently, TL doesn't show 'you are now marked as being away' and 'you are no longer marked as being away' messages, so when you set yourself away/back, you do not get any feedback about that. This used to be different. @xPaw pointed out that this is "maybe because irc-fw handles them now, and we handle it via away event".

I've looked, and irc-fw emits 'away' and 'back' upon receiving these raws.

I've had a look into `src/plugins/irc-events/away.js` and found out that it doesn't send a message `if (!user || user.away === away)`. There is no user though, because user is defined as 
 `'chan.findUser(data.nick)`, however data.nick in this event is now the server, i.e. `tolkien.freenode.net`.

Also, where there's an on away event, there probably should be an on back event too.

**Comment by xPaw** [comment]
@MaxLeiter want to look into this?

**Comment by Jay2k1** [comment]
Since I'm taking this over, I'll sum up a bit to keep track.

Things regarding away handling that needs fixing:
- raw 306: setting yourself /away doesn't display feedback (irc-fw emits `away`)
- raw 305: setting yourself /back doesn't display feedback (irc-fw emits `back`)
- raw 301: PRIVMSG someone who is away doesn't display feedback (irc-fw emits nothing, see kiwiirc/irc-framework#150)
- away and back templates are currently only useful for away-notify (and 301 if it wasn't broken) but not for 305/306
- away and back message types probably expect user or nick and need being looked at
