### ISSUE TITLE
Scroll channel list to place joined/switched-to buffer in view

### ISSUE THREAD

**Issue by dgw** [thelounge/thelounge#2062]
When navigating the channel list with <kbd>Ctrl</kbd>-<kbd>↑</kbd> or <kbd>Ctrl</kbd>-<kbd>↓</kbd>, or joining a new channel (either by command or by the server forcing it), I believe the channel list should scroll up or down until that channel is in view. Not to center it, but just so it's the first/last item visible depending on whether it was hidden above or below the current list viewport.

I don't believe this is a duplicate issue, but apologies if I missed a similar issue while searching.

**Comment by xPaw** [comment]
This is done for the userlist in #1842, so similar approach can be done for this.

**Comment by xPaw** [comment]
This can actually be achieved easily by calling `scrollIntoView(false)` on the active channel. @dgw do you want to do this?

**Comment by dgw** [comment]
Sure, assign to me and I should have a chance to poke at this/test later this week.
