### ISSUE TITLE
Channel was being treated as a private message

### ISSUE THREAD

**Issue by Wetrain** [thelounge/thelounge#2103]
We run an internal instance of thelounge at work.

I left a channel but thelounge then started notifying me of messages from the channel as a private chat?

I could not /leave or /join the channel again.

I had to disconnect from the IRC server and reconnect in order for it to stop notifying me of every message in the channel.

has this ever been reported before?

**Comment by xPaw** [comment]
What Lounge version? I imagine this bug was fixed in 2.7.1.

**Comment by Wetrain** [comment]
I'm currently running 2.7.1

**Comment by xPaw** [comment]
If you can give us repro steps, then it could be possible to look further into. Otherwise right now we can't do much about this.

**Comment by Wetrain** [comment]
@xPaw This doesn't seem to be occurring again however, so this issue could have been down to the server being updated to 2.7.1. Please feel free to close and i will reopen if i see this again with more detailed information :)
