### ISSUE TITLE
Networks settings

### ISSUE THREAD

**Issue by Haarolean** [thelounge/thelounge#2125]
Hi,

it looks like that's not possible to edit network settings after adding one.
That becomes a problem in case you need to change the password, for example. 
Also "disconnecting" from a network results in removing the network from the list with tons of channels and PMs.

Correct me if I'm wrong, but I haven't found network edit buttons or any other related stuff.

**Comment by dgw** [comment]
This is a duplicate of #179, which addresses the need to edit existing networks, and (though there's probably an issue for it) #2114, which implements disconnecting and reconnecting networks without removing them.

**Comment by Haarolean** [comment]
Yeah, indeed, thank you. Didn't find that issue via search.
