### ISSUE TITLE
Better README image

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/thelounge#2129]
We need a nice, aesthetically pleasing way to demonstrate features. The current screenshot is pretty bad.

Features that I think should be shown:

- Previews
- Emojis (not necessarily auto-complete, just showing support)
- Responsivenes(...? Two images?)
- Colored nicks (in messages and on sidebar)
- One connected network and one disconnected network
- Channels and PMs

**Comment by astorije** [comment]
I know it's asking a lot, but can you think of a way we can generate those easily going forward? It could be a script, and/or a dummy SQLite file that we load/adapt every time we want to showcase a new screenshot, etc.

**Comment by MaxLeiter** [comment]
That would probably be ideal, however, I'm not sure how feasible it is. I guess you could setup a fake user and logs like @xPaw did for Electron (in regards to making a user). Definitely possible, not sure if worth the effort.

**Comment by astorije** [comment]
I think once SQLite stuff is merged, effort will be minimal, and could probably serve as a test case or something.

**Comment by xPaw** [comment]
@MaxLeiter Want to make a new screenshot?

**Comment by xPaw** [comment]
Uploading a pic here so I can use a link in readme

![](https://user-images.githubusercontent.com/613331/44947980-3b2f2f00-ae1e-11e8-9bd9-9e1aff5cd7e1.png)
