### ISSUE TITLE
Channel treated as a private chat

### ISSUE THREAD

**Issue by Wetrain** [thelounge/thelounge#2141]
This issue seems to have reappeared for me again.

Running V2.7.1

Yesterday i left a channel and thelounge now treats this as a private chat and it pinging me with every message from every user.

I can not leave the chat or join/leave the channel again.

![screenshot from 2018-03-02 09-21-29](https://user-images.githubusercontent.com/4598620/36892022-61bdb88e-1dfb-11e8-96d0-9c4980784de3.png)

#herebeagroupchat is actually a channel, but as you can see here it is treated as a private chat.

The only solution is disconnect from the server and reconnect

**Comment by xPaw** [comment]
What network are you on? Is there anything special about it (e.g. can it possibly send you PRIVMSG after leaving it?)

**Comment by Wetrain** [comment]
@xPaw sorry yes i should have reopened!

I'm not sure about the server configuration as i do not run it, what settings on the server could cause this to happen?

**Comment by xPaw** [comment]
> I'm not sure about the server configuration as i do not run it, what settings on the server could cause this to happen?

That's what I'm asking. What network do you see this problem on?

**Comment by xPaw** [comment]
@Wetrain I was able to reproduce this in 2.7.1 public mode, but not on master in private mode.

What version and mode are you running in?

**Comment by Wetrain** [comment]
@xPaw it's an internal IRC at work, not a public network.
