### ISSUE TITLE
Compact sidebar CSS customization produces odd result now

### ISSUE THREAD

**Issue by kode54** [thelounge/thelounge#2151]
When using the wiki's listed Compact sidebar code with 3.0.0-pre.2, the result is that server names and the first item under them are indented, but the rest of the list is not indented.

This exact piece of the ruleset is the apparent cause:

```
#sidebar .chan {
	padding: 5px 15px;
}
```
![channels_padding](https://user-images.githubusercontent.com/796316/36957705-16f24148-1feb-11e8-9442-f18dfa6cffd2.png)

**Comment by McInkay** [comment]
We don't officially support the css customisation, but maybe someone else in the community will be able to help. It'll be because of the new collapse button, which you can fix by increasing the right padding on the line you mentioned, that should move the other channels further left.

**Comment by astorije** [comment]
Note that the wiki is editable by the community, so feel free to make changes if you manage to find a fix!
