### ISSUE TITLE
Leaving a channel goes to an empty page

### ISSUE THREAD

**Issue by realies** [thelounge/thelounge#2174]
It seems no channel gets selected after leaving a channel and an empty page is presented instead. Currently the flex refactor is the main suspect, although #2173 seems related, TBI.

**Comment by dgw** [comment]
This appears to be working properly on d164882.

**Comment by realies** [comment]
Indeed, was testing against `589d7a9`. False alarm.

**Comment by astorije** [comment]
Yeah, I noticed we broke this on `master` and fixed it shortly after.
