### ISSUE TITLE
Synchronization bug on mobile safari: Notification variable not found

### ISSUE THREAD

**Issue by zachbr** [thelounge/thelounge#2191]
The Lounge is running from source (commit 38b8cdb).
ReferenceError: Can't find variable: Notification

After enabling client sync in mobile safari I am no longer able to use the client. I assume this is some issue related to mobile safari not supporting notifications. So the client tries to sync that setting, can't find it, and causes a problem. But that's just my own inference.

![](https://i.imgur.com/wP1id0M.png)

**Comment by creesch** [comment]
Can you use the client in something else than mobile safari?

**Comment by zachbr** [comment]
I do not experience this issue on desktop web browsers only on iOS browsers.

The same happens in Chrome for iOS and Firefox for iOS (I believe these all use the same core as Safari, or at least used to). I can login and use the client just fine until I enable synchronization and then refresh the page.

**Comment by creesch** [comment]
Alright, I think I found the issue and your initial reasoning is probably right. Going to fix that now.
