### ISSUE TITLE
Firefox: "TypeError: 'block' member of ScrollIntoViewOptions 'nearest' is not a valid value for enumeration ScrollLogicalPosition."

### ISSUE THREAD

**Issue by creesch** [thelounge/thelounge#2193]
This happens on current master (38b8cdbb5ea281fb9e3c4e976e7b71bb25d19107) with Firefox, chrome doesn't have an issue. 

```
"TypeError: 'block' member of ScrollIntoViewOptions 'nearest' is not a valid value for enumeration ScrollLogicalPosition."
```

Specifically on
```
utils.js:67:1
```

**Comment by dgw** [comment]
@xPaw Assign me, since I'm the one that broke it.

**Comment by dgw** [comment]
As of 4ee4d015 + Firefox 60, I can see no error when switching channels in TL.

**Comment by xPaw** [comment]
Looks like 'block' got implemented FF54, and last ESR is 60.
