### ISSUE TITLE
Alt+Up/Down should not cycle through channels of a collapsed network

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge#2200]

**Comment by xPaw** [comment]
We should also make [ctrl or shift]+alt+up/down jump between servers directly.

**Comment by astorije** [comment]
@xPaw, open a dedicated issue for that?

**Comment by dgw** [comment]
Aren't the shortcuts Ctrl-Up/Down?

**Comment by McInkay** [comment]
@dgw It has changed for 3.0

**Comment by benharri** [comment]
I'd expect the shift modifier to skip to a channel with unread messages rather than naively moving servers. 

Any thoughts on that?

**Comment by dgw** [comment]
Whatever the modifier, something needs to jump servers. I don't care if it's Shift or Ctrl. The unused one can jump to next unread, maybe?
