### ISSUE TITLE
Cycle through networks with a keyboard shortcut

### ISSUE THREAD

**Issue by dgw** [thelounge/thelounge#2203]
Could be <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>↑</kbd> (or <kbd>↓</kbd>), as the existing channel-cycling shortcuts are <kbd>Ctrl</kbd>-<kbd>↑</kbd> (or <kbd>↓</kbd>).

<kbd>Alt</kbd> could be used instead of <kbd>Shift</kbd> but for some reason I have a nagging feeling that <kbd>Ctrl</kbd>-<kbd>Alt</kbd>- shortcuts are more likely to be defined at the system level (at least on Windows) and conflict.

Follow-on to #2200.

**Comment by McInkay** [comment]
> as the existing channel-cycling shortcuts are Ctrl-↑ (or ↓).

Psst, that's changed. It's not Alt-↑ (or ↓)

**Comment by dgw** [comment]
Well that'll wreak hell on my muscle memory for a good few weeks after release.

On Mac keyboards, then, I think <kbd>Alt</kbd>-<kbd>Shift</kbd> is easier to input than <kbd>Cmd</kbd>-<kbd>Alt</kbd>. But I don't have any source to back that up, just personal opinion based on contorting my fingers around a MacBook Pro keyboard.

**Comment by McInkay** [comment]
I'd be fine with either <kbd>Alt</kbd>-<kbd>Shift</kbd> or <kbd>Ctrl</kbd>-<kbd>Alt</kbd>.
