### ISSUE TITLE
Thelounge character error

### ISSUE THREAD

**Issue by ircalem** [thelounge/thelounge#2204]
How can I change the character of Thelounge (iso-8859-9)

http://www.imgim.com/8763incit3310126.png

**Comment by xPaw** [comment]
Duplicate of #1094

**Comment by ircalem** [comment]
he could not solve the problem,

iso-8859-9 character i have to do .

**Comment by xPaw** [comment]
Yes the problem is not solved, hence why it's a duplicate issue.

**Comment by ircalem** [comment]
how can you get rid of this problem ?
