### ISSUE TITLE
Send button doesn't close nick suggestions

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/thelounge#2209]
![ezgif com-resize](https://user-images.githubusercontent.com/2070503/37334921-8aef46d6-26ad-11e8-9099-a4c3cfc4e50f.gif)

**Comment by ESWAT** [comment]
Taking a look at this. The textcomplete package doesn’t have a public method for hiding the dropdown manually so will make a PR to add that to textcomplete and a PR to fix this issue in the-lounge.
