### ISSUE TITLE
Unread count should exclude status messages when condensed

### ISSUE THREAD

**Issue by hho** [thelounge/thelounge#2211]
The unread count in the badge next to a channel currently includes status messages, like users joining and leaving and nick changes.

This is irritating, especially when those status messages are condensed via the settings.

It would be better to only count messages and actions in that case.

**Comment by xPaw** [comment]
Are you sure about that? Only messages marked "increases unread" or highlights increase the unread counter. Join/part/quit and others do not do either of these things.

I also just tested it, and it did not increase it for either join or quit.

**Comment by dgw** [comment]
On 2.7.1, I see the unread count including only actual messages/CTCP actions (`/me`). Joins, parts, quits, nick changes, mode changes, etc. do not increase the unread count.

**Comment by hho** [comment]
Oh. I'll upgrade to 2.7.1 and see if I still get the issue.

Sorry for the noise.
