### ISSUE TITLE
Select lobby when collapsing a network

### ISSUE THREAD

**Issue by McInkay** [thelounge/thelounge#2224]
When you are on a channel, and you collapse a network, it should probably select the lobby of that network.

**Comment by Jay2k1** [comment]
Hmm. Should it?

I'm not sure. I mean, you're not selecting (as in clicking) the lobby, you're just hiding the channels. Should that change the buffer you're viewing? And what about if you're on a channel of network A and collapse network B? I often like to make screenshots of my Lounge for people in some IRC channel (call it promoting), and I collapse most of my networks in that case, so I don't have to photoshop the screenshot later. I wouldn't like it to switch to the lobby when doing so...

**Comment by McInkay** [comment]
>  And what about if you're on a channel of network A and collapse network B? 

Yup, it shouldn't change you to network B if you are on network A, good catch. It should only do it if you are on a channel for network B.

I do think that having you selected a channel that you can't see in the sidebar is confusing. But that's a very good point.

**Comment by xPaw** [comment]
I'm not sure what we achieve by switching to lobby whenever a network is collapsed. Is there some use case I am missing?

**Comment by McInkay** [comment]
My point is that it's confusing, imo, to collapse a network and still see the channel if it isn't in the sidebar anymore. Same reason that we don't want Alt+Up to go to collapsed channels.

**Comment by astorije** [comment]
I'm playing with your branch and I think it's rather intuitive. I agree that being on a channel that was part of a collapse is odd. For example, when Alt+Up/Down is fixed, switching channels will completely move to another network.
