### ISSUE TITLE
mathjax support?

### ISSUE THREAD

**Issue by pbzweihander** [thelounge/thelounge#2226]
Can thelounge have mathjax support like glowing bear?

**Comment by McInkay** [comment]
That's probably not something we'd put into core, but feel free to speak up if you disagree @thelounge/maintainers 

Might be better in a plugin. Not sure exactly what this would need API wise.

**Comment by pbzweihander** [comment]
Oh, I agree that it should be in form of plugin, not core API. I'll close this issue.

**Comment by McInkay** [comment]
Feel free to open an issue for plugin APIs that you would need if yo uwant to build this yourself, or chat to us in #thelounge on Freenode if you want to chat about it.

**Comment by astorije** [comment]
(I know this belongs to a dedicated plugin-related issue: I think it would be nice to make the message parsing pluggable, as that would allow for things like all sorts of parsing like MathJax or Markdown, and we could dog-food it by giving it our own parsing for links, channels, nicks, etc.)
