### ISSUE TITLE
Fail2ban invalid password

### ISSUE THREAD

**Issue by McGriddle** [thelounge/thelounge#2227]
I have a host with nginx running on it that proxies to various other backend services. Some of these services will respond with a 401 when an invalid password is used. This is easy enough to catch via fail2ban using nginx logs on the host.

I've noticed that when I try a bad password with thelounge, there is nothing in the nginx access or error logs that I could add to fail2ban. Is there any way I could change either via the lounge or nginx?

Here is my nginx location for thelounge
```
location /irc/ {
        proxy_pass http://<backend_ip>:9000/;
        proxy_http_version 1.1;
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Forwarded-For $remote_addr;
 
        # by default nginx times out connections in one minute
        proxy_read_timeout 1d;
     }
```

I do understand that having fail2ban on the machine I'm trying to protect is the ideal scenario because it could potentially check for thelounge logs locally. Sadly that isn't possible in my case.

**Comment by xPaw** [comment]
You don't see anything in logs because authentication happens over websockets.

**Comment by astorije** [comment]
I don't have enough experience with logging of other systems so I'm not going to be able to make a suggestion as to how to implement it, but I think it would be nice to have auth-related logging like this.

I'd be thrilled to have fail2ban rules for The Lounge somewhere.

**Comment by dgw** [comment]
@astorije Actually I think this is more or less a duplicate of #1048, not a new feature request.

**Comment by astorije** [comment]
Ah, good eye @dgw, thanks!
@McGriddle, I'm going to close this issue, feel free to subscribe to #1048 and/or #2247 to get updates.
