### ISSUE TITLE
Binding to ipv6 address is not working

### ISSUE THREAD

**Issue by karnauskas** [thelounge/thelounge#2232]
I wanted to connect to irc server which have both ipv4 and ipv6 addresses. But I found that binding to ipv6 address is not working.

The workaround I found: add `family: 6` to tls.connect in irc-framework library.

**Comment by xPaw** [comment]
Just wondering, does it work without specifying `family` when you use a IPv6 address for the server directly (without dns)?

**Comment by karnauskas** [comment]
I think it would fail because tls cert don't have that IP address in their SAN. Can't test that atm.

**Comment by xPaw** [comment]
Either way I think this needs to be fixed in irc-framework directly to specify family based on the bind address. 

Do you want to make a PR over there?

**Comment by karnauskas** [comment]
Here it is https://github.com/kiwiirc/irc-framework/pull/141.

**Comment by xPaw** [comment]
Gonna close this as it's more of a irc-fw issue.
