### ISSUE TITLE
Scroll jumping in browsers that do not support scrollIntoViewOptions

### ISSUE THREAD

**Issue by williamboman** [thelounge/thelounge#2233]
I'm running latest master + 2207, 2206, 2195, 2114

**Comment by xPaw** [comment]
That's an extensive list of PRs. Can you please narrow it down where the problem happens?

**Comment by williamboman** [comment]
Ah, yeah it scrolls to the currently active channel, on page load as well as when joining a channel. I can debug this more later on if you want and find the offending commit

![s](https://user-images.githubusercontent.com/6705160/37452842-0deacf72-2836-11e8-849b-0c6b57522cd1.gif)

**Comment by xPaw** [comment]
What browser are you using?

cc @dgw

**Comment by williamboman** [comment]
I primarily use TL on iOS Safari so I noticed it there first. Screen recording is macOS Safari. Can't repro in Chrome.

**Comment by dgw** [comment]
This report was the last straw. Safari and Edge are just too flaky, and I don't want to do browser-detection hijinks. Revert proposed.

**Comment by kode54** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

Neither IE/Edge nor Safari support the entire object method of passing parameters. They only support scroll the object to the top of the view, period. Lovely.

**Comment by williamboman** [comment]
<img src="https://user-images.githubusercontent.com/6705160/37552890-c31273b8-29bd-11e8-8be2-c48cd737b5e6.jpeg" width="250">

@kode54 🤷🏼‍♂️

**Comment by dgw** [comment]
@kode54 Indeed. Apparently Safari, at least, also has awful fallback behavior when a page tries to use arguments that it doesn't understand. One would think ignoring the function call and printing an error to the developer console the logical fallback when passed arguments it doesn't understand. But no, it has to treat the object as `true` and scroll the element to the top of the container. (FWIW `false` will scroll the element to the bottom of the container. But an object is never falsy.) \</rant>

I'm going to test a couple polyfills, and/or try writing a generic scroll function that will be good enough for the user and channel lists (which are the parts of TL that need this). Next week-ish.

**Comment by kode54** [comment]
I love this question and actual useful reply, from 2012:

https://stackoverflow.com/questions/9445842/does-scrollintoview-work-in-all-browsers

Supported, yes. User experience, bad. Has it changed much since then? Nope.

**Comment by xPaw** [comment]
Related issue: #2193

**Comment by xPaw** [comment]
I believe this was fixed.

@williamboman reopen if you can still repro.
