### ISSUE TITLE
Show channel name in list when joined successfully

### ISSUE THREAD

**Issue by birkof** [thelounge/thelounge#2245]
I hope this issue has not been discussed before, but would be great to display channel name in list only   if you join successfully.

**Comment by dgw** [comment]
I poked through the code on my phone and it looks like the join event is emitted to the client after receiving it from IRC (so after the server confirms it), but I could me misreading stuff on this tiny screen.

Are you using a git version, a 3.0 prerelease, 2.7.1, or something older?

**Comment by xPaw** [comment]
The channel is created instantly because you can also join it while you are disconnected (e.g. from connect window). If these channels were invisible until joined in server it would be pretty poor experience.

**Comment by xPaw** [comment]
The server is aware of channel states now, and in the Vue branch that state is synced to the client, so there will be a visual difference when the channel is parted.
