### ISSUE TITLE
Channel list empty on refresh

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/thelounge#2249]
Should probably re-fetch `/list`

**Comment by astorije** [comment]
I confirm it's empty after page refresh. Instead of re-fetching, we should not be losing its content though, no?

**Comment by MaxLeiter** [comment]
@astorije: I agree we shouldn't lose content in the first place. I think reloading the list is a separate,  solid idea

**Comment by astorije** [comment]
I'm confused, what is a separate idea?

**Comment by MaxLeiter** [comment]
To refresh the list.

The bug is the channel is blank. The fix is don’t have it be blank (just show what was there before)

The new idea is to refresh list

**Comment by astorije** [comment]
Wait, I'm even more confused now lol. Isn't this issue about the bug that displays a blank page on reload?

**Comment by MaxLeiter** [comment]
Yes... the bug is the page is blank. As of now, the proper functionality is to show what was there before. (If the bug didn’t exist)

I’m also proposing the list should be reloaded instead of displaying what was present when the command was sent.

**Comment by astorije** [comment]
I'm not sure it should do that. An entire `/list` on page refresh is pretty heavy, but more importantly I think consistency across page refresh is better. If we want to add a "Refresh" button within the list page, that would probably be a better option.
