### ISSUE TITLE
Mobile keyboard opens on channel switch

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/thelounge#2257]
1. Have TL open on android and have the keyboard visible, e.g. by sending a message or just tapping into input box
2. Press your phone's back button to close the keyboard
3. switch to another channel

**Expected behavior:** Keyboard stays closed
**Actual behavior:** Keyboard opens

When in step 2, you tap into empty space in the channel instead, that will also hide the keyboard, but in this case, switching channels will not bring up the keyboard, so that's fine. 

I was told #2215 is responsible for this bug.

**Comment by xPaw** [comment]
> I was told #2215 is responsible for this bug.

It's not because I can remember this behaviour going months back.

I don't know why that happens because there's no focusing happening on touch devices (focus function is no-op).

**Comment by MiniDigger** [comment]
If you focus something else (just clicking into chat) it closes the keyboard and doesn't reopen on channel switch.
