### ISSUE TITLE
Sidebar needs better visual cue for active channel

### ISSUE THREAD

**Issue by andyross** [thelounge/thelounge#2260]
The sidebar is a bland list of channels names displayed as light gray text on a dark gray background.  The only thing that tells you which channel you're currently reading is the fact that its name is white, which isn't very notable.

Fundamentally the sidebar is acting as a vertical "tab bar" here, so IMHO it should look more like one and highlight the active channel in a much more visible way.

I prototyped this with a quick style hack, and despite a gltch with the display of the close icon, I like it so much that I'm going to keep this as-is.  It would be nice if a more pleasing presentation was done in the software:

    #sidebar .active { background: black; }

**Comment by xPaw** [comment]
Fixed in pre7.
