### ISSUE TITLE
Being kicked isn't very intuitive

### ISSUE THREAD

**Issue by lol768** [thelounge/thelounge#2266]
Being kicked isn't very intuitive, the input field doesn't disable and the kick message for yourself is collapsed by default. Additionally, issuing `/join` to rejoin doesn't work, since the channel name isn't assumed from the currently open buffer.

I'd suggest kick messages for yourself should display by default and perhaps the input field should be disabled if you are not in the channel

**Comment by lol768** [comment]
cc @mbax

**Comment by xPaw** [comment]
Messages that affect the user are no longer collapsed, so that should at least help. #2268

**Comment by astorije** [comment]
@lol768, @xPaw, enough to close this issue and mark it as v3?

**Comment by MaxLeiter** [comment]
@astorije: I would say 
> Additionally, issuing /join to rejoin doesn't work, since the channel name isn't assumed from the currently open buffer.

is reason enough to elave it open

**Comment by astorije** [comment]
Fair enough!

**Comment by lol768** [comment]
My bad for not splitting it into two tickets!

**Comment by xPaw** [comment]
I'll consider this fixed. There's a PR to make `/join` assume current channel (which isn't directly related to kicks anyway).
