### ISSUE TITLE
installing with yarn does not install yarn locally... and `thelounge install` does not handle stderr from the yarn process

### ISSUE THREAD

**Issue by benharri** [thelounge/thelounge#2301]
* *Node version:* 6.13.1
* *Browser version:* firefox 59
* *Device, operating system:* ubuntu 16.04
* *The Lounge version:*  v3pre3

---

I installed thelounge with yarn: `yarn global add thelounge@next`. Somewhere along the line, the `yarn` executable (used for `thelounge install`) does not get installed locally. 

Additionally, the stderr from `thelounge install` is not returned, leaving just `Failed to install` and an exit code of 1.

**Comment by xPaw** [comment]
We probably should fallback to executing global `yarn` if the locally installed one doesn't exist.

**Comment by benharri** [comment]
Yeah that's a good idea. 

AFAICT, yarn installs the dependencies at one level, skipping duplicates for the node_modules of each installed package and installing those at the top level. This means we can't depend on the yarn executable to be inside thelounge's node_modules.

**Comment by xPaw** [comment]
You are right about that. However `thelounge/node_modules/.bin/yarn` does exist, which is symlinked to the javascript file.

**Comment by benharri** [comment]
I'm not seeing any symlinks to yarn on linux (ubuntu 16.04) in `thelounge/node_modules`

Just: `ansi-styles/  chalk/  supports-color/`

**Comment by astorije** [comment]
Fixed by #2303.

**Comment by xPaw** [comment]
It isn't fixed.

**Comment by astorije** [comment]
Woops, my bad!
