### ISSUE TITLE
blocking/delays on multiuser instance

### ISSUE THREAD

**Issue by cadsu** [thelounge/thelounge#2304]
Using thelounge@`2.7.1` from npm with `Node.js 9.9.0` in public mode on Debian 9 x64 stretch updated to latest.

When there are more than ~20 users connected simultaneously on the same thelounge instance, it starts delaying processing new requests (new clients), like something is blocking in there. 
Firstly i was using Cloudflare -> Nginx -> thelounge and thought it might be issue of misconfiguration of first ones, but lately I tried Cloudflare -> thelounge directly and also tried accessing the instance directly via clearnet, which gave same results. It waits undetermined time interval until accepts connections, some just timeout with 504 error. Once i restart the instance, the problem disappears temporarily but comes back with increasing load and users.
When this happens my CPU doesn't get load of even 1%, as well as RAM is not loaded in full.
Right now, this is what is happening: 

root@localhost:~# free -h
              total        used        free      shared  buff/cache   available
Mem:           996M        170M        496M        9.0M        329M        665M
Swap:          511M          0B        511M

CPU load average: 0.11 0.03 0.01

Is thelounge supposed to be used by 1-2 users only and was not designed for multiuser scenario ?

**Comment by xPaw** [comment]
The Lounge definitely and easily supports over 20 users. Last time someone had a similar issue was a problem with their firewall.

It's hard to suggest any solution here, you'll have to do some debugging on your own. https://nodejs.org/en/docs/inspector/

**Comment by astorije** [comment]
I'll close this issue for now. I concur with @xPaw, but feel free to provide more details and we'll happily re-open if there appears to be a bug on our end.
