### ISSUE TITLE
New Install with Yarn, command not found

### ISSUE THREAD

**Issue by whiteazn** [thelounge/thelounge#2306]
* *Node version:* 9.9.0
* *Browser version:* Chrome 65
* *Device, operating system:* Ubuntu 16.04.4 LTS
* *The Lounge version:* 2.7.1

---

I had just installed nvm, installed node 9.9.0 (aliased it to default).  

I then installed thelounge and everything seems to work.  But then I try to start thelounge, and it says command not found.

```
~$ nvm --version
0.33.8
~$ yarn --version
1.5.1
~$ node -v
v9.9.0
~$ nvm ls
->       v9.9.0
default -> v9.9.0
node -> stable (-> v9.9.0) (default)
stable -> 9.9 (-> v9.9.0) (default)
iojs -> N/A (default)
lts/* -> lts/carbon (-> N/A)
lts/argon -> v4.8.7 (-> N/A)
lts/boron -> v6.13.1 (-> N/A)
lts/carbon -> v8.10.0 (-> N/A)

~$ yarn global add thelounge
yarn global v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "thelounge@2.7.1" with binaries:
      - lounge
      - thelounge
Done in 20.67s.
~$ thelounge start
-bash: thelounge: command not found
```
I try to run with the old command
```
~$ lounge start
-bash: lounge: command not found
```

Should I just try to install with npm?  (I was able to install a separate unrelated package with npm just fine)

Edit:  I forgot to mention, I did add the yarn bin directory to my $PATH
```
~$ echo $PATH
/home/<USER>/.yarn/bin:/home/<USER>/.nvm/versions/node/v9.9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
~$ thelounge --help
-bash: thelounge: command not found
```

**Comment by xPaw** [comment]
Does your PATH match `yarn global bin` output?

**Comment by whiteazn** [comment]
yes

```
~$ yarn global bin
/home/<USER>/.yarn/bin

~$ echo $PATH
/home/<USER>/.yarn/bin:/home [....]
```

**Comment by xPaw** [comment]
Did you check if that folder contains `thelounge` executable symlink?

I just tried it on my machine and it worked just fine. I added `export="${PATH}:$(yarn global bin)"` and then restarted by session.

**Comment by whiteazn** [comment]
yeah, it had links for for several files, but saw the 2 files (lounge and thelounge, both pointing to .config/yarn/global/node_modules/thelounge/index.js).  

I just uninstalled, reinstalled, then relogged back in a couple times, and it seems to have worked.

Though now, it only has the 2 symlink files for thelounge/lounge (the other symlinks are gone?  shrug)

thanks (and sorry for the thread)

**Comment by xPaw** [comment]
> Though now, it only has the 2 symlink files for thelounge/lounge (the other symlinks are gone? shrug)

What do you mean? On 2.7.x there are supposed to be 2 binary names symlinked `thelounge` and `lounge`. When 3.0 is released, `lounge` will be removed.

**Comment by whiteazn** [comment]
yeah, earlier when i first installed, the bin folder had 8 symlinks.  2 of them were for thelounge (thelounge and lounge), and 6 others (don't recall the exact names though, 1 was rc, can't remember the others).

After I reinstalled, now there is 2 binaries.
