### ISSUE TITLE
Changing your nickname resets the unread markers in all channels of that network

### ISSUE THREAD

**Issue by MiniDigger** [thelounge/thelounge#2324]
The number next to the channel is still accurate, but the marker is right behind the nick change msg and not before that actual last unread message.

**Comment by xPaw** [comment]
My guess is that this is happening due to `self` being `true` in message sent to each channel.

**Comment by xPaw** [comment]
I have a branch that should fix this: https://github.com/thelounge/thelounge/compare/xpaw/fix-2324

Needs testing.
