### ISSUE TITLE
Join button when joining channel on existing server doesn't work

### ISSUE THREAD

**Issue by Gilles123** [thelounge/thelounge#2329]
* *Node version:* 8.11.1 LTS
* *Browser version:* Safari 11.1
* *Device, operating system:* Mac OS 11.13.4
* *The Lounge version:* 3.0.0-pre.5

---
When clicking the + on the sidebar on an existing server, entering a channel name, and clicking Join, nothing happens and the channel is not joined. This seems to be the case regardless of browser. astorije on IRC said they were able to reproduce this on master.

**Comment by 0xE02B7** [comment]
Got the same problem:

OS: Ubuntu 16.04 LTS // 4.4.0-119-generic
Node:  v8.9.4
Chromium: 65.0.3325.181 (official build) Arch Linux (64-Bit)
TheLounge: v3.0.0-pre.5

Updated via "npm install -g thelounge@next" and afterwards nstalled sqlite3:
cd /usr/lib/node_modules/thelounge/
npm install sqlite3 --save

I can connect to a new Freenode server and then open the new channel, but I am not able to connect to multiple channel via one Freenode server.

**Comment by xPaw** [comment]
@0xE02B7 You can use `/join` command.

**Comment by astorije** [comment]
It should be pretty easy to fix if someone wants to give it a shot.
