### ISSUE TITLE
 Packages/plugins should be able to specify their version compatibility

### ISSUE THREAD

**Issue by creesch** [thelounge/thelounge#2333]
Issue made after a discussion on irc.

Currently packages get loaded at all times. But there are situations where some packages might only work on older versions or in some cases will no longer work in newer versions of the lounge. 

Ideally packages get to define what versions of the lounge they are expected to work against, the most obvious route of implementation a package field using semver. 

- https://semver.org/
- https://docs.npmjs.com/misc/semver

**Comment by McInkay** [comment]
Couple thoughts on this to add:

1. What should we do by default when a user tries to install a version of a package that doesn't support the version of lounge they are on? Fail, or succeed with an error?
2. If we fail by default, we should add an override for users if they want (they know a package or theme definitely supports this version, the package maintainer just specified an upper limit and hasn't updated it)
3. Should we do any fancy stuff with installing the newest version of the plugin that supports this version of lounge if they user doesn't specify a version?

**Comment by creesch** [comment]
My initial instinct is to allow it to install with an error and then refuse to load it. However if people are allowed to ignore the version then `<plugin> <version> is not compatible with the lounge <version>. Continue with installation Y/N?` seems like a good alternative. 

Also whenever the lounge starts with incompatible packages loading it probably should output this to the command line and possible in the case of front-end packages display warnings on the about/help page. 

Regarding the third point... commandline plugin installation should just use the latest stable version I guess? I mean installation probably uses yarn/npm so you could probably just support usage of `@` if people insist on using a different plugin version.

**Comment by McInkay** [comment]
> My initial instinct is to allow it to install with an error and then refuse to load it.

Hmm, I was thinking not installing at all, installing but not loading seems odd.

> However if people are allowed to ignore the version then <plugin> <version> is not compatible with the lounge <version>. Continue with installation Y/N? seems like a good alternative.

I'm thinking as a flag, to allow for unattended install.

> Also whenever the lounge starts with incompatible packages loading it probably should output this to the command line and possible in the case of front-end packages display warnings on the about/help page.

Yeah, sounds good

> Regarding the third point... commandline plugin installation should just use the latest stable version I guess? 

Yeah, that's what I was thinking. Trying to go back and install the last version that supports this version of the lounge automatically feels messy and complicated. I just wanted to bring this up for discussion.

> I mean installation probably uses yarn/npm so you could probably just support usage of @ if people insist on using a different plugin version.

We already support this, it was added in #2161 my question was in addition to this, if the user doesn't specify a specific version, should we do anything if the latest doesn't support their version of the lounge or leave it to them?

**Comment by creesch** [comment]
A flag that specifically needs to be set is probably better yeah.

If `@` already is supported I don't think anything more is needed as working out versions seems like a lot of effort for something that people really ought to pay attention to anyway.
