### ISSUE TITLE
Add keyboard shortcuts to toggle server/user list visibility

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#2345]
With these menus being fixed in 3.0 it would be nice to have keyboards bindings to toggle them.

**Comment by richrd** [comment]
I could happily grab this one. The simplest solution is adding an `accesskey` attribute to the buttons.

**Comment by dgw** [comment]
The Lounge uses Mousetrap (a JS library), never `accesskey`. (In fact, this issue is the sole mention of "accesskey" anywhere in the repo.) See [client/js/keybinds.js](https://github.com/thelounge/thelounge/blob/master/client/js/keybinds.js), which holds most of the keybind definitions.

**Comment by richrd** [comment]
Hmm, ok! Should a new mousetrap binding be added then with the same code as here: https://github.com/thelounge/thelounge/blob/master/client/js/lounge.js#L46

My intuition would be that the accesskey would be the simplest solution, as it requires no extra code anywhere, and it automatically always runs the same action that clicking the button would run (no duplicate code etc).

**Comment by richrd** [comment]
Which shortcuts do we want to go with?

**Comment by myself248** [comment]
Using the same shortcuts as other chat systems is awfully nice for users. Slack uses Ctrl-. to show/hide the right-side pane, but doesn't seem to have a way to show/hide the left side. That's so obnoxious someone wrote a Chrome extension to add such a feature, and they bind it to ctrl-s. 

Mattermost seems to have copied many of Slack's shortcuts for navigation, but not show/hide panes. If TheLounge is gaining more keyboard shortcuts, these are some nice established customs to aim for compatibility with:

https://slack.com/help/articles/201374536-Slack-keyboard-shortcuts
https://docs.mattermost.com/help/messaging/keyboard-shortcuts.html
https://chrome.google.com/webstore/detail/slack-toggle-sidebar/falbhdlejfolflphlfnkkpdmialebkdl
