### ISSUE TITLE
VCS-friendly user configuration files

### ISSUE THREAD

**Issue by williamboman** [thelounge/thelounge#2350]
I keep my configuration files in git which quickly becomes quite awkward due to the nature of some properties, most notably `sessions`. One way to solve this particular issue would be to store properties of such nature in separate file(s),  thoughts?

**Comment by MiniDigger** [comment]
could use partial commits I guess, bu thats a hassle too.

**Comment by poncki** [comment]
@xPaw sessions are part of runtime. Keeping sessions with configuration is a design error and has one particular drawback: you cannot .gitignore sessions only (and other dynamic, runtime files) without ignoring configuration...

**Comment by xPaw** [comment]
I disagree. User files were not designed to be "configuration" like the server configuration, rather it's data storage.

**Comment by xPaw** [comment]
Feel free to make a PR with proposed changes then. I still disagree that this is a design error. Do you also put your other software's data in git, like your browser?

**Comment by poncki** [comment]
Sorry, but no. I'm no longer interested in your software. Thx.

**Comment by williamboman** [comment]
![image](https://user-images.githubusercontent.com/6705160/38694335-a7f5a3c6-3e89-11e8-88fb-2a74a6b5b750.gif)

**Comment by williamboman** [comment]
> I disagree. User files were not designed to be "configuration" like the server configuration, rather it's data storage.

Ok, I can buy that.
