### ISSUE TITLE
Inconsistent handling of punctuation at end of URLs

### ISSUE THREAD

**Issue by dgw** [thelounge/thelounge#2351]
As brought up in the comments for #2343, the URL parser includes plenty of different punctuation characters at the end of a URL. It rejects `!`, `?`, `.`, `,`, `:`, `;`, and other common sentence- or phrase-enders, as well as every paired character I tested (`{}`, `[]`, `<>`, `()`, `'`, `"`, `` ` ``). But that leaves plenty of punctuation that _is_ accepted at the end of a URL, including things that perhaps shouldn't be. In particular: `*`, `@`, `$`, `|`, `\`, `~` (and others, I'm just tired of typing).

I'm not sure if this is something The Lounge should fix, or if I need to bring this upstream to a third-party library, but the inconsistency does bother me. It seems like either all trailing punctuation should be accepted, or none should (with few exceptions like `-`, `+`, & `=`), but not this hit-or-miss hodgepodge of stuff.

To be clear, I'm testing on The Lounge 2.7.1. I don't believe the Node version or server OS affects this (but I can fetch those details from my server if needed).

**Comment by xPaw** [comment]
Related: #1302

**Comment by xPaw** [comment]
Please test master version. The library has changed and I added tests for this behaviour: https://github.com/thelounge/thelounge/commit/19cce592c82c815a0493dfcc598b4f5575847699#diff-ae6d7fbc9de5e19faaeac523a355a6fcR175

**Comment by dgw** [comment]
As of a6ed4f3, all of the example characters I gave that were accepted at the end of a URL but probably shouldn't be, still are.

**Comment by xPaw** [comment]
Honestly I wouldn't consider this a bug.

Looking at linkify-it's test suite, they already covered punctuation, and I would trust them on this.
