### ISSUE TITLE
Allow showing passwords in password fields

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#2360]
Mostly relevant on edit network page.

Trivial demo: http://demo.itsolutionstuff.com/demo/demo-bootstrap-show-hidetoggle-password-input-field-using-bootstrap-show-passwordjs-pluginexample.html

**Comment by c-ciobanu** [comment]
Hey, i want to contribute with this project, can i take this task?

**Comment by xPaw** [comment]
Yes.
