### ISSUE TITLE
2.7.1 TypeError: d(...).off is not a function 

### ISSUE THREAD

**Issue by KlaasT** [thelounge/thelounge#2372]
The current version 2.7.1 won't load in Firefox 59.

> TypeError: d(...).off is not a function 

> 
> Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: ;undefined.
> lounge:1
> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: (function(){function e(t,n,r){function s....
> lounge:1
> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element.
> lounge
> TypeError: d(...).off is not a function[Learn More]
> autocompletion.js:18:2
> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element.
> tk-inpages-frame.html

* *Node version: 9.11.1
* *Browser version: Firefox 59
* *Device, operating system: Debian 9
* *The Lounge version: 2.7.1

---

**Comment by xPaw** [comment]
That's more than likely fixed in 3.0/master.

You also have truekey extension as far as I can see that is injecting broken code in the page.

**Comment by dgw** [comment]
It has to be extension-related. I just installed Firefox 59 to test on my system (Win7) and my instance of The Lounge 2.7.1 loaded up flawlessly on a fresh Firefox profile. Smells like `Status: Invalid` to me.

**Comment by KlaasT** [comment]
Just to let you know. Even with the True Key extension disabled the same problem appears. I'll move back to the 2.6.0 or 2.4.0 for the moment and wait for 3.0.0 to arrive.
