### ISSUE TITLE
Rework client processSetting() and add a bit clearer inline documentation  about restructured settings. 

### ISSUE THREAD

**Issue by creesch** [thelounge/thelounge#2375]
[Based on this conversation](https://github.com/thelounge/thelounge/pull/2328#event-1570068221) I came to the conclusion that the options/settings refactoring in client can use some finishing touches. 

- [ ] restructure `processSetting()` to allow an additional argument so when it is called outside the regular sync process a setting can still get synced properly. 
- [ ] Reword comments to explain settings flow better. @astorije did initially overlook `processSetting()` which I can understand as I could word the comments in that area bit more clearly. 

This issue is here for me as a reminder to actually do that stuff and not forget about it.

**Comment by xPaw** [comment]
Settings code was rewritten by @timmw, so that's no longer applicable.
