### ISSUE TITLE
Event compacting shows quits as "undefined"

### ISSUE THREAD

**Issue by kode54** [thelounge/thelounge#2393]
* *Node version:* 6.14.1
* *Browser version:* Safari 11.1 (13605.1.33.1.2)
* *Device, operating system:* MacBookPro11,2 macOS 10.13.4 (17E199)
* *The Lounge version:* v2.7.0-pre.4-780-g4ff5995

---

As of updating my local copy to this version, I find that at least single Quit events compact to "undefined". Events that contain multiple event types, such as joins and mode changes, only show the number of joins and mode changes, but don't mention the quits.

**Comment by McInkay** [comment]
This should have been fixed in master already, can you update to at least 8d7cd4e and let us know if it's still an issue for you.

Also, your version number is incorrect, it's a 3.0.0-pre.5 version with short commit hash 4ff5995. It's not 2.7.0-pre.4.

**Comment by kode54** [comment]
Weird, I should have used the version info from the app. I instead used `git describe --tags`

**Comment by McInkay** [comment]
That's very odd, it should have picked up the latest tag (3.0.0-pre.5). The fact that it doesn't makes it sound like maybe your local git is missing the newer tags? When you most recently updated, did you fetch in a way that only pulls down branches and not tags?

**Comment by kode54** [comment]
I pull with `git pull origin master`, which may not be the best way to do it. I also see you're using two different notations there:

```
obj["part"]
```

versus

```
obj.part
```

**Comment by McInkay** [comment]
Those 2 notations are functionally equivalent and wasn't the issue. Is the issue fixed for you after updating?

> `git pull origin master`

Try doing a `git fetch -a` and see if that pulls down the tags.

**Comment by kode54** [comment]
Disregard this, I had to shift+refresh the page, because apparently plain refresh is not enough to get my browser to actually reload the scripts. It may also be because I'm running the web gateway behind Cloudflare, and I don't have it set to development mode.
