### ISSUE TITLE
Channel link styling doesn't match channel joined with some ending characters (colons)

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/thelounge#2417]
Visually, seems like you'll join `#2416`, but in reality you join `#2416:`

Either need to show the proper channel, or ignore the : and join the channel as its meant to be.
Yes, `#2416:` is a valid channel, but 99% of the time incorrect.

<img width="843" alt="screen shot 2018-05-03 at 9 23 07 am" src="https://user-images.githubusercontent.com/8675906/39589660-aea4fe80-4eb3-11e8-91c8-3d85e85f4868.png">

**Comment by xPaw** [comment]
There's no special styling on channels, that's just how Wendy formats issue numbers.

**Comment by astorije** [comment]
Regardless of styling (which like @xPaw said is not on our end), I think @MaxLeiter raises a good point that a channel that looks like `#foo:`, `#foo.`, `#foo,`, and probably others that end with punctuation should be parsed without the end character, just like we do with URLs+`?`, etc.

Thoughts?
