### ISSUE TITLE
Query params no longer working for prefilling fields in public mode

### ISSUE THREAD

**Issue by lol768** [thelounge/thelounge#2424]
* *Node version:* 8.11.1
* *Browser version:* Firefox 61.0a1
* *Device, operating system:*  Linux, Ubuntu
* *The Lounge version:* 4a9c3236

---

Query params no longer seem to work on this revision, the fields aren't populated with the data from the search string.

To reproduce: Visit http://localhost:9000/?nick=foo and observe it still uses the defaults from the config file.

Is this a known issue?

**Comment by xPaw** [comment]
Fixed by #2378

**Comment by lol768** [comment]
Confirmed to fix the issue locally.

Cheers.
