### ISSUE TITLE
Chat view moves out of place after loading old messages with inline media in Firefox

### ISSUE THREAD

**Issue by iiiGerardoiii** [thelounge/thelounge#2446]
* *Node version:* 
9.10.1
* *Browser version:* 
Firefox 61.0b5 / Chrome 66.0.3359.181
* *Device, operating system:* 
Windows 10
* *The Lounge version:* 
2.7.1
---

![8766](https://user-images.githubusercontent.com/6264194/40286198-9fd52500-5c6a-11e8-9d75-eaa3a191f368.gif)
Note: I didn't scroll after reaching the top. Sometimes it goes up, sometimes it goes up and then down. Quite confusing.

If you disable inline media, the chat view stays in the correct place.

**Comment by MaxLeiter** [comment]
Can you try this on master? See the README for instructions on setup

**Comment by iiiGerardoiii** [comment]
@MaxLeiter yup, still happens on 3.0.0-pre.6 with Firefox. Haven't tried on chrome though.

**Comment by xPaw** [comment]
Okay yeah I can somewhat reproduce this in Firefox.

I have no idea how we could fix it though.

**Comment by xPaw** [comment]
@iiiGerardoiii Do you still see this bug on latest Firefox?

**Comment by iiiGerardoiii** [comment]
yup, still present

**Comment by xPaw** [comment]
@iiiGerardoiii Can you test v4.0 pre release and see if it still happens?

**Comment by iiiGerardoiii** [comment]
Apologies for late response.
I'm on v4.1.0 and it doesn't happen anymore 👍

**Comment by iiiGerardoiii** [comment]
It's present on v4.4.3.
