### ISSUE TITLE
Scrolling with middle click stops after loading old messages in Firefox

### ISSUE THREAD

**Issue by iiiGerardoiii** [thelounge/thelounge#2447]
* *Node version:* 
9.10.1
* *Browser version:* 
Firefox 61.0b5 / Chrome 66.0.3359.181
* *Device, operating system:* 
Windows 10
* *The Lounge version:* 
2.7.1
---
Click the mouse wheel to scroll, notice how it stops after it loads more old messages. You gotta click it again.

**Comment by dgw** [comment]
I very much doubt there is anything The Lounge can do about this. Middle-click scrolling is a very Windows-specific thing, unless I'm mistaken. (I've never seen it work on any other OS.)

How this can happen, I have a pretty good idea, but it would be in code for the scrolling implementation that is part of either the OS or the browser, which TL can't touch.

**Comment by iiiGerardoiii** [comment]
Ok I'm testing (a7fdea72 / v3.0.0-pre.5) and it works fine on Chrome, but not on Firefox thx mozilla

**Comment by xPaw** [comment]
Yeah, it stops scrolling in Firefox.

I don't think there's possibly any way we could fix this.

**Comment by iiiGerardoiii** [comment]
Fixed on Firefox 65.0
