### ISSUE TITLE
mask-image causes aliased text

### ISSUE THREAD

**Issue by williamboman** [thelounge/thelounge#2448]
The mask-image property, introduced in 23c969a, on container elements is what's causing this. Not all browsers seems to have this issue (only noticed on macOS Safari). Only happens on monitors with low-medium DPI.

Difference in Safari (make sure you view in 1:1 scale):

![screenshot 2018-05-14 at 17 54 21](https://user-images.githubusercontent.com/6705160/40138771-f84aef64-594d-11e8-9b1e-7524c89b4572.png)
![screenshot 2018-05-14 at 17 54 40](https://user-images.githubusercontent.com/6705160/40138772-f8660bf0-594d-11e8-80f7-5a8d7ff36cde.png)

**Comment by xPaw** [comment]
Is this still happening?

**Comment by williamboman** [comment]
Nope
