### ISSUE TITLE
Remove URIjs

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#2469]
Now that linkify-js was merged, URIjs is only used to parse `location.search` here:

https://github.com/thelounge/thelounge/blob/f5a8f23d2bf19774c38f671f4f22d58a6fb82ea5/client/js/socket-events/configuration.js#L90

We could use `URLSearchParam`: https://caniuse.com/#feat=urlsearchparams

**Comment by xPaw** [comment]
The code to use `URLSearchParams` would be here: https://github.com/thelounge/thelounge/commit/3b04e6860952a7aacdc1a97aea248df3e2d60413#diff-fa1d2a20452fbba6f1fea505e143ef84R89

**Comment by xPaw** [comment]
@astorije Are you fine with switching to `URLSearchParams`? Since these params are only parsed in public, I could add a check `"URLSearchParams" in window` to avoid unnecessary crashing in older Edge.

**Comment by astorije** [comment]
Yeah, that's reasonable. Could we use a polyfill (https://github.com/WebReflection/url-search-params) for a few months?

**Comment by xPaw** [comment]
Yeah I don't feel like there's enough reason to polyfill it.
