### ISSUE TITLE
Join by clicking chan name after being kicked does not work 

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/thelounge#2472]
* *The Lounge version:  source (commit 0de90da)* 

---

Steps to reproduce:

1. have someone kick you from the currently opened channel
2. have them invite you back (the invite will show up in the still open channel window)
3. click the channel name in the invite message to (re)join

**Expected behaviour:** 
You (re)join the channel you were kicked out of

**Actual behaviour:** 
nothing happens (actually, TL will focus the channel if you click its name on another buffer, e.g. the server console, but not attempt to join it - probably because the window is still open)

![image](https://user-images.githubusercontent.com/2070503/40610839-2ebfa1f0-6274-11e8-8c19-b0b28746889f.png)

Maybe somewhat related:
#2266
#2216

**Comment by xPaw** [comment]
I believe this would be fixed by #2281

**Comment by Jay2k1** [comment]
Okay, gonna grab this.
