### ISSUE TITLE
Typing does not focus input box when a link is focussed

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/thelounge#2473]
* *The Lounge version: source (commit 0de90da)* 
* Tested in Chrome, Firefox and Safari on macOS

---

When you click a URL, it opens in a new tab. Close the tab, you're back in TL (depending on the browser and its settings) but the input box doesn't have focus and typing doesn't focus it either. You have to click somewhere (empty space in chat/userlist/channel list or input box) to make it focus. 

*This ^ applies to Chrome and Firefox on macOS, in Safari it works as expected. This is because URLs in channels are not tab-selectable in Safari, only channel names are (another bug?).*

To reproduce, you can also shift-tab in a channel to move the focus from the input box to focusable element in the chat and then start typing.

*This ^ fails as described in all three browsers I tested, just that Safari always focuses something starting with `#` and the others select the most recent URL or channel name etc.*

I'm not sure how intentional this is, but especially in the "URL clicking" scenario it feels a bit... clunky.

**Comment by xPaw** [comment]
This works as expected in the sense that the focus doesn't change if you already have some element focused.

However to fix the behaviour with opening links, I imagine we could reset focus state on `visibilitychange` document event.
