### ISSUE TITLE
Add indicator to page title on new query/highlight

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/thelounge#2489]
This has heavily been discussed in IRC, so let's have some ordered, readable discussion here.

I had the idea of adding something to the title as (another) indicator for new query messages and highlights - basically everything that would trigger the "alerted" favicon. The main intention is to make Chrome *(edit: and Firefox, thx @MrLemur)* show a dot on a pinned TL tab like so:
![image](https://user-images.githubusercontent.com/2070503/40783231-1a147ed6-64e2-11e8-9d79-0cdeb219b74e.png)
![image](https://user-images.githubusercontent.com/2070503/40784219-4e92103a-64e5-11e8-81ab-780cac90fe7b.png)

They do this when the title changes and the tab is pinned.

Because other browsers do not do this afaik, and because you don't always have TL pinned, it makes sense to think about *how* to change the title so it benefits regular tabs in all browsers too. I have two ideas:

1. prepend the title with a &bull; bullet point (Chrome on top, Vivaldi below): 
![image](https://user-images.githubusercontent.com/2070503/40783812-e51169cc-64e3-11e8-806b-0a221bd0076b.png)
![image](https://user-images.githubusercontent.com/2070503/40783379-80bd68be-64e2-11e8-8f50-a07849598b36.png)

2. prepend the title with a count of events: 
![image](https://user-images.githubusercontent.com/2070503/40783782-cef9bff4-64e3-11e8-88ab-d19c51a5c55b.png)
![image](https://user-images.githubusercontent.com/2070503/40783437-ad33fcb4-64e2-11e8-8d93-3c3d3a3b355d.png)

As you can see, the Vivaldi browser adds its own "count badge" to the favicon when the title starts with (number).
It is also Twitter's way of doing it.

I prefer 2. for these reasons.

Something that came up is what the count should include. New query messages? Highlights? Notices? Maybe even disconnects? Server notices?

**Comment by MrLemur** [comment]
Just a note: Firefox shows a blue icon under a pinned tab if the title changes.

**Comment by xPaw** [comment]
To futher add a reason to change title:

On windows, pinned websites use favicon image that doesn't change, so the alerted icon is not visible in the taskbar.

Putting number of highlights in the title should work just fine. The only problem that will need fixing is propagating the actual number to the client, AFAIK the client doesn't know how many messages were highlights.

**Comment by McInkay** [comment]
So, there's probably not a reason to have the number, just a symbol when there have been unread or notifications since you last looked, and then you clear the symbol from the title when you go back to the tab.

**Comment by xPaw** [comment]
I imagine we would apply the same logic to title as changing favicons.

**Comment by Jay2k1** [comment]
> I imagine we would apply the same logic to title as changing favicons.

Well, that's here: https://github.com/thelounge/thelounge/blob/e30984a13dfea51fffee7ce96fe27aca94a33f66/client/js/utils.js#L88-L99

Locally, I already add/remove a "• " here, but couldn't we as well increase or reset a counter here that is then shown in the title? Not as elegant as actually getting the number from the server, agreed, but if this function is actually always called when a highlight or query message occurs and the tab is inactive, that should work, right? It would be my noobish approach anyway, but I also love global variables. 😂

**Comment by xPaw** [comment]
@Jay2k1 You can start by showing the number of `.badge.highlight` (or whatever the classname) elements, which is how alerted favicon is applied in the first place IIRC.

**Comment by Jay2k1** [comment]
To sum up what was discussed in IRC today:

- We want to prepend the title with the number, i.e. my initial suggestion no. 2.
- It should be a count of highlights and query messages (which are highlights too, code-wise).
- About removing: If you have 2 unread highlights, and you switch to the tab, it should keep the 2 in the title, and then go down to 1 when you click on 1 of the channels, and go away when you click on the second channel.

This means that
- whenever the notification and alert favicon logic is being triggered, this has to be triggered as well
- clicking a channel list item needs to trigger the logic too, in order to decrement the number

Notes to self:
- 11:44:47 <+xPaw> Jay2k1, FYI you'll need to send highlights count in chan.js, same way unread is sent
- also https://github.com/thelounge/thelounge/blob/master/client/js/lounge.js#L228-L235 needs to be separated into a new function which will then also be responsible for changing the title accordingly

**Comment by astorije** [comment]
I really like the suggestion of adding the number of total highlights/queries in the title (`(6) #thelounge - The Lounge`)! 👏 Pretty cool if you manage to make this happen, @Jay2k1!

(Also pretty dope for a browser to parse the title for the number, that's a neat idea as you can see this pattern used quite often!)

**Comment by fuzzy76** [comment]
FWIW, this will also make [Nativefier](https://github.com/jiahaog/nativefier) able to [display a badge](https://github.com/jiahaog/nativefier/blob/master/docs/api.md#counter).
