### ISSUE TITLE
Display nice error messages

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#251]
As @astorije pointed out in #167, some errors are only printed as special strings, instead of something descriptive.

Here's how Kiwi handles these: https://github.com/prawnsalad/KiwiIRC/blob/6f90124e0f15d4cc373496110d1150ffd75072fc/client/src/models/network.js#L856-L917

**Comment by astorije** [comment]
This would go well along with #677 (but both issues can be fixed independently).

**Comment by MaxLeiter** [comment]
Is this still an issue?
