### ISSUE TITLE
Make font format/color static... Stay until user chooses something different

### ISSUE THREAD

**Issue by dollabi11z** [thelounge/thelounge#2516]
This is by far my new fav client just found it a few days ago. They only thing stopping me is i have alot of noob chatters some of which cant barely refresh let along do keyboard shortcuts for font colors

Is there a way to have user font palette popup including bold italic etc AND have the color format/text format stay with them until they clear or choose something different like lightirc

**Comment by McInkay** [comment]
Just to check I understand what you are asking for, are you asking for a button to change the colour of text instead of having to use the keyboard shortcut?

**Comment by dollabi11z** [comment]
Yes  or just a way to have font color/format stick instead of having to hit control+k every line

**Comment by know75** [comment]
Just my comment moved from Shout to here:

_I agree, it would be great to have these options in TheLounge to make it much more user friendly for those that don't know IRC and unnecessary complicated keyboard shortcuts._

**Comment by know75** [comment]
dollabi11z wrote (from Shout/issues):

_This feature for font/text format i would pay for it's that important to my
site. I currently use Lightirc but the project is Abandoned and Flash is
pretty much dead so i wanted to move over to your html client but i need
these features_

In reply, I wrote:

_I'm in the same position, using LightIRC with users that don't even know what IRC is, are older in age and not particularly computer literate. I'm not sure they're going to make the step from the very intuitive LightIRC to TheLounge without some simplification of TheLounge.

Personally I think TheLounge is amazing and use it every day in Private Mode, I just hope it can adapt a little to accommodate what could be a huge 'webchat' audience._

<End of duplications>

**Comment by dollabi11z** [comment]
Yep exactly i have alot of older users too who arent very pc advanced so to
speak. But with Mobile traffic taking over Lightirc's days are numbered
unfortunetly

**Comment by xPaw** [comment]
I don't think this is something we would want to have. This effectively reads as "I want to change color of my messages by default" which some old IRC client allowed doing, but I don't see this as something we should do.

@McInkay Agree to close?

**Comment by dollabi11z** [comment]
Thx for the reply. Yes, you are absolutely right on about "Old Clients". I've been using LightIRC for a decade but its abandoned, obsolete and Flash so it has 2 go lol

Ya close this up, i can customize this client
