### ISSUE TITLE
Opera on iOS - issues with client loading

### ISSUE THREAD

**Issue by christer88** [thelounge/thelounge#2521]
There's an issue when opening Opera browser and loading the client. It happens on "cold starts" of browser, but not after reloading the webpage. See video below. I've tried with both Mininapse and default theme.

https://www.dropbox.com/s/ptv9tdqyk8qkhvg/2018-06-04%2013.30.31.mp4

iOS 11.3 on Apple iPhone 8 Plus
Opera 16.0.10
TheLounge 3.0.0-pre.6

No issue with Safari.

**Comment by astorije** [comment]
That is super weird!
Can you confirm you have run `yarn build` (looks like you have, but just checking) before? Also, could you try 2.7.1 and maybe an earlier v3 pre-release to compare and try to pinpoint when that started to happen?

**Comment by astorije** [comment]
Oh, my bad, I thought you were running from source!

Yes, you can install specific versions with `thelounge@3.0.0-pre.x` (instead of `thelounge@next`). It would be awesome if you could work your way down and isolate which version introduced this 🙏
Thanks! :)

**Comment by xPaw** [comment]
Closing because there's nothing we can about this (and seemingly only one user with this specific browser has the issue).
