### ISSUE TITLE
Rotate logs / write one log per day

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/thelounge#2556]
Inspired by @astorije's [comment in #1423](https://github.com/thelounge/thelounge/issues/1423#issuecomment-322769306):

> Since logs are not rotated

I feel like this should be changed. It's common to write one log per day (and target) with the date in the name. This has several advantages:
- you don't have single logs with hundreds of megabytes
- file based server backups using e.g. rsync or something similar don't have to copy the same data again and again just because a few lines are being appended to the file
- you could delete or compress old logs to save space

Non-rotated logs are a sysadmin's nightmare, because sooner or later, they're going to fill up your disk.

So even if it would make coding a UI for downloading logs a bit more difficult because you'd need a file listing or date range picker, assuming such a feature would actually deliver the actual text log files, I'm in huge favour of rotating logs. Should be easy to just have TL put the current date in the filename somewhere (I know because I made a PR to improve the text logger).

Before putting work into it and making a PR, I'd like to hear your opinions on that.

**Comment by christer88** [comment]
This will make it rather horrible to search for stuff in the log files. :/ Please wait with this until a propper search function is established.

PS! No, SSH grep ain't enough from my point of view.

**Comment by Jay2k1** [comment]
A "proper search function" that is based on, in bash terms, grepping the respective log, will break when logs are being rotated, so it makes sense to think and discuss this first.

I agree though that SSHing to the server and grepping logs is not something every TL user (which might not be the same person as the TL hoster) could do and we thus need a search UI.

**Comment by dgw** [comment]
> This will make it rather horrible to search for stuff in the log files.

Search should probably use the sqlite log, not the text files, anyway.

**Comment by christer88** [comment]
It's what comes first, dgw. If we start to logrotate now and it takes half a year to get sqlite db search implemented, it will be half a year with hell for those that cannot or doesn't know how to use grep.

**Comment by GewoonYorick** [comment]
Until there is a proper search function please let it stay as it is now.

**Comment by astorije** [comment]
I really think rotating logs is not The Lounge's job actually.

I understand that _in theory_ it should just be as simple as naming files with a date in them, but surely some people will want to be able to disable that, others will want to be able to customize that, etc. Next thing you know, we have to maintain our own version of logrotate :/

Don't get me wrong, I'm not saying there is no value in this, I'm saying as a core maintainer, I don't want to have to maintain (fix, improve, etc.) this in the core project. I would rather keep a focus on what makes the Lounge a good or better IRC client.
I would however be very happy to keep tutorials or recipes to integrate with logrotate or similar on the website (or wiki until docs are finish and let us keep random guides), or ultimately try to have package APIs give the ability to do this.

I suggest closing this as out-of-scope for this project. Thoughts?

**Comment by McInkay** [comment]
I think I agree. This is an external thing. Some people will want this, some won't, and there are plenty of tools to deal with this if people will want it. It's completely unrelated.
