### ISSUE TITLE
Sidebar has weird behavior on desktop viewports with touch

### ISSUE THREAD

**Issue by williamboman** [thelounge/thelounge#2572]
Demo on an 9.7" iPad (I am dragging my finger towards the right-hand side in the chat messages container): https://streamable.com/zw7cc

**Comment by astorije** [comment]
Wow, that is freaky! Would you be able to test on pre.6 by any chance? Just want to rule out a few things.

**Comment by williamboman** [comment]
This is on somewhat fresh master (1 week +- 4 days) + a few open PRs. I can retry on a fresh 3.0.0-pre.6 release later

**Comment by williamboman** [comment]
> Wow, that is freaky! Would you be able to test on pre.6 by any chance? Just want to rule out a few things.

I can repro on pre.6

**Comment by xPaw** [comment]
This bug is most likely rather old.

**Comment by fuzzy76** [comment]
The commit says it fixes this, so it can probably be closed?

**Comment by xPaw** [comment]
It's not merged yet.
