### ISSUE TITLE
Short nicks often get's wrongly highlighted

### ISSUE THREAD

**Issue by joandrsn** [thelounge/thelounge#2574]
In a channel I'm in, there's a bot named "m". 
In thelounge, the bot often get's highlighted.

![thelounge_highlight_username](https://user-images.githubusercontent.com/5766695/41640403-04b45ed2-7462-11e8-8f3d-5cc998d4ad32.png)
The highlighter often works correctly (does not highlight when part of a longer word) but sometimes it does. This is my example:
![thelounge_highlight](https://user-images.githubusercontent.com/5766695/41640404-04d36c6e-7462-11e8-9759-71261c0b00b6.png)

As you can see it highlights the m's in `i'm` and in `måske` (m followed by a danish character). I would have expected none of the above to be highlighting the m.

`node --version: v8.11.3`
`thelounge --version v2.7.1`
Operating system: Debian 9 stretch
Browser version: Firefox 61.0b14 64-bit + Google Chrome 67.0.3396.87 (64-bit)

**Comment by xPaw** [comment]
Duplicate.
