### ISSUE TITLE
Add CTCP callbacks messages filter for /ignore

### ISSUE THREAD

**Issue by christer88** [thelounge/thelounge#2597]
10:05  * UnitedKingdumb sent a CTCP request: NIGGER
10:05  * UnitedKingdumb sent a CTCP request: TIME
10:05  * UnitedKingdumb sent a CTCP request: faggot

Above CTCP callbacks messages would be useful to filter with /ignore for cases where the user know how to send CTCP callbacks messages.

Using TheLounge 3.0.0-pre.7.

---

Ref. IRC @ 26.06.2018: 13:55 <+xPaw> Xinayder, want to add filtering to ctcp callbacks? ⬆️

**Comment by RockyTV** [comment]
Should the filter be applied to requests only or should it also be applied to responses?
