### ISSUE TITLE
Introduce .github folder

### ISSUE THREAD

**Issue by Zarthus** [thelounge/thelounge#2600]
Move

- CONTRIBUTING.md
- ISSUE_TEMPLATE.md
- SUPPORT.md

to a `.github` folder (if desired), to reduce clutter in the repo root.

I don't think `SECURITY.md` does anything special, but it's probably best kept in the root anyway (or directly in the README)

[documentation](https://help.github.com/articles/setting-up-your-project-for-healthy-contributions/)

**Comment by xPaw** [comment]
SUPPORT.md is not a github file. I think this file should be removed with info merged into contributing and issue templates.

**Comment by dgw** [comment]
SUPPORT.md is definitely one of the supported files. GitHub has [a docs page for it](https://help.github.com/articles/adding-support-resources-to-your-project/).

**Comment by xPaw** [comment]
Oh, TIL

**Comment by dgw** [comment]
I had to dig for a minute to find that article, so don't feel like you missed something obvious. :)
