### ISSUE TITLE
Permalink to client to join specific channels

### ISSUE THREAD

**Issue by MineRobber9000** [thelounge/thelounge#2629]
Sorry if this is a duplicate issue or already implemented, but I was wondering if there was a way to add parameters to the link to change default values, a la qwebirc. Something like https://webchat.example.com/?channel=#notdefaultchannel perhaps?

**Comment by Zarthus** [comment]
https://demo.thelounge.chat/?join=hey

There's more, but I don't know exactly where in the code to find them.

**Comment by MineRobber9000** [comment]
That solves my issue, thanks!
