### ISSUE TITLE
html-minifier-loader deletes a closing tag and nests divs that should be siblings

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge#2635]
* *Node version:* 8.11.3
* *The Lounge version:* master, v3.0.0-pre.7

---

For some reason I can't figure out, `html-minifier-loader` gets rid of [this closing tag](https://github.com/thelounge/thelounge/blob/master/client/views/user.tpl#L5).

With `html-minifier-loader` | Without `html-minifier-loader`
--- | ---
<img width="580" alt="screen shot 2018-07-10 at 01 46 14" src="https://user-images.githubusercontent.com/113730/42491587-64498ac6-83e3-11e8-9d54-d6ee3351eb24.png"> | <img width="575" alt="screen shot 2018-07-10 at 01 45 51" src="https://user-images.githubusercontent.com/113730/42491588-645536d2-83e3-11e8-8bc5-32e4aa93fcf2.png">

Probably some misconfiguration of `html-minifier-loader` but I couldn't figure it out. @xPaw, I know you're all in with Vue right now, but mind taking a quick look at this? 🙏

**Comment by xPaw** [comment]
Try using `<!-- htmlmin:ignore -->` in that template.
