### ISSUE TITLE
Double message and opens user query on "User information" when user not online

### ISSUE THREAD

**Issue by christer88** [thelounge/thelounge#2638]
When right clicking on user in channel chat window and choosing "User information", if the user is not online:

- "No such nick/channel (no_such_nick)" is shown in channel chat.
- User query opens and "No such nick: MOMO" is shown.

Is it really needed to open user query with the text if the user is not online? In my opinion it's sufficient to show "No such nick/channel (no_such_nick)" in channel chat.

--------

* *Node version: 8.x LTS* 
* *Browser version: Opera 54.x* 
* *Device, operating system: Windows 10* 
* *The Lounge version: 3.0.0-pre.7* 

---

**Comment by christer88** [comment]
**User query:**
![user2](https://user-images.githubusercontent.com/11909212/42505839-483464b6-8440-11e8-883e-6711b27ff7bd.png)

**Channel message:**
![user](https://user-images.githubusercontent.com/11909212/42505841-489894e0-8440-11e8-969f-8c5e28481521.png)

**Comment by xPaw** [comment]
This was fixed in #2050, as it no longer opens a new query window for errors.
