### ISSUE TITLE
Pinch too zoom for image previews (on touch enabled devices)

### ISSUE THREAD

**Issue by MiniDigger** [thelounge/thelounge#2660]
### Feature Description
It would be cool if you could pinch too zoom on an image preview, especially on mobile that would increase the usefulness and usability of the image viewer.

**Comment by xPaw** [comment]
I somewhat implemented this in the Vue branch, you can test it out. It still requires polishing and some bug fixing though.

https://github.com/thelounge/thelounge/commit/67eda3f0d9325b848fb0f9fb790985e1596ee12a

**Comment by MiniDigger** [comment]
Switched my instance to vue, the viewer works fine, I just get this warning when I open the instance: https://hasteb.in/efemefiy.sql

one slight suggestion for the viewer would that you can close it by clicking everywhere outside of the picture, not just the X. (basically everywhere where cursor != grab or pointer)

**Comment by xPaw** [comment]
> I just get this warning when I open the instance

Figured out why, added an issue in the list of things to fix in vue.

> one slight suggestion for the viewer would that you can close it by clicking everywhere outside of the picture, not just the X. 

Yep will be done.
