### ISSUE TITLE
Clean presentation for bridges

### ISSUE THREAD

**Issue by rgarrigue** [thelounge/thelounge#2711]
### Feature Description

Hello,

It's quite obvious seing the screenshot below : in #yunohost on freenode, there's a bot/bridge for slack matrix whatever. The output is messy. I wish I coud sed it to remove `<` and `:xyz>`. The perfect things would be to remove it entirely and replace the bot name by the nick extracted from the message. But that might be messy.

![image](https://user-images.githubusercontent.com/1872031/44405165-e60b3780-a558-11e8-9080-76e23a2daf87.png)

I dunno if this would be useful to a lot of people, but dealing with bridge & so on would be quite a 2018 feature :-)

**Comment by xPaw** [comment]
"Bridges" are simply another IRC user, and there's simply no way of detecting or verifying their legitimacy. This is simply not feasible to support.
