### ISSUE TITLE
Setting: Ability to only have server notices in server tab, instead of active window

### ISSUE THREAD

**Issue by itssimple** [thelounge/thelounge#2714]
### Feature Description
As a user I would like to be able to set whether I want server notices in my active window or only in the server tab.

Being a network admin this would help a lot, so the chat log doesn't drown in connections/disconnections.

**Comment by dgw** [comment]
I can see the usefulness of this, but good luck getting a new setting added… 😏

**Comment by itssimple** [comment]
One can always dream, right? :)

**Comment by xPaw** [comment]
If notices actually come from the server, they do directly go to the lobby.

**Comment by itssimple** [comment]
![Screenshot](https://itssimple.se/share/u/multinet/chrome_2018-08-23_10-34-58.png)

**Comment by xPaw** [comment]
Server name has to match what you are connecting to right now, otherwise it's not really possible to detect if it's a server.

**Comment by itssimple** [comment]
In 2.6.0 this was not a problem though. :)

**Comment by itssimple** [comment]
Solved it by adding custom CSS:
```css
.chan.channel div.msg.notice[data-from="<servername>"]
{ 
    display: none !important; 
}
```
