### ISSUE TITLE
Unread markers are not updated when closing a window from the context menu

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge#2746]
* *Node version:* v8.11.3
* *Browser version:* Chrome 68.0.3440.106
* *Device, operating system:* macOS 10.13.6
* *The Lounge version:* 3.0.0-pre.7 (I know, haven't updated to pre.8 yet...)

---

When closing a query/channel window with unread messages from the context menu (without opening the window), the notification icons (favicon + left sidebar icon dot) do not clear, and the unread counter in window title is not updated.
These are correctly reset when clicking any other window.

**Comment by xPaw** [comment]
Does this also happen when channel is closed from another client?

**Comment by astorije** [comment]
Yup! Closing from another client doesn't update the menu icon dot / window title until clicking somewhere on the first client.

**Comment by astorije** [comment]
Could this be related to https://github.com/thelounge/thelounge/pull/2547 in any way?

**Comment by xPaw** [comment]
Nah, the issue here is that `part` event does not call relevant functions to update title or favicon.

**Comment by xPaw** [comment]
I refactored and fixed this in Vue.
