### ISSUE TITLE
File size on links in chat

### ISSUE THREAD

**Issue by fnutt** [thelounge/thelounge#2754]
We currently have config for not showing previews on images larger than X mb. But, what if the image is above this limit and you wonder if you should open it or not?  What about pdfs and other files we do not show previews of?

I can see the usefulness of knowing the file size when you're not at home and have limited data traffic. Considering we have implemented file uploading, there will (my guess) probably be more files and images shared in the future since it's far easier now - making it even more useful to know the file sizes.

I suggest: https://www.test.com/test.pdf (X MB)

<img width="507" alt="skjermbilde 2018-09-05 kl 13 19 47" src="https://user-images.githubusercontent.com/11909212/45090166-dcfc9780-b10e-11e8-81c9-b51a004424d1.png">

**Comment by richrd** [comment]
Would it make sense to only show the size when the preview is hidden due to the size being too big?

**Comment by christer88** [comment]
> Would it make sense to only show the size when the preview is hidden due to the size being too big?

Only server owners know what the image previews are limited to. For everyone else it's useful to know the file size. Also think it's more consistent showing it on all links, instead of just a few.

**Comment by Raqbit** [comment]
@fnutt If I read this correctly the other users can know the image preview size limit, it's in the error message:
```
This image is larger than {{friendlysize maxSize}} and cannot be
				previewed.
```
([msg_preview.tpl](https://github.com/thelounge/thelounge/blob/d303246d24c766989bf4d14324e56b53e3d16999/client/views/msg_preview.tpl#L54))

Though, I agree that it could be handy to show on all links
