### ISSUE TITLE
Add "update" indicator on help icon

### ISSUE THREAD

**Issue by McInkay** [thelounge/thelounge#2758]
### Feature Description

We currently show if there are lounge updates that the user hasn't installed on the help screen, however you have to go to the help screen to do that. It would be nice if we were to add an indicator to the icon so that you get an indication when you are just going about normally.

**Comment by astorije** [comment]
That and the updates about main project would greatly fit the admin panel thingy (#1950). I'll resume that one post-Vue.

**Comment by McInkay** [comment]
Well, it wouldn't be in the admin section, it would be on all screens on the icon in the bottom left. 

But yeah, I agree once we have the admin account implemented, we should only show it for admins.
