### ISSUE TITLE
Rename previously named log folders when creating log folders based on the new naming format

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge#2763]
* *The Lounge version:* v3.0.0-pre.7, v3.0.0-pre.8

---

Prior to https://github.com/thelounge/thelounge/pull/2366, log folders were named after the network host. After that PR, it is now a concatenation of the network name and its uuid.

While this change helps a lot with duplicates and such, the transition is not too smooth, and as v3 is soon coming out, this is going to mess with a lot of logs.

I suggest the following:

- When creating a folder named after the new convention, check if this user currently has more than one network with this host in their configuration.
- If there is exactly one matching network, and a folder named after its host exists in the log, rename it accordingly prior to writing any new logs. Print an info on server output that said rename was done.
- If there is more than one matching network, there is a naming duplicate and this is a confusion we cannot automatically sort out. Print a warning on server output that an existing host could not be renamed due to a conflict.
- If the new folder already exists (for example, for anyone who already ran pre-releases), do nothing and warn on server output. It would be too tricky to deal with merging files and such.

Is there anything I am missing here?

I suggest leaving this for a few minor versions or a few months, whichever comes first based on what "a few" means.

I initially thought this would be quite a lot of efforts for the small amount of pain when someone mentioned it in the channel, but as I was thinking more about this, I realize this change is actually pretty disrupting, and hard to reconcile after the fact, so we might as well endure the pain ourselves rather than our users. Also implementing this might not be as painful as I initially thought it would be.

**Comment by xPaw** [comment]
It's worth mentioning that the log format itself has changed too, along with timezone, format settings removed).

Because of that, I think overall it's cleaner if we do *not* rename the folders. We shouldn't have problems because this will be documented (right?) in the changelog/upgrade guide.

**Comment by xPaw** [comment]
> but format is now the same as the defaults use to be

By format I meant not only time format, but logging format itself (#2501).

> It's a very disruptive change for whoever actually uses logs. 

If anyone automates anything in regards to logs, renaming folders alone won't solve the problem entirely.

**Comment by astorije** [comment]
Alright then.
