### ISSUE TITLE
Insert space after channel completion

### ISSUE THREAD

**Issue by paride** [thelounge/thelounge#2769]
It would be nice if the nick completion inserted a comma and space (`nick, `) if the completion happens at the beginning of a message, and a space if the completion happens within a message. `#channel` completions should also add a space after the completed channel name.

**Comment by MaxLeiter** [comment]
You can achieve this by adding a comma and a space to the nick autocomplete postfix in the client settings (gear icon in the bottom left)

**Comment by fnutt** [comment]
https://github.com/thelounge/thelounge/pull/1799 added this to TheLounge. Be sure to use 2.7.0 or newer version, and click on advanced settings to see it.

**Comment by McInkay** [comment]
Oh, you also mentioned after `#channel` completion. I'll reopen and we can discuss that.

**Comment by fnutt** [comment]
When would you want a space after channel name? huh..?

**Comment by McInkay** [comment]
When typing something after it?

**Comment by fnutt** [comment]
Seems a bit random to have space only after channel name? Would this be for writing commands only?

Here are so examples of situations where you would not need or want space:
- /join #testchannel
- /sajoin Testuser #testchannel
- Something bad happening in #testchannel. Can you please have a look?
- Let's join #testchannel!

**Comment by McInkay** [comment]
Euch this is going to be configurable again isn't it? 

Time to shut it down.

**Comment by paride** [comment]
First of all thanks for the very quick feedback! Having a space after the channel name could not be a good idea, after all.

**Comment by McInkay** [comment]
Cool, that's fine, I'll close the issue then.

Maybe this setting shouldn't be in advanced settings?

**Comment by paride** [comment]
@McInkay in my opinion it is fine in advanced settings, but it should default to `,␣`. But I guess it's a matter of personal taste.

**Comment by McInkay** [comment]
Yeah, we had quite a lot of discussion about what it should default to ... and ended up with it defaulting to ... well nothing. But ... ach well.

Maybe it should default to a space? Is that better than defualting to nothing?

**Comment by paride** [comment]
Personally: I would prefer a space to nothing.
