### ISSUE TITLE
Click on the channel's topic to edit it

### ISSUE THREAD

**Issue by TheSonAlsoRises** [thelounge/thelounge#277]
You can view, but not directly edit, a channel's topic from The Lounge. It would be nice if you could click on a topic and get an edit prompt so you can change it.

**Comment by MaxLeiter** [comment]
Working on this now, should the titlebar be a content-editable, should a modal appear, or should the message box be set to `/title <title>`? Or something else?

**Comment by YaManicKill** [comment]
I would say the topic in the title should be content-editable. It's the most user friendly. Modals work for some things (for example, ban list, when we come to that) but it's overkill for this.

When editing, return should save and esc should cancel.

I think onBlur should probably save, but I'm not 100% sure about that. I'm thinking that it would be confusing to me if it didn't save when I clicked out of it. We should probably have a visible way of cancelling the edit, though. Not sure on that one.

**Comment by MaxLeiter** [comment]
Not sure if the content-editable is great due to mobile and titles not wrapping. I think adding a context menu option to launch a modal is the way to go.  

For reference, this context menu:
![this](https://sr.ht/P00b.png)

**Comment by maxpoulin64** [comment]
Thing to keep into consideration: topics can contain colors and other codes, so content-editable probably isn't a good idea for that. I would rather just swap the topic with an `<input>` box on click, and save when it loses focus and the topic has changed. That way it's formatting safe and you get the scrolling and everything for free.

**Comment by astorije** [comment]
I agree with @maxpoulin64 except for the save. Saving shouldn't apply without the user consent, aka clicking on a ✅ button.
Example of negative side effect: setting a topic that requires a URL, you start typing, click somewhere else on the chat to select a URL someone gave, boom, too late, topic updated. Not very user-friendly.
Also, rather than the text being clickable, an edit button would be nicer. Opposite can collide with an existing URL, for example if the topic is a URL only.
I'm thinking the edit button should appear within the entries of the dropdown menu.

**Comment by YaManicKill** [comment]
Would doing the same as what the username has now work well enough?

**Comment by PolarizedIons** [comment]
A way to just _view_ the entire topic would also be nice. Some channel topics (especially on mobile) are cut off and the only way to view it currently is to hover over it, and a tooltip appears. This isn't nice if you want to click a link though

**Comment by MaxLeiter** [comment]
Short term you can just use /topic

**Comment by astorije** [comment]
> A way to just view the entire topic would also be nice. Some channel topics (especially on mobile) are cut off and the only way to view it currently is to hover over it, and a tooltip appears. This isn't nice if you want to click a link though

This is a different topic, but there is a PR opened about tooltips right now so why not. @xPaw, what about adding this in your timestamp tooltip PR (#824)? It might look super ugly though, so just an idea.

> Would doing the same as what the username has now work well enough?

@maxpoulin64 says no, but I think it's worth giving it a shot.
