### ISSUE TITLE
Using "User Information" in context menu sends the WHOIS to the wrong server sometimes

### ISSUE THREAD

**Issue by spangborn** [thelounge/thelounge#2771]
If you have a channel selected in network A, and right click a PM from network B and select "User Information" from the context menu, it'll try to send the WHOIS on network A instead of the correct network B.

This is occurring in 3.0.0-pre8.

**Comment by xPaw** [comment]
This happens because it sends the command to `$("#chat").data("id")` channel (currently open channel), which is incorrect.

It should send it to server where the "context menu" belongs to. This part is tricky because it can be opened in either channel list, user list or chat messages.

**Comment by richrd** [comment]
This is probably fixed by vue?

**Comment by xPaw** [comment]
It is, yep!
