### ISSUE TITLE
Website links that error out always show preview cannot be loaded box

### ISSUE THREAD

**Issue by rossengeorgiev** [thelounge/thelounge#2800]
Docker: 3.0.0-rc.1

The below boxes show on links that error out, regardless of the "auto-expand websites". Surely if I've unchecked the box, I do not care of they cannot be expanded. A few sites tend to error, due to to user-agent string too, which makes this box show up often.

![image](https://user-images.githubusercontent.com/2720787/45961561-b5fefa80-c016-11e8-89b7-daf3e5730c40.png)

**Comment by xPaw** [comment]
This would be hidden by auto expand media checkbox, but I imagine that's counter intuitive.
