### ISSUE TITLE
Copy text includes <> when username is not selected

### ISSUE THREAD

**Issue by rossengeorgiev** [thelounge/thelounge#2801]
Docker: 3.0.0-rc.1
Firefox: v59

Doesn't copy the full username when you dont select the full line

![image](https://user-images.githubusercontent.com/2720787/45962078-f6ab4380-c017-11e8-9992-3a6b541c1dc3.png)

Video: https://s.rgp.io/20180924l10u7.mp4

**Comment by McInkay** [comment]
The not copying the username (or the full username) unless you select it all is not a bug, that is expected behaviour. We don't want it to automatically copy the username if you don't have it selected.

However, it showing the <> when there isn't a username is a bug.

**Comment by fnutt** [comment]
Seems like the issue is there if you try to copy some text and you copy all the way to the nick, but not including the nick. Obvisiouly < > should not show if the nick is not included in your copy selection, and nick should not be included in all copy selections either if you don't intend to include the nick.

Can confirm this is an issue on vue branch (1e59a280) as well.

**Comment by dgw** [comment]
@astorije I still use 2.7.1, and yes it is a regression.

On my instance of The Lounge, if I stop at the beginning of a line without including any characters of the nick, `<>` is not included in the copy. Including even just the last character of the nick puts `<k>` (for example) in the copied text as expected.

**Comment by astorije** [comment]
@dgw, what browser did you try that on? Mind trying on Firefox, in case you haven't?
On v3.0.0-rc.1, I can reproduce the issue on Firefox but not on Chrome. On Chrome, it works just as you described, even on v3.0.0-rc.1.

**Comment by fnutt** [comment]
I can reproduce this on vue branch in Opera browser, which use Google's Blink.

**Comment by xPaw** [comment]
> Do you think that was introduced recently? Wondering if that's a regression from 2.7.1.

It isn't and always was the case.

**Comment by dgw** [comment]
@astorije I can't reproduce on Firefox with 2.7.1, either. Earlier test was in Chrome, but it doesn't seem to make any difference.

**Comment by xPaw** [comment]
So I checked out 2.7.1, and tried on Firefox and see the same behaviour just as on master, so this is not a bug we introduced recently.

Either way, I will try to tackle message copying stuff once and for all after dealing with it in Vue (probably by putting invisible <> in the text directly).

**Comment by xPaw** [comment]
As I said yesterday, I fixed this on the Vue branch for multiple reasons: whitespace is properly controlled, `<>` is directly in DOM, so copying is consistent (e.g. if you only copy half of the nick, it puts the arrow on one end).
