### ISSUE TITLE
/me copied text does not correspond with log text

### ISSUE THREAD

**Issue by fnutt** [thelounge/thelounge#2804]
TheLounge 3.0.0-rc.1, commit 1e59a280

```
13:42 <fnutt> Test1
13:42 <fnutt> Test2
13:42 <fnutt> Test3
13:42 <fnutt> Test4
13:42  fnutt does some testing
13:43 <fnutt> Test5
13:43  fnutt does another test
```

Above text have two /me messages, but it's not very visible when copying the text where the /me messages are. The only difference is one more space and the lack of <>.

https://github.com/thelounge/thelounge/pull/2501 added * in front of nick on /me messages in logs, and in channel you see a ⭐️. For both consistency and to make it easier for everyone to see when /me command was used, I think we should add * in front of the messages when copied.

**Example:**
`13:42 * fnutt does some testing`

**Comment by xPaw** [comment]
That's a bug on Vue branch.
