### ISSUE TITLE
please re-add arrow key on preview

### ISSUE THREAD

**Issue by dateno1** [thelounge/thelounge#2806]
### Feature Description
1. on theLounge 3.0.0 user can upload files on server

but can't manage it

can you add auto-delete expired files like [kiwi's fileuploader](https://github.com/kiwiirc/plugin-fileuploader)?

2. on old version(2.7.1) user can change previous/next preview image by keyboard arrow key

but can't do that on lastest (3.0.0-rc1)

please re-add that

**Comment by xPaw** [comment]
Create separate issues for each of your requests, don't combine them into multiple ones.

> but can't manage it

That's why this feature is disabled by default, as it's a minimum viable implementation, and further improvements will be done in the future.

> on old version(2.7.1) user can change previous/next preview image by keyboard arrow key

I just tried on master, and it still works just fine. Can you elaborate?

**Comment by dateno1** [comment]
> Create separate issues for each of your requests, don't combine them into multiple ones.
> 
> > but can't manage it
> 
> That's why this feature is disabled by default, as it's a minimum viable implementation, and further improvements will be done in the future.
ok i will wait future version

> I just tried on master, and it still works just fine. Can you elaborate?
i can change previous/next image by keyboard's arrow key (click small preview image -> press arrow key (left/right) -> move previous/next image) on 2.7.1 but it not worked on 3.0.0-rc1

server : linux x64 + nodejs 8.10.0 + theLounge 3.0.0-rc1
client : windows10 x64(rs1) + firefox 62.0.2 (x64)

**Comment by dateno1** [comment]
> 
> 
> > i can change previous/next image by keyboard's arrow key (click small preview image -> press arrow key (left/right) -> move previous/next image) on 2.7.1 but it not worked on 3.0.0-rc1
> 
> Works fine here. Do you see arrows in the UI? Are there other images that you can see in chat?
> 
> Make a video if you can.

can't find arrows and when i press key nothing to changed
![iv](https://user-images.githubusercontent.com/12645246/46025205-5cd0bd00-c123-11e8-82b8-7927d32d6040.png)

**Comment by xPaw** [comment]
Are there multiple images in the channel when you are looking in 3.0? Can you record a video?

**Comment by dateno1** [comment]
> 
> 
> Are there multiple images in the channel when you are looking in 3.0? Can you record a video?


[iv.zip](https://github.com/thelounge/thelounge/files/2415925/iv.zip)
it captured on virtualbox (7 x86 + firefox) (same result)

**Comment by xPaw** [comment]
Can you make a screenshot of Lounge version in help tab on your 3.0 install?

**Comment by fnutt** [comment]
It seems like I'm not able to do it either, and I'm on vue branch. Just tested in #thelounge-spam channel, where there are atleast 5 images (2 from one user and 3 from me). Using arrow keys have no affect.

**Comment by dateno1** [comment]
> 
> 
> Can you make a screenshot of Lounge version in help tab on your 3.0 install?

![version](https://user-images.githubusercontent.com/12645246/46026894-66f4ba80-c127-11e8-92bc-7af9e801e761.png)
current theLounge version

**Comment by xPaw** [comment]
Well there you go, you are running the Vue branch (commit a19658be), which is not an issue with 3.0 release.

Please state your version correctly next time so we don't waste time going back and forth.
