### ISSUE TITLE
Can't use TAB to autocomplete a nick if text cursor is not at the end.

### ISSUE THREAD

**Issue by iiiGerardoiii** [thelounge/thelounge#2820]
* *Browser version:* 
    Firefox 63.0b7
* *Device, operating system:* 
MacOS High Sierra
* *The Lounge version:* 
    v3.0.0-pre.8

---
![23p23p2](https://user-images.githubusercontent.com/6264194/46322088-a2bad480-c5ac-11e8-842a-0a72714c11a0.gif)

**Comment by dgw** [comment]
Duplicate of #1801

**Comment by iiiGerardoiii** [comment]
oh, my bad
