### ISSUE TITLE
Logging - limit disk usage of logs/<username>.sqlite files, remove old records

### ISSUE THREAD

**Issue by zeten30** [thelounge/thelounge#2822]
### Feature Description
Currently, there's no way how to control logs/<username>.sqlite file size. It can grow forever. Although this is usually not an issue, it will be good to have a mechanism that will keep file size under control.

### Use-cases

- deployments with many users
- deployments in public/private clouds (on OpenShift), where persistent storage for applications is usually limited

### Ideas

- keep max N messages in tables, use maxHistory parameter and run regular cleanups (SQL - delete oldest entries)
- check sqlite vacuum feature and check if this can help to improve disk space usage of sqlite

**Comment by richrd** [comment]
I think it would be great to be able to limit the messages by how old they are.
For example maybe I'd like to configure it to delete messages that are over 365 days old.

**Comment by zeten30** [comment]
Or the other way around. Add function to clear history. Something like clear browsing history in browsers. Clear message history older than: <select>.

**Comment by zeten30** [comment]
Agree. I already tried that on my OpenShift deployment -> sqlite dies while executing the query... But I assume it's because resource limits.

**Comment by mans3n** [comment]
Any news about this topic? I've deployed thelounge in a docker container and trying to get rid of some messages to reclaim some space back. How can i execute this command "delete from messages where time < strftime('%s', datetime('now', '-365 day'))*1000;" to sqlite? Commandline?

**Comment by xPaw** [comment]
>  Add function to clear history. 

Latest pre-release has the feature to clear history of a channel.

**Comment by Stiefmeister** [comment]
Would be great to have an option to set maximum amount of lines per channel to log - currently having troubles with fast growing log-files

**Comment by alekna** [comment]
> ssages to reclaim some space back. How can i execute this command "delete from messages where time < strftime('%s', datetime('now', '-365 day'))*1000;" to sqlite? Commandline?

Yes, you need to use `sqlite` command line tool. You may also want to run `vacuum` command after a delete.

**Comment by richrd** [comment]
@alekna Hi, thanks for the follow up!

Just checking if I understand this correctly, this is what I assume:
1. `DELETE` somehow marks the rows as deleted, but doesn't actually purge them from the file
2. `vacuum` actually alters the file to remove the deleted rows from disk

Did I get that right?

**Comment by alekna** [comment]
@alekna, not exactly. Have a look at https://www.sqlite.org/fileformat.html and https://sqlite.org/lang_vacuum.html if you're curious.

**Comment by im-n1** [comment]
This feature is highly needed. If you connect to one of those torrent channels where messages are constantly piling up 24/7 you reach 1gig of logs withing a week. Running Lounge on Rpi bricks it within a month.

**Comment by Erwyn** [comment]
I tried the "clear history" of a channel feature, but I'm not sure it's actually cleaning the sqlite database... It's still more than 600Mo on my side although I actually cleared everyone of my channel's histories

**Comment by klausenbusk** [comment]
That is expected, you can try to vacuum the database. Please see: https://sqlite.org/lang_vacuum.html

**Comment by Erwyn** [comment]
Will take a look, thanks

**Comment by orliesaurus** [comment]
+1 - I got several gigabytes of logs and I would like to get rid of them natively without having to do it manually

**Comment by pbek** [comment]
> That is expected, you can try to vacuum the database. Please see: https://sqlite.org/lang_vacuum.html

Maybe thelounge could do that periodically for all databases?

**Comment by pbek** [comment]
A temporary workaround could be to use [logrotate](https://www.digitalocean.com/community/tutorials/how-to-manage-logfiles-with-logrotate-on-ubuntu-16-04) to archive log-databases when they grow too big.

**Comment by orliesaurus** [comment]
I am looking for a solution that doesn't require me to stop thelounge to clean up logs

**Comment by pinpox** [comment]
Any updates or working workaronuds for this? I'm running an instance with several users and the `.sqlite` files are growing to a point where this is becoming a serious problem.

**Comment by brunnre8** [comment]
Sure: https://github.com/thelounge/thelounge/wiki/Purging-logs-older-than-X-days

is a workaround that does just that.

**Comment by azeemba** [comment]
Is there interest in this feature if someone else provides a solution. I can think of two ways to implement this:

- On startup, the server uses a `setInterval` to repeatedly run the delete command. This is nice because each delete operation will be relatively cheap. 
- We use sql [triggers](https://www.sqlite.org/lang_createtrigger.html), so on each update, sqlite itself will delete old records. This one is a little hard to configure for the user. We probably would need a new commandline "command" to insert/update this trigger.

**Comment by brunnre8** [comment]
Triggers are the wrong tool for the job in this case would be my guess, especially as you want to make this configurable and somewhat dynamic.

I'd also like to have the ability to only delete status messages, while keeping the import stuff like privmsgs around.
In other words some sort of timer on the JS side of things.
We do need to be a bit careful not to hang the rest of the system though by running a huge delete.

My plan is to limit this to N rows per iteration
