### ISSUE TITLE
.gitignore - Better preserve user data

### ISSUE THREAD

**Issue by 4oo4** [thelounge/thelounge#2839]
Please add `users/*.json` to the main `.gitignore`, it makes it much easier to upgrade from source.

**Comment by xPaw** [comment]
Why are you putting user data into the same folder as the source?

**Comment by 4oo4** [comment]
I didn't choose to put it there, that seems to be the default location when installing it from source. Is there a config option for that?

**Comment by xPaw** [comment]
Default location is `~/.thelounge` which is specified in https://github.com/thelounge/thelounge/blob/master/.thelounge_home

**Comment by 4oo4** [comment]
Got it, thanks!
