### ISSUE TITLE
/leave a channel but don't close it

### ISSUE THREAD

**Issue by iiiGerardoiii** [thelounge/thelounge#2865]
### Feature Description
Lots of IRC clients do this. Once you type ```/leave``` or ```/part```  the channel stays on the sidebar greyed out to let you know that you're not in it, and you can still read that chat.

#2216 is asking something similar, I think.

**Comment by xPaw** [comment]
This was discussed on IRC before, but we didn't hear any compelling use case. Do you have one?

**Comment by iiiGerardoiii** [comment]
I think it's mostly an expected behavior from the previous IRC clients I've used. Some people probably feel the same. My previous IRC clients were Textual, and HexChat and both behaved this way.

Having such feature made me develop the habit of using ```/leave``` as a "join later" option, and ```delete``` the channel if I just don't want to visit it anymore.

In a way it's like treating the channels on the sidebar as if they were bookmarked sites on the toolbar of a web browser.

**Comment by dgw** [comment]
The most compelling use case I can think of is leaving a channel after some discussion, but still wanting to refer to the chat history for some reason. Can't tell you the last time I've wanted to do that (I log in ZNC anyway), but maybe for some users it happens more often.

Disconnecting the `/leave`/`/part` command from `/close` is technically trivial, I'm sure. The UX is what requires consideration, yes?

**Comment by xPaw** [comment]
@thelounge/maintainers What do you think? I personally see no value in this.

**Comment by McInkay** [comment]
I mean, I can definitely see the value in it. But maybe a better way to do it would be when we have search, we can search closed channels as well. The fact is sometimes you want to see something you said, or someone else said, in a channel that you have left. But leaving the channel in the sidebar when you leave it is probably not the best way to do it.

**Comment by xPaw** [comment]
Yeah, message searching in closed channels is the better way of solving this instead of keeping parted channels around.

So I'm closing this in favor of #109.

**Comment by sopos** [comment]
I've got an usecase and I use with pidgin.
There's and department in our company which maintains a tool. They have their own irc channel. I have that channel disconnected in the list so I can connect it, ask for something relevant people and disconnect after the discussion is done. 
The advantage of such approach is that the channel is mostly occupied by SMEs so I can ping virtually anyone who's online and I have quite high chance that they are the right persons.
Other who are just a "guests" asking for help are there usually for a limitted time period.
So I have such channels in pidgin with uncheck "auto-join" and "persistent". That means the channel is not connected at the start of pidgin and the channel is left once I close its tab.
Here, in The Lounge, I can imagine a button or a command  for leaving the channel as well as a configurable timeout after which, in case of my inactivity (being focused would be counted as an activity - reading), the channel would be left.
Having the channel disconnected on a sidebar acts as a bookmark so I do not need to be looking for the right channel name.
