### ISSUE TITLE
FR: use standard passwd file with bcrypt?

### ISSUE THREAD

**Issue by lil5** [thelounge/thelounge#2879]
### Feature Description

Passwd file support. 

#### Example `user`:`password` (in bcrypt)

```
user:$2a$04$SQbu7.i6poOvEci4nO1ATO5XUzUOUunfWlPxZyCgYqtIf7C5gjl7i
```
file: `/users.passwd`

#### Reason 

This keeps the passwords encypted and adds posibility to manage users from one file (say someone uses [`webdav`](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/) and [`radicale`](https://radicale.org/configuration/)

**Comment by xPaw** [comment]
Lounge user passwords are already hashed with bcrypt, and each user has their own json file in `~/.thelounge/users` folder.

Managing user:password pairs from a single file would not have any benefit in lounge (and only would introduce unnecessary problems).

That being said, authentication system is somewhat abstracted out already, and if you wanted such a feature, it wouldn't be too hard to hook something up (e.g. like we already do with LDAP).

**Comment by lil5** [comment]
@xPaw Thanks for the tip.

I didn't find the fact that passwords were bcrypted in the documentation :astonished: .
