### ISSUE TITLE
Client shows "Reconnecting", nodejs process at 100% CPU

### ISSUE THREAD

**Issue by viperidae** [thelounge/thelounge#2884]
Every now and then the client gets disconnected and tries to reconnect.
I've tried with 2.7.1 and with github source. Same problem.

I don't see anything at all in the logs. Sometimes it will run for a few hours, sometimes minutes.

Is there any way I can enable more verbose logs, or capture a stack trace or something when the process has start what appears to be an infinite loop?

* *Node version:* 11.0.0
* *Browser version:* Chrome 70
* *Device, operating system:* Chrome on Windows 10, thelounge on Debian 8, armhf
* *The Lounge version:* 2.7.1

---

**Comment by xPaw** [comment]
Try downgrading to Node 10 or LTS. Someone else reported the same problem on IRC the other day with Node 11.

**Comment by viperidae** [comment]
I've switched to v10 and haven't had any further issues

**Comment by kode54** [comment]
Looks like Arch broke Lounge when they updated me from 11.15 to 12.10 today. Switching to nodejs-lts-dubnium fixes it.
