### ISSUE TITLE
When scrolled up into history, do not scroll back down on new messages until you've scrolled back down

### ISSUE THREAD

**Issue by itssimple** [thelounge/thelounge#2926]
### Feature Description
As a user, who uses the clients on multiple platforms/devices, in networks with high throughput, I'd like a setting where I could turn off the "Scroll to latest message", when I started looking at my backlog/scrollback.

If I try and pinpoint something that is about 3k messages up, and a new message pops in, I get automatically scrolled down again, which is slightly irritating when you're looking for a specific time period.

I'm running version 2.7.1

OS: Windows 10 / Android 9 (OnePlus 6T)
Browser:
- Chromium: 71.0.3578.80 (Windows 10)
- Chrome: 71.0.3578.83 (Android 9)

**Comment by itssimple** [comment]
Awesome! :) Thanks. Awaiting with high anticipation!

**Comment by xPaw** [comment]
Are you sure this is not a duplicate of #1103?

Also please specify what OS/browser you see this issue on, because I've heard this issue happens more often on iOS.

**Comment by itssimple** [comment]
@xPaw Updated post with OS and Browser.

**Comment by xPaw** [comment]
Could you try pre-release version (thelounge@next) and see if the issue persists?

If it still happens, I'm rather confident it's fixed for good in the Vue branch.

**Comment by itssimple** [comment]
Seems to be resolved in `@next`, so I'm staying here!

Thanks!
