### ISSUE TITLE
Sluggish text rendering when scrolling

### ISSUE THREAD

**Issue by williamboman** [thelounge/thelounge#2928]
* *Node version:* 
* *Browser version:* Chrome 70.0.3538.110
* *Device, operating system:* macOS 10.14.2
* *The Lounge version:* 3.0.0-rc.5

---

https://streamable.com/p59r4

**Comment by xPaw** [comment]
How is this a problem with The Lounge? The messages are all in DOM already, scrolling is handled entirely by browser.

That being said it's probably slow because all channels are in DOM, so Vue branch probably helps here.

**Comment by williamboman** [comment]
> How is this a problem with The Lounge?

I'd assume this is due to some CSS that jinxes the render pipeline

**Comment by xPaw** [comment]
Without any concrete details, it's practically impossible to do anything about it.

If this is an issue on Vue then it's definitely an issue on your end.

**Comment by williamboman** [comment]
I did some quick debugging and from the looks of it the main thread becomes rather busy when receiving new messages, might be the cause.

I could investigate in more detail later.

**Comment by xPaw** [comment]
Is this still an issue?

**Comment by williamboman** [comment]
Can't reproduce anymore :+1:
