### ISSUE TITLE
Implement 'badging' when it starts shipping in browsers

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#2933]
Reference: https://developers.google.com/web/updates/2018/12/badging-api

Basically it allows controlling badges on the app icon:
![badges](https://user-images.githubusercontent.com/613331/50043524-4da44000-007e-11e9-924d-4cb06214c7f5.png)

The Lounge already syncs unread counts per channel, and we already support push notifications with service workers. So we will just need to add a sync count for _all_ unread channels when pushing notifications and add a new sync message when the unread counter decreases (might be a problem as browsers require showing a notification whenever something arrives in a SW).

**Comment by xPaw** [comment]
Implemented here: https://github.com/thelounge/thelounge/compare/xpaw/native-badging

![17-165858844](https://user-images.githubusercontent.com/613331/56306511-518ac080-614b-11e9-892a-c2fdb2516d59.png)

**Comment by CirnoT** [comment]
Been using this for quite some time now and it seems to be working pretty well. Maybe it's time to merge it?

**Comment by xPaw** [comment]
The spec is not finalized and will change, so not yet.

**Comment by xPaw** [comment]
I updated the branch with latest spec changes, and added syncing badge count via web push (so if the app is closed, you get updated counter). Haven't tested it yet though.

**Comment by CirnoT** [comment]
Can this be updated to to recent Vue merge?

**Comment by xPaw** [comment]
Rebased, tell me if it still works correctly.

**Comment by CirnoT** [comment]
Yup, it seems to work.
