### ISSUE TITLE
Channel Search 

### ISSUE THREAD

**Issue by arch1mede** [thelounge/thelounge#2935]
### Feature Description
Running latest v3.0.0-rc.5
In client log search rather than ssh'ing into the shell and manually searching. Sort of similar request #1289 but searching in the channel logs. Issue #109 seems more promising but not sure what version this was implemented in.

Not sure if this is feasible but would make sense to click on the topic and it change to search then when you are done it changes back to the topic.

Currently, while you can do a ctrl-f to search, you would have to issue a /expand for it to work properly.

**Comment by xPaw** [comment]
You just created a duplicate issue of the issue you linked.
