### ISSUE TITLE
Lounge usernames should be case-insensitive

### ISSUE THREAD

**Issue by pcolmer** [thelounge/thelounge#2943]
I'm running thelounge 2.7.1 in the provided Docker container, with Edge on Windows 10.

I've configured the software to authenticate using LDAP and initially signed in on my PC. I then opened a web browser on my phone and signed in … but didn't realise that the phone's keyboard had auto-capitalised the first letter and so, although authentication succeeded, it created essentially a new user with their own configuration.

I can't imagine many scenarios where the Lounge login username would need to be case-sensitive, so would it be safer to explicitly lower-case the names or, for backwards compatibility perhaps, do a case-insensitive check against existing names or config files?

**Comment by lockntross** [comment]
My user configuration for Networks doesnt work and the json breaks the docker. Were you able to choose a network on a per user basis? 

```
{
  "user": "example",
  "password": "password",
  "log": false,
  "networks": [{
    "name": "Freenode",
    "host": "irc.freenode.net",
    "port": 6697,
    "tls": true,
    "password": "serverpw",
    "nick": "john",
    "realname": "John Doe",
    "commands": [
      "/msg NickServ identify password",
      "/msg ChanServ op #chan"
    ],
    "join": "#foo, #bar"
    }]
}

```

**Comment by astorije** [comment]
That seems reasonable to me. What do other @thelounge/maintainers think?

**Comment by McInkay** [comment]
I don't have an objection to this, it just means that migrating could be awkward. If there are usernames that are the same with different case, we need to bear that in mind when implementing.

**Comment by xPaw** [comment]
There's an open PR for this now, are you able to give it a try? #3918

**Comment by pcolmer** [comment]
> There's an open PR for this now, are you able to give it a try?

Not immediately, I'm afraid. I can schedule the work but it won't be for a few days.
