### ISSUE TITLE
Ability to customize titles

### ISSUE THREAD

**Issue by Kage** [thelounge/thelounge#2948]
### User Story
**As a** The Lounge operator
**I want** to customize template titles
**So that** I can use more recognizable branding

### Feature Description
In short, I'd like to be able to change "The Lounge" to something else in `client/index.html.tpl`, `client/views/windows/connect.tpl`, and elsewhere that "The Lounge" is presented in the GUI.  It creates confusion for our users when they see our web chat labeled as "The Lounge" rather than with our IRC network name.

**Comment by williamboman** [comment]
For now you could create a new script file and include it in the document:

```js
const MY_TITLE = "Foo"
document.title = MY_TITLE

const startObserving = (observer) =>
  observer.observe(document.querySelector("title"), { childList: true })

startObserving(
  new MutationObserver(function callback(mutationsList, observer) {
    observer.disconnect()
    document.title = MY_TITLE
    startObserving(observer)
  })
)
```

🤷‍♂️

**Comment by Kage** [comment]
Thanks, but that feels too hacky for me.  I added PR #2949 to resolve this instead. ;)

**Comment by astorije** [comment]
FYI we had a similar request a couple years ago: https://github.com/thelounge/thelounge/issues/566
I'm still not in favor of this, it's easier (for us to maintain) and more accurate (to specific use cases) to fork the project and give it the branding you want.
If we offer customization of the name, we need to offer customization of the logo, you'll likely want dedicated colors (which can already be done via themes), probably customization of hardcoded texts, etc.

**Comment by xPaw** [comment]
I'm with @astorije on this.

**Comment by Kage** [comment]
I'm not much in favor of the forking approach because it can lead to maintainability problems for users and isn't user-friendly to those who aren't proficient in Node.js.  I wouldn't think it should be too difficult to maintain upstream.  The relevant places are already updated in my PR, and I also left some alone to retain relevant application branding (i.e. in the version checker).  As for additional customizations like you mentioned, dedicated colors are covered, and customized logos could be done in a separate PR if someone has such a need (I may even prep one if you want).  But everything else, like customized hardcoded text, I would agree that should go into a fork since that's far beyond the scope of a simple configuration value.

Aside from the concern of a customization slippery slope, could you please go into more detail about the challenges this poses with respect to your maintenance of the code?

**Comment by xPaw** [comment]
@Kage See https://github.com/thelounge/thelounge/issues/566#issuecomment-240259756 for a little more info.

It boils down to the fact that we don't quite want to allow this.

**Comment by McInkay** [comment]
@Kage The fact is that we don't want to put in the effort, either to create the customisability, nor to maintain it (anytime we put the name somewhere, we'll need to make sure we make that work properly).

Anyone is free to take our project and do what they want with it, but what is the reason why we would make it easier for people to rebrand it?

**Comment by xPaw** [comment]
Closing as discussed.

To the points above, I'll add that we would like 'The Lounge' branding to be kept.
