### ISSUE TITLE
LDAP tests produce (expected) console messages

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#2950]
After I added extra logging in LDAP, it now logs messages into CLI when running tests:

```
2019-01-02 12:07:41 [ERROR] LDAP bind failed: InsufficientAccessRightsError: InsufficientAccessRightsError
2019-01-02 12:07:41 [WARN] LDAP Search did not find anything for: eve (0)
```

We should catch these messages so they are not printed (could even add asserts for them).

**Comment by moundahiwale** [comment]
@xPaw I would like to work on this. Also this would be my 1st commit to an open source project, I have read the contributing guidelines but might need some help on this and also on this issue. I think your team uses freenode, but couldn't find any channel for English - is there a way to contact you directly to discuss the high level changes required to fix this issue?

**Comment by xPaw** [comment]
`#thelounge` is the channel.
