### ISSUE TITLE
Can't connect to twitch chat.

### ISSUE THREAD

**Issue by tumeden** [thelounge/thelounge#2952]
cant connect to irc.chat.twitch.tv
https://help.twitch.tv/customer/portal/articles/1302780-twitch-irc

**Comment by Zarthus** [comment]
What error are you getting?

**Comment by xPaw** [comment]
You most likely did not specify all the correct details. I know twitch chat IRC works for a fact.

**Comment by tumeden** [comment]
This is how i would of filled it out
https://i.gyazo.com/7e1ff1634aa72b050fc526be337a012f.png
The password being the oauth code.

**Comment by xPaw** [comment]
You still didn't answer on what error you are getting.

Did you include `oauth:` prefix in the password?

**Comment by tumeden** [comment]
I did include oauth:      yes.
It immediately disconnected me with no specific error code, other then being disconnected strangely.

**Comment by xPaw** [comment]
The Lounge version? Node version?

Try upgrading to thelounge@next (pre-release) and see if it works or gives a better error.

**Comment by tumeden** [comment]
node v8.14.0
lounge v2.7.1 - 2018-02-18

**Comment by tumeden** [comment]
Interesting.   It's working now.

Clearing the browser cache seemed to somehow fix it?   Confused at how that would have any effect but i'll take it....    Using the latest version of google chrome for reference.  No idea what happened.

**Comment by xPaw** [comment]
Your browser cache doesn't matter as the connection happens on the server.

**Comment by tumeden** [comment]
Yeah, that's why i'm a little puzzled...   I've restarted the browser over a dozen times,  and have been using the exact same connection details.

**Comment by tumeden** [comment]
works awesome actually...  thanks for developing this 👍
