### ISSUE TITLE
Using two `@` after any word triggers auto completion

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [thelounge/thelounge#2960]
When typing something like `command@@` the auto completion feature is triggered and I believe that this should not happen.  
The issue actually affects both desktop and mobile devices.

* *Node version:* v10.15.0
* *Browser version:* Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* *Device, operating system:* 64 bit Windows 10 Home (Version 10.0 1803 Build 17134.472)
* *The Lounge version:* v3.0.0-rc5 (isntalled via `yarn global add thelounge@next`)

---

**Comment by xPaw** [comment]
This bug stems from the fact that we use `\B` for word boundaries, and that basically detects anything not a-z0-9.

So you can trigger this bug by using any non english language too: `привет@`.

Perhaps we should change `\B` to `(^|\s)` to detect whitespace?
