### ISSUE TITLE
Support oembed for previews

### ISSUE THREAD

**Issue by fuzzy76** [thelounge/thelounge#2963]
A lot of IRC clients does atleast video playback of YouTube videos inline. One general way to solve this would be https://oembed.com/

**Comment by xPaw** [comment]
oembed directly doesn't solve this as you would still need to embed the youtube iframe (including all of its megabytes of scripts) for every video.

**Comment by fuzzy76** [comment]
Ok, inline was probably not a good idea, but when expanded, like the current preview.

It could even be done inside the popup that shows up when clicking on images.

**Comment by xPaw** [comment]
Gonna close this as duplicate of #14 to keep the discussion in one place.
