### ISSUE TITLE
Crash when running over unix socket w/o X-Forwarded-For set

### ISSUE THREAD

**Issue by metafex** [thelounge/thelounge#2966]
When running behind a reverse proxy over a unix socket, if X-Forwarded-For is not being set by the reverse proxy it crashes with this exception:

```
/tmp/thelounge/src/server.js:239
        return ip.replace(/^::ffff:/, "");
                  ^

TypeError: Cannot read property 'replace' of undefined
    at getClientIp (/tmp/thelounge/src/server.js:239:12)
    at authCallback (/tmp/thelounge/src/server.js:683:81)
    at localAuth (/tmp/thelounge/src/plugins/auth/local.js:11:10)
    at Socket.performAuthentication (/tmp/thelounge/src/server.js:728:2)
    at Socket.emit (events.js:188:13)
    at /tmp/thelounge/node_modules/socket.io/lib/socket.js:528:12
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
error Command failed with exit code 1.
```

* *Node version: v11.6.0* 
* *Browser version: Chrome 71* 
* *Device, operating system: Arch Linux* 
* *The Lounge version: 2a1e711*

**Comment by xPaw** [comment]
With `reverseProxy` Lounge expects a valid x-forwarded-for to be there, but since it's missing it fallsback to `socket.handshake.address` which I assume is undefined over unix socket.

Can you confirm it doesn't crash if you fix your reverse proxy to add the header correctly?

**Comment by metafex** [comment]
Yes, it runs perfectly as soon as X-Forwarded-For is set correctly, sorry for not including those details in the report initially.

**Comment by xPaw** [comment]
I have made a PR #2967, can you test that?

**Comment by metafex** [comment]
It works as expected. After logging in it shows 127.0.0.1 in the current sessions.
