### ISSUE TITLE
Constant ping timeouts on stable network

### ISSUE THREAD

**Issue by GaWdLy1** [thelounge/thelounge#2971]
* *Node version:* nodejs-yarn-1.9.2-1.fc29.noarch
nodejs-10.15.0-1.fc29.x86_64

* *Browser version:* Rambox (upstream Fedora chromium 71 I believe)
* *Device, operating system:* Fedora 29
* *The Lounge version:* thelounge@2.7.1

---
Ping is blocked on the network my IRC server is on. I get quite annoying timeouts every 90-120 sec. 

How can I disable the ping check? I can't find any option to do this in the prefs.

Thanks.

**Comment by xPaw** [comment]
Pings are handled by irc-framework and are done by the IRC servers, you can't disable them.
