### ISSUE TITLE
"Viewed up to" line

### ISSUE THREAD

**Issue by Daniel15** [thelounge/thelounge#2987]
### Feature Description
I'm not quite sure how to describe this, but with some chat clients, when you alt+tab away from them for a while, then alt+tab back, it keeps the scroll position exactly where it was when the window had focus, and renders a line showing where you have read up to. It'd be nice for TheLounge to have that, too.

**Comment by xPaw** [comment]
The lounge already has a "new messages" line. It however keeps the scroll at the bottom by design.

**Comment by Daniel15** [comment]
@xPaw - I just noticed that, however it seems to only display when I switch channels, not when I switch browser tabs (eg. using [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API)). Is that by design?

**Comment by MiniDigger** [comment]
which version are you on? for me it properly shows the unread marker for both when I tab out of the browser and switch to another tab.
