### ISSUE TITLE
Query Message Not Being Sent

### ISSUE THREAD

**Issue by infosisio** [thelounge/thelounge#3009]
IRCCloud and all web clients, when you do /query user "yourmessage" it will send the message after switching to that tab, thelounge doesn't, it just switches you to the tab and then you have to re-enter that message.

**Comment by xPaw** [comment]
This is an easy contribution to do for someone that wants to.

Essentially just need to merge this file https://github.com/thelounge/thelounge/blob/master/src/plugins/inputs/query.js

into this https://github.com/thelounge/thelounge/blob/master/src/plugins/inputs/msg.js

Effectively just wrapping the channel creation into an `if(cmd === "query")` just before sending a message.

**Comment by infosisio** [comment]
@xPaw If it's easy, it would be a good idea for the issue to be sorted out. Even though it may seem insignificant, it's a UX flaw for those who are trying to ditch things like IRCCloud and move to thelounge. I would do it myself if I could.

**Comment by xPaw** [comment]
I gave pointers on how to effectively solve it.

**Comment by infosisio** [comment]
@xPaw I know, I wasn't asking anything from you or anyone specifically, just added that for the record.

**Comment by infosisio** [comment]
If anyone is interested in solving this with a bounty, I am willing to deposit it on bountyissues or issuehunt. I think this is worth getting solved.

**Comment by infosisio** [comment]
@xPaw Are you one of the main project authors? 

What's wrong with doing the merge and improving the functionality of the solution, it seems to be something trivial for you?

**Comment by infosisio** [comment]
@xPaw Would you consider solving it, considering how trivial it is to you and how it would improve usability of the solution?

**Comment by xPaw** [comment]
@infosisio Pinging maintainers every few days is a quick way to get yourself blocked.

I have no interest in fixing this, another user tried to make a PR but closed it without finishing it. This is an open source project and people work on it in their free time.

**Comment by infosisio** [comment]
@xPaw Where did you see me pinging you every few days?

**Comment by Dominent** [comment]
Went through the previous pull request, updated and fixed the issue with running query without msg #3138

**Comment by Dominent** [comment]
#3138
