### ISSUE TITLE
Receiving messages in channels starting with & and + puts them in the wrong window

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge#3013]
* *The Lounge version:* v3.0.0

---

_(Feel free to rename this issue if inaccurate)_

@vivienlacourba from W3C noticed that v3.0.0 breaks sending/receiving messages from `&` channels.

This issue has already been reported (and fixed, thanks @xPaw!) in `irc-framework` and we're now just waiting for a release. I am opening this issue to keep track of the underlying problem for the v3.0.1 milestone, and/or if someone is experiencing this and doesn't find an open issue.

Related issues/PRs on [`irc-framework`](https://github.com/kiwiirc/irc-framework):
- https://github.com/kiwiirc/irc-framework/issues/185
- https://github.com/kiwiirc/irc-framework/pull/186
- https://github.com/kiwiirc/irc-framework/pull/187

**Comment by vivienlacourba** [comment]
Thanks @astorije for forwarding my report and thx @xPaw for the quick debugging.

**Comment by xPaw** [comment]
Fixed by #3040
