### ISSUE TITLE
Provide a snap package

### ISSUE THREAD

**Issue by vvug** [thelounge/thelounge#3023]
It would be great to have a snap package of thelounge distributed via snapcraft.io. Snap packages are cross-distribution and allow to install and setup *services*, something that can't be done with Flatpaks.

**Comment by astorije** [comment]
@McInkay mentioned it [a while ago](https://github.com/thelounge/thelounge/issues/414#issuecomment-227118929).

@vvug, we have packages [for Debian](https://github.com/thelounge/thelounge-deb) and [for Arch](https://github.com/thelounge/thelounge-deb) at the moment (also [some Docker stuff](https://github.com/thelounge/thelounge-docker)). Would you be open to come up and maintain what's necessary for a snap package?

**Comment by vvug** [comment]
The Debian package is not actually in good shape, in no way it could be included in the official Debian archive. A snap package would be more appropriate and cross-distribution.

Snaps are capable of setting up isolated services, something Flatpaks can't do.

**Comment by astorije** [comment]
> The Debian package is not actually in good shape

Do you have details about this? Feel free to open issues at https://github.com/thelounge/thelounge-deb/issues, that would be helpful.

**Comment by rodneyrod** [comment]
I believe someone has done some preliminary work on getting this up and running with Flatpak:

https://github.com/vrutkovs/lounge-flatpak

**Comment by Lin-Buo-Ren** [comment]
Snap packager passing by, may look into this.

**Comment by hallamjeff** [comment]
A snap package exists but has not been updated since Oct 2019 (currently version 4.0.0). If I can figure out how to make a snap I will work on publishing the latest version.

**Comment by paride** [comment]
The snap package is now well maintained. It packages what was the latest version up to 8 days ago.

**Comment by hallamjeff** [comment]
Agreed. I was looking at the wrong date. The stable channel was updated Feb 15th 2020. Recommend closing.

**Comment by xPaw** [comment]
Closing, as there's at least two packages on snapcraft.

P.S. They're not maintained by The Lounge maintainers.
