### ISSUE TITLE
Away status will appear in all channels you share with a user when opening a query

### ISSUE THREAD

**Issue by nkreer** [thelounge/thelounge#3026]
* *Node version:* 10.15.1
* *Browser version:* Firefox 64
* *Device, operating system:* macOS 10.14.2
* *The Lounge version:* 3.0.0

---

When sending a private message to a user and they are set as away, thelounge will output their away status across all chatrooms the users share on a given network. I think the intended behaviour for this feature is that the notice will only show up in the corresponding query window.

**Comment by xPaw** [comment]
I'm not entirely sure we can differentiate away-notify vs a reply to a privmsg.

**Comment by McInkay** [comment]
We could solve it using labeled-response but only on servers that support it. But that might be better than just ignoring it?
