### ISSUE TITLE
Users will get stuck at their own uploaded media on iOS 

### ISSUE THREAD

**Issue by nkreer** [thelounge/thelounge#3027]
* *Node version:* 10.15.1
* *Browser version:* Safari, iOS 12.1.2
* *Device, operating system:* iPhone 7 Plus, iOS 12.1.2 
* *The Lounge version:* 3.0.0

---

When thelounge is added to the homescreen as a webapp on iOS, using the included media uploader and opening a link generated by it, it will not open a new Safari tab, but rather loads the content in the current instance. This behaviour forces the user to quit and then re-open the app in order to get back to the IRC client. 

To circumvent this, thelounge should always open links in new windows when it's being accessed from iOS.

**Comment by xPaw** [comment]
The links already have `target=_blank` set, so they should open in a new tab.

How is this not an iOS/Safari issue?

**Comment by kgbm3** [comment]
:$ Honestly, I cringed a lil' while reading: *as a webapp on iOS*

**Comment by nkreer** [comment]
As of iOS 12.2, this is no longer a problem as Safari opens everything in native web views now that can be closed by the user.
