### ISSUE TITLE
Rewrite file uploading to use fetch()/FormData

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#3032]
Right now we use a library that sends files by manually chunking them over socket.io, but this can be done much simper by just using the old school file uploads where the browser itself will do all the necessary chunking when sending the file. Luckily all the modern browsers support `FormData` which simplifies this.

Server code would also be simplified a lot, as we won't need to need to rely on a third party library, which to be frank, has a lot of questionable decisions.

Here's how I think it should work:
- Create an express route to handle file uploads
- Over the existing socket.io connection, client asks to allow for a new file upload
- Server generates a one time use token (which can expire) and sends it to the client
- Client uses this token to upload a file to the new route

On server, we won't need to sanitize file names, as we always generate a random name for the file.

Implementing the uploading ourselves should also allow us to do stream transformation directly during the upload process (e.g. to detect jpeg files and strip EXIF data from it) without saving the file to disk and then copying it.

Potential problem: I think `fetch` is unable to provide current upload progress, but we can work this around by sending the progress over the socket.io connection.

**Comment by xPaw** [comment]
Branch: https://github.com/thelounge/thelounge/tree/xpaw-richrd/file-uploads

**Comment by Raqbit** [comment]
Funnily enough, `XMLHttpRequest` does support upload progress updates.
