### ISSUE TITLE
user-select:none breaks copying in Firefox

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#3035]
Try to copy multiple lines in chat, and if there's an expand button (links or condensed messages) it will only copy text before that.

I think this is caused by the fact that we only do `getRange(0)` here: 

https://github.com/thelounge/thelounge/blob/0f4e29d60dd923e25b9c2a47fe9dc9b129f15613/client/js/clipboard.js#L14

I haven't tested it, but if that's the case, we will need to read all of the ranges.

**Comment by xPaw** [comment]
I was wrong, it's not `user-select` that breaks it, but the mere fact that `<button>` elements are there. Setting `user-select: all` on buttons does not fix it. And `getSelection` only returns one range, so this sounds like a Firefox bug.

**Comment by xPaw** [comment]
This is a Firefox bug: https://jsfiddle.net/oyzLgrf5/

**Comment by kode54** [comment]
Firefox reports multiple `selection.rangeCount`, and returns the other ranges from `selection.getRangeAt(0...count-1)`
