### ISSUE TITLE
Support /clear

### ISSUE THREAD

**Issue by laptop006** [thelounge/thelounge#3047]
Would be nice to have support "/clear", likely just to visually hide scrollback from that point.

**Comment by xPaw** [comment]
See #1526 and #1519 for discussion on this.

**Comment by Jay2k1** [comment]
@laptop006, what is your use case for this command?

**Comment by vBm** [comment]
@Jay2k1 One of the use case where `/clear` would be needed is to destroy history when one has enabled link/image preview and someone links to nsfw content.

**Comment by Jay2k1** [comment]
You can use `/collapse` to collapse all previews (and `expand` to bring them back).

**Comment by vBm** [comment]
damn, didn't notice that, prolly overlooked it in docs. Thanks for info.

**Comment by Snuupy** [comment]
Here is my use case for `/clear`: 

Some channels have spam or zalgo text (how unfriendly). I would like to use /clear to make my screen less annoying to read, especially for channels that have useful information, but sometimes have rude users. As a comparison, IRCCloud supports `/clear` and creates a button for loading messages in the past.

I would imagine support for this implementation would be something like:
- if no scrollback has been loaded, show the "Show More" button
- once the scrollback has been triggered, continuous scrolling activates if the user scrolls to the top at any point in time
- a user entering `/clear` would (re)-disable the continuous scrolling
