### ISSUE TITLE
URL's not clickable in special cases

### ISSUE THREAD

**Issue by fnutt** [thelounge/thelounge#3052]
![skjermbilde](https://user-images.githubusercontent.com/11909212/52853351-a3977180-311b-11e9-859e-734bcb9638c7.PNG)

URL's seems to not be clickable in special cases, e.g. zero width space in front of url, or emoji. This happens atleast on a84650de/v3.0.0 vue branch, 3.0.0 and f49bf19/v3.0.0-rc.6.

**Comment by xPaw** [comment]
That's per design of the URL detection library we use https://github.com/markdown-it/linkify-it

A space is generally required.

If you think that should be changed, this issue seems to relevant https://github.com/markdown-it/linkify-it/issues/57
