### ISSUE TITLE
Chat scrolls to bottom after reconnecting to a The Lounge instance

### ISSUE THREAD

**Issue by RockyTV** [thelounge/thelounge#3117]
* *Node version:* whatever comes installed with the docker image
* *Browser version:* Bromite v73.0.3683.70
* *Device, operating system:* Xiaomi Poco F1, Android 9
* *The Lounge version:* 3.0.1

---

If you're using a device that momentarily loses connection, for whatever reason, you're connected to a The Lounge instance and you're scrolled up in a channel window, the window will scroll back down after it manages to reconnect to the instance.

I've seen it happen with XHR Poll Error iirc, it happened because my phone was changing wi-fi networks.

**Comment by xPaw** [comment]
I believe this is not an issue on master. Can you verify?

**Comment by xPaw** [comment]
@richrd says he also thinks we fixed it and can't repro.
