### ISSUE TITLE
3 min ping timeout and reconnect

### ISSUE THREAD

**Issue by Ylawy** [thelounge/thelounge#3121]
I'm using thelounge as a front-end for ZNC (v. 1.7.2).  With the latest thelounge version I'm having problems where thelounge reconnects to ZNC (via https but without a valid cert) with a constant 3 min interval to every network I'm connected to. I do know that the issue is with thelounge since any other client doesn't give me that reconnect.
This is how it looks:

`21:55 Ping timeout, disconnecting…
21:55 Ping timeout, disconnecting…
21:55 Disconnected from the network. Reconnecting in 11 seconds… (Attempt 1 of 360)
21:55 Connected to the network.
21:55 Connected to the network.
21:55 Connected to the network.`

any idea how I can deactivate the ping timeout? I couldnt find anything that is related to that in the config file.
thanks

**Comment by jordanstacy** [comment]
I'm having this same issue but am not using ZNC. Happens only on EFnet servers. I've cycled through all the various servers. I'm not seeing debug.raw in the config. Is it not exposed in the Settings screen?
