### ISSUE TITLE
"Back" from image viewer scrolls chat to bottom

### ISSUE THREAD

**Issue by dgw** [thelounge/thelounge#3130]
Reporting from mobile (Android 8.1, Chrome as homescreen icon, stable 3.0.1)

If I tap an image, and then tap outside of it, I get taken back to where I was in the chat log.

If I tap an image, then press the system Back button, I end up at the bottom of the chat log.

I think both of these should have the same result. Preferably remembering scroll position, but at least consistent.

**Comment by xPaw** [comment]
That does not appear to be happening to me on master. Can you test that?
