### ISSUE TITLE
Fix "Critical dependency" warning when running tests

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#3132]
> Warning in ./node_modules/vue-server-renderer/build.dev.js
Critical dependency: the request of a dependency is an expression

This only happens when compiling Vue test stuff with webpack.

**Comment by JessWallin** [comment]
Hi! I can take a look at this

**Comment by JessWallin** [comment]
Submitted a PR for this adding a webpack plugin to clear the warning - hope it helps!
