### ISSUE TITLE
Condensed messages container closes when updated

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#3139]
*The Lounge version:* master after vue merge

1. It has to be at the bottom
2. Open a condensed container
3. Receive another event (join/leave/etc)
4. Condensed container closes itself

What probably happens is that the `MessageCondensed` component gets re-rendered and the collapsed state gets reset:
https://github.com/thelounge/thelounge/blob/892737d1d8ade7b80fe22356a191c6715a0c08e6/client/components/MessageCondensed.vue#L39

**Comment by FryDay** [comment]
I'll take a look at this.
