### ISSUE TITLE
Do not sync the "Enable notification sound" setting across devices

### ISSUE THREAD

**Issue by vvug** [thelounge/thelounge#3144]
* *Browser version:* Chrome 73
* *Device, operating system:* Android Oreo
* *The Lounge version:* v3.0.1

The option to play a notification sound is very useful on Desktop devices, where no sound is played otherwise. When syncing the settings, the "play notification sound" setting is synced to the mobile devices too. This causes *two* notification sounds to be played on Android devices: the one of thelounge itself, and the standard notification sound of Android. This is of course quite annoying.

Can this somehow be worked around? For example by not syncing the "play notification sound" option, or by distinguishing between desktop and mobile clients?

**Comment by dgw** [comment]
Can you use Android's notification settings to silence the notifications on your mobile device?

If you're talking about the setting I think you are ("Enable notification sound" under "Browser Notifications"), that plays even if push notifications or browser notifications are disabled.

All that said, it might be more of a device-dependent thing in general, whether one wants a sound to play on highlight/PM, so I could see a case for not syncing that setting.

**Comment by vvug** [comment]
> Can you use Android's notification settings to silence the notifications on your mobile device?

Yeah this is the first thing I tried. While that option exists for "real" apps, the option is not offered it the case of the notifications generated by thelounge (that is by Chrome).

> If you're talking about the setting I think you are ("Enable notification sound" under "Browser Notifications"), that plays even if push notifications or browser notifications are disabled.

I see your point: it makes sense as an independent setting. The ideal solution would be for thelounge to be able to generate a notification *with sound*, I think.

> All that said, it might be more of a device-dependent thing in general, whether one wants a sound to play on highlight/PM, so I could see a case for not syncing that setting.

I agree!

**Comment by dgw** [comment]
> While that option exists for "real" apps, the option is not offered it the case of the notifications generated by thelounge (that is by Chrome).

So, Android makes a sound for notifications generated by websites via Chrome, but doesn't allow turning off said sound? (I knew there was a reason I always "Deny" websites asking to send me notifications…)

**Comment by vvug** [comment]
It allows to disable the notifications from thelounge altogether, but not to only mute them.

**Comment by dgw** [comment]
That sounds like a prime feature request for Chromium, honestly. Whatever The Lounge ends up doing, the lack of control on Chrome's side is a shame.

**Comment by vvug** [comment]
> That sounds like a prime feature request for Chromium, honestly. Whatever The Lounge ends up doing, the lack of control on Chrome's side is a shame.

There could be reasons for which it is not easy to implement it, I really don't know. I retitled this issue, as I think the notification sound should be a per-device setting anyway. Up to you what to do with it :)

**Comment by McInkay** [comment]
I'd be ok with that, tbh.

**Comment by xPaw** [comment]
I'm actually wondering how it plays Lounge's notification sound for you on Android. Last time I looked at it, sounds could only be played directly from a user interaction.

Perhaps we need to set `Notification.silent` if sound is enabled? https://developer.mozilla.org/en-US/docs/Web/API/Notification/silent

**Comment by astorije** [comment]
Rather than not syncing that one setting, which would be weird across laptops, should we disable this setting on mobile?

Kind of annoying that for notification badges, we use the browser feature, but for notification sounds, we play them ourselves. I don't believe there is a way around that though unfortunately.

**Comment by dgw** [comment]
> Rather than not syncing that one setting, which would be weird across laptops, should we disable this setting on mobile?

Ignore it if push notifications are enabled, _maybe_, but not just blanket disable it on all mobile devices. I don't have push notifications on because I get them from ZNC, but I do appreciate The Lounge playing a sound on my phone if I've left it open.
