### ISSUE TITLE
Suppress "Insecure Connection" warning for specific server

### ISSUE THREAD

**Issue by oemupenn** [thelounge/thelounge#3146]
### Feature Description

Being able to suppress the yellow triangle with an "Insecure Connection" notice for a specific server would be very helpful.

My particular use case is to have IRC hosted on a private network alongside TheLounge, so users have the option of having a nice web interface for our internally hosted IRC chat solution. I was going to simply set the local server in the "defaults" section and lock it down so users can only connect to our internal IRC host.

Because this is all on a private network, configuring the IRC server to use TLS with a self signed certificate does not seem to suppress the warning.

**Comment by xPaw** [comment]
The warning is there deliberately to promote secure connections the same way web browsers do it.

localhost connections are always considered secure.

If you are unable to get a valid certificate (let's encrypt is free), you can suppress it by modifying the CSS styles (either custom styles in settings, or making a theme).

**Comment by dgw** [comment]
I believe the warning is already suppressed for localhost. Maybe private IP ranges should be optionally included in that? (Optional, because some LAN environments shouldn't have unencrypted passwords flying around even just locally.)

**Comment by oemupenn** [comment]
This is not a localhost connection. TheLounge and my IRC server are separate Docker containers and share an encrypted Docker network, and only TheLounge is publicly available. Because of the private network, I don't believe you can generate a proper SSL certificate.

Thanks for the tip about modifying the CSS style.

**Comment by McInkay** [comment]
> Because of the private network, I don't believe you can generate a proper SSL certificate.

You can use DNS let's encrypt. I'm using that, and you can do it by only modifying the DNS records, you don't need the domain to resolve anywhere.

**Comment by anoma** [comment]
SSL is just one way to secure a connection. Whilst it is a valid warning for many users, IRC is as old as the hills and used in many ways well beyond the basic "SSL fixes all matra".

This should be suppressible.

**Comment by McInkay** [comment]
@anoma as has been mentioned above, it is suppressible, through css changes. If someone is technical enough to know that there are other ways to secure a connection, or to decide "I don't care, and I truly understand what I am doing when I do this" then they are technical enough to copy some CSS and paste it into the custom css in the settings. 

We do not want it to be easily accessible, as people should be dealing with this properly in 99% of cases, and making a "don't warn about insecure connections" button would make it far too easy for people who don't understand things to make a mistake.

**Comment by Addvilz** [comment]
> The warning is there deliberately to promote secure connections the same way web browsers do it.

This is not at all the same thing. Server to server communications and client to server communications is a wildly different thing. Adding a flag would be nice - I use overlay networks and see no point adding TLS on top of TLS. And above Docker use case is also valid.

**Comment by MiniDigger** [comment]
you can disable it via css, I think its
```css
.not-secure-tooltip,
.not-secure-icon {
    display: none;
}
```

**Comment by Addvilz** [comment]
Not saying you can't - you absolutely can. Just that it's a hacky way to do it and it could be done in a better way. Regardless, not a deal breaker.

**Comment by anoma** [comment]
Just to follow on and to add context since someone down voted my post.

In my use case all IRC users connect first via a VPN. Maintaining TLS in this environment is a meaningless maintenance burden which is non trivial in a walled garden.

Yes this is an edge case but as I pointed out previously, IRC is "as old as the hills" and every deployment option that can exist likely does exist :)
