### ISSUE TITLE
Update or replace css-loader and minifier

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#3154]
We currently have old version of css-loader because the major update removed a lot of stuff related to minification so we never updated.

We should keep our css deps updated to make sure it doesn't break in the future.

Some requirements:
- Emit clean css file so it can be loaded directly with a link tag.
- Minification
- Combine `@import` into one file

There's modules like postcss-loader and cssnano that can be looked at.

**Comment by ericblancas23** [comment]
I will take a look at this and make updates!
