### ISSUE TITLE
Default logging not consistent after upgrade

### ISSUE THREAD

**Issue by Wetrain** [thelounge/thelounge#3168]
Hi,

We run an instance of thelounge inside our company. 

Recently we enabled logging for all users on the latest release, but we recently did a restart, and logs were not preserved. 

The cause of the issue seems to be that the users already connected to the instance before the upgrade did not get their default logging setting set to "true".

This commit https://github.com/thelounge/thelounge/commit/4fe7dc0808732993d7a3fc63a0bd711040e37227 changed the default for LDAP users from 'dont log' to 'log'.

On upgrade to 3.0 it should have changed log to true for all ldap-derived users imo, given that was the new default.  I ended up stopping the container, running a regex over the entire folder, and restarting.

There may be a way of doing it that isn't so awful, but i couldn't find it.

Any idea if i can better document this somewhere for other users? 

Thanks

**Comment by dgw** [comment]
Sounds like expected behavior to me. Defaults apply to *new* users; existing users' settings shouldn't change because the default was updated.

**Comment by xPaw** [comment]
Defaults do not modify existing users as per the definition of the word default

**Comment by Wetrain** [comment]
It would be nice if you notified users when you change your mind on what a default is. 

We had a clear issue with users not being able to opt in to changing the default logging behaviour?

**Comment by xPaw** [comment]
Logging can be changed by the server admin. Users can't control that because it uses server resources.

**Comment by Wetrain** [comment]
Ok that is fine, but we were not alerted of this change prior to the update. How are we supposed to know that we have to reset users defaults?

All I was asking was if this could be documented for other users.

I can’t see it in the release notes?

**Comment by xPaw** [comment]
It is mentioned in the changelog.

**Comment by Wetrain** [comment]
I looked here:

https://github.com/thelounge/thelounge/releases/tag/v3.0.1

But can’t see anything?

**Comment by Zarthus** [comment]
it's a commit to the 3.0.0 version, not 3.0.1 with "Message logging is now enabled for LDAP users."

**Comment by Wetrain** [comment]
Ah ok thanks, sorry for the noise.

I came here to make sure other people didn’t have the same issue. I didn’t realise it was a 3.0.0 change, ops told me 3.0.1.
