### ISSUE TITLE
Auto Rejoin Channels

### ISSUE THREAD

**Issue by manfrin** [thelounge/thelounge#3184]
### Feature Description
I was poking around to see if the plugins featureset would be able to accomplish this, but I haven't found a way. It would be great if there were a way to **auto rejoin** channels. 

I am in some channels where there are dumb bots (e.g. roulette, pass-the-bomb, etc) where losing causes you to be kicked. mIRC has a feature where it'll rejoin on kick. I believe it's built around the event system in mIRC. I *thiiiink* I read somewhere a while ago that events were on the radar for thelounge, which would open this up pretty easy (`on('kick', () -> {rejoin()})` for example). 

Is this something that could be done, is it something that's been considered, and if it's not something planned then are there any tips you can give vis-a-vis the plugin system and how I could watch for such an event (I don't mind hacking together a plugin to do this, just not sure where the best place to start is).

Thank you,

**Comment by manfrin** [comment]
So looking in to the plugins a bit more, I noticed the irc-events folder (not sure how I missed that before). 

I believe that I could, naively, add `irc.join(chan.name)` in `kick.js` for the block handling when the kicked user is the irc user, which would end up looking like:

```
		if (data.kicked === irc.user.nick) {
			chan.users = new Map();
			chan.state = Chan.State.PARTED;

			client.emit("channel:state", {
				chan: chan.id,
				state: chan.state,
			});
               // vvvvvvvvvvvvvvv
               irc.join(chan.name)
               // ^^^^^^^^^^^^^
		} else {
			chan.removeUser(msg.target);
		}
```

Ideally I know I'd want to move this out in to its own module, and to conditionally rejoin based on a config. I also feel I need to let the `kick.js` handler finish executing before rejoining, so it doesn't cause state issues -- this would mean I'd want to emit a message from `kick.js` (`"kicked"`?) that I would then listen for in my join-after-kick handler, but this is where I get stuck. I'm having trouble sussing out how to handle internal messaging gracefully. Could I do a `client.emit("kicked")`? But how would I then listen? `network.on` or `irc.on`? 

For now, would something like this work:

In `plugins/irc-events/kick-rejoin.js`
```
"use strict";

const Chan = require("../../models/chan");
const Msg = require("../../models/msg");

module.exports = function(irc, network) {
	const client = this;

	irc.on("kick", function(data) {
		const chan = network.getChannel(data.channel);

		if (typeof chan === "undefined") {
			return;
		}

    if (data.kicked === irc.user.nick) {
      irc.join(chan.name)
    }
});
```

**Comment by xPaw** [comment]
Plugins are planned. See https://github.com/thelounge/thelounge/projects/4

Auto rejoining on kick breaks the concept of kicking and not something this client will do.
