### ISSUE TITLE
Enter/Return key causes line break instead of message sending in Firefox 66.0.3

### ISSUE THREAD

**Issue by StraToN** [thelounge/thelounge#3185]
* *Node version:* 8.2.0
* *Browser version:* Firefox 66.0.3 (updated on 23/04/2019)
* *Device, operating system:* Server : Ubuntu server 16.10 / Client : Ubuntu 18.10
* *The Lounge version:* Latest release (3.0.1)

---

Hitting the Enter key on Firefox 66.0.3 does not send the message to the channel. Instead it triggers a line-break.
Besides, clicking the "send message button" actually seems to reload the page.

I tested this before and after updating Mozilla Firefox and I can confirm it was working fine before updating.

**Comment by xPaw** [comment]
Not The Lounge's fault.

See https://github.com/keepassxreboot/keepassxc-browser/issues/481

**Comment by StraToN** [comment]
Indeed, disabling KeepassXC's Firefox extension solves the problem. Thanks!
