### ISSUE TITLE
/away doesn't unset away status

### ISSUE THREAD

**Issue by klausenbusk** [thelounge/thelounge#3189]
* *Node version:* `v10.15.1`
* *Browser version:*  `Firefox Nightly 68.0a1 (2019-04-23) (64-bit)`
* *Device, operating system:* `Laptop - Arch Linux`
* *The Lounge version:* `v3.0.1` (Docker `thelounge/thelounge:latest`)

---

Running `/away` doesn't unset the away status.

**Comment by dgw** [comment]
Duplicate of #870, I think.

**Comment by klausenbusk** [comment]
> Duplicate of #870, I think.

You are definitely correct. Sorry for the noise
