### ISSUE TITLE
Reconnect with exponential backoff and only with a working network

### ISSUE THREAD

**Issue by amyspark** [thelounge/thelounge#3190]
Hi all!

### Feature Description

I'd like The Lounge to reconnect to existing networks with exponential backoff, and detect (if it is possible) when there is no connection available.

### Rationale

Currently, I use this app on a Macbook, which is pretty aggressive when it comes to sleeping. When I wake it up, I get a wall of error messages and I realise it had been trying to reconnect while the WiFi was off. IIRC, The Lounge currently uses 360 tries with 10-sec constant backoff.

**Comment by dgw** [comment]
Arguably, the best solution for this is to run The Lounge on a machine that is always running and (ideally) always connected, and merely access the client from your MacBook.

But there's still a use for exponential backoff, and even more use for detecting when the local machine's network is offline.

If you have an always-on machine available to you, consider it a workaround? At least until this idea is developed (if accepted).

**Comment by amyspark** [comment]
@dgw, yes, it's actually not an issue. I think this would be just an improvement over the existing situation (which is vastly better than what I used to have).

**Comment by xPaw** [comment]
Theres already an open issue about exponential back off in the irc-framework repo. You can create a separate one there for network availability checking.
