### ISSUE TITLE
Ability to connect Imgur API for uploading photos

### ISSUE THREAD

**Issue by mhajder** [thelounge/thelounge#3192]
### Feature Description
Then everyone in the settings on the user's side could set their own api key and upload photos to their own account.
Of course, you would also be able to disable this on the server side in the config.

**Comment by fnutt** [comment]
This is a good example of a feature that will fit perfectly in a future plugin for The Lounge.

**Comment by dgw** [comment]
Yup. I've always been under the impression that The Lounge's file upload feature will be pluggable in a future release, so we can use alternate hosting.

**Comment by xPaw** [comment]
Closing as this won't be done in core, and is well suited for the plugin system as others have said.
