### ISSUE TITLE
Skip printing local user JOIN and topic message when joining a channel

### ISSUE THREAD

**Issue by amyspark** [thelounge/thelounge#3193]
### Feature Description

It would be great if we could turn off JOIN and TOPIC messages when joining a channel.

### Rationale

Related to #3190 , if one is on a flaky network or with an aggressive battery-saver OS, every time The Lounge reconnects these message are printed to the channel buffer.
In my case they make up the great bulk of logs in certain low-traffic channels.
At present, only MOTD at server login can be skipped.

**Comment by xPaw** [comment]
I don't really see a way of reliably filtering these, and it can be weird if we start internally filtering out certain messages.

@McInkay What do you think about this?

**Comment by McInkay** [comment]
I agree that filtering these out would be silly.

However, I'm a bit confused as to why these are printing often. They shouldn't be printing when you connect to thelounge. Unless you are in public mode, I guess. If you are in private mode, they should only do it once when thelounge connects to the server.

**Comment by xPaw** [comment]
Lounge prints them because you reconnect to the server and get fresh topic and join messages.
