### ISSUE TITLE
Incorrectly using "Nick" instead of "Username" when logging in to SASL server

### ISSUE THREAD

**Issue by rappo** [thelounge/thelounge#3197]
* *Node version:* 
```
# node --version
v10.15.1  
```

* *Browser version:* 
```
Chrome Version 74.0.3729.131 (Official Build) (64-bit)
```

* *Device, operating system:* 
```
Windows 10 Pro 1809
```

* *The Lounge version:* 
```
# thelounge --version
v3.0.1 
```

---

I have a private server that requires SASL to log in. If I set my username and password correctly, login fails. If I set my Nick to my user, login succeeds. The workaround right now is to set my Nick to my username, log in, and then change my nick after.

- [ ] SASL should use the Username field for login purposes.

**Comment by richrd** [comment]
The Lounge uses irc-framework which has a related issue here: https://github.com/kiwiirc/irc-framework/issues/103

**Comment by xPaw** [comment]
Closing as this is mostly an irc-framework issue.

**Comment by xPaw** [comment]
This is now fixed on master, you can specify SASL credentials separately.
