### ISSUE TITLE
Do not send notifications while receiving a chat history batch

### ISSUE THREAD

**Issue by amyspark** [thelounge/thelounge#3203]
* *Node version:* 10.15.2
* *Browser version:* Firefox 68.0a1 (Nightly 2019-05-07)
* *Device, operating system:* MacOS High Sierra 10.13.6
* *The Lounge version:* 3.0.1

---

I recently joined a server which support the `batch` and `chathistory` capabilities. When I join a channel, I get the past 12h worth of logs. This is a lot, and while The Lounge receives them it spams me with push notifications until the final count of unread messages is obtained (which is usually only a few messages).

Would it be possible for you to block push notifications while processing a batch?

**Comment by xPaw** [comment]
> I recently joined a server which support the batch and chathistory capabilities.

Lounge doesn't support chathistory, so the server is just sending you the history as normal messages.

If the message server-time is older than 15 minutes, no push notification is triggered.
