### ISSUE TITLE
Freshly upgraded via git pull & npm install — Uncaught TypeError: Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by thistehneisen** [thelounge/thelounge#3208]
* *Node version:* v11.13.0
* *Browser version:* Google Chrome Version 74.0.3729.131 (Official Build) (64-bit)
* *Device, operating system:* (Server) Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux (Client) Darwin nilsdigital.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
* *The Lounge version:* The Lounge source (63fc320a / v3.0.1) (Node.js 11.13.0 on linux x64)

---

<img width="1680" alt="Screenshot 2019-05-09 at 11 01 29" src="https://user-images.githubusercontent.com/6432992/57437131-d1d3ab80-7249-11e9-935d-b34a33b34612.png">

**Comment by McInkay** [comment]
Have you re-run `npm run build`?

**Comment by thistehneisen** [comment]
Thanks, that fixed it.
