### ISSUE TITLE
Not saving networks in user config

### ISSUE THREAD

**Issue by willfurnell** [thelounge/thelounge#3211]
* *Node version:* v10.15.3
* *Browser version:* Firefox 66.0.5
* *Device, operating system:* Server: Debian 9.9, client Mac OS X
* *The Lounge version:* v3.0.1

---

Hi,

It appears that thelounge is not saving my networks and channels in my user configuration file. I've installed it via the global install instructions, but every time the server is restarted, all information about networks/channels is lost, and I can see these haven't been added to the config file. The user itself and password remains.

Thanks,
Will.

**Comment by xPaw** [comment]
Either you're not using private mode, or there are permission issues (see stderr of lounge).

**Comment by willfurnell** [comment]
Ah yeah thanks, the file was owned by root - I didn't think to check that as auth worked fine!
