### ISSUE TITLE
Allow user remove to be run against LDAP users

### ISSUE THREAD

**Issue by thinkl33t** [thelounge/thelounge#3221]
When an user is disabled in LDAP, the user's thelounge user will remain connected to their IRC networks until the server is next restarted.

User commands don't work on LDAP users, however It would be useful in the above situation to specifically allow users to be removed on the command line when LDAP is enabled.  

I suspect this conditional would just need to be modified a bit https://github.com/thelounge/thelounge/blob/master/src/command-line/index.js#L40

**Comment by xPaw** [comment]
I wonder, can't we just enable all user commands for LDAP?

I can only think of `reset` command being useless.
