### ISSUE TITLE
Control re-connection attempts after ping timeout

### ISSUE THREAD

**Issue by Frotty** [thelounge/thelounge#3244]
Hi, I have had the issue multiple times now, that when my server loses connection to the IRC server, in this case Quakenet, it tries to reconnect all clients at the same time.
This causes my server IP to be g-lined because of too many connections:

```
13:20 [465] Too many connections from your host (xxx) - see https://www.quakenet.org/help/trusts/connection-limit for details.
13:20  Disconnected from the network. Reconnecting in 11 seconds… (Attempt 1 of 360)
13:21  Connected to the network.
13:21 <irc.quakenet.org>  *** Looking up your hostname
13:21 <irc.quakenet.org>  *** Checking Ident
13:21 <irc.quakenet.org>  *** Your forward and reverse DNS do not match, ignoring hostname.
13:21 <irc.quakenet.org>  *** No ident response
13:21 [465] Too many connections from your host (xxx) - see https://www.quakenet.org/help/trusts/connection-limit for details..
13:21  Disconnected from the network, and will not reconnect. Use /connect to reconnect again.
```

And then thelounge never attempts to connect again, even tho manually it works after 15-20 minutes.

Thus my request is an option to control the amount and wait duration between reconnects and to not reconnect all clients at the same time.

**Comment by timokroeger** [comment]
I have a similar issue, where the lounge reconnects with a different nickname (because the previous one is still in use) after my DSL connection dropped.
This issue can also be solved by a configurable reconnect time.

**Comment by xintron** [comment]
An exponential backoff reconnect strategy would be good to have with a configurable max interval (and a sane default value). Just as mentioned above, if retrying to connect and eventually end up retrying every 1h (or configured interval) it would help scenarios where a user is temporarily g-lined or if the server is undergoing maintenance.

**Comment by xPaw** [comment]
See https://github.com/kiwiirc/irc-framework/issues/140

**Comment by xPaw** [comment]
Gonna close this, as it will be solved on irc-framework side: https://github.com/kiwiirc/irc-framework/pull/248
