### ISSUE TITLE
Difficulties while installing

### ISSUE THREAD

**Issue by ThijsEigenwijs** [thelounge/thelounge#3263]
* *Node version: v12.4.0* 
* *Browser version: not applicable* 
* *Device, operating system: Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 * 
* *The Lounge version: 3.0.1-1 and 3.0.0-1* 

I've been trying to install the lounge on my VPS, but it constantly gives an error.
I tried to install it using yarn, but then it states 
`2019-06-17 16:19:00 [ERROR] Unable to load sqlite3 module. You might need to install it manually.
2019-06-17 16:19:00 [INFO] The Lounge v3.0.0 (Node.js 12.4.0 on linux x64)
2019-06-17 16:19:00 [INFO] Configuration file: /etc/thelounge/config.js
2019-06-17 16:19:00 [ERROR] Error: listen EADDRINUSE: address already in use :::9000
2019-06-17 16:19:00 [WARN] Config file owner does not match the user you are currently running The Lounge as.
2019-06-17 16:19:00 [WARN] To avoid issues, you should execute The Lounge commands under the same user.`

But netstat shows no outgoing connection on the port 9000.

If i remove thelounge-yarn and try to install it any other way i get this error
(pastebin cause its soo much: https://pastebin.com/xBTgspZW)

Can someone help me

**Comment by Jay2k1** [comment]
The sqlite3 module is for storing messages to a sqlite database, so they can be reloaded when you restart your thelounge instance and don't lose all backlog in the clients. It is not necessary but certainly nice to have. 

As for the EADDRINUSE: You said netstat wouldn't report any outgoing connection, but you should rather check for listen ports, using the ´-l´ for switch. Try `netstat -tlpn | grep 9000` and see what happens.

Also pay attention to which user you are running thelounge as. The config files (and their folder) need to be writable by that user, hence the last warning.

**Comment by ThijsEigenwijs** [comment]
Thanks, it was used by php-fsm, thanks!
(i changed the port in config file)
