### ISSUE TITLE
demo.thelounge.chat The certificate has expired

### ISSUE THREAD

**Issue by TheXaver** [thelounge/thelounge#3265]

**Comment by dbolton** [comment]
When I visit: https://demo.thelounge.chat/  it says: 

Did Not Connect: Potential Security Issue

Firefox detected an issue and did not continue to demo.thelounge.chat. The website is either misconfigured or your computer clock is set to the wrong time.

It’s likely the website’s certificate is expired, which prevents Firefox from connecting securely.

What can you do about it?

demo.thelounge.chat has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

Your computer clock is set to Monday, July 29, 2019. Make sure your computer is set to the correct date, time, and time zone in your system settings, and then refresh demo.thelounge.chat.

If your clock is already set to the right time, the website is likely misconfigured, and there is nothing you can do to resolve the issue. You can notify the website’s administrator about the problem.
