### ISSUE TITLE
Change password for server is not storing the new password

### ISSUE THREAD

**Issue by mellowcandle** [thelounge/thelounge#3269]
User password (the one that identifies against nickserv) is unchangeable from UI.
When I change it and open the channel configuration again, I see the old password.

* *Node version:* 
v12.4.0
* *Browser version:* 
Version 71.0.3578.98 (Official Build) (64-bit)
* *Device, operating system:* 
PC, Linux (Ubuntu)
* *The Lounge version:* 
v3.1.0-pre.2 
---

**Comment by xPaw** [comment]
Verify your permissions. User running lounge should be able to write to the configuration files.

**Comment by mellowcandle** [comment]
Which permissions, of the user that run the server ? (it's root)

**Comment by xPaw** [comment]
The user that runs the lounge.

**Comment by xPaw** [comment]
Does it close the edit window after pressing save?
If you reload the page do you still see the old password?
Have you tried another browser?
Do you see any errors in browser console?

**Comment by mellowcandle** [comment]
Does it close the edit window after pressing save? Yes
If you reload the page do you still see the old password? Yes.
Have you tried another browser? 
Chrome Version 74.0.3729.169 (Official Build) (64-bit) has the same issue
Do you see any errors in browser console?
Nope, empty.

**Comment by xPaw** [comment]
Try another browser that isn't Chrome. Make sure it's not extension interfering.

It works fine for me in Chrome though.

**Comment by mellowcandle** [comment]
Alright ! It was Lastpass, don't understand why, perhaps it fills in the password even though it's prefilled by lounge.

**Comment by xPaw** [comment]
Report this to LastPass.
