### ISSUE TITLE
Email or similar notifications when away

### ISSUE THREAD

**Issue by clawoflight** [thelounge/thelounge#3278]
With weechat, I can use screen_away.pl to set myself away whenever I detach tmux.
Then, email_away_highlights.py sends me emails while I am away for three cases:

- private messages
- mentions
- custom keywords

The first two are very important for me, especially when posting a question into a high-latency channel or one in a different timezone.

**Comment by MiniDigger** [comment]
lounge does support browser notifications via a service worker.  that means, if you subscribe to notification on a device, you will receive them even if you don't have the tab open (or in case for mobile, the browser open).
for example, if you open your thelounge instance on mobile and subscribe to notifications in the settings, you will receive push notifications whenever someone pings you, sends you a private message or one of your custom keywords are triggered (altho I am no 100% sure custom keywords work)

**Comment by xPaw** [comment]
Push notifications cover the use case of "highlights when away".

Email specifically is something that could be done as a plugin (when possible).
