### ISSUE TITLE
Can't send command while not being connected to a irc server

### ISSUE THREAD

**Issue by MiniDigger** [thelounge/thelounge#3284]
* *Node version:* 10.16.0
* *Browser version:* chrome 75
* *Device, operating system:* wsl
* *The Lounge version:*  3.1.0 rc1

---

As the title says, thelounge doesn't accept commands to be send when not being connected to a irc server. while that might have made sense in the past, where all commands where irc commands, with the introduction of plugins this doesn't make much sense anymore as plugins might still be able to work without irc connections, they should be responsible for checking that themselves.

**Comment by xPaw** [comment]
Exporting `allowDisconnected = true` does this.
