### ISSUE TITLE
Add secure WEBIRC support for UnrealIRCd

### ISSUE THREAD

**Issue by finalhit** [thelounge/thelounge#3302]
In src/models/network.js Network.prototype.createWebIrc should pass info if connection is secure.

First needs to be fixed:
https://github.com/kiwiirc/irc-framework/issues/135

**Comment by xPaw** [comment]
I made a irc-fw pr: https://github.com/kiwiirc/irc-framework/pull/230

And a branch to support that in TL: https://github.com/thelounge/thelounge/tree/xpaw/fix-3302

Would you be able to test this?

**Comment by xPaw** [comment]
Code in TL was merged, but we still need the irc-framework update for this to work.
