### ISSUE TITLE
Option to stop condensing messages

### ISSUE THREAD

**Issue by finalhit** [thelounge/thelounge#3303]
It would be nice to introduce option in config.js to stop condensing messages like "2 user has joined, and 1 user has left".

It looks very unintuitive on mobile phones.

Also the message "1 user has joined" is strange, because it occupies single line, just like the message being condensed.

**Comment by Jay2k1** [comment]
Someone is working on a better version of the condensing in #1685.

As for a config option: You can choose to disable condensing in your settings:
![image](https://user-images.githubusercontent.com/2070503/61174376-6ab2da00-a59f-11e9-840e-b989a7bc5141.png)

**Comment by finalhit** [comment]
Is it possible to disable it in config.js?

Would like to configure default values for statusMessages, desktopNotifications, notifyAllMessages, showSeconds in config.js.

**Comment by xPaw** [comment]
It isn't, why do you want to change them in config.js?

**Comment by finalhit** [comment]
For the same reason users can change them.

The majority of users won't go to Settings, so would like to set default values I think are the best for them.

In this particular example, I would like to set "statusMessages": "shown".
