### ISSUE TITLE
Scrolling channel list no longer works on some touch devices after #3297 PR

### ISSUE THREAD

**Issue by kode54** [thelounge/thelounge#3309]
* *Node version:* v11.15.0
* *Browser version:* Mobile Safari
* *Device, operating system:* iPad 2018 running iOS 12.3.1
* *The Lounge version:* v3.0.1-617-g01347787

---

When operating this version of Lounge that I just updated to last night, on my iPad, it is impossible to change chats from whatever was last viewed on a desktop, or scroll in the chat list. It behaves as if I am simply “hovering” a cursor over the list when I move my finger over the list.

**Comment by MiniDigger** [comment]
can you install 3.1.1 and try again? 3.1 completely rewrote the chat view

**Comment by xPaw** [comment]
Your commit `01347787` seems to be last master, but the `v3.0.1-617` is completely wrong. Make sure your own git is correctly up to date and you have rebuilt the client correctly.

Also try the default theme in lounge, and try another browser.

**Comment by kode54** [comment]
There is no other browser for iOS. By requirement of Apple, all third party browsers must use the system WebKit engine.

I don’t usually do a fetch --tags to update my tags.

**Comment by xPaw** [comment]
> As I said, it's not the chat view that's broken, it's the chat list on the left. 

Call it channel list.

> Could be #3297

Very possible, if pointerType or the filter event does something weird in Safari. Try getting devtools to work and see if there's any errors.

**Comment by xPaw** [comment]
Can you test this change?
```diff
diff --git a/client/components/NetworkList.vue b/client/components/NetworkList.vue
index 83a4e617..0a19ac60 100644
--- a/client/components/NetworkList.vue
+++ b/client/components/NetworkList.vue
@@ -9,6 +9,7 @@
 		v-else
 		:list="networks"
 		:filter="isCurrentlyInTouch"
+		prevent-on-filter="false"
 		handle=".lobby"
 		draggable=".network"
 		ghost-class="ui-sortable-ghost"
@@ -52,6 +53,7 @@
 				drag-class="ui-sortable-dragged"
 				:group="network.uuid"
 				:filter="isCurrentlyInTouch"
+				prevent-on-filter="false"
 				:list="network.channels"
 				class="channels"
 				@change="onChannelSort"
```
