### ISSUE TITLE
IDN-URL gets pasted encrypted by file upload

### ISSUE THREAD

**Issue by Lucki** [thelounge/thelounge#3322]
- _Node version:_ 8.10.0
- _Browser version:_ FF 68.0.1
- _Device, operating system:_ CentOS 6
- _The Lounge version:_ 3.1.1

---

While using TheLounge with a [Internationalized domain name URL](https://en.wikipedia.org/wiki/Internationalized_domain_name) and uploading a file the resulting pre-pasted url into the input field contains the url in the encrypted version instead of the human readable version.

Using the example of wikipedia:
- _TheLounge_url:_ `thelounge.bücher.example`
- _Pre-pasted_url:_ `thelounge.xn--bcher-kva.example/uploads/…`
- _expected_url:_ `thelounge.bücher.example/uploads/…`

**Comment by xPaw** [comment]
We use browser APIs to handle the URLs and they deal with punycode. I don't think we can easily (or safely) convert it back to 'human' form. This also helps with compatibility with other IRC clients which may not deal with internationalized domains correctly. As such I will close this issue, as I don't think we'd change this behaviour.

For reference:
```js
new URL("https://thelounge.bücher.example").href
"https://thelounge.xn--bcher-kva.example/"
```

**Comment by Lucki** [comment]
Sad, IMHO the user should always see the readable format. But I can see that it's not easily possible without an [external librarie](https://github.com/bestiejs/punycode.js/). Would be nice to have an internal function like [`decodeURI`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI) to make access to them easy.
