### ISSUE TITLE
Option to disable emoji replacement

### ISSUE THREAD

**Issue by igalic** [thelounge/thelounge#3324]
### Feature Description

currently, emoji use EmojiOne as font, and are replaced with with images + alt-text.

I'd like to have an option (config or UI doesn't really matter) to disable that feature and simply use the system native Emoji font.

**Comment by xPaw** [comment]
The Lounge does nothing that you describe. Check your browser extensions.

**Comment by igalic** [comment]
what about this? 
https://github.com/thelounge/thelounge/blob/9ef5c6c67e463c1f401e33b21dfb5641636e5ed1/client/js/libs/handlebars/parse.js#L142-L159

**Comment by xPaw** [comment]
That just wraps the emoji into a class so it can be styled. We don't use emojione.

**Comment by igalic** [comment]
Thank you very much for the explanation, and sorry about opening this issue.

First off, i misidentified the font: It's "Twemoji Mozilla".
and secondly, it's a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1567856
