### ISSUE TITLE
Is thelounge working on Mac OSX?

### ISSUE THREAD

**Issue by dmitriz** [thelounge/thelounge#3332]
- _Node version:_ 10.16.0
- _Browser version:_ Firefox 48.0.2/ Chrome 49.0.2623.112
- _Device, operating system:_ MacBook Pro, OSX 10.8.5
- _The Lounge version:_ 3.1.1

---

I have just installed `thelounge` via `yarn add global thelounge`, no errors.

However, running it seems to produce errors in my browser.
In console:

```sh
~ thelounge start
2019-07-25 13:34:19 [INFO] The Lounge v3.1.1 (Node.js 10.16.0 on darwin x64)
2019-07-25 13:34:19 [INFO] Configuration file: /Users/dmitrizaitsev/.thelounge/config.js
2019-07-25 13:34:19 [INFO] Available at http://:::9000/ in private mode
2019-07-25 13:34:19 [INFO] There are currently no users. Create one with thelounge add <name>.
```

The cursor appears right below the last line with no time prefix and reacts with empty output to any command.

Viewing http://localhost:9000/ in my Firefox browser, I see the following error message:

```
SyntaxError: missing = in const declaration
```
while in Chrome the message is different:
```
Uncaught SyntaxError: Invalid regular expression flags
```

The Chrome console output:
```
Uncaught SyntaxError: Invalid regular expression flags
service-worker.js:45 

Uncaught SyntaxError: Unexpected token function
undefined:1 

Uncaught (in promise) DOMException: Failed to register a ServiceWorker: ServiceWorker script evaluation failed
```

Meanwhile the Node console remains completely silent.

Any direction what is wrong here or what else to check?

**Comment by xPaw** [comment]
You have very outdated browsers.

**Comment by dmitriz** [comment]
Yes and I cannot update them without upgrading my OS. :(

But there is also no prompt in my terminal console, 
which cannot be related to my browser. Is this normal?

**Comment by MiniDigger** [comment]
there is no promt, yes. 
there is a cli you can use however: https://thelounge.chat/docs/usage
