### ISSUE TITLE
generate nickname colors based on pure randomness instead of the nickname hash

### ISSUE THREAD

**Issue by tokariu** [thelounge/thelounge#3346]
currently, I always get the same nickname color (unfortunately pink, which I don't like).

as seen in the code here: https://github.com/thelounge/thelounge/blob/9ef5c6c67e463c1f401e33b21dfb5641636e5ed1/client/js/libs/handlebars/colorClass.js
the nickname colors are generated from the nickname hashes and if you don't change your nickname, it will always get the same color...

it would be better to either:
- generate nickname color from pure randomness.
- have an option to decide between pure randomness or nickname hash.
- have an option to statically define the own-nickname-color.

**Comment by xPaw** [comment]
They're generated from nick to stay consistent, otherwise it would be a complete mess of constantly changing colors. Even if you keep a list of generated colors for each user, that would be lost on page reload.

**Comment by tokariu** [comment]
@xPaw and having a look at the 3rd option? a statically defined own-nick color?

**Comment by xPaw** [comment]
You can achieve that easily with CSS.

```css
#chat .self .from .user {
    color: blue;
}
```

**Comment by tokariu** [comment]
that's it, alright :)
