### ISSUE TITLE
Input history lost on front-end reconnect

### ISSUE THREAD

**Issue by dgw** [thelounge/thelounge#3350]
- _Node version:_ 10.12.0
- _Browser version:_ Chrome 75
- _Device, operating system:_ Windows 10 Pro, version 1903; Asus Zenbook 15 notebook
- _The Lounge version:_ 3.1.1

---

When The Lounge loses connection to its server (i.e. wireless connection drops for a moment), all input history is cleared after it reconnects. The last time this happened, I had just sent a message into the void before TL realized it had lost connection, and it was not possible to simply press the up arrow and send it again as I used to do with TL pre-3.1 in similar situations.

Under The Lounge 3.0, I don't remember this happening. Maybe a regression in the Vue rewrite? I guess there had to be some kind of trade-off for per-window history.

**Comment by xPaw** [comment]
Please test v3.2.0-rc.1, it shouldn't happen there, as the reconnection stuff changed a bit.

**Comment by dgw** [comment]
Bit harder to test than I expected because of [this nearly five-year-old Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=423246), but I did work around that with multiple LAN devices. Confirmed that in v3.2.0-rc.1, input history appears to be kept after the frontend reconnects. Or at least, "Works on my machine." Thanks!
