### ISSUE TITLE
send parameters from url (eg: user/password/invite code etc)

### ISSUE THREAD

**Issue by ERR1R** [thelounge/thelounge#3354]
it would be nice if you can send url parameters from a website with a button..

eg: I have a website and i only want to run the irc deamon on my site for my network.

- i want that logged in users just click a button to join my irc server with the username already filled from the url they click with a button.
- send some invite code to an eggdrop bot from that same url

etc..

**Comment by xPaw** [comment]
https://thelounge.chat/docs/guides/network-overrides

**Comment by ronilaukkarinen** [comment]
@xPaw Is there an option to autoconnect with url parameters? Now it just prefills the form and still needs to click the connect button. What I'd like is that this link would automatically connect the channels: https://demo.thelounge.chat/#/connect?join=foo,bar without that extra button click. Any parameter or way to achieve this?

**Comment by MaxLeiter** [comment]
@ronilaukkarinen we don't have plans to support auto-connect due to it's likelihood for abuse

**Comment by ronilaukkarinen** [comment]
@MaxLeiter I understand the general concern but If it's well validated / nonce etc and only these same certain options allowed how would it be abused exactly?
