### ISSUE TITLE
lockNetwork is true, but /connect still works

### ISSUE THREAD

**Issue by Y4kuzi** [thelounge/thelounge#3376]
/connect still works even with lockNetwork set to true, so users can connect to other servers with my servers' IP address and abuse it.

- _Node version:_ v8.10.0
- _Browser version:_ any
- _Device, operating system:_ Ubuntu 18.04
- _The Lounge version:_ v3.2.0

---

**Comment by xPaw** [comment]
Can't reproduce. It creates a new network (expected) but connects to the locked network.

**Comment by Y4kuzi** [comment]
You are correct, I think I was blind for a second. My apologies.
