### ISSUE TITLE
TL stops reconnecting on some errors while it should continue to reconnect.

### ISSUE THREAD

**Issue by tokariu** [thelounge/thelounge#3419]
example:

I'm re-connecting to the irc network after my connection has been lost or dropped (connection reset by peer case again).
So my old connection is still alive on the irc-server and it needs a few more minutes until it ping-timeouts. until then, the irc-server doesn't allow me to connect with the same ip-address, because it allows only one connection per ip-address.

when I try to connect, this is what happens:

```
[020] * Please wait while we process your connection.
mynick: Nickname is already in use.
Closing Link: mynick[unknown@ip.host.com] (Too many host connections (local)) (irc)
Disconnected from the network, and will not reconnect. Use /connect to reconnect again.
```

At this point The Lounge does not try to reconnect anymore. it stays offline indefinitely.
But it should try reconnecting! After a few minutes the old connection drops out and I would be able to reconnect.
This way however, I'll stay offline forever until someday I manually login to the lounge and type /connect. Needless to say that I expected to be able to read the irc/chan history when I came back, but TL wasn't connected, so there is nothing to read.

summa summarum: The lounge needs to try reconnecting at an interval of like one to five minutes when the error is "too many host connections (*)"

**Comment by xPaw** [comment]
irc-framework handles reconnections, so create the issue there please: https://github.com/kiwiirc/irc-framework

As far as reconnections go, it will not reconnect if initial connection failed (registration failed).
