### ISSUE TITLE
IPv4 precedence over IPv6 when connecting to network

### ISSUE THREAD

**Issue by gschanuel** [thelounge/thelounge#3420]
- _Node version:_ v12.10.0
- _Browser version:_ Firefox 69.0
- _Device, operating system:_ Archlinux (on server and client)
- _The Lounge version:_ v3.2.0

My internet connection has an IPv6 and a CGNAT ipv4.
When connecting to chat.freenode.net, thelounge tries to connect via ipv4 by default.
If I edit the Network and put the IPv6 on the server, it does not connect due to ssl.

TheLouge should try to connect first with IPv6 when available

Since the public ipv4 is shared among other people, it got listed on DroneBL.

**Comment by xPaw** [comment]
It's mostly Node that decides which IP to connect to, as the hostname is passed into `net` or `tls` as-is.

See https://github.com/kiwiirc/irc-framework/blob/1b9263ed59fc19f60c121e6ea5e88141a64bc9b5/src/transports/net.js#L104-L122

If you set ipv6 in `bind` in TL's config, it should work.

**Comment by gschanuel** [comment]
> If you set ipv6 in `bind` in TL's config, it should work.

OK, setting my public ipv6 in bind worked, the problem is my ip is dynamic. When I tried "::1" it could not connect.

**Comment by sfan5** [comment]
I have patched my local thelounge install like this:
```diff --git a/index.js b/index.js
index 7c00d1e7..fcfbfe1a 100755
--- a/index.js
+++ b/index.js
@@ -4,6 +4,8 @@
 
 process.chdir(__dirname);
 
+require("dns").setDefaultResultOrder("verbatim");
+
 // Perform node version check before loading any other files or modules
 // Doing this check as soon as possible allows us to
 // avoid ES6 parser errors or other issues
```

If this is considered generally desirable behaviour this change can easily be applied upstream.

**Comment by brunnre8** [comment]
Can you send a proper PR please?

**Comment by sfan5** [comment]
Sure.
