### ISSUE TITLE
Notify on user connection

### ISSUE THREAD

**Issue by azlux** [thelounge/thelounge#3429]
### Feature Description
It's would be great if we can have a notification for specific user connection ?
I want to speak to someone not always connected. Currently I send a message to check if he is connected.

On Hexchat, I was using the feature `/notify` for that.
This feature allow me to set a notify event when this user will be connected.

**Comment by McInkay** [comment]
I feel like this is not something we'll put in core, but this would work really well as a plugin.

@xPaw any objection to closing and suggesting someone make a plugin if they want this feature? (Obviously, opening an issue if we are missing a feature for the plugin to work)

**Comment by xPaw** [comment]
Agreed.

What we'd put in core would be #337 to display user connects/quits in query window, but that wouldn't trigger a notification.

**Comment by McInkay** [comment]
Cool. I'll close this now.

If anyone creates such a plugin, and has any questions, feel free to ask in IRC or create an issue if there's a missing plugin API.

**Comment by azlux** [comment]
Hi, thanks for all the answers.

Is there are any places I can ask for plugins ?
I'm not able to do it on my own.

**Comment by McInkay** [comment]
Probably our IRC channel (#thelounge on freenode) is the best place to see if anyone wants to work on it.
