### ISSUE TITLE
Add a close button when hovering a channel

### ISSUE THREAD

**Issue by alexherbo2** [thelounge/thelounge#3456]
A close button is only displayed for the active channel.  So in order to leave a channel, we have to switch to it beforehand.  It would be nice to be able to leave a channel on hovering, by drawing a close button for example.

**Comment by MaxLeiter** [comment]
This was the old behavior but it was removed as it was easy to accidentally close when you meant to switch. You can use context menus to close the channel without opening it, although I guess that's the same amount of clicks as switching channels.

**Comment by dgw** [comment]
This was a feature of older versions, and was intentionally removed: #61

**Comment by xPaw** [comment]
See linked issues for discussion as to why it is this way.

You can however achieve this with CSS yourself:
```css
#sidebar .chan:hover .close {
  display: unset;
}
```
