### ISSUE TITLE
Enable auto join on invite feature

### ISSUE THREAD

**Issue by ERR1R** [thelounge/thelounge#3457]
Checkbox or param to enable auto join on invite by bot or user. I have the lounge running on my server and web users can invite themselves with a button (that sends a invite command to eggdrop) but need to manually click the channels to join (invite only channels).

When using mirc or other clients you can enable auto join on invite. 
Would be nice if you can enable this function in:

- config for specific channels or servers etc...
- with url params.   --> autojoin=yes

**Comment by xPaw** [comment]
This would be better suited as a plugin.

Such a feature would certainly be prone to abuse, and not something core TL should have.

**Comment by McInkay** [comment]
Agreed, this is a feature that really frustrates me in chats that have it (slack for example), and anyway feels like something of a core IRC feature rather than something we'd want to stick on the side. 

But yeah, this could be done with a plugin if someone wants.

**Comment by SawkeeReemo** [comment]
Any updates on this?
