### ISSUE TITLE
Equivalent of mIRC /hop command

### ISSUE THREAD

**Issue by nanaya** [thelounge/thelounge#3459]
mIRC has `/hop` command which without additional parameter will just do a leave/join cycle for the current channel. I use this when I joined channel before identifying my nickname and thus operator status isn't applied correctly.

**Comment by xPaw** [comment]
`/cycle`?

**Comment by fnutt** [comment]
How do you identify with NickServ? Do you use SASL (password field in the "edit network")?

If you use SASL there shouldn't be a need for this?

**Comment by nanaya** [comment]
oh whoops sorry for the noise.

re: identification, my nickname wasn't available (thanks to random disconnect) when connected so I don't think any identification method would help.
