### ISSUE TITLE
Strict mode on Ipad 2

### ISSUE THREAD

**Issue by ThijsEigenwijs** [thelounge/thelounge#3469]
- _Node version:_ v10.16.3
- _Browser version:_  safari 9
- _Device, operating system:_ iPad 2 with IOS 9.3.5 (13G36)
- _The Lounge version:_ V3.2.0

---

I've tried to use the lounge on my ipad that i still had laying around by i got this error:

SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

I've tried googling for this issue, and also looked though the current and past issues but couldn't find anything on how to solve it. Can you help me?

**Comment by xPaw** [comment]
The Lounge only supports evergreen browsers. Safari 9 is outdated and not supported.
