### ISSUE TITLE
can't connect to any irc servers

### ISSUE THREAD

**Issue by gregf** [thelounge/thelounge#3479]
- _Node 12.13.0
- _Browser version: firefox 70
- _Device, operating system: ubuntu 18.04lts
- _The Lounge version:v3.3.0 - 2019-10-28

Connection closed unexpectedly: Error: connect EINVAL 94.125.182.252:6697 - Local (127.0.0.1:39553)

```
server {
   listen 443 ssl http2;
   server_name irc.hugops.pw;

   ssl_certificate 	/etc/letsencrypt/live/irc.hugops.pw/fullchain.pem;
   ssl_certificate_key 	/etc/letsencrypt/live/irc.hugops.pw/privkey.pem;
   include /etc/nginx/ssl.conf;
   include /etc/nginx/security.conf;

location / {
    proxy_bind 127.0.0.1;
    proxy_pass http://127.0.0.1:9000;
}

}
```

**Comment by xPaw** [comment]
Did you set bind in config to 127.0.0.1?

**Comment by gregf** [comment]
Yes. Why did you close this before it was resolved?

**Comment by xPaw** [comment]
Because it's an issue on your end.

https://thelounge.chat/docs/configuration#bind

**Comment by gregf** [comment]
I gotcha, ty. Providing the link would have helped explain why the first time.

**Comment by jeff15110168** [comment]
Hello - i’m also having this same issue of trying to connect using a secure connection / port 9000 for an IRC server. I am running The Lounge downloaded from the Unraid Community App Store. Could someone help a total noob out on how to get this up and running? I’m not super familiar on how to setup “SSL” or anything.
