### ISSUE TITLE
Make upload file name / path / domain configurable

### ISSUE THREAD

**Issue by sn0opy** [thelounge/thelounge#3484]
I'd like to propose a change in the way file uploads work in The Lounge. Right now, file uploads work like this:

- files are uploaded to a hardcoded `uploads/` directory
- A random filename is generated for the file and the first 2 characters are used to create a random directory. That directory is just internally to prevent system limitations
- files are stored without their file extension. TL will read the file type from the file's headers  
- the URL that is returned by the server is relative. The client will append the file path to the current domain
- the actual file's name doesn't matter for TL to find the file. The random bit is relevant though.

I am uploading files via SCP to my server. My tools usually set the file's name to a random string and prepend a defined domain to the file's name. I'd like to have such an option in TL too.

Most things can be done via NGINX's URL rewriting + modify TLs code to allow me to choose a domain name for uploaded files, but I'd like to get some feedback from users or other developers if people are interested in having the ability to make these URLs fully configurable in TL's config. My proposal:

- ability to set random string length
- ability to set a custom domain where files are served from (requires client modifications since only the relative path is passed from server)
- ability to set upload directory location (probably requires extra permission checks like being able to write/read from that location)
- ability to disable random named folder creation
- choose whether to append the file's extension to the file's name in file system (to completely bypass TL and serve static files through web server instead)

Is this something people are interested in?

**Comment by xPaw** [comment]
> ability to set random string length
> ability to disable random named folder creation

Adding options like this goes against the idea of TL having the least amount of options possible, for better or worse. We try to avoid adding options that are basically one-off for specific users.

> ability to set a custom domain where files are served from (requires client modifications since only the relative path is passed from server)
> choose whether to append the file's extension to the file's name in file system (to completely bypass TL and serve static files through web server instead)

The uploads folder is essentially a dumb blob storage, and TL does a couple of things (like setting correct mime type and disposition) so letting web servers serve uploads directly would probably open a can of worms.

Changing the base url was asked about more than once, and I made a PR for it: #3485

> ability to set upload directory location (probably requires extra permission checks like being able to write/read from that location)

Can probably be done right now with symlinks?
