### ISSUE TITLE
multiline `CAP LS 302` responses are not parsed correctly

### ISSUE THREAD

**Issue by slingamn** [thelounge/thelounge#3500]
This issue was observed with the debian package of thelounge, version 3.3.0, and node version 13.1.0, against the [oragono](https://github.com/oragono/oragono) testnet at testnet.oragono.io. It should be reproducible against testnet.oragono.io (plaintext on 6667 or TLS on 6697).

It seems that The Lounge doesn't correctly implement ["Multiline replies to CAP LS and CAP LIST"](https://ircv3.net/specs/core/capability-negotiation.html#multiline-replies-to-cap-ls-and-cap-list) during capability negotiation. In particular, the oragono testnet's response to `CAP LS 302` is multiline:

```
:oragono.test CAP * LS * :account-notify account-tag away-notify batch cap-notify chghost draft/acc draft/event-playback draft/labeled-response-0.2 draft/languages=13,en,~bs,~de,~el,~en-AU,~es,~fr-FR,~no,~pl,~pt-BR,~ro,~tr-TR,~zh-CN draft/rename draft/resume-0.5 draft/setname echo-message extended-join invite-notify message-tags multi-prefix oragono.io/bnc oragono.io/maxline-2=2048 oragono.io/nope sasl=PLAIN,EXTERNAL server-time sts=duration=86400,port=6697
:oragono.test CAP * LS :userhost-in-names znc.in/playback znc.in/self-message
```

The Lounge appears to ignore the first line and only interpret the second, as per this response:

```
CAP REQ :userhost-in-names znc.in/self-message
```

When the server was temporarily reconfigured to send a shorter, one-line `CAP LS` response, The Lounge correctly requested all supported caps, including SASL.

**Comment by xPaw** [comment]
1. Can you test latest master and see if still happens?
2. https://github.com/kiwiirc/irc-framework handles the CAP negotiation, if the issue still happens on master, move the issue there please.

**Comment by slingamn** [comment]
Thanks, I'll mention it to the kiwi devs --- they might be in the best position to isolate the bug.

**Comment by xPaw** [comment]
It's somewhat a shared development (I have access to irc-fw too), hence why I mentioned making the issue there 😊
