### ISSUE TITLE
ERR_FAILED on Android

### ISSUE THREAD

**Issue by Daedren** [thelounge/thelounge#3518]
- _Node version:_ 12.13.0
- _Browser version:_ Android Chrome 77
- _Device, operating system:_ XZ1 Compact, Android 8.0
- _The Lounge version:_ Docker 3.3.0-alpine

---

I'm find it hard to find a way to reproduce this consistently, but at times, my Android phone stops loading The Lounge's webpage. This issue doesn't happen on my iOS or Windows devices.

Chrome yields a ERR_FAILED error. The console says the following
```
service-worker.js:88 Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': Cannot construct a Request with a Request whose mode is 'navigate' and a non-empty RequestInit. https://lounge.<endpoint>/
networkOrCache @ service-worker.js:88

The FetchEvent for "https://lounge.<endpoint>/" resulted in a network error response: the promise was rejected.
service-worker.js:1 Uncaught (in promise) request-not-in-cache
```
I took the liberty of replacing my endpoint with `<endpoint>` in the above log.

On the phone's browser, cleaning "Cookies and site data" fixes the problem, but temporarily.

**Comment by xPaw** [comment]
Are you able to debug this further, and see what URL it fails to fetch?

Are you reverse proxying, is there any elaborate setup?

**Comment by Daedren** [comment]
I am using a reverse proxy, nothing elaborate. I'm using the linuxserver/letsencrypt container, the proxy config is their default:
https://github.com/linuxserver/reverse-proxy-confs/blob/master/thelounge.subdomain.conf.sample

If I clear the cookies and site data for TheLounge, it'll allow me to login, but if I refresh the page I always get an ERR_FAILED

Chrome's network inspector says:

```
Request URL: https://lounge.<endpoint>/
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Linux; Android 8.0.0; G8441) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36
X-DevTools-Emulate-Network-Conditions-Client-Id: 1A04014A3FE47010B28EBE71553E29CA
```

Checking "Bypass for Network" on the Service Workers tab makes everything work.
The worker does say "Activated and is running". Also tried unregistering and refreshing.
 
I tried doing what the error message implied _(Cannot construct a Request with a Request whose mode is 'navigate' and a non-empty RequestInit.)_
I removed the RequestInit at line 98 of service-worker.js
Going from this
```
		let response = await fetch(event.request, {
			cache: "no-cache",
			redirect: "follow",
		});
```
to this
`let response = await fetch(event.request);`
And the error stopped happening. No idea the implications of this though, I'm not a javascript dev.

**Comment by xPaw** [comment]
Are you actually running updated Chrome? It doesn't make sense why it would fail only for you, while everyone else using Chrome (me included) don't get this error (I did verify that service worker gets a fetch request with mode=navigate).

I also looked at chromium repo for any references, and I see a test that makes sure it doesn't throw in this case: 
https://github.com/chromium/chromium/blob/77578ccb4082ae20a9326d9e673225f1189ebb63/third_party/blink/web_tests/external/wpt/service-workers/service-worker/request-end-to-end.https.html#L25-L29

**Comment by xPaw** [comment]
And specifically, here's the Chromium commit that removed this error: https://github.com/chromium/chromium/commit/6fb5f98ffb279885f80232d46b0b3e2e4dd8a58a

**Comment by Daedren** [comment]
I reinstalled Chrome everything started working fine, so I'm a bit lost on this.
Well, I'll close this for now then, clearly a browser problem on my end in any case.

Thanks for your help.
