### ISSUE TITLE
Previous/next image buttons in the image viewer

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#3522]
Vue branch currently does not implement these, and I'm making this separate issue for it because I'm more than certain it won't be implemented in the `vue` branch.

It was initially implemented in TL in #1365

I want to know whether people use these buttons, and if they do, does it work as expected? In over 2 years of these existing I have not used them once.

Furthermore, the imageviewer in vue implements a lot more interactions with the image (zooming, moving around, etc), and adding arrow buttons might affect that behaviour.

**Comment by richrd** [comment]
I used to use the arrow keys to browse photos when someone posts multiple photos at once. I think it's a handy feature to have. 

I don't think it's too hard to implement, apart from coming up with a smart way to find the correct next and previous images. The only quick way I can think of is using `querySelectorAll` to find all images and looking for the correct images from the returned image elements. This would also work in the changelog and other possible places in the UI.

**Comment by dgw** [comment]
I'm holding off on an upgrade to TL 4.x specifically so I don't lose this feature.
