### ISSUE TITLE
Add keybinds to expand and collapse networks

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#3523]
We have Alt+Shift+↑ bind to jump to a network lobby, an accompanying bind to expand/collapse a network would be useful.

**Comment by dgw** [comment]
<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>→</kbd> to expand and <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>←</kbd> to collapse?

It doesn't look like those bindings are taken by anything else.

**Comment by xPaw** [comment]
I agree.

Question is, do you have to be in the lobby to collapse, or should it work in any channel (collapse current network)?

**Comment by dgw** [comment]
Probably fine to have it work from anywhere. Collapsing a network leaves the current channel selected, so it's easy to undo if pressed by accident (just hit the binding to expand).

I know _I_ would find it very frustrating to have to navigate up to the lobby first. It's highly unlikely that I'm the only one who would find it so!

**Comment by xPaw** [comment]
> Unless that's changed in the vue branch?

Vue is why it works this way :)
