### ISSUE TITLE
Public installation with locked network still shows `register IRC handler` button

### ISSUE THREAD

**Issue by proton-ab** [thelounge/thelounge#3569]
- Node version: v10.17.0
- Browser version: Any
- Device, operating system: Any
- The Lounge version: 2a84d8239b17dd9f384ac777278aaafe0d46588a

---

Public installations with locked network settings should hide 'Open irc:// URLs with The Lounge". The functionality will obviously never work as the network is locked server-side but might cause confusion to user should he use the button.

**Comment by xPaw** [comment]
This should be as simple as checking `lockNetwork` here: https://github.com/thelounge/thelounge/blob/master/client/components/Windows/Settings.vue#L524

Want to make a PR?
