### ISSUE TITLE
Show Older Messages Persistence

### ISSUE THREAD

**Issue by cinderblock** [thelounge/thelounge#3631]
### Feature Description

Sometimes I click "Show Older Messages" 3/4 times to get back to the most recent messages.

The feature I'm hoping for is, after I temporarily switch to a different channel's tab, and switching back, to not have to click "Show Older Messages" again. It should still remember the older messages that I last told it to show.

### Screen Recording of the "annoyance" this feature would fix

![7fdcedb3-1e1c-4ff9-a960-7f4237c2b4da](https://user-images.githubusercontent.com/419955/71382703-e9b82f80-258d-11ea-8a2a-5fb33a07dd16.gif)

**Comment by xPaw** [comment]
This is fixed in v4

**Comment by cinderblock** [comment]
That was fast! ;)

**Comment by fnutt** [comment]
https://github.com/thelounge/thelounge/pull/3603 for reference.
