### ISSUE TITLE
All install methods fail on all common linux OS's.

### ISSUE THREAD

**Issue by scottprovost** [thelounge/thelounge#3634]
The following packages have unmet dependencies:
 thelounge : Depends: nodejs (>= 10.16.3)
E: Unable to correct problems, you have held broken packages.
root:~# node --version
v12.13.0
root:~# yarn global add thelounge
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'global'

- _Node version:_ Any
- _Browser version:_ Never get that far
- _Device, operating system:_ ALL
- _The Lounge version:_ This one

---

**Comment by xPaw** [comment]
Follow the installation guide and install latest Node and Yarn versions (or use the provided .deb).

https://thelounge.chat/docs/install-and-upgrade

**Comment by scottprovost** [comment]
I can make the software install just fine but your installer is broken and your nasty support people are incompetent. The software is being designated as hacked failed software with no working install instructions. Please fix or remove the faulty install. If you would like a competent organization to take over the support, please let me know.

**Comment by SleepingPanda** [comment]
Was this a joke? There are _very_ clear instructions on the website and a link to said instructions were provided by the so-called "nasty support people".

**Comment by scottprovost** [comment]
Just fix the install. Any one of them to work and not screw up the computer it is put on. I will help if you like. We test on all OS versions provided by digital ocean and always use clean installs. Closing a bug you have not fixed is nasty.

**Comment by dgw** [comment]
It's not a bug, so there's nothing to fix. The issue _must_ be on your side, or this tracker would be _flooded_ with reports about installation not working.
