### ISSUE TITLE
Implement multiple file share backends

### ISSUE THREAD

**Issue by AlexGustafsson** [thelounge/thelounge#3636]
### Feature Description

I’m thinking of a feature where one can upload a file to a number of backends such as Firefox Share and Dropbox Transfer.

Currently the only way to share files is by uploading them and making them available via the lounge.

I’m willing to implement this. Would it be a welcome contribution or is it not a direction you’re looking for?

**Comment by xPaw** [comment]
This was discussed and thought about before. The Lounge itself will only support upload files locally (otherwise people ask to implement their favourite service).

This is something that could be done via plugins, but the plugin system is not at the stage where this is possible just yet.
