### ISSUE TITLE
Change integers to something more user friendly

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [thelounge/thelounge#3669]
### Feature Description
Currently, [here](https://github.com/thelounge/thelounge/blob/master/defaults/config.js#L139) and [here](https://github.com/thelounge/thelounge/blob/master/defaults/config.js#L165) we are using kilobytes to refer to image/file sizes.

IMHO, would be more user friendly to have something like `1K`ilobyte, `1M`egabyte, `1G`igabyte.

That way users wouldn't have to do the maths to specify the size of the image/file.

Just a small idea that popped out.

Cheers

**Comment by xPaw** [comment]
You change this setting at most once, its trivial to figure out kilobytes if you need it. Adding this would require enough effort (parsing, backwards compatibility, tests, documentation updates).

**Comment by PeGaSuS-Coder** [comment]
Understandable. 😀

Was just an idea and it doesn't hurt to expose it. 😁

But I do understand the effort that would be needed to do this and I must agree with the reason to not implement it.

Nonetheless, keep up the good work!

Cheers
