### ISSUE TITLE
WebIRC and reverse proxies

### ISSUE THREAD

**Issue by pinkgothic** [thelounge/thelounge#3671]
- _Node version:_ v10.18.0
- _Browser version:_ 79.0.3945.88
- _Device, operating system:_ Laptop, Windows 10
- _The Lounge version:_ 4.0.0

---

It seems as though thelounge's webirc cannot be used in combination with a reverse proxy (which makes some sense, of course). This is my webirc configuration:

```
        webirc: {
            "localhost": (webircObj, network) => {
                webircObj.password = "<snipped>";
                webircObj.hostname = `webirc.${webircObj.address}`;
                return webircObj;
            },
        },
```

TheLounge is behind a reverse proxy (so that it can be accessed using port 443, in parallel to other websites running on the same host). I did get it to connect a user with the proper IP (from a tab where I navigated to `:9000` directly):

```
[19:58] pinkgothic is pinkgothic@ijsxcf.49.846.03.71 * Lounge User
[19:58] pinkgothic is connecting from *@webirc.80.137.82.74 80.137.82.74
```

However, if I was already connected from a localhost mask (having opened the connection in a reverse proxied tab), then disconnected and reconnected in the window (without refreshing), I would still get this instead:

```
[20:20] pinkgothic is pinkgothic@xnanir.::4 * Lounge User
[20:20] pinkgothic is connecting from *@webirc.::1 0::1
```

Could you add it to the documentation that the combination reverse-proxy and webirc does not work - or provide information on how to expand the reverse-proxy configuration to forward the IP address in a way that The Lounge will understand?

(And thank you for the awesome IRC client.)

**Comment by Mikaela** [comment]
Does your TheLounge config enable reverse proxy? And does your reverse proxy configuration include sending the header to TheLounge?

* https://thelounge.chat/docs/configuration#reverseproxy
* https://thelounge.chat/docs/guides/reverse-proxies

**Comment by pinkgothic** [comment]
Hmm. I've changed so much about the configuration and my setup in the past hours that I can't figure out what was originally wrong with this, because that does work. I do know I didn't change (just commented out) my reverse proxy configuration in the web server, so I must have originally overlooked the `reverseProxy: true` setting - that's really the only realistic option. My deepest apologies. Thank you for bumping my nose on it!
