### ISSUE TITLE
[Feature request] Command to clear outgoing server message queue

### ISSUE THREAD

**Issue by Mikaela** [thelounge/thelounge#3672]
### Feature Description

In case one accidentally pastes many lines to IRC, it would be nice to have a command to stop sending that in the middle so clear the outgoing message queue. I am used to this feature existing in other clients.

* HexChat: `/flushq`
* WeeChat: `/server deloutq`

**Comment by xPaw** [comment]
There is no send queue that can be cleared.

Closing as a duplicate of #794
