### ISSUE TITLE
[Feature request] Partyline / communicating with other users of the same The Lounge instance

### ISSUE THREAD

**Issue by Mikaela** [thelounge/thelounge#3677]
### Feature Description

I am not sure if this is within scope of The Lounge, but it would be nice to be able to message with other users on the same The Lounge instance without having to run an IRCd on the same host or trusting a IRCd outside of The Lounge.

ZNC (and Eggdrop) called this as [partyline](https://wiki.znc.in/Partyline), but it failed in ZNC when they released support for multiple networks, but as The Lounge isn't ZNC and kind of forces the user to see all networks they are on, I think it could work.

Another usecase would be user using it to contact someone running the instance when they are having problems getting TL connected to the network e.g. due to full I-line or similar situation.

**Comment by xPaw** [comment]
We thought about having an internal IRC server before but quickly decided not to do it, because it vastly increases the developer investment.

partyline is certainly not something that will exist in core, and this can be left to a plugin.
