### ISSUE TITLE
Room history gone after updates/reboot

### ISSUE THREAD

**Issue by BRTPOB** [thelounge/thelounge#3680]
Ever since I upgraded to the latest version, v4.0.0, channel and PM history is completely wiped out whenever the client is restarted due to the underlying host rebooting. This is new since 4.0.0, and I'm not sure if this is a config problem or an actual bug.

Steps to repro:

Run v4.0.0
Ensure history is in IRC chat window (PM or channel)
Restart server
Login to TheLounge again

Result: No previous history is shown.

Expected Result: Expected history to be shown.

**Comment by Scrxtchy** [comment]
Just ensuring that messageStorage contains `"sqlite"` in your `config.json`
If it only contains Text, then TL doesn't load back these
https://github.com/thelounge/thelounge/blob/9ef5c6c67e463c1f401e33b21dfb5641636e5ed1/src/plugins/messageStorage/text.js#L110-L115

**Comment by BRTPOB** [comment]
I don't seem to have config.json...anywhere. Where should it be located?

**Comment by Scrxtchy** [comment]
run `thelounge` and it should tell you your default THELOUNGE_HOME path, it's in there

```
$ thelounge
Usage: thelounge [options] [command]

Options:
  -v, --version             output the version number
[....]

  Environment variable:

    THELOUNGE_HOME   Path for all configuration files and folders. Defaults to /home/scratch/.thelounge.
```

**Comment by BRTPOB** [comment]
OK, so I have a config.js not a config.json. I have a feeling that might be the problem.

**Comment by Scrxtchy** [comment]
ahh, that would be my error, apologies

**Comment by BRTPOB** [comment]
OK, well if it's supposed to be config.js, it's got the array set to ["sqlite", "text"]

        // their JSON configuration file.
        //
        // This value is set to `["sqlite", "text"]` by default.
        messageStorage: ["sqlite", "text"],

**Comment by Scrxtchy** [comment]
Well that's a good sign, the sqlite db for each configured user is in the logs folder. I'd assume that this is storage recent messages as appropriate when set

**Comment by BRTPOB** [comment]
Sure, but the sqlite DB hasn't been written to since 12/31, which is roughly when I updated to v4 of TheLounge.

**Comment by Scrxtchy** [comment]
the final thing I can think about it being a config issue is if it's somehow flipped off on the user level, this is found in the user json file, or thelounge edit <user>.

TL checks to see if it's running in not public mode, and if your user has log enabled
https://github.com/thelounge/thelounge/blob/55e5c69958b986310d3502d9046d0ca5a329f532/src/client.js#L68

Outside of that, the system *should* be logging error logs when it catches one and prints to stderr

**Comment by xPaw** [comment]
Look at the server console output, you most likely have a message about sqlite module not being loaded.

Try reinstalling TL and see if it gets resolved. Unfortunately the native module installation is outside of our control and we can't give more help on that.

I'm closing this because native module not loading is always the reason for logging to sqlite not working.
