### ISSUE TITLE
Nickserv authentication code gets confused by colon character (:) in password field

### ISSUE THREAD

**Issue by gpoppino** [thelounge/thelounge#3691]
- _Node version:_ 6.9.0
- _Browser version:_ Firefox 72.0.1
- _Device, operating system:_ MacOS 10.15.2
- _The Lounge version:_ 4.0.0

---

When using a password with the colon character (:) for authenticating a user, the server (freenode network) shows a failed authentication with nickserv. However SASL works. Message from the server is "Notice:NickServ- partOfPassword is not a registered nickname." where "partOfPassword" is your password before the colon character.

How to reproduce:

1. Edit your ~/.thelounge/users/youruser.json file and add a password in "networks -> password" field with a colon character. For example, "yourpassword:abc"
2. Log into freenode and you will see a notice from nickserv with the first part of your password before the colon character. In this case "yourpassword".
3. Your nick is authenticated nevertheless through SASL. Question: if already authenticated, why does it try to authenticate through nickserv again?

**Comment by xPaw** [comment]
This is not a bug in TL, it sends the password with colon in `PASS` correctly. It does not try to authenticate with nickserv (freenode does that when you send in PASS command).

However the fact that SASL and server password is the same field is tracked here - https://github.com/kiwiirc/irc-framework/issues/103
