### ISSUE TITLE
Channel autocomplete frequently interferes

### ISSUE THREAD

**Issue by mortie** [thelounge/thelounge#3695]
- _Node version:_ v12.10.0
- _Browser version:_ Firefox Nightly 74.0a1
- _Device, operating system:_: Linux
- _The Lounge version:_ 4.0.0

---

When writing a message, the channel name autocomplete can break what I'm trying to say in unintuitive ways. For example, if I try to send the message "I like C++", because I'm in the channel `##c++`, autocomplete turns my message into "I like C+##c++".

This seems like a bug; I'd expect autocomplete to turn the message into "I like ##c++", not insert the channel name into the middle of the word which triggered the autocomplete. However, even if it worked as it "should" and autocomplete turned the message into "I like ##c++", autocomplete probably shouldn't be applied to any message which happens to contain part of the name of a channel. It only seems to happen with the channels ##c++ and ##C++-general, so that part might also be a bug?

**Comment by xPaw** [comment]
This would be due to the fact that `+` can be a channel type, and it detects it as a start of a channel.

This is the same bug as #2960 because we use `\B` to detect word boundaries.

I'm gonna close this issue, can you leave your comment in that issue?

**Comment by Mikaela** [comment]
Shouldn't + only detected as a beginning of channel name when `CHANTYPES=` from ISUPPORT contains a `+`?

**Comment by xPaw** [comment]
I fixed in the PR by searching for channels that begin with the prefix.
