### ISSUE TITLE
The Lounge can get stuck with network with connection problems or not receiving response to QUIT or similar

### ISSUE THREAD

**Issue by Mikaela** [thelounge/thelounge#3697]
- _Node version:_ v12.14.0
- _Browser version:_ Firefox Beta (pending restart for update, but irrelevant)
- _Device, operating system:_
  - Server: Debian GNU/Linux 9.11 (stretch)
  - Client: Debian GNU/Linux bullseye/sid
- _The Lounge version:_ 4.0.0-1

---

This has previously been reported in https://github.com/thelounge/thelounge/issues/1059#issuecomment-342676594 and IRC, but I think this is actually a bug.

Last night I was performing IRC network maintenance including rebooting the host TL was connected to and to reconnect faster I issued `/QUIT`, but apparently that doesn't disconnect TL from the server, but instead leaves it to hang as the powered off server won't answer the QUIT. I was unable to use `/connect`, because TL said that it was already connected. `/reconnect` again doesn't exist as per #1059.

My solution was to restart my TL instance, but `/quit` by user should just disconnect and not wait the IRCd to accept me quitting, the IRCd will timeout the ghost in the end anyway.

**Comment by xPaw** [comment]
`/quit` command removes the network entirely, so I don't know how you were able to issue connect to it again. Did you mean `/disconnect`?

And how long did you wait, it *should* timeout.

**Comment by Mikaela** [comment]
I don't remember so deep details from last night (I was sleep deprived and under melatonin) and I thought I would have raw log after minutes of scrolling, but it appears that hte raw log and server tab get cleaned on restart.

I remember surely that the raw log ended to TL saying QUIT to the server.

Does irc-framework also handle not being able to connect while being connected while not actually being connected?

**Comment by xPaw** [comment]
Raw log is not the same as debug log (debug.ircFramework goes into server stdout).

> Does irc-framework also handle not being able to connect while being connected while not actually being connected?

Did it say `You are already connected.`? If not, then `connection.connected` in irc-framework was set to false, but the socket still possibly existed? Which I'm not sure why it would matter as calling connect destroys it.

**Comment by Mikaela** [comment]
I think it did say `You are already connected.` because that is the string that I can get out by `/connect` in a network I am connected to without issues and I remember the text being similar and in red.

**Comment by xPaw** [comment]
Closing this due to some fixes merged in irc-framework.

If you experience problems like this again in the next version, please make an issue over there with extra info (debug.ircFramework is kind of required to get any useful information).
