### ISSUE TITLE
Channel entered on login page no longer becomes active window after connect

### ISSUE THREAD

**Issue by chotaire** [thelounge/thelounge#3699]
- _Node version:_ ´The one included in thelounge Docker image (4.0.0)
- _Browser version:_ Chrome Version 79.0.3945.117 (64-bit), Firefox 72.0.1
- _Device, operating system:_ Fedora Linux 31 (Server), Windows 10 64-bit (Client)
- _The Lounge version:_ 4.0.0 (Docker)

---

With previous versions, when configuring a channel on the login page of TheLounge, the channel window would become active after connecting and joining the channel. This is no longer the case. The server window stays active. This leads to unnecessary confusion, especially when TheLounge is used for public, direct access to a pre-configured channel.

When manually joining a channel or when connecting to a bouncer that makes the client auto-join channels, the channel window still becomes active as expected. This issue only exists for channels configured on the login page.

**Comment by xPaw** [comment]
This would be caused by this:
https://github.com/thelounge/thelounge/blob/d7513b43dc82c0a8848f78a4240f494127a8de0e/client/js/socket-events/network.js#L17

We should take the latest element in `channels` instead of the first (the lobby) to fix it.

Something like `switchToChannel(network.channels[network.channels.length - 1]);` should work.

Can you make a PR?

**Comment by chotaire** [comment]
In my docker container, I've replaced this in `/usr/local/share/.config/yarn/global/node_modules/thelounge/public/js/bundle.js` and `bundle.js.map`, cleared browser cache but it did not seem to have any positive effect.

**Comment by xPaw** [comment]
I don't know what exactly you replaced but it was most likely not the correct place (don't edit the bundle.js, edit the source file and build it).

**Comment by chotaire** [comment]
I've replaced the only occurance of switchToChannel(network.channels[0]); in both files, so I am guessing it should have worked. Hm.

**Comment by xPaw** [comment]
I just tested it and that fix works. PR: #3703
