### ISSUE TITLE
Extended join information is not shown

### ISSUE THREAD

**Issue by Mikaela** [thelounge/thelounge#3700]
- _Node version:_ v12.14.0
- _Browser version:_ Firefox Beta 73.0b5 (64-bittinen)
- _Device, operating system:_
  - Server: Debian GNU/Linux 9.11 (stretch)
  - Client: Debian GNU/Linux bullseye/sid
- _The Lounge version:_ 4.0.0-1

---

When an user joins channel, The Lounge shows `nick (user@host) has joined the channel` while the raw message is `:nick!~user@host JOIN #channel accountname :Real Name`

I would expect to see the Real Name also as it's in the raw message.

If I understand correctly, WeeChat shows this in format `--> nick <[account]> (real name) (user@host) has joined #channel`

**Comment by xPaw** [comment]
Do you want to look into implementing this? Just need to propagate `account` and `gecos` fields in the join event, and then on the client display them in the message if they are set.
