### ISSUE TITLE
Auto Completion of nickname prefixes the nickname with "$1"

### ISSUE THREAD

**Issue by GewoonYorick** [thelounge/thelounge#3716]
- _Node version:_v10.18.0
- _The Lounge version:_Latest source; https://github.com/thelounge/thelounge/compare/e8ba4f4...master

---
When typing the start of an nickname, and then pressing tab it inserts$1 in front of the nickname
for example: typing "sha" then pressing tab results in $1Shadoozo.

**Comment by GewoonYorick** [comment]
I think #3696 caused this bug.
https://github.com/thelounge/thelounge/blob/e8ba4f4fb9c3622228ccc41cae41143a075938cf/client/js/autocompletion.js#L60

**Comment by xPaw** [comment]
Odd, I specifically remember testing this.
