### ISSUE TITLE
Alt-A inputs get handled by keybinding in input field

### ISSUE THREAD

**Issue by DarkMio** [thelounge/thelounge#3719]
- _Node version:_ v12.14.0
- _Browser version:_ Firefox 72.0.1
- _Device, operating system:_ MBP 2018, OS X 10.14.6 (18G95)
- _The Lounge version:_ v4.0.0

Upon entering text in the chat input field (in this case the letter ä, written by typing ``ALT`` + ``A`` (EurKey Layout: https://eurkey.steffen.bruentjen.eu/), the keybinding for jumping to the next unread channel is invoked. This is inconsistent behavior as the user search supports writing ``ä`` just fine.

Demonstration: https://i.miomoto.de/YvGfWWWL8Q.mp4

**Comment by xPaw** [comment]
Alt+S and Alt+U will have the same issue.

Since the chat input has `mousetrap` class on it, that allows mousetrap to process the keybinds, thus TL handles it instead of inputting the `ä`.

I guess we need to ignore handling these keybinds (alt+<letter> ones) if you have focus in input element.

**Comment by DarkMio** [comment]
You could likely look if the content of any text area changed and if it didn't check if it matches an input. Best of both worlds, I guess.
