### ISSUE TITLE
Dynamic web page current state

### ISSUE THREAD

**Issue by fede220** [thelounge/thelounge#3732]
### Feature Description
Hi is it possible to save the page in its current state and make it work dynamically with all its functions including sending messages offline? Thank you very much.

**Comment by dgw** [comment]
Let me get this straight: You want to send messages to a network service whose every protocol detail assumes that you are connected to the server… without a connection to the server?

This is like asking to use Discord or Slack while offline. I guess a plugin could cache messages and make it possible to catch up on backlog without a connection, but wanting to *send* messages while offline makes no sense.

**Comment by fede220** [comment]
Because I would like to have a copy of that page on file that works dynamically in its current offline state.

**Comment by fede220** [comment]
Because I would like to have a copy of that page on file that works dynamically in its current state including sendig messages offline. Thank you very much.

**Comment by xPaw** [comment]
Not really possible without fundamentally changing some of the aspects in TL to store a lot of data on the client (and more than likely introduce a myriad of out of sync bugs).
