### ISSUE TITLE
Channel list view tabs

### ISSUE THREAD

**Issue by fede220** [thelounge/thelounge#3736]
### Feature Description
Hi It's possible add the channel list view tabs in The Lounge? Thank you very much.

**Comment by fnutt** [comment]
Type /list or right click on a network name and choose "List all channels"?

**Comment by fede220** [comment]
I mean viewing tabs channels as CSS graphics. I attach an example of what I'm asking.
![Thelounge channel view tabs](https://user-images.githubusercontent.com/25830051/73561438-49410f00-4459-11ea-96de-74384cc4bef3.jpg)

**Comment by dgw** [comment]
I'm sure it's possible for, say, a theme to reskin the application to look like that. Might be a bit much for user CSS (a LOT of overrides would be needed).

**Comment by fede220** [comment]
It will be implemented the option to choose the list view and tabs view? Thank you very much.

**Comment by fnutt** [comment]
I hardly doubt the maintainers would want an option built into the client code to redo the entire UI, only to let you have some buttons to click on for servers, channels and pm's.

**Comment by xPaw** [comment]
Our design revolves around having the sidebar (including the interactions with it), so it would be a rather big change to do.

That being said, I saw someone theme it to be horizontal with CSS alone.
