### ISSUE TITLE
Please consider gpg --detach-sign:ing the releases

### ISSUE THREAD

**Issue by Mikaela** [thelounge/thelounge#3756]
### Feature Description

I would feel better installing the packages provided at GitHub if they were signed and I could be sure that they haven't been modified by unauthorized people after being posted to GitHub.

**Comment by xPaw** [comment]
Not worth the headache. You're already downloading it via https.

**Comment by Mikaela** [comment]
What kind of headache? Would [signify](https://github.com/aperezdc/signify) or similar be an option? Is there any way to help make this happen?

HTTPS doesn't guarantee that it hasn't been modified by an unauthorized party through e.g. compromised login details or pressure towards GitHub/Microsoft.

I like [QubesOS policy to distrust the infrastructure](https://www.qubes-os.org/faq/#what-does-it-mean-to-distrust-the-infrastructure) while they are likely bigger target than The Lounge.

**Comment by SinZ163** [comment]
Github/Microsoft have the capability of modifying it prior to gpg signing via github actions which is where the release gets built, so the GPG signing wouldn't remove them from the threat vector.
