### ISSUE TITLE
Add a pushover/webhook integration

### ISSUE THREAD

**Issue by SakiiR** [thelounge/thelounge#3766]
That would be great to have a way to receive notification on the phone when a message is received.

That's why I am asking about a webhook system or a direct pushover integration [https://pushover.net/](https://pushover.net/).

**Comment by dgw** [comment]
Open TL on your phone, visit settings, and enable Browser Notifications.

Hopefully a future plugin API expansion would make third-party push notification service integration possible with a plugin, but I doubt it'll be implemented in TL core.

**Comment by xPaw** [comment]
TL implements native web push out of the box which works anywhere outside of iOS.

If you need other push services, you can use ZNC push module.

**Comment by SakiiR** [comment]
I left ZNC because of what TL suggest me :)

Thanks for the answer anyway
