### ISSUE TITLE
Channels autojoin

### ISSUE THREAD

**Issue by SakiiR** [thelounge/thelounge#3771]
Maybe add an option server/channel sided to autojoin channels ? (when kicked, it happens a lot to me)

**Comment by xPaw** [comment]
Auto join when kicked is not something that will be added to TL.

Can be implemented as a plugin when that's exposed.

**Comment by varac** [comment]
> Auto join when kicked is not something that will be added to TL.

Well joining when kicked is just one use-case of it, re-joining on lost network connection is another one, and it's pretty annoying when you loose backlog on some channels because of this.

**Comment by xPaw** [comment]
Channels are rejoined on a network reconnection.

**Comment by varac** [comment]
> Channels are rejoined on a network reconnection.

Thx for the clarification, I missed that.
