### ISSUE TITLE
Please Re-Add select preview by Keyboard shortcut key

### ISSUE THREAD

**Issue by dateno1** [thelounge/thelounge#3772]
I can select pre/next preview by keyboard left/right key on theLounge 3.3.0 but it not worked on 4.0.0

Client Enviroment : Windows 10 + Firefox lastest version (x64)
Server Enviroment : Ubuntu 18.04 + nodejs v12.15.0
![Version](https://user-images.githubusercontent.com/12645246/74934974-b6c5d700-542a-11ea-8a53-058376583ca1.png)
Lounge Version (Downloaded Source code from here and Installed by yarn)

Feature is removed? (I can't found that on release page)

It needs to view old image link preview on long mixed chat log without scroll up (can find image by click any preview& press arrow key few times) or compare image file

**Comment by dgw** [comment]
Duplicate #3522

**Comment by dateno1** [comment]
> 
> 
> Duplicate of #3522

Checked
