### ISSUE TITLE
I think I was banned accidentally?

### ISSUE THREAD

**Issue by hypnotizeddolphin27** [thelounge/thelounge#3775]
Hi!

My username on the coverthypnosis lounge is Amy_Brainwashed_Stoner - I received this message, "You are not welcome on this network. G-Lined: Amy_Brainwashed_Stoner_aka_NeuralNets" and got booted off. I think it's because I tried to paste a link to the site NeuralNets? I didn't know it wasn't allowed, and hit paste like ten times before giving up, and only then did I see in the lobby that it said I couldn't post it. 

I had no idea - but when I emailed the provided email address to ask to be reinstated, I was told the email was no longer valid. Could I please be reinstated? Thank you!
-Amy

**Comment by dgw** [comment]
What's a coverthypnosis lounge?

This is an issue tracker for The Lounge _the software project_. We don't have any connection to any entity that might be running a publicly accessible (or private, for that matter) instance of The Lounge.
