### ISSUE TITLE
Please notify me when NickServ complains about identification

### ISSUE THREAD

**Issue by simpleauthority** [thelounge/thelounge#3788]
I would like to receive a more visible notification when NickServ has something to say about my account.

On an IRC server, I was in a channel that requires NickServ identification. I did not realize I wasn't identified, and so I was sending messages and wondering why nobody was replying or seemingly noticing my messages at all. In the Channel UI, it certainly seemed like the messages were sending just fine.

But they weren't. Apparently my server tab was filled with these: https://reeee.ee/PbFfLp.png

My server tab had no visuals added to indicate there were unread items or something I needed to take action on, so I had no idea. I happened to check it completely by coincidence and then solved the problem.

I've now added the pass to Lounge so that it should auto-identify, but my feature request stands that there should be a better way of notifying the user that the message they tried to send did not actually go through.

Thanks.

Tagging @MiniDigger who recommended I open an issue.

**Comment by xPaw** [comment]
If you had the lobby open on some client, then that's possibly you didn't see the unread counter.

Nickserv implementations differ from server to server, as that's not an IRC standard. When ircv3 gains authentication specification then we can look into making this more prominent.

There's not much we can do here specifically because you were getting an unhandled message, and they so increase the unread counter.

**Comment by simpleauthority** [comment]
@xPaw What in the world is "If you had the lobby open on some client" supposed to mean? I was looking directly at one channel and never got an unread counter even once. No notice. Nothing.

**Comment by xPaw** [comment]
> What in the world is "If you had the lobby open on some client" supposed to mean?

TL can be open in multiple places/devices at once, if one of these had the lobby focus, then you wouldn't see the unread counter increase in other clients.

**Comment by simpleauthority** [comment]
I did not have lounge open in a second (or more) device(s). Just my single laptop. So what exactly is the fault on my part?

**Comment by xPaw** [comment]
I'm giving you an explanation on why the unread counter could possibly not increase for you.

You asked for a "visual" when there's messages in the lobby, we do have that mechanism — unread counters.

**Comment by simpleauthority** [comment]
So there is this weird situation where it won't increase, but it doesn't apply to me -- so you close the issue?

Great. I'm glad your software is free of issues. I will no longer use it. Have a great day.

**Comment by xPaw** [comment]
I just tested it against spigot irc server specifically, and it works there as expected by increasing the unread counter on the lobby window.

The improvement to this we can do is add handling for 477 in irc-framework so this message goes into the target channel instead. https://github.com/kiwiirc/irc-framework/blob/master/src/commands/handlers/generics.js

**Comment by fnutt** [comment]
> Great. I'm glad your software is free of issues. I will no longer use it. Have a great day.

Less drama please and grow up?
