### ISSUE TITLE
Expand/collapse network keybind conflicts with selecting words in text area

### ISSUE THREAD

**Issue by belak** [thelounge/thelounge#3813]
- _Node version:_ v12.16.1 (using the official docker image)
- _Browser version:_ Firefox 74.0
- _Device, operating system:_ MacBook Pro 15", macOS 10.14.6
- _The Lounge version:_ v4.1.0

---

On macOS, the keybinds "alt-shift-left" and "alt-shift-right" select the previous and next words respectively. This conflicts with the keybinds recently added for expand/collapse network.

It looks like some of the keybind code uses the following snippet:

```
if (e.target.tagName === "TEXTAREA") {
  return true;
}
```

However, this doesn't appear to be in expandNetwork and collapseNetwork.

**Comment by xPaw** [comment]
Well, that's annoying.

We do indeed have the textarea check in a few binds, but I feel like it will get annoying real quick if we applied to all keybinds. Perhaps if you're focused in a textarea, it should also check whether it's empty?

**Comment by belak** [comment]
That seems like a reasonable workaround
