### ISSUE TITLE
Pasting text doesn't seem to work

### ISSUE THREAD

**Issue by thechantaro** [thelounge/thelounge#3819]
- _Node version:_
- _Browser version:_
68.6.0
- _Device, operating system:_
OnePlus 7T Pro, OxygenOS 10.0.7
- _The Lounge version:_
The Lounge is running from source (commit 0b38a881).
---
I cannot paste text into the chat field. I always have to type something for the cursor to appear, only then can i click on it and paste it.

**Comment by xPaw** [comment]
That's an issue with oneplus.
