### ISSUE TITLE
SASL ECDSA-NIST256p-CHALLENGE

### ISSUE THREAD

**Issue by loungebug** [thelounge/thelounge#3827]
This SASL mechanism is usefull to protect your password when you don't self-host thelounge.

I'ts some kind of standard which is available on most irc clients.

See: https://github.com/kaniini/ecdsatool

**Comment by xPaw** [comment]
> I'ts some kind of standard which is available on most irc clients.

It's not. https://ircv3.net/docs/sasl-mechs


I have worked on implementing EXTERNAL support here https://github.com/thelounge/thelounge/tree/xpaw/certfp which would also "protect your password".

**Comment by xPaw** [comment]
Closing this until this can be implemented in irc-framework (requires someone to actually look into implementing it).

For now, The Lounge has EXTERNAL sasl (which is TLS client cert).
