### ISSUE TITLE
Password field serves no purpose for services-enabled public instances

### ISSUE THREAD

**Issue by Addvilz** [thelounge/thelounge#3836]
For instances with services and with public Lounge there is no point in having the password field visible - it is confusing for non-technical and novice users, and serves no purpose as it seems entering password in the field does not identify against nickserv anyway. It is also misleading to new users who might be looking for registration form.

**Comment by richrd** [comment]
It's necessary if one wants to connect to a password protected IRC server.

**Comment by xPaw** [comment]
>it seems entering password in the field does not identify against nickserv anyway

It does, if the server supports SASL.

**Comment by Addvilz** [comment]
Yes, I understand that. But it does nothing for those which do not have SASL enabled and have no password protection in place.

@xPaw there is also the usability bug of the password not being visually optional. This confuses users - in fact a user reported that they did not know how to proceed because they did not see how to get past the password field as they were new to the network.

**Comment by xPaw** [comment]
Yes I understand that. For public mode, we could hide password and realname under "advanced options" dropdown, or perhaps have a checkbox that says "I have a password".

Unsure what would work better, needs some testing.

**Comment by Addvilz** [comment]
Kiwi seems to have solved this with a checkbox. I seem to recall qwebirc was doing something similar.

**Comment by Addvilz** [comment]
I can make a demo PR at some point later if you want! :)

**Comment by richrd** [comment]
A PR would be welcome, if you feel like doing it :)

**Comment by xPaw** [comment]
Might want to wait a little, as irc-framework might get a separate field for SASL passwords, so we will need to get UI for that.

**Comment by xPaw** [comment]
Can you test #3844, I changed public mode to have a password behind a checkbox.

**Comment by Addvilz** [comment]
LGTM. The checkbox label could use some minor CSS love for spacing and alignment but other than that, looks great.
