### ISSUE TITLE
Not possible to remove networks on iOS

### ISSUE THREAD

**Issue by fnutt** [thelounge/thelounge#3865]
Running master git, https://github.com/thelounge/thelounge/tree/ce6f188a

**Issue**
I cannot remove networks on my iOS phone. It however seems to work on desktop.

When I click on a network in the left sidebar, then click on the three dots at upper right corner and choose "Remove", nothing happens. There is no promt box.

**Comment by xPaw** [comment]
Don't ignore the bug report template, and specify all the versions (browser, os).

And this should have been fixed by #3723

**Comment by fnutt** [comment]
Closing until more testing has been done due to the possible fix noted in above comment.
