### ISSUE TITLE
Thelounge stop and crash

### ISSUE THREAD

**Issue by NicolasChoco** [thelounge/thelounge#3892]
Hi Guys,

I run theLounge  with systemd, I noticed so far this helped to restart the service automatically if it stops for a reason I can't give. ( the other advantage is the longe logs to syslog ) 

But yesterday, it just failed, we had to restart it manually. 
I'll paste below all logs I have.  

I wish I could get much more info to give you, but it is hard for me, I wish I could ( I assume it could help )  **get  debug with node** ,  bbut I doon't know how, please help at least to do that. 

Please give me some infos I could  use t grab more infos about that. 

Thx.
========LOGS======== 

**user@serveurthelounges$ sudo systemctl  --user status thelounge**
● thelounge.service - The Lounge IRC client
   Loaded: loaded (/etc/systemd/user/thelounge.service; enabled; vendor preset: enabled)
   Active: inactive (dead)

Apr 23 13:29:27 localhost systemd[102385]: thelounge.service: Main process exited, code=killed, status=9/KILL
Apr 23 13:29:27 localhost systemd[102385]: thelounge.service: Failed with result 'signal'.
Apr 23 13:29:27 localhost systemd[102385]: thelounge.service: Service hold-off time over, scheduling restart.
Apr 23 13:29:27 localhost systemd[102385]: thelounge.service: Scheduled restart job, restart counter is at 9.
Apr 23 13:29:27 localhost systemd[102385]: Stopped The Lounge IRC client.
Apr 23 13:29:27 localhost systemd[102385]: Started The Lounge IRC client.
Apr 30 03:10:47 localhost systemd[102385]: Stopping The Lounge IRC client...
Apr 30 03:10:50 localhost systemd[102385]: thelounge.service: Main process exited, code=exited, status=1/FAILURE
Apr 30 03:10:50 localhost systemd[102385]: thelounge.service: Failed with result 'exit-code'.
Apr 30 03:10:50 localhost systemd[102385]: Stopped The Lounge IRC client.

**Syslog output:**

Apr 30 03:10:47 localhost thelounge[125129]: 2020-04-30 03:10:47 [INFO] Exiting...
Apr 30 03:10:47 localhost thelounge[125129]: 2020-04-30 03:10:47 [DEBUG] [undefined (113040cc-0b1c-4949-92ad-97c386b5176a) on IRC-server-name (1a299292-316                                              c-4eb0-a381-e8f1e27497d0] Connection.end() connected=true with data=true had_error=false
Apr 30 03:10:47 localhost thelounge[125129]: 2020-04-30 03:10:47 [DEBUG] [undefined (113040cc-0b1c-4949-92ad-97c386b5176a) on IRC-server-name (1a299292-316                                              c-4eb0-a381-e8f1e27497d0] Connection.end() connected=true with data=true had_error=false
Apr 30 03:10:47 localhost thelounge[125129]: 2020-04-30 03:10:47 [DEBUG] [undefined (113040cc-0b1c-4949-92ad-97c386b5176a) on IRC-server-name (1a299292-316                                              c-4eb0-a381-e8f1e27497d0] Connection.end() connected=true with data=false had_error=false
Apr 30 03:10:47 localhost thelounge[125129]: 2020-04-30 03:10:47 [DEBUG] [undefined (113040cc-0b1c-4949-92ad-97c386b5176a) on IRC-server-name (1a299292-316                                              c-4eb0-a381-e8f1e27497d0] NetTransport close() ending
Apr 30 03:10:47 localhost thelounge[125129]: 2020-04-30 03:10:47 [DEBUG] [undefined (113040cc-0b1c-4949-92ad-97c386b5176a) on IRC-server-name (1a299292-316                                              c-4eb0-a381-e8f1e27497d0] Connection.end() connected=true with data=false had_error=false
Apr 30 03:10:47 localhost thelounge[125129]: 2020-04-30 03:10:47 [DEBUG] [undefined (113040cc-0b1c-4949-92ad-97c386b5176a) on IRC-server-name (1a299292-316                                              c-4eb0-a381-e8f1e27497d0] NetTransport close() ending
Apr 30 03:10:47 localhost thelounge[125129]: 2020-04-30 03:10:47 [DEBUG] [undefined (113040cc-0b1c-4949-92ad-97c386b5176a) on IRC-server-name (1a299292-316                                              c-4eb0-a381-e8f1e27497d0] NetTransport socketError() read ECONNRESET
Apr 30 03:10:47 localhost thelounge[125129]: 2020-04-30 03:10:47 [DEBUG] [undefined (113040cc-0b1c-4949-92ad-97c386b5176a) on IRC-server-name (1a299292-316                                              c-4eb0-a381-e8f1e27497d0] NetTransport socketClose()
Apr 30 03:10:47 localhost thelounge[125129]: 2020-04-30 03:10:47 [DEBUG] [undefined (113040cc-0b1c-4949-92ad-97c386b5176a) on IRC-server-name (1a299292-316                                              c-4eb0-a381-e8f1e27497d0] Socket closed. was_connected=true safely_registered=true requested_disconnect=true
Apr 30 03:10:50 localhost systemd[102385]: thelounge.service: Main process exited, code=exited, status=1/FAILURE
Apr 30 03:10:50 localhost systemd[102385]: thelounge.service: Failed with result 'exit-code'.

**Comment by NicolasChoco** [comment]
I am also adding the output of My browser ( Firefox debugger ) dunno if those things may help : 

SRY this output is in french,  2 main errors : 
-44,230  Value aint valid, abandonned
-**00:19:52,044      404      to get   https://urlof.mythelounge.server.fr/js/bundle.vendor.js?v=591ab37fb5

-other are "rules ignored"

**Let me know if you are DEV from thelounge i'll give you the Url, then**

```

**00:19:44,230 Error d’analyse de la valeur pour « -webkit-text-size-adjust ».  Déclaration abandonnée. normalize.css:13:2
Éléments correspondant au sélecteur : html
NodeList(1)
​
0: <html>
​
length: 1**
​
<prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }


00:19:44,230 Valeur non valide trouvée pour la fonctionnalité de média. build.css:1:3333
00:19:44,230 Pseudo-classe ou pseudo-élément « -ms-input-placeholder » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. style.css:45
00:19:44,231
Propriété « -moz-osx-font-smoothing » inconnue.  Déclaration abandonnée. style.css:333:1
00:19:44,233 Jeu de règles ignoré suite à un mauvais sélecteur. style.css:2696
00:19:44,233 Jeu de règles ignoré suite à un mauvais sélecteur. style.css:2700
00:19:44,233 Jeu de règles ignoré suite à un mauvais sélecteur. style.css:2705
00:19:44,233 Pseudo-classe ou pseudo-élément « -ms-input-placeholder » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. NetworkList.vue:141
**00:19:52,044 Erreur dans les liens source : Error: request failed with status 404
URL de la ressource : https://urlof.mythelounge.server.fr/js/bundle.vendor.js?v=591ab37fb5
URL du lien source : bundle.vendor.js.map**

```
​

**Comment by xPaw** [comment]
The logs you are showing appear to say that the service is being killed with a signal, and TL exits as a result, this is not a crash.

Join #thelounge and ask there, maybe someone can give you a better idea.

**Comment by NicolasChoco** [comment]
Thx Xpaw ^^  GG ! 
I confirm my noobiness ... i was using /etc/systemd/user/ repository >> causing the service to stop when  I quit ssh-session ....  THX again
