### ISSUE TITLE
Vue Devtools can't detect Vue.js and can't be usable on thelounge

### ISSUE THREAD

**Issue by FrazerClews** [thelounge/thelounge#3897]
The official browser extension `Vue Devtools` can't be used on thelounge, this is meant to be used with Vue JS projects as it massively helps out in the development process and debugging. At a glance I am guessing it's because thelounge isn't properly structured to Vue JS standards, but this is only a guess and I have seen other projects using both Javascript and Vue JS being able to use `Vue Devtools`, but that could be another potential issue and it's getting confused. So maybe something is wrong with how the project is structured

- Node version: >=10.15.0
- Browser: firefox 75
- System: fedora 32
- The Lounge version: master

**Comment by xPaw** [comment]
Vue devtools work fine if you don't build for production (yarn dev).
