### ISSUE TITLE
Make `add` and `reset` CLI commands scriptable

### ISSUE THREAD

**Issue by flying-sausages** [thelounge/thelounge#3913]
### Feature Description
I'd like to plug these commands into a script which manages users on a shared server, and I'd like to be able to do this in a clean way. I've seen this done on other scripts like nextcloud's `occ` through an environment variable, but a parameter would also work.

Currently I'm doing this by forwarding into the STDIN but this seems a bit sketchy as the format of those commands can change in the future, and it doesn't _just_ work for the `add` command. Any suggestions on how to do this are welcome

**Comment by xPaw** [comment]
Seems like adding optional arguments that can be passed into these commands would make this easily scriptable.

For example `thelounge reset user --new-password 123456`, and if `--new-password` is passed, it will not ask for a new password in the prompt.

**Comment by xPaw** [comment]
@flying-sausages Are you willing to implement this?

**Comment by flying-sausages** [comment]
> @flying-sausages Are you willing to implement this?

I intend to, but not immediately
