### ISSUE TITLE
[NSFW?] Automatic /ignore on matching keywords in PMs.

### ISSUE THREAD

**Issue by jtagcat** [thelounge/thelounge#3916]
### Feature Description
![image](https://user-images.githubusercontent.com/38327267/82302807-9d8ce200-99a9-11ea-8b12-765b0d011949.png)
![image](https://user-images.githubusercontent.com/38327267/82302824-a2519600-99a9-11ea-9d8f-8b90616189c2.png)
![image](https://user-images.githubusercontent.com/38327267/82302839-a67db380-99a9-11ea-8e6b-042e5919c535.png)
![image](https://user-images.githubusercontent.com/38327267/82302852-ab426780-99a9-11ea-9ce9-fbdd74a51571.png)
_Instead of female, age 22/18, I always read Fedora 22, Fedora 18.._

Bots advertising in PMs aren't even trying. It's annoying to get the notification and have 4 new PMs to close.

For any new PMs initiated by other users:
 - Check any messages before user has sent any (if user has sent any messages, we can assume the participant to not be spam).
 - Remove any formatting for search (stops getting around spam blocking with changing one letter to bold)
 - Search all messages for keywords from a user-defined list (global (across all users, across an instance) list?).
 - If matched, /ignore the user, close the PM (that it doesn't appear for the user) and somehow 'have a spam folder'. For example, in the network's channel with something on the lines of 'username was identified as spam due to the following keyword: olibay'.

This functionality could be extended to hiding messages in channels.

**Comment by xPaw** [comment]
Automatic ignore is getting into realm of server management (and somewhat plugins), certainly not something we would want to add into TL core.

For example on freenode you can set `/mode +R` to ignore private messages from users who are not identified with services.
