### ISSUE TITLE
Emit a message for SASL loggedin/loggedout events

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#3921]
irc-framework emits them, but we do not handle them so it's "lost".

https://github.com/kiwiirc/irc-framework/blob/2321afaa4ef7a2a670738cc8eb79092a3e4d7e1e/src/commands/handlers/registration.js#L289-L296

https://github.com/kiwiirc/irc-framework/blob/2321afaa4ef7a2a670738cc8eb79092a3e4d7e1e/src/commands/handlers/registration.js#L314-L321

**Comment by RobustProgram** [comment]
Hi, I would like to give this a go

**Comment by dipayanDebTheCoder** [comment]
Is anyone working on this. I am new to open source so I am looking for some easy coding job to boost my confidence and get started in contributing to open source.  If no one is working on this in that case I can give it a try

**Comment by xPaw** [comment]
Pull requests welcome.
