### ISSUE TITLE
Alt-Tab-like switching

### ISSUE THREAD

**Issue by sopos** [thelounge/thelounge#3942]
Fo reariser switching between the moset recent conversations it would make sense to have similar way of switching between chats as Alt-Tab or Ctrl-Tab.
I would prefer Alt-S or Alt-X or Alt-Z.

**Comment by sopos** [comment]
https://github.com/thelounge/thelounge/issues/3944 would be a prerequisity for this one

**Comment by xPaw** [comment]
You can navigate using browser history (e.g. alt+left/right or mouse4/5 keys). Is that not enough for you?

**Comment by sopos** [comment]
Looks like that's it. So maybe just a doc could be updated.

**Comment by igalic** [comment]
the❓ icon on the bottom left leads to keyboard shortcuts
![Screenshot_20200629-171536](https://user-images.githubusercontent.com/497249/86023615-30e71780-ba2c-11ea-93c9-7a290d3bdea9.jpg)

**Comment by sopos** [comment]
right, maybe it's me but I do not see alt+left/right there..

**Comment by dgw** [comment]
The Lounge doesn't define Alt-Left/Alt-Right as shortcuts. They're defined in most browsers' default shortcuts, and they work on any site (that doesn't override them).

**Comment by sopos** [comment]
I see, I did not realize it is simply back and forth in browsing history.
