### ISSUE TITLE
New Server Install Import Logs

### ISSUE THREAD

**Issue by jabarel** [thelounge/thelounge#3956]
### Feature Description
Hello , from what i read i dont find this option. I wana make an clean install and i wana to import old logs, how can be this possible ? i just tried with copy logs etc but seems not working.
Will be very good to have an option to export/import logs.
Hope doesent exist, because i didnt find anything about this. Or a metod to export logs from old server and import to the new one.
Thanks

**Comment by xPaw** [comment]
I'd you copy the entire the lounge folder over, it will work. If you only copy logs but not users, creating a new network will not load old logs (the guid must match).
