### ISSUE TITLE
Add an emoji browser to the message box

### ISSUE THREAD

**Issue by lewri** [thelounge/thelounge#3958]
### Feature Description
While it's all and well being able to access emojis using the :....: format in messages; this is no good if you don't know the name of the emoji.

It may be better, like other message apps, to have an emoji browser button next to the send button. I don't know if this is present in certain client interfaces to others but at least not in webclient for PC.

I suppose something like this... without the recents section. And maybe just a single browsable tab.
![image](https://user-images.githubusercontent.com/20030128/85805009-1585bf00-b743-11ea-840d-a167ef619101.png)

**Comment by NGTmeaty** [comment]
May I recommend [emoji-mart.](https://github.com/missive/emoji-mart)

**Comment by igalic** [comment]
i usually fallback to my operating system's emoji selector…

**Comment by xPaw** [comment]
We decided a while ago to not add an emoji selector because all operating systems come with a native one now. Existing libraries for emojis are usually so large, it would balloon the JavaScript bundle size.

**Comment by Jay2k1** [comment]
A lot of people probably don't know about this. How about adding it to the shortcuts on the help page?

**Comment by xPaw** [comment]
PRs welcome if someone wants to figure out these shortcuts per OS.
