### ISSUE TITLE
INFO and HELP(OP) responses should be displayed like a MOTD

### ISSUE THREAD

**Issue by SadieCat** [thelounge/thelounge#3961]
### Feature Description

INFO and HELP (HELPOP on InspIRCd) responses are currently displayed like an unknown numeric. It would be nice if they could be displayed in a similar fashion to how the MOTD is displayed because they typically contain content which requires a fixed width font to be seen correctly.

The numerics used by INFO are:

- RPL_INFO (371) &mdash; A line within an INFO response.
- RPL_ENDOFINFO (374) &mdash; Marks the end of an INFO response.

These numerics are specified in RFC 1459 and do not have any conflicts according to ircdocs.horse.

The numerics used by HELP(OP) are:

- RPL_HELPSTART (704) &mdash; A title for the help message.
- RPL_HELPTXT (705) &mdash; A line within a help response.
- RPL_ENDOFHELP (706) &mdash; Marks the end of a help response.

These numerics are not standardised but are used by every IRCd derived from ircd-hybrid (charybdis, plexus, ircd-ratbox, ircd-seven, etc) as well as InspIRCd v3. There are also no conflicts according to ircdocs.horse.

**Comment by xPaw** [comment]
These numerics should be handled by irc-framework first, then we can handle it.

**Comment by xPaw** [comment]
I opened a PR into irc-framework and implemented it in TL. Would you be able to give this a test?

**Comment by SadieCat** [comment]
I've tested it and it seems to display properly. Thanks for the quick response! :+1:
