### ISSUE TITLE
Modify default settings

### ISSUE THREAD

**Issue by finalhit** [thelounge/thelounge#3964]
Cannot find a way to change default values for "Show seconds in timestamp" (showSeconds), "Enable colored nicknames" (coloredNicks) and other settings?

**Comment by xPaw** [comment]
You can't without modifying the code. https://github.com/thelounge/thelounge/blob/master/client/js/settings.js

When you change settings in the UI they are stored in your browser (or your account if syncing is enabled).

**Comment by finalhit** [comment]
I know, that's why this is a feature request and you've closed it?

**Comment by xPaw** [comment]
Because you can change settings and they are saved. I see no reason to implement modifying default settings for majority of use cases.

**Comment by finalhit** [comment]
We need to change default settings for all users, because they are used to certain things in previous IRC client.

**Comment by xPaw** [comment]
As I said, you can modify the code for your needs. I see no greater purpose as to why TL needs to allow changing default user settings out of the box (which would basically mean adding _all_ settings to the config).

TL's primary purpose is private hosting for self use, if you are using it for public chat or many users, you will need to tweak the code yourself.
