### ISSUE TITLE
Uploads fail if they take longer than a minute

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#3982]
We invalidate upload tokens here:
https://github.com/thelounge/thelounge/blob/189f7d84ba002c81a5226e07adc9e620b6f46d0a/src/plugins/uploader.js#L42-L43

They need to be kept alive somehow.

**Comment by xPaw** [comment]
Possible fix would be to let client send a keep alive every ~40 seconds so that timer resets on server.

**Comment by igalic** [comment]
i imagine this very useful when used via mobile networks…

**Comment by xPaw** [comment]
This appears to only be a problem if TL is being proxied, as the upload request can be buffered.

Opening TL directly and uploading hits the request straight away, and token is validated.
