### ISSUE TITLE
a contact is not tracked through nick changes

### ISSUE THREAD

**Issue by sopos** [thelounge/thelounge#3997]
- _Node version:_ nodejs-12.18.2-1nodesource.x86_64
- _Browser version:_ Google Chrome 83.0.4103.116
- _Device, operating system:_ RHEL-7.8
- _The Lounge version:_ https://github.com/thelounge/thelounge/tree/0ac1fcb

---
If a contact changes its nick and writes a new message it gets opened in a separate thread and vice versa, I'm not able to answer it as it appears not to be connected anymore.

**Comment by xPaw** [comment]
This is discussed in #337.
