### ISSUE TITLE
Support MODE_CBC/ECB/MIRCYPTION

### ISSUE THREAD

**Issue by McDeffice** [thelounge/thelounge#4016]
I would like to use to encrypt and decrypt IRC messages via thelounge. This message uses CBC or ECB blowfish mircryption using block and base64 encryption.

I find information here :
`Blowfish plugins for IRC seem to use the MODE_ECB (electronic code book), which is probably the least secure of the blowfish algorithms.

For encryption, they break the plaintext up into 8-byte chunks (the Blowfish ECB blocksize). They then encrypt each 8-byte block separately, and take the output of each encrypted block, and chunk that into (2) 4-byte longs, and base64encode each long, padding them to length of 6 base64 characters.

For decryption, this process is reversed, but because it's somewhat confusing I'll also describe that. Take 12 of the ciphertext bytes, decoding each 6-byte representation as a long ('>L'), so that you now have 8 bytes, which you then pass to the blowfish decryption algo.`

Source :[ IRC blowfish encryption mode? Block_cipher_mode_of_operation ](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation)

The official mircryption site seems to give more support [http://mircryption.sourceforge.net/](http://mircryption.sourceforge.net/)

- [Java Code example ](https://github.com/d-fens/drftpd/blob/master/src/plugins/org.drftpd.plugins.sitebot/src/org/drftpd/plugins/sitebot/Blowfish.java)

- [Eggdrop module blowfish](https://github.com/eggheads/eggdrop/blob/develop/src/mod/blowfish.mod/blowfish.c) 

- [ZNC Fish Module ](https://gist.github.com/v4lli/ee4edd99128e7cb518ebad548cab7a41)

- [FISH 10 for mirc ](https://github.com/flakes/mirc_fish_10/blob/master/fish_10/src/blowfish.cpp)

- [python code](https://github.com/fladd/py-fishcrypt)

what I found closest to javascript is here: [https://www.npmjs.com/package/egoroof-blowfish](https://www.npmjs.com/package/egoroof-blowfish)
I tried to do CBC MODE here is my code snippet. I am not an experienced developer [https://www.donationcoder.com/forum/index.php?topic=49725.msg437385#msg437385](https://www.donationcoder.com/forum/index.php?topic=49725.msg437385#msg437385)

**Comment by xPaw** [comment]
Blowfish is outdated and not something we will have in TL core. There's been some discussions about E2E encryption in ircv3 but nothing concrete yet.

I'm closing this because it's highly unlikely to be implemented.
