### ISSUE TITLE
Typing messages slow in chrome with a lot of history

### ISSUE THREAD

**Issue by jhd85** [thelounge/thelounge#4018]
- Node version: The one in the docker container
- Browser version: Chrome 84.0.4147.105 (64-bit)
- Device, operating system: Windows 10.0.18362
- The Lounge version: v4.1.0

---

The issue me and some of my friends have noticed is that the page and typing messages becomes really slow and laggy when you have a lot of history. To force this behavior you can scroll all the way back in your history, then try to type a message.

What we tried:
- Use Firefox: no problem
- Use Edge: no problem
- Use older version of chrome: no problem
- Try slow of fast pc: no difference

Seems like it has to do with new versions of Chrome combined with The Lounge. Any idea what could cause this?

**Comment by xPaw** [comment]
Typing in input causing lag is a known Chrome 85 issue (should be fixed in 86), you can update to latest The Lounge pre-release for a fix.

Alternatively, custom css fix: `#chat-container {overflow: hidden;}`

**Comment by jhd85** [comment]
Ah that explains. Thanks for the reply!

**Comment by lcarva** [comment]
Custom CSS fix works for me. Thank you so much!
