### ISSUE TITLE
Add Dracula theme

### ISSUE THREAD

**Issue by alexherbo2** [thelounge/thelounge#4067]
https://draculatheme.com

**Comment by xPaw** [comment]
You can create a theme and publish it yourself on npm.

**Comment by xnaas** [comment]
@alexherbo2 bro, just look with your eyes first: https://www.npmjs.com/package/thelounge-theme-dracula 😛

**Comment by alexherbo2** [comment]
How does The Lounge know about themes?

**Comment by McInkay** [comment]
From the link that has already been provided to you:

`To install in thelounge run the following command: thelounge install thelounge-theme-dracula`

**Comment by MiniDigger** [comment]
you can find a full list of themes here https://www.npmjs.com/search?q=keywords:thelounge-theme
as stated in the documentation https://thelounge.chat/docs/usage#installing-additional-themes
