### ISSUE TITLE
Native iOS mobile client (app)

### ISSUE THREAD

**Issue by ssbarnea** [thelounge/thelounge#4079]
While using thelounge in Safari works ok, it is inconvenient as you do not get:
* app icon with number of unread messages
* native notifications
* ability to use the browser for other purposed without losing the chat app

I would not mind even to pay a small subscription for an app, so the user could fund the cost of developing and maintaining it.

**Comment by xPaw** [comment]
https://thelounge.chat/docs/usage#native-app

We already support all of these features, as PWA. In Safari unread counter and native notifications do not work because Apple is not willing to implement these features.
