### ISSUE TITLE
How to update TheLounge? (Snapcraft w/ CentOS)

### ISSUE THREAD

**Issue by adir6** [thelounge/thelounge#4081]
Hi, I wish to update my TheLounge (v4.1.0) hosted on CentOS AWS Server to the Latest Version.

I installed thelounge using SnapCraft.

Here it the link: https://snapcraft.io/install/thelounge/centos

Thanks.

**Comment by xnaas** [comment]
It looks like all you can do is wait for whoever manages "snapcraft" to update the package. As far as I can tell from [the wiki](https://thelounge.chat/docs/install-and-upgrade), installing via snap is not supported in any way.

**Comment by adir6** [comment]
I would have used Docker if I knew how to install Docker and then TheLounge on it.

**Comment by xnaas** [comment]
[The Docker instructions](https://thelounge.chat/docs/install-and-upgrade#docker) are pretty straightforward if you’ve used Docker previously.
