### ISSUE TITLE
Add option to force timezone

### ISSUE THREAD

**Issue by three** [thelounge/thelounge#4083]
### Feature Description

I would like to be able to force the client to use my timezone, which apparently my browser isn't reporting correctly (related https://github.com/thelounge/thelounge/issues/2770#issuecomment-479496795 ). This could be a dropdown on the advanced settings, something like https://gist.github.com/nodesocket/3919205 but with an additional option for the default behavior. Times could be converted with dayjs's Timezone plugin.

**Comment by xPaw** [comment]
Fix your browser.
