### ISSUE TITLE
Enable dialog when nickserv asks for password

### ISSUE THREAD

**Issue by Jan01985** [thelounge/thelounge#4084]
Can it be implemented that when a user enters the chat with a registered nickname, he requests the password through a dialog?

This would make things much easier since there are adults who do not understand much about entering the data if you do not ask them

**Comment by xPaw** [comment]
Nickserv is not an IRC standard, if some network does not have that (or has a different method) someone could spoof it.

If IRCv3 gains some account management, then we can look into it.
