### ISSUE TITLE
Trouble running thelounge on webserver with Plesk

### ISSUE THREAD

**Issue by DenizGelion** [thelounge/thelounge#4085]
Hi there!

I'm rather new to all this and I'm sorry already if this is yet another dumb person who cannot follow simple instructions.

Speaking of which, I did follow your manual here: https://thelounge.chat/docs/install-and-upgrade#running-from-source

I managed to run all the required commands and the response was successful. But when I try to actually run thelounge it doesn't seem to work. 

I also tried NODE_ENV=development yarn build but the result wasn't any different.

I'm trying to run thelounge on a virtual server with the help of Plesk. I hope these screens can grant you any useful information to assist me on launching the app: https://imgur.com/a/Jjjhtp8

**Comment by xPaw** [comment]
Ask on Plesk community forums or whereever they do support.

Briefly looking at the screenshot, it looks like you did not pass `start` argument into thelounge, and it printed help.
