### ISSUE TITLE
Cannot auth to an UnrealIRCd server if server password enabled and SASL disabled

### ISSUE THREAD

**Issue by amyspark** [thelounge/thelounge#4086]
- _Node version:_ 12.18.4
- _Browser version:_ Firefox Nightly 83.0a1
- _Device, operating system:_ Windows 10 1903
- _The Lounge version:_ 4.2.0 (docker version)

---

A friend of mine has an UnrealIRCd (5.0.4) server to chat with them. I am not able to authenticate with an account there, because their server requires a password on connection, and SASL is disabled.

The alternative would be to add a manual command `/msg NickServ IDENTIFY <user> <pass>`, but I think that logs my password every time I reconnect to the NickServ chat history.

**Comment by xPaw** [comment]
I don't understand the issue, can you not enter the server password under network settings?

You can also put the nickserv command under commands when editing the network.
