### ISSUE TITLE
Expand config.js to allow visibility of realname and username fields

### ISSUE THREAD

**Issue by pxdnbluesoul** [thelounge/thelounge#4091]
### Feature Description
I would love to see a toggleable setting to hide the username and realname fields. We have a public instance for users who largely have never used IRC in their life and they are unfortunately taking the realname field as an opportunity to use their actual name, despite instruction to leave it on its default. Leaving the visibility alone but making the inputs disabled would also satisfy our use case.

Unfortunately I don't know squat about the languages at play here to make this a possibility.

**Comment by brunnre8** [comment]
https://github.com/thelounge/thelounge/issues/3974
