### ISSUE TITLE
Links with parentheses are broken

### ISSUE THREAD

**Issue by JeremyMahieu** [thelounge/thelounge#4095]
- _The Lounge version: 4.2.0
---
When linking a url with parentheses in it (and possibly other characters) the link is presumed ended before the closing parentheses.

Example `https://foo.com/bar.(par)` results in a link to `https://foo.com/bar.(par`
The period in the example is nescessary otherwise it works correctly.

**Comment by fnutt** [comment]
Is this an issue for https://github.com/markdown-it/linkify-it ?

**Comment by xPaw** [comment]
Yep, this issue belongs linkify-it, and if you do create an issue there, provide real world examples of what this is actually breaking.

**Comment by JeremyMahieu** [comment]
FYI https://github.com/markdown-it/linkify-it/issues/94

**Comment by xPaw** [comment]
As I mentioned earlier, provide real world examples of what this is actually breaking (not foobar)

**Comment by JeremyMahieu** [comment]
I cannot share the link I've found in the wild. And it would be pointless to craft a link just to prove a point so I will not provide a "real world" example.

Becides it's a perfectly valid link that actually requests a page and returns "not found".

**Comment by MiniDigger** [comment]
wikipedia has this pretty often when multiple words have different pages
https://en.wikipedia.org/wiki/Tester_(disambiguation)
https://en.wikipedia.org/wiki/Tester_(surname)

**Comment by xPaw** [comment]
These links work correctly, you can test that here: https://markdown-it.github.io/linkify-it/ (or in lounge)

I am interested in what site uses dots and parenthesis like that (linkify-it maintainer will want to know that too), because their approach is to support reasonable real-world urls that people would share.

**Comment by MiniDigger** [comment]
man, I would have sworn those links have issues. Ill remember this ticket the next time I stumble upon a broken link, I can't manage to break it in the demo right now.

**Comment by JeremyMahieu** [comment]
Fileshare links that have the filenames in them and spaces replaced by dots for example.
