### ISSUE TITLE
Switching channels shouldn't push new screens to the back stack

### ISSUE THREAD

**Issue by nyanpasu** [thelounge/thelounge#4096]
- _Browser version:_ Using the lounge as a PWA (So chrome?)
- _Device, operating system:_ Android 10
- _The Lounge version:_ 4.2.0

---

Every time I switch channels it adds another item to the stack. When I press back the app should either exit or do nothing. The only times a new item should be pushed would be when I open a non-chat screen (e.g: settings / help)

**Comment by xPaw** [comment]
I will respectfully disagree.

**Comment by nyanpasu** [comment]
What's your justification for that? It doesn't make sense that it should, literally no other chat interface / app works this way.

**Comment by xPaw** [comment]
You are switching contexts (pages), back and forward buttons make sense in this behavior.

>  literally no other chat interface / app works this way.

This is very much not true.

**Comment by nyanpasu** [comment]
>This is very much not true.

Can you give me an example of one?

I can give plenty of examples of the top of my head where it doesn't:

  - Slack
  - Discord
  - Whatsapp for web

I struggle to recall even one where it works like this. It's highly incovenient from an end-user's perspective. I open thelounge, I switch channels as I should, and I'd expect back to either close the app or take me back to some kind of index page (thelounge does not have one, so close it instead.)

>You are switching contexts (pages), back and forward buttons make sense in this behavior.

You are switching contexts, yes, but not pages. It's still the same "page". So the justification still does not really make sense in this behaviour.

**Comment by fnutt** [comment]
I also disagree. When I switch channel I often find myself swiping back in browser on phone to get back to the channel I had in focus before. I see this as a feature, which I really like.

**Comment by nyanpasu** [comment]
Swiping left just pulls open the drawer / channel list for me. Swiping right does nothing. I'd also like to benefit from that behaviour if it worked for me.

**Comment by nyanpasu** [comment]
Sensing that you already consider this discussion over, I'll just add that while it is indeed this is how you would treat pages, and following a consistent navigation behavior for them. it's not practical to think of channels/chats in the same manner. Hence why no other chat app does it this way!

>When I switch channel I often find myself swiping back in browser on phone to get back to the channel I had in focus before.

And that's fine. Add swiping between channels in as a feature even, I would like that as well. Just don't make the back button behave like this. It doesn't make sense. Nor does thinking of / treating channels as "pages" so that you can (ab)use the user agent's back behavior to navigate between channels like this.

**Comment by dgw** [comment]
It's patently false that Discord doesn't do this, certainly. Discord's web app uses the same technique as The Lounge to push a history state when navigating between channels/PMs. I just tested it 30 seconds ago.

So does Facebook Messenger, also tested less than a minute ago. (I don't use Slack or WhatsApp, but I'd be surprised if they don't also do this.)

**Comment by nyanpasu** [comment]
Admittedly, I was only taking into account the native mobile app equivalents while thinking about comparisons. No idea the web versions behaved that way as well. I only use native IRC clients on my desktop. Still a bummer it works like that on mobile. I'll just settle for pressing the home button instead.
