### ISSUE TITLE
Search user list is not refreshing

### ISSUE THREAD

**Issue by mzelenka** [thelounge/thelounge#4098]
After typing the username search and using backspace user list is not refreshing (you cant see user that matched your search).

It will stay that way (user can cycle chatroom but it wont change) unless you switch chat rooms or switch active panel (like Direct message to user).

**Comment by xPaw** [comment]
I can't reproduce this, it refreshes just fine, both when something is entered in search box, and after clearing it.

Please follow the bug report template when creating issues. What version of The Lounge are you running and what browser?
