### ISSUE TITLE
UI: Emoticons option for user

### ISSUE THREAD

**Issue by mzelenka** [thelounge/thelounge#4099]
The lounge has already emoticons build inside itself. Could we add emoticon picker next to button send?

![Screenshot_6](https://user-images.githubusercontent.com/53977501/98468106-3a05a380-21d9-11eb-8e83-010682a8add3.jpg)

Something like this perhaps.

**Comment by brunnre8** [comment]
https://github.com/thelounge/thelounge/issues/3958
