### ISSUE TITLE
ECONNRESET without any retries after

### ISSUE THREAD

**Issue by ssbarnea** [thelounge/thelounge#4103]
Apparently thelounge has a hardcoded reconnect configuration that has too few retries which span over less than 3 minutes. This means that a simple router restart or other networking glitch could render the application offline until a human performs a manual reconned.

This happened to me twine in a week, usually it was not happening but based on what I see on the log I think that the app was not able to retry enough before giving up. I was not able to see any  options configurable in the UI around the retry logic.

Even more interesting is the fact that after the attempt no4 it succeeded establishing a connection but received a ECONNRESET and gave up.

If the retry behavior is configurable in another place hidden from the UI, it should at least be mentioned in the settings window, those for connection and/or general ones.

Version: 4.2.0 (container)

---
```
07:35 Ping timeout, disconnecting…
07:35 Disconnected from the network. Reconnecting in 5 seconds… (Attempt 1)
07:35 *** Connection closed unexpectedly: Error: getaddrinfo EAI_AGAIN chat.freenode.net
07:35 Disconnected from the network. Reconnecting in 8 seconds… (Attempt 2)
07:36 *** Connection closed unexpectedly: Error: getaddrinfo EAI_AGAIN chat.freenode.net
07:36 Disconnected from the network. Reconnecting in 6 seconds… (Attempt 3)
07:36 *** Connection closed unexpectedly: Error: getaddrinfo EAI_AGAIN chat.freenode.net
07:36 Disconnected from the network. Reconnecting in 11 seconds… (Attempt 4)
07:36 Connected to the network.
07:36 -card.freenode.net- *** Looking up your hostname...
07:36 -card.freenode.net- *** Checking Ident
07:36 -card.freenode.net- *** Found your hostname
07:38 *** Connection closed unexpectedly: Error: read ECONNRESET
07:38 Disconnected from the network, and will not reconnect. Use /connect to reconnect again.
```

**Comment by xPaw** [comment]
irc-framework handles the reconnection.

See https://github.com/kiwiirc/irc-framework/issues/211

**Comment by ssbarnea** [comment]
This went far worse since yesterday when I redeployed my container to a new host. Now it does the ECONNRESET and reconnects every 2-4 hours and sending all the (blue) notify messages inside the current channel instead of the root connection one, creating a huge amount of spam. 

I am not sure if this was because of a newer container being pushed or if there is something with the network stack on the new host that makes it drop connections. The new host is a fedora 33 with docker 20.10 while old one was a centos 8 with older docker. Somehow my bets are on internal thelounge chnages.

**Comment by nanaya** [comment]
There seems to be no response on upstream regarding this and I've been manually patching the file on each update. Is it possible to fix this here instead?

**Comment by brunnre8** [comment]
it's an open issue there, consider sending a proper PR where discussion can happen if you want to see this changed.

Everyone has their own pet issue they need fixed asap, while others simply don't have that issue.
If it's not fast enough, scratch your own itch.

But no, we should not work around it in TL. We'd be rewriting the whole logic for no gain.

**Comment by nanaya** [comment]
the thing is they seem to be convinced it's as intended (and I asked for confirmation on this but no response so far) and thus making pr might be pointless.
