### ISSUE TITLE
Client disconnects when tab is not kept in foreground

### ISSUE THREAD

**Issue by keybrdist** [thelounge/thelounge#4108]
I'm running thelounge inside a docker container. When the user switches to another tab in their browser or minimizes the browser, the client disconnects and they must completely refresh the app to reconnect to IRC.  If the user keeps the tab in the foreground or detaches the tab to its own browser window, the client stays connected as long as the browser is not minimized.

Is there anything I can do to ensure the client stays connected?

- _Node version:_ latest
- _Browser version:_ Chrome, Safari
- _Device, operating system:_ OSX, Windows
- _The Lounge version:_ latest  

---

**Comment by xnaas** [comment]
Are you running thelounge in private or public mode?

**Comment by keybrdist** [comment]
public mode

**Comment by xnaas** [comment]
You need to run in private mode for persistence.

**Comment by brunnre8** [comment]
public mode works by removing clients that "went away" and all their state with it.  
Went away here means disconnected from the server. If that's done by going to the background there's nothing TL can do about that, you'd need to fix the browser.  
It's the same issue on mobile.

Tje solution as xnaas already told you is to use private mode, then your user's state is saved and they will gracefully reconnect upon loading the tab.

**Comment by keybrdist** [comment]
Thanks for the response.  Do you have any ideas why the current version of KiwiIRC does not have this issue? I tested them side by side and KiwiIRC has remained connected all morning, meanwhile thelounge disconnected soon after switching away from the tab.

**Comment by keybrdist** [comment]
> public mode works by removing clients that "went away" and all their state with it.
> Went away here means disconnected from the server. If that's done by going to the background there's nothing TL can do about that, you'd need to fix the browser.
> It's the same issue on mobile.
> 
> Tje solution as xnaas already told you is to use private mode, then your user's state is saved and they will gracefully reconnect upon loading the tab.

can you see my previous message about KiwiIRC now having this problem?

**Comment by keybrdist** [comment]
@brunnre8  The issue is related to this problem in socketio.  I am very certain.
https://github.com/socketio/socket.io/issues/3259
