### ISSUE TITLE
Side-scrollable topic

### ISSUE THREAD

**Issue by flying-sausages** [thelounge/thelounge#4130]
### Feature Description
Topics are usualy super long. It would be nice if we can scroll them to the side instead of reading tiny text off the browser's hover tip :) Trackpad and some mouse users alike will rejoice

**Comment by fnutt** [comment]
Ducplicate of https://github.com/thelounge/thelounge/issues/276

**Comment by flying-sausages** [comment]
Oops, thanks! was checking topics only
