### ISSUE TITLE
Display IRCv3 message-tags in the web client

### ISSUE THREAD

**Issue by ThisIsAreku** [thelounge/thelounge#4132]
### Feature Description
On https://ircv3.github.io/software/clients.html#web-clients the table says that message-tags are supported but i can't find them _[in the UI]_. Also there is no issue to track this feature, despite being referenced in [projects/1](https://github.com/thelounge/thelounge/projects/1)

I feel that displaying raw message tags in the webui is a bit of an advanced user feature but it would be a first step, which could be improved with #1422 later _[with plugins to parse vendor-specific tags]_.

**Comment by dgw** [comment]
What are you expecting to "find" regarding message-tags? That support matrix just means that TL understands how to parse tags, not that it necessarily _does anything_ with the tags/values.

This really is a feature request, I guess. I suggest retitling the issue to "Show message tags in the UI" or something if that's what you want. TL definitely supports tags already, but only for internal use.

**Comment by ThisIsAreku** [comment]
The underlying IRC client library handle tags, but there is no mention of them anywhere in TL, in either the server nor the client.

My use-case is to show details for vendor-specifics tags like those used by Twitch. 

I will edit the title, and I can work on a PR to display them raw in the UI but I also wanted to have opinions on how people expect to have tags displayed.

**Comment by MaxLeiter** [comment]
Tags can be inspected by enabling the irc-framework debug in your config.js. I don't think we'll expose them in the client anytime soon, but I wouldn't be opposed to adding debut logging as a per-user feature
