### ISSUE TITLE
Uploaded GIFs are re-encoded as PNGs

### ISSUE THREAD

**Issue by GoogleBot42** [thelounge/thelounge#4144]
- _Node version:_  v12.18.4
- _Browser version:_ N/A
- _Device, operating system:_ N/A
- _The Lounge version:_ v4.2.0

---

Steps to reproduce:
1) Upload an animated GIF file to thelounge via file upload.
2) Open/Download file at url.
3) File is PNG and is no longer animated or a GIF

Since thelounge intentionally re-renders images for removal of metadata, perhaps this can be done while preserving the frames of the GIF?

Alternatively, metadata maybe can be removed with a lib that targets the metadata specifically and avoids the re-render. This is something I found after a quick search, I'm not sure if it is exhaustive of potential metadata sources. https://github.com/hMatoba/piexifjs

**Comment by dgw** [comment]
Will be fixed in v4.3.0 by #4110.
