### ISSUE TITLE
Option to use Serviceworker Notifications instead of PUSH API (via GCM)

### ISSUE THREAD

**Issue by outis151** [thelounge/thelounge#4145]
### Feature Description
Chrome ( the Chrome Blink Engine ) uses Google Cloud Messaging/Firebase Cloud Messaging to deliver notifications to users when the Push API is used. It would be nice to have an alternative which does not rely on GCM/FCM such as direct Serviceworker Notifications or allowing custom notification handling.

**Comment by klausenbusk** [comment]
You can't run long living code in the serviceworker and ex: websocket isn't supported. The Push API is only way to support push notifications when the "app" is not running, there isn't any other ways to implement it at the time of writing.

**Comment by xPaw** [comment]
"direct Serviceworker Notifications" This is not a thing, and requires the use of Push API. Your browser decides which service to use for push delivery and reports a url to the server, server then sends a notification to that url.
