### ISSUE TITLE
No messages displayed anymore in channels after logging in to Undernet's channel services

### ISSUE THREAD

**Issue by tbergeron** [thelounge/thelounge#4146]
- _Node version:_ 10.9.0
- _Browser version:_ Chrome 87.0.4280.141
- _Device, operating system:_ Windows 10
- _The Lounge version:_ 4.2.0

---

I started going back to `Undernet` to talk with friends (`irc.undernet.org`) and once logged in I cannot receive any messages from channels anymore. Queries still work and join/part/quits too but messages don't display anymore. 

I found it very weird at first until someone told me via a query that they were talking to me on a channel and that channel had no messages displayed after I logged in. I replicated the issue multiple times on multiple devices.

Any idea or suggestion of what I could try to work around this?

I'm quite new to this project so I cannot really help but if I keep using it I might jump in and collaborate for this kind of issue.

Thanks and have a great day

***

Example of what is happening:

```
/msg x@channels.undernet.org LOGIN username password
...
-X- AUTHENTICATION SUCCESSFUL as username
-X- Remember: Nobody from CService will ever ask you for your password, do NOT give out your password to anyone claiming to be CService.
```
No messages ever display again in channels until I quit and reconnect since there are no way of logging out.

**Comment by progval** [comment]
Hi,

I just tried to reproduce this (same version of The Lounge as you, also on Undernet), but I can't. Could you check it still happens?

If yes, could you set both `debug.ircFramework` and  `debug.raw` to `true` in your config file, and copy-paste what you get in The Lounge's logs and in your client's server buffer when someone messages you? (both before and after logging in)

**Comment by MaxLeiter** [comment]
I couldn't reproduce this either, please report back if it occurs again and you have new information.
