### ISSUE TITLE
willing to pay someone to help me setup HTTPS or reverse proxy

### ISSUE THREAD

**Issue by jbehrmusic** [thelounge/thelounge#4153]
noob here. after 5+ hours of going through multiple pieces of documentation, help from people on (https://demo.thelounge.chat/#/chan-2), I still cannot figure this out.

willing to pay someone to help me set this up. and here are the guides I've already tried.

- https://thelounge.chat/docs/guides/reverse-proxies
- https://saputra.org/threads/how-to-install-the-lounge-web-irc-chat-on-ubuntu-server-with-lets-encrypt-https.165/

I already have a lets encrypt cert running just fine on my Vultr VPS. I can also access TL just find at (mydomain):9000. But I can't get HTTPS to work. At all.

**Comment by dgw** [comment]
I'm willing to try and help out tomorrow afternoon (CST), if you're still having trouble. My reverse proxy setup also uses nginx like the guide you linked that I clicked through to. Even if mine is just passing self-signed certs to Cloudflare (which handles the "real" TLS for me), configuring the reverse proxy in nginx should be the same on yours.

**Comment by jbehrmusic** [comment]
> 
> 
> I'm willing to try and help out tomorrow afternoon (CST), if you're still having trouble. My reverse proxy setup also uses nginx like the guide you linked that I clicked through to. Even if mine is just passing self-signed certs to Cloudflare (which handles the "real" TLS for me), configuring the reverse proxy in nginx should be the same on yours.

if you could help that would be great. thank you!

**Comment by f855cbde34a4** [comment]
Similarly, I was talking to you on #thelounge on Freenode the other night, if you're still in a bind and "just want it done", PM me (bigfluff) and I'd be glad to get you setup with Nginx + LetsEncrypt.

**Comment by jbehrmusic** [comment]
> 
> 
> I'm willing to try and help out tomorrow afternoon (CST), if you're still having trouble. My reverse proxy setup also uses nginx like the guide you linked that I clicked through to. Even if mine is just passing self-signed certs to Cloudflare (which handles the "real" TLS for me), configuring the reverse proxy in nginx should be the same on yours.

Yeah, I still need some help. Let me know when you're free.

**Comment by dgw** [comment]
We connected on IRC and sorted this out.
