### ISSUE TITLE
API chat posts

### ISSUE THREAD

**Issue by Festeazy** [thelounge/thelounge#4157]
the ability to generate an API Key per user and then use that key to post to the channel/chat via an endpoint. 

could start off easy with just a post and then develop into more and be also a great start point to other app integration.

personally I would use it to provide a place for Alerts from a smart home setup, if you put in the ability to send a API POST per command would be cool too. that way it could also send alerts to a smart home.

**Comment by dgw** [comment]
This sounds like something a plugin should do if that system ever gets built out, but honestly… it has nothing to do with The Lounge's purpose of providing an always-connected, browser-based IRC client for human users. There are lots of IRC bot/automation frameworks out there, and TL doesn't need to become another.

**Comment by MaxLeiter** [comment]
Closing as this is out of scope like @dgw commented. You may want to look at the existing [plugins API](https://thelounge.chat/docs/api/commands), you can create a custom command to send an http request.
