### ISSUE TITLE
away command help is incorrect

### ISSUE THREAD

**Issue by brunnre8** [thelounge/thelounge#4158]
/away has a wrong documentation after the logic change in #745

Reported by @autra in https://github.com/thelounge/thelounge/issues/870#issuecomment-779823424

**Comment by brunnre8** [comment]
/back isn't documented at all with a help text and should be added for symmetry and to make it discoverable

**Comment by brunnre8** [comment]
The help command isn't a thelounge internal command but an IRC one https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands#HELP

TL simply relays that.

I don't think we should override the output even if it is wrong, but it may make sense to add /help for internal commands

**Comment by autra** [comment]
Thanks for opening this issue @brunnre8. 

> The help command isn't a thelounge internal command but an IRC one [en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands#HELP](https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands#HELP)

It's a user command not formally defined. It may or may not be what's coming from the server. For instance weechat displays its own help.

> I don't think we should override the output even if it is wrong

If the lounge redefines command to behave differently than the standard (`/away` and `/back`), then it makes absolutely sense to me to modify the help command for them. And it's even allowed by the standard (as there is none here).

If UX is the primarily criteria (the main argument for the non standard `/away` behaviour, which I think I agree with, after having thought about it) , then I strongly think `/help away` should explain the non-standard behaviour. Same for `/back`.

Please consider reopening this issue.

**Comment by brunnre8** [comment]
the issue is that TL doesn't control "/help" at all, it sends the command on to the server which replies with whatever.

Our help text is in the panel you'll get when you click the help button on the lefthand side.

>away [message]	
>Mark yourself as away with an optional message.

>/back	
>Remove your away status (set with /away).

So every output you'll get from /help is bound to be wrong as it's not a TL thing but freenode that answers

**Comment by autra** [comment]
> Our help text is in the panel you'll get when you click the help button on the lefthand side.

I see. There is no perfect answer, but in this case I think I'd use this text for the `/help` command as well, ignoring the server output.

**Comment by brunnre8** [comment]
No that's not a very good idea.

Passing along unknown commands is needed as some networks use extensions and people want to be able to use that.

/help in the case of freenode does have valid responses, as for example

```
/help umode
MODE <nick> <+|-><modes>

Usermodes:

     USERMODE     DESCRIPTION
-----------------------------------------------------------------
         +i     - Invisible - hides you from channel listings by users who do
                  not share the channel with you.
         +g     - "caller id" mode - prevents anyone from messaging you until
                  /accept-ed.
         +u     - Unfiltered - messages to you will not be subject to
                  server-side content filtering.
         +w     - Wallops - you receive /wallops messages from staff.
         +D     - Deaf - ignores all channel messages.
         +Q     - Prevents you from being affected by channel forwarding.
         +R     - Prevents unidentified users from messaging you. You may
                  exempt individuals with /accept .
         +Z     - Is connected via TLS (cannot be set or unset).
```

Blanket banning such thing is certainly worse than showing it.

What I think would make sense is to inject a message that this is a server response and doesn't originate from TL

**Comment by autra** [comment]
> /help in the case of freenode does have valid responses, as for example

Yes there is no ideal solution. I agree that displaying server help is necessary.

> What I think would make sense is to inject a message that this is a server response and doesn't originate from TL

Or maybe concatenate the 2, with a "Server help" and a "TL help" section ? If the TL help section says something like "TL command overloads server one", it could make things clear to the user... Alternatively the injected message could contain a link that opens the TL help. Both would work for me (as soon as I can find and understand relevant informations easily).
