### ISSUE TITLE
Feature request: Exponential Backoff on Auto-Reconnection

### ISSUE THREAD

**Issue by DavidBuchanan314** [thelounge/thelounge#4159]
### Feature Description

I am a member of multiple IRC networks with rather flaky hosting. Sometimes they go down for a long time, before coming back. The auto-reconnect usually gives up before they come back online:

```
[...]
07:14 Disconnected from the network. Reconnecting in 11 seconds… (Attempt 354 of 360)
07:14 *** Connection closed unexpectedly: Error: connect ECONNREFUSED 13.49.61.60:6697
07:14 Disconnected from the network. Reconnecting in 11 seconds… (Attempt 355 of 360)
07:14 *** Connection closed unexpectedly: Error: connect ECONNREFUSED 13.49.61.60:6697
07:14 Disconnected from the network. Reconnecting in 11 seconds… (Attempt 356 of 360)
07:15 *** Connection closed unexpectedly: Error: connect ECONNREFUSED 13.49.61.60:6697
07:15 Disconnected from the network. Reconnecting in 11 seconds… (Attempt 357 of 360)
07:15 *** Connection closed unexpectedly: Error: connect ECONNREFUSED 13.49.61.60:6697
07:15 Disconnected from the network. Reconnecting in 11 seconds… (Attempt 358 of 360)
07:15 *** Connection closed unexpectedly: Error: connect ECONNREFUSED 13.49.61.60:6697
07:15 Disconnected from the network. Reconnecting in 11 seconds… (Attempt 359 of 360)
07:15 *** Connection closed unexpectedly: Error: connect ECONNREFUSED 13.49.61.60:6697
07:15 Disconnected from the network. Reconnecting in 11 seconds… (Attempt 360 of 360)
07:15 *** Connection closed unexpectedly: Error: connect ECONNREFUSED 13.49.61.60:6697
07:15 Disconnected from the network, and will not reconnect. Use /connect to reconnect again.
```

I only check my IRC client occasionally, which often means I've missed out on conversation, by the time I notice. I realise I could probably just configure a higher reattempt limit, but I think implementing Exponential Backoff would be better (https://en.wikipedia.org/wiki/Exponential_backoff)

**Comment by brunnre8** [comment]
What's your TL version?
The issue is not with TL but with irc-framework (as the reconnection logic is in there) and was fixed by https://github.com/kiwiirc/irc-framework/pull/248

We updated irc-framework in 761d4825 which is released as v4.2.0

**Comment by DavidBuchanan314** [comment]
Ah, sorry, I am in fact using a slightly ancient version ( v4.1.0 ). I will update, hopefully fixing this. Thank you!

**Comment by brunnre8** [comment]
do note that the upper limit is set to 5min (iirc) so you still might want to patch the config if that's too short for you
