### ISSUE TITLE
Add option to ignore very short nicknames in message bodies (unless it's your nickname)

### ISSUE THREAD

**Issue by andrewphorn** [thelounge/thelounge#4163]
### Feature Description

Short nicknames like `a` and `s` come up a LOT in general chatting. Maybe add an option to not highlight them in message bodies unless it's your nick.

![image](https://user-images.githubusercontent.com/1857241/108801901-cc913f00-754b-11eb-842c-10ff3296e3bd.png)

maybe only highlight it if the following character is a comma, colon, or some other mark used to denote that you're responding to somebody. while the current behavior is "correct", it is contextually wrong 99% of the time.

**Comment by brunnre8** [comment]
Considering that we probably don't want to have a gazillion config options I don't see that as particularly good to have.
After all there is someone with that nick in the room...  
Heuristics based on the character that follows aren't very good as people tend to have very different ways of highlighting nicks, which would be even more confusing.

**Comment by andrewphorn** [comment]
To be clear, I meant as a setting that each user could choose, maybe hidden behind the "advanced settings" toggle since that seems to be for hiding away uncommon or advanced settings.

While true it is somebody's username, I for one would much rather ignore the highlighting on them. It'll be clear if somebody is referring to them even without highlighting.

Alternatively, allow the user to input a list of names not to highlight in message bodies, just like there's the ability to suppress pings when certain strings are present?

**Comment by MaxLeiter** [comment]
Going to close this as it's a fairly niche setting I'd rather not have to maintain. A potential solution to `'s` being tagged is to add logic checking for closed quotes before linking usernames.  (as `'s'` should still link `s`, while `'s` should not be linked)

**Comment by ransagy** [comment]
Sorry for the necro, but i imagined opening a new issue just to link the same exact thing is redundent.
As someone recent to start using thelounge, this immediately drove me insane on QuakeNet, which has a heap of single letter bots/network services like A, S and so on that are triggered so many times in text.

Is there any way to skip those? maybe in CSS (aside from disabling link coloring at all, i guess) if there's a way to isolate the case.
