### ISSUE TITLE
Automatic light/dark theme based on OS settings

### ISSUE THREAD

**Issue by ronilaukkarinen** [thelounge/thelounge#4165]
### Feature Description

It would be nice to have the theme switch automatically to a chosen light theme or dark theme based on which is enabled on the system. Tried to create a [theme](https://github.com/pulinairc/thelounge-themes/blob/a0ee75b588602beb5983c7759c0646b0e745aef8/src/auto-day-midnight.scss#L3) with `preferes-color-scheme` but it always shows the first loaded. It seems either The Lounge or browser or both don't support this feature.

Programmatically this would mean we'd need admin settings for light and dark themes and then it would recognize automatically if the system has changed its theme and change the theme accordingly on The Lounge as well.

**Comment by andrewphorn** [comment]
Just to test out whether or not prefers-color-scheme worked, I made this hideous tweak:

![image](https://user-images.githubusercontent.com/1857241/109390901-276ac380-78c9-11eb-9903-be233c232793.png)

So it looks like it definitely does support that.

**Comment by ronilaukkarinen** [comment]
Some of our users report that my automatic theme actually works. But why it doesn't work for me I'm not sure...

**Comment by MaxLeiter** [comment]
I don't think we'll natively support this, as it doesn't work well with our theme switcher. Themes are welcome to support `prefers-color-scheme` though, I don't see why that shouldn't work as long as a users browser supports it.
