### ISSUE TITLE
Infinity scroll

### ISSUE THREAD

**Issue by sfkpmr** [thelounge/thelounge#4173]
### Feature Description

Currently you can't scroll up "forever". You are shown a "show older messages" button pretty quickly. It would be nice if you could scroll all the way up while messages are loaded continuously.

**Comment by MaxLeiter** [comment]
This has been implemented since 2.5.0. What's your The Lounge version and browser/OS?

**Comment by sfkpmr** [comment]
Ouch, yes, seems to work in Firefox. I normally use Chromium.

But I'm on 4.2.0 with Docker.

**Comment by MaxLeiter** [comment]
Is your Chromium up to date? What version? It works fine for me on Chrome 88.0.4324.192

**Comment by sfkpmr** [comment]
I'm using ungoogled Chromium, so maybe it's missing something? Version 88.0.4324.190.

**Comment by brunnre8** [comment]
Considering that this works on firefox and chrome and chromium I'm gonna close this. Please open up a bug with your browser

**Comment by brunnre8** [comment]
works on edge as well
