### ISSUE TITLE
(X)DCC Support

### ISSUE THREAD

**Issue by optix2000** [thelounge/thelounge#4202]
### Feature Description
Surprised this hasn't been asked before, but it would be nice to have (X)DCC support to handle direct messages and file transfers. For file transfers, TL could either proxy the file directly to the client, or save it on TL for later download via some Downloads/File tab.

**Comment by fnutt** [comment]
It has been asked before, many many times. The answer is still no, and it won't be implemented (confirmed by The Lounge maintainers). If you want to pirate, please use something else than The Lounge.
