### ISSUE TITLE
Don't aggregate hidden messages when loading more messages

### ISSUE THREAD

**Issue by williamboman** [thelounge/thelounge#422]
In channels where the actual text message vs. "ubiquitous messages that are hidden through settings" (e.g. join, part, quit) ratio is very low one can click the `Show more` button multiple times without it actually showing any new messages.

**Comment by astorije** [comment]
See #608 for more details and reproduction steps.

**Comment by richrd** [comment]
Should be fixed in v4 right @xPaw ?

**Comment by xPaw** [comment]
It certainly has been improved by #3603

**Comment by fuzzy76** [comment]
I'm seeing this in 4.1.0?

**Comment by fuzzy76** [comment]
Oh, I hit the 1000 max marker. By far, actually.

The reason is that I run [Bitlbee](https://www.bitlbee.org/) with the Facebook plugin, and it generates join/parts for every time a person among my Facebook friends go online or offline...
