### ISSUE TITLE
Setting to hide unread in title

### ISSUE THREAD

**Issue by ronilaukkarinen** [thelounge/thelounge#4226]
I use telegramircd a lot and I hide some chats because for particular discussions I want to use the Telegram app and not IRC. Anyway, for this reason I'd like to hide the unread number in title. I mean this one:

![image](https://user-images.githubusercontent.com/1534150/118396805-e37e9380-b659-11eb-8e4d-a6342969f16d.png)

Is this possible with any setting option currently? If not, how do you propose to hide it?

**Comment by brunnre8** [comment]
Patch the code, I don't think this use case warrants a setting as it's very niche in my opinion

**Comment by brunnre8** [comment]
https://github.com/thelounge/thelounge/blob/db807d0c5611872de075533280a661b1bccef32c/client/js/store.js#L182-L188
^ here's the code in question

**Comment by ronilaukkarinen** [comment]
> Patch the code, I don't think this use case warrants a setting as it's very niche in my opinion

Okay, I will, thanks for pointing out the correct place in the code! 👍
