### ISSUE TITLE
Network-wide nick autocomplete

### ISSUE THREAD

**Issue by eliocamp** [thelounge/thelounge#4229]
For our conference we are using a bot to do things like inviting people to videocalls with jisti, creating secret channels, and asking people's pronouns. However we would like to restricts those commands to a query with the bot so that public channels are not flooded with bot commands. Also, some commands might be better kept private (like the creation of a secret channel). 

The issue is that since right now autocomplete only autocompletes from the list of nicks on the current channel, when an user wants to send `+pronouns <nick> ` privately to the bot, they don't get the nice autocomplete, and needs to remember the nick. 

Would it be possible to extend autocomplete to search through all nicks on the network. Or at least all the nicks that share a channel with the user on the same network?

**Comment by brunnre8** [comment]
ehm, please don't do that.... I frequently check with the tab key if a user is still online in a chan or not.

Why don't you have the bot spam the perticipants when they first connect, like "Hi I'm your friendly bot, these things I can do"

Then just tell people to communicate in the query message

**Comment by eliocamp** [comment]
Right, that's what we'll do. But that's the problem. When sending to the query window, they lose the autocomplete features and it's way harder to type people's nicks.

**Comment by brunnre8** [comment]
No, I mean literally in the private conversation you have with the bot.
Any messenger these days has a concept of a group chat and a one to one chat.

Just tell them that they need to talk to the bot in the one on one chat with it.
it's easy enough to understand, people are used to it.

**Comment by eliocamp** [comment]
Right. We have a command that creates a jitsi link and send it to people mentioned. So if I want to have a videocall with you, i'd go to the private conversation I have with the bot and type 

`+jitsi brunnre8`

so that you and I would receive a link that we could use to talk. 

The issue is that if I do that, then I wouldn't have autocomplete and I'd  have to literally type `brunnre8` instead of `bru` and then tab to autocomplete.

**Comment by dgw** [comment]
Type from the channel, `/msg botnick +command bru<tab>`. You don't have to be in the private message conversation to send messages there.

**Comment by eliocamp** [comment]
Right. But that's a lot for people who are not used to IRC commands.

**Comment by MaxLeiter** [comment]
Closing as this is out-of-scope for the client. Would be nice for conferences but it would be confusing for the majority of users who have used other clients and previous versions of TL.
