### ISSUE TITLE
Move demo and support channels to Libera Chat.

### ISSUE THREAD

**Issue by bardiharborow** [thelounge/thelounge#4233]
The Freenode team have lost operational control of the freenode network and are cordially suggesting that the community abandon ship.

* https://kline.sh/
* https://fuchsnet.ch/freenode-resign-letter.txt
* https://blog.bofh.it/debian/id_461

**Comment by MaxLeiter** [comment]
Nothing on the repo will be updated until the transfer is complete, but I have filed a project registration request with Libera for #thelounge and our sub channels (-spam, -offtopic). It will probably take longer for the demo to move over, as on Freenode we had an i-line setup and we may use a different method this time around. Thanks for the issue

**Comment by MaxLeiter** [comment]
Verifying this for Libera: libera-958370

**Comment by xPaw** [comment]
The channel got moved, and all references got updated.

The only remaining thing is the demo, which is pending approval/solution from the staff, as far as I can see.
