### ISSUE TITLE
On refreshing the page, a browser form resubmission notification comes and user is logged out of all connected rooms

### ISSUE THREAD

**Issue by t0xic0der** [thelounge/thelounge#4244]
I am using the Dockerized version of the client and this seems to exhibit the above strange behaviour. Is it intended?

**Comment by brunnre8** [comment]
public mode?
Then kinda, as soon as a client disconnects the user gets cleaned up.

**Comment by t0xic0der** [comment]
How can I find that out if my client is in public or private mode?

**Comment by brunnre8** [comment]
look at your config file

**Comment by t0xic0der** [comment]
Here's an illustration,

![image](https://user-images.githubusercontent.com/49605954/119934730-e0fa3300-bfa3-11eb-9c3f-e782ac56c56b.png)

And yes, it is indeed in PUBLIC mode.

![image](https://user-images.githubusercontent.com/49605954/119934778-f8d1b700-bfa3-11eb-89cf-e03a329170b8.png)

Should I type in `false` in place of `true` in front of the `public` property and restart the Docker container for the changes to take effect?

**Comment by brunnre8** [comment]
Please read https://thelounge.chat/docs/configuration#user-management and then https://thelounge.chat/docs/users

Choice is up to you, public mode is intended for ephemeral short connections and not for permanent usage really.

I'm closing this as it isn't really a bug, feel free to hop into IRC on irc.libera.chat on the #thelounge channel if you need help with the setup.

**Comment by brunnre8** [comment]
(link shouldn't have included the anchor tag, fixed it up)

**Comment by t0xic0der** [comment]
Thanks.

I have enabled the private mode and added a new user.

![image](https://user-images.githubusercontent.com/49605954/119935590-5ca8af80-bfa5-11eb-81c3-ca4f4ef94265.png)
