### ISSUE TITLE
Configure logo into TheLounge

### ISSUE THREAD

**Issue by LizHareDogs** [thelounge/thelounge#4245]
Hi! We are using TheLounge for the UseR! 2021 conference this summer.

We'd like to have a configurable option to replace the default logo with the logo of our conference. 

Thanks,
Liz

**Comment by MaxLeiter** [comment]
This has been discussed previously (but I can't find an issue, so maybe it was on IRC). Adding this would make the config more crowded than it already is and you can always just swap the image files and not have to change the code. I talked with @eliocamp about adding it to your fork.

**Comment by LizHareDogs** [comment]
Thanks Max, 

@Elio was uncomfortable making our own fork, and more comfortable doing something form a configuration file.

We are hoping to publish a guide to how to make accessible conferences for other organizations that might want to implement what we did but don't necessarily have the JavaScript or programming skills.

Thanks, 
Liz

Liz Hare, PhD
Dog Genetics LLC
***@***.***
http://www.doggenetics.com

**Comment by dgw** [comment]
If this keeps coming up, and the issue really is only about adding more things to the config, one alternative would be to define/document a path for a custom logo file to be placed and use it if present.

**Comment by el-profesor926** [comment]
Can this not be done by CSS?

**Comment by xPaw** [comment]
We didn't allow configuring this not because of configuration crowding, but to keep the branding.

You can see it being briefly discussed here: #566
