### ISSUE TITLE
Auto expand youtube links and allow to be played in browser

### ISSUE THREAD

**Issue by yaztromo99** [thelounge/thelounge#4253]
Something very useful irccloud has that I miss a lot in the lounge is that pasted youtube links expand and can be played in the irc room without having to open a second tab to youtube.

Is this a planned feature or something implementable with thelounge?

**Comment by MaxLeiter** [comment]
This was addressed by #4135. You need to adjust `prefetchMaxSearchSize` in your config to be large enough to support youtube.  

I would take a look at https://github.com/thelounge/thelounge/blob/master/defaults/config.js#L153-L160

**Comment by yaztromo99** [comment]
Reading through #14 it is hard to tell if it was ever implemented and there's no mention of youtube in there. Is there a plugin already i can use?

**Comment by MaxLeiter** [comment]
Sorry @yaztromo99, there's no way to embed youtube videos in the chat at the moment.

**Comment by xnaas** [comment]
@yaztromo99, #14 and #701 reference what you want: which is richer embeds. I don't know if there's any intention of richer embeds ever being added to core, but maybe there's room for someone to make a plugin someday. Not sure if that'd be possible or not.
