### ISSUE TITLE
Chat message dissappear when I leave the channel

### ISSUE THREAD

**Issue by BlueCell101** [thelounge/thelounge#4255]
Hi, I'm casual user who have just discovered this awesome application but for some reason whenever I leave the channel, the message disappear. I check the config for the user configuration and it's already set in Private  with me having to log into it whenever I use a new browser.  All the setting are still in default and I haven't made any change.
```
// This value is set to `false` by default.
	public: false,
```
<img src="https://i.imgur.com/fVjnlqq.gif">

I use The Lounge application on my seedbox, shared server

This is the specific version of The Lounge that I currently use
```
About The Lounge
v4.2.0
```

**Comment by brunnre8** [comment]
Do you have the sqlite storage backend active?

https://github.com/thelounge/thelounge/blob/53a7227e2eae23ae0fbc9898dca4dd608927e00f/defaults/config.js#L290

If not, it wouldn't save the messages as such because the backlog would just have been in RAM, leaving a channel clears that.

**Comment by brunnre8** [comment]
and by active I actually mean that it's also installed and working, what OS are you on? How did you install thelounge? sqlite is an optional dep, meaning it fails to install for some reason it will log it but happily continue without aborting the installation.

**Comment by BlueCell101** [comment]
Hi, brunnre8. I don't personally know if the server that I use install have sqlite or not. I'm using a rent shared server, and installed the lounge application through the CPanel that are provided by the administrator from the server that I rent.

As for the OS that got used on my server it's this one.

```
 Operating System: Debian GNU/Linux 9 (stretch)
 Kernel: Linux 4.19.0-0.bpo.16-amd64
 Architecture: x86-64
```

**Comment by fnutt** [comment]
You need to ask your service provider then. When installing/starting The Lounge through command line you should be able to see if sqlite was installed and in use or not.

Are you using private mode? As in, do you log into The Lounge with username and password?

**Comment by BlueCell101** [comment]
> 
> 
> You need to ask your service provider then. When installing/starting The Lounge through command line you should be able to see if sqlite was installed and in use or not.
> 
> Are you using private mode? As in, do you log into The Lounge with username and password?

Hi, thanks for the suggestion and I'm sorry for the late reply. I have asked my service provider and they already confirmed that the SQLite are already been enabled and installed on my node. I have also confirmed it with myself, this is the SQlite version that got installed on my service
`SQLite version 3.16.2 2017-01-06 16:32:41`

sqlite backend storage is also confirmed to be activated

`        // This value is set to `["sqlite", "text"]` by default.`
`        messageStorage: ["sqlite", "text"],`

As for my mode I also have been using private mode, when I first start loading the lounge it asked me to log into The Lounge with my username and password that I have set up first.

**Comment by brunnre8** [comment]
the sqlite binary thelounge uses isn't the system installed one, but one which comes bundled by npm / yarn.

You can have a perfectly working system sqlite binary but a non working binary which TL tries to use via JavaScript.

Look at the install and startup logs of TL to see if that's the problem.
