### ISSUE TITLE
Vue error when clicking on user while channel operator. 

### ISSUE THREAD

**Issue by eliocamp** [thelounge/thelounge#4276]
If I'm a channel operator, I get `Vue Error: Cannot read property '0' of undefined` if I click on another user.

With operator

![Peek 2021-07-03 11-43](https://user-images.githubusercontent.com/8617595/124357860-0d811a80-dbf4-11eb-832e-c5beda6f1157.gif)

Without operator mode

![Peek 2021-07-03 11-44](https://user-images.githubusercontent.com/8617595/124357866-12de6500-dbf4-11eb-98cc-b8dc66e23924.gif)

- _Node version:_ v14.17.2
- _Browser version:_ Version 91.0.4472.114 (Official Build) (64-bit)
- _Device, operating system:_ Ubuntu 20.04.2 LTS (GNU/Linux 5.8.0-1035-gcp x86_64)
- _The Lounge version:_  v4.3.0-pre.4

---

**Comment by brunnre8** [comment]
already known and in the works at https://github.com/thelounge/thelounge/pull/4267 will fix it up in a bit
