### ISSUE TITLE
TheLounge showing IRCd password when `lockNetwork` is true

### ISSUE THREAD

**Issue by sndrsmnk** [thelounge/thelounge#4288]
With the IRC network pre-set in the `config.js` file, and `lockNetwork` set to true, the web interface allows the user to change the name of the connection, i'm OK with that, but it also shows the preconfigured IRCd connect password, and i fail to see why that would be practical.

```
        defaults: {
                name: "Test network",
                host: "my.cool.ircd.hostname.example.tld",
                port: 6668,
                password: "123412341234",
                tls: true,
                rejectUnauthorized: true,
                nick: "Nick%%",
                username: "nick",
                realname: "We're all Nick",
                join: "#nick",
        },
        
        lockNetwork: true,
```

![scrot-valor-1627486742](https://user-images.githubusercontent.com/1305017/127352593-cffefed0-b513-4362-abcd-b1aace9178e8.png)

**Comment by brunnre8** [comment]
I think that's a matter of perspectives...
A IRC server password is there to limit access to the server, not force a specific client.

If you want your IRC network to only be accessible via TL you should enforce that with the firewall of the ircd server.

**Comment by sndrsmnk** [comment]
Every bug can be a feature. :smile: 

I can see how this can be used to keep unwanted clients out, maybe even use it in conjunction with an IRCd config that sets connections in a specific class with differing passwords. But i still think the field should _only_ show if the password was not pre-configured in `config.js`.

Our IRCd is accessed by traditional IRC-clients too. It's not that this password is **very** secret. Everyone that may connect, can look up that password, it's just that it's so in-your-face in this current configuration and the less "savvy" users might try and fill their own account password or something.

Same goes for the 'Authentication'-section. Perhaps that could be polished away behind a config flag too?

**Comment by brunnre8** [comment]
The authentication is on the nick (/"account") level.
Only because a default server has a password doesn't mean that suddenly no nick auth is possible.

**Comment by brunnre8** [comment]
What I mean by that is that it's hard to gate the behavior behind the current flags that TL has in the config... and I'm not sure if we really want to add a gazillion config options there.
Some might not want the channel option or realname or what have you and we end up with a bool toggle for every field

**Comment by sndrsmnk** [comment]
Well, let's keep it as you started your first reply, it's a matter of perspective indeed. :sweat_smile: 

 I think i might try to ""fix"" this with a custom theme perhaps. Thanks, brunnre8.
