### ISSUE TITLE
Handle Matrix long message links somehow

### ISSUE THREAD

**Issue by strugee** [thelounge/thelounge#4289]
### Feature Description

If a Matrix user posts a message that is too long, the Matrix IRC bridge will post a link to a text file with that message instead of posting the message itself. It would be nice if The Lounge could handle this intelligently. Maybe if it notices that a link is to a `text/plain` type document, it could just use the text directly instead of showing a link preview? Though I guess this would break linking to "ordinary" text files. Maybe the Matrix folks would be willing to add an HTTP header or something to signal what's happening.

**Comment by strugee** [comment]
This might be a GNOME-specific problem, see https://github.com/matrix-org/matrix-appservice-irc/issues/1172. (GNOME IRC is what originally prompted me to file this bug.)

**Comment by brunnre8** [comment]
not a TL bug, that's up to the matrix folks to make less awkward, meaning prohibit multiline like any other IRC client when they are in a IRC bridged room or not make it a #$@& x sent a long message action but something more intelligent.

The bridge is very configurable so raising the message limit might be an option (matrix org uses 3 iirc)

**Comment by brunnre8** [comment]
https://ircv3.net/specs/extensions/multiline will make this much less akward but it's in a draft stage

**Comment by strugee** [comment]
Ah yes, that seems like a much less hacky fix, when it's ready. Closing then.
