### ISSUE TITLE
Long channel names will not be truncated in the chat top-bar, causing buttons to be pushed off screen.

### ISSUE THREAD

**Issue by itsjohncs** [thelounge/thelounge#4336]
<img width="288" alt="Screen Shot 2021-10-17 at 1 30 34 AM" src="https://user-images.githubusercontent.com/367832/137618756-b3ea9b4d-81c9-4ff6-a221-a7699086f333.png">

**Comment by brunnre8** [comment]
I mean, the easy way out is to truncate the channel name, indicating that we truncated it.
In practice no sane channel has a name that is that long, as this removes the free space a user can actually use to type things.
(IRC is limited to 512 chars per message)
