### ISSUE TITLE
Playback issues with ZNC blowfish plugins

### ISSUE THREAD

**Issue by ylxb2016** [thelounge/thelounge#4346]
- _Node version:_ v10.24.0
- _Browser version:_ Chrome 94.0.4606.81
- _Device, operating system:_ Debian GNU/Linux 10 (buster)
- _The Lounge version:_ both 4.2.0 and 4.3.0-pre.4

---
Sorry to bother you, but I did not find the solution anywhere.  

It might not be possibly to sort out for this issue  https://github.com/thelounge/thelounge/issues/4016 .  

But I have a issue when use thelounge and ZNC plugin(blowfish or crypt). thelounge works well as a receiever, while if I take thelounge as a senter, the issues occurs.  

I have test Hexchat/mIRC with ZNC, the messages playback normally no matter send or receieve.  

- [Thelounge with **ZNC+fish**](#thelounge-with-zncfish)
- [Thelounge with **ZNC+crypt**](#thelounge-with-znccrypt)
- [Thelounge with **ZNC only**](#thelounge-with-znc-only)

> ZNC 1.8.2  
Thelounge(4.2.0 or 4.3.0-pre.4)  
[Crypt](https://wiki.znc.in/Crypt)  
[fish](https://wiki.znc.in/Fish)  
key: 123456   
unencrypted message: `test`  
`ZNC-blowfish` ECB **encrypted** message: `+OK mhsZJ1noMOB/`  
`ZNC-crypt` CBC **encrypted** message: `+OK *pnNNNNKn+HTsKt8ft6De9Q==`  

# Thelounge with **ZNC+fish**

While I send the message via thelounge with **ZNC blowfish**, thelounge could send the crypted messages succusefully, the receiever could decrypt it and playback it as what we suppose, but what thelounge sent could not be shown at thelounge itself, it show nothing, just like it has never send a message.

| Senter                      | Receiever | Thelounge Playback |
| --------------------------- | --------- | ------------------ |
| Thelounge with **ZNC+fish** | Hexchat   | Thelounge          |
| test                        | test      | None               |

# Thelounge with **ZNC+crypt** 

If I send the message via thelounge with **ZNC crypt**, thelounge could send the crypted messages succusefully, the receiever could decrypt it and playback it as what we suppose, but what thelounge show is the crypted messages `+OK *pnNNNNKn+HTsKt8ft6De9Q==` rather than unencrypted messages `test`.  

| Senter                       | Receiever | Thelounge Playback            |
| ---------------------------- | --------- | ----------------------------- |
| Thelounge with **ZNC+crypt** | Hexchat   | Thelounge                     |
| test                         | test      | +OK *pnNNNNKn+HTsKt8ft6De9Q== |

# Thelounge with **ZNC only** 

If I send the message via thelounge with ZNC only, everything is fine.

Thanks!

**Comment by alfablac** [comment]
@ylxb2016 

I have the same issue. I suspect it's something on znc+fish. My own messages are not getting encrypted, so thelounge doesn't display them (no idea why). Other clients display it as unencrypted, so at least you get a buffer of what you type. 
On znc logs you can see your messages are plaintext while others are encrypted. Never found a way to fix this, ended up using thelounge that way because it's one of the few webirc clients that work for me

**Comment by BakasuraRCE** [comment]
Try this module for ZNC: https://github.com/BakasuraRCE/znc-fishlim-reloaded

**Comment by alfablac** [comment]
> Try this module for ZNC: https://github.com/BakasuraRCE/znc-fishlim-reloaded

Tried, the .py file is not recognized on znc

**Comment by BakasuraRCE** [comment]
@alfablac 
I believe I forgot to add that to the readme. First, you need to install Python 3.x on your system and make sure that your ZNC is compiled with the modpython module. After that, restart ZNC, and you will see the modpython module in your administrator panel. Enable it.

If you need further assistance, please open an issue in my repository :)
