### ISSUE TITLE
Do not offer freenode as the default server

### ISSUE THREAD

**Issue by EugenMayer** [thelounge/thelounge#4347]
I do not think (no longer) that freenode should be the default offered server when connecting.

I guess it might be `Libera.Chat` or `OFTC`. I do not really want to pick an opinion which other - what ever is the common good here, not my opinion.

I just think freenode is no longer a sensible choice. 

Thanks!

**Comment by brunnre8** [comment]
where do you mean?

**Comment by brunnre8** [comment]
ah, the new network dialog, I see.

**Comment by EugenMayer** [comment]
Exactly, when launching the first time (as a user)

**Comment by GewoonYorick** [comment]
This might be because you still have an old config file or you use an version that has not had the change yet. The default server was changed in https://github.com/thelounge/thelounge/commit/42bafe71655a73cfcbfb15043f39963f0cd9a2b2.
