### ISSUE TITLE
Condense single messages

### ISSUE THREAD

**Issue by aminvakil** [thelounge/thelounge#4355]
### Feature Description

I've just installed latest beta release (https://github.com/thelounge/thelounge/releases/tag/v4.3.0-pre.6) and faced something caused by https://github.com/thelounge/thelounge/pull/4313.

I don't really care for join/part/mode ... messages even when they're a single one of them, showing them this way just causes more trouble, but I do want to see and open them whenever I want.

Simply I prefer the old way.

**Comment by Jay2k1** [comment]
In contrast to that, I welcome this recent change, as I like to see who joins or leaves while I look at a channel, and it makes little sense to condense single events because it does not save any space. It's difficult to please everyone...

**Comment by aminvakil** [comment]
@Jay2k1 Right, and there was a reason someone implemented this, I brought this up as I was wondering if this could be an option for someone to enable?

**Comment by brunnre8** [comment]
Making this an option seems rather strange I think, considering that we'd end up with a gazillion option if we do that for every change.

You could simply revert the patch on ypur local install

**Comment by aminvakil** [comment]
> You could simply revert the patch on ypur local install

Sure.

What do you think about nicknames get shown like regular text (not coloured) in these messages then?

**Comment by aab12345** [comment]
Don't forget it's open source software.  Developers don't get paid to code this and it's free for everyone to use.

If you want to customize it there might be a developer willing to be hired to help you.

Too many options take time to configure.

@brunnre8 @MaxLeiter maybe an api for options might be handy.  I wonder if there's a way possibly to add options through plugins?  That would open it up to a world of configurations.

**Comment by aminvakil** [comment]
> Don't forget it's open source software. Developers don't get paid to code this and it's free for everyone to use.
> 
> If you want to customize it there might be a developer willing to be hired to help you.
> 
I didn't want to be rude or demanding, I was just trying to give feedback on recent beta release and tell maintainers my opinion.

**Comment by aab12345** [comment]
Of course without people talking about things there wouldn't be development of it to make it better.

The problem is everyone will ask for everything to be added to settings and we would end up with millions of settings then if the devs approved every change request.

On the flip side I don't have status messages turned on so I don't see them regardless but that's a setting.

**Comment by aminvakil** [comment]
> Of course without people talking about things there wouldn't be development of it to make it better.
> 
> The problem is everyone will ask for everything to be added to settings and we would end up with millions of settings then if the devs approved every change request.
> 
I wasn't demanding this to be added to settings. Read my sentence again: "I was wondering if this could be an option for someone to enable?"
> On the flip side I don't have status messages turned on so I don't see them regardless but that's a setting.

**Comment by aab12345** [comment]
config.js or a setting it still has to be added somewhere.  

That was my point really.

**Comment by MaxLeiter** [comment]
I like the recent change and don't want to add an option for it, but will leave this issue open in case others want to share their views.

**Comment by aminvakil** [comment]
After a month, I have got used to current situation and it feels just fine (better than before actually :))

I'm going to close the issue as I'm no longer interested in changing this fine new tweak, thanks again for your work!
