### ISSUE TITLE
Says update is available but it's not

### ISSUE THREAD

**Issue by makeworld-the-better-one** [thelounge/thelounge#4357]
- _Node version:_ v14.17.6
- _Browser version:_ Firefox 93.0
- _Device, operating system:_ The Lounge runs on Debian Bullseye,  the client is Arch Linux
- _The Lounge version:_ v4.2.0

---

![image](https://user-images.githubusercontent.com/25111343/140618530-0ff79538-87c7-488a-9a2c-301df16a9377.png)

The link leads to [here](https://github.com/thelounge/thelounge/releases/tag/v4.3.0-pre.5_fix). This is a pre-release, and not a release for updating. I assume this is just because it breaks the expected pre-release format by having `_fix` appended.

**Comment by MaxLeiter** [comment]
Sorry about that, this should now be fixed (the tag has been deleted).
