### ISSUE TITLE
Add option to disconnect on close in private mode

### ISSUE THREAD

**Issue by AndroidKitKat** [thelounge/thelounge#4358]
### Feature Description
I'd really like to be able to have The Lounge disconnect when I disconnect. I know that's how Public Mode of instances work, but from my experience, this does not save network connections in browser cache. I primarily use [ZNC](https://wiki.znc.in/ZNC), [znc-clientbuffer](https://wiki.znc.in/Clientbuffer), and [znc-push](https://wiki.znc.in/Push) to coordinate multi-client IRC with push notifications, which requires clients to disconnect from ZNC when not in use. 

Since by nature, The Lounge runs in an "always-connected" mode, this breaks compatibility with the above method. I think The Lounge is one of the better (if not best) cross-platform desktop IRC clients, and allowing it to run as a standalone client (i.e. just disconnecting from IRC when the user closes their browser tab) would make it even better. 

Would love to hear more people's thoughts, concerns, etc.

Thanks.

**Comment by brunnre8** [comment]
Then shut down TL or simply disconnect from znc.
TL doesn't keep a connection open nor connects automatically when you manually disconnect first.

**Comment by brunnre8** [comment]
As is, the Lounge really ought to be a client that acts like a bouncer, it's meant to be up 24/7 rather than a thing you fire up when you need it.
I don't think what you want is a goal the project has.

**Comment by itsjohncs** [comment]
Public mode currently doesn't save the user's settings like their nick to their browser, but it could. And if we were to implement #4299 it might make sense to save the networks they're connected to as well.

So I think this issue might be resolved by implementing #4299 and saving a user's configuration to local storage.

I don't know that this issue is obviously out-of-scope @brunnre8.

**Comment by AndroidKitKat** [comment]
@itsjohncs idea of saving a user's connections in a public session to browser storage was my original idea, and probably more closely aligns with the projects goals (if I had to guess).
