### ISSUE TITLE
Add persistent storage

### ISSUE THREAD

**Issue by willwh** [thelounge/thelounge#442]
We should add persistent storage to the server, for logging, users, etc.

Using something like [node-any-db](https://github.com/grncdr/node-any-db) might be a good idea, to allow people to configure with their desired database in config.

**Comment by willwh** [comment]
https://github.com/thelounge/lounge/issues/109

**Comment by YaManicKill** [comment]
So...this I think should be pretty high priority.

We already have a PR for this #501, but ....

I guess we need to make a decision about what we should use for this, and then run with that. Snoonet have just set up a lounge instance and this is their biggest thing, and this would solve the memory leak we have (in a non-horrible way).

Here are the options:

1. Just choose 1 backend and stick with that. sqlite for example
2. Use something like http://docs.sequelizejs.com/en/v3/
3. Use something like node-any-db

I suggest we go for 2.

2 is a nice balance between 1 and 3. We support multiple db options (sqlite, mysql, etc) but we don't go down the full ORM way of having a library that is a jack of all trades, master of none (which is definitely my experience with something like waterline).

Any objections with going with 2 (we don't have to go with that exact one)?

**Comment by MaxLeiter** [comment]
I'd hate to see the work @astorije has put into #663 go to waste, but I think 2 is our best long-term bet.

**Comment by YaManicKill** [comment]
@MaxLeiter That definitely won't be wasted. It will be an option for people who don't want to use a database.

Also, #663 wouldn't be the only solution ever anyway, as it doesn't solve the in-memory issue. It is only for loading messages from the logs on startup. While we are running it does nothing.

So it's still useful on it's own.
