### ISSUE TITLE
Docs/UX: guide users on how to display SASL certfp

### ISSUE THREAD

**Issue by zotanmew** [thelounge/thelounge#4424]
As far as I can tell, at the moment neither the docs nor the network settings direct users to `/whois` their own user to get their certfp so they can add it with nickserv. This would save new users who are looking to set this up some headaches.

**Comment by brunnre8** [comment]
That depends 8n the services used.

Some expose it in whois, others (like libera) don't require the fp at all, simply say `cert add` and it will use the one you are currently connected with.

What I'm trying to say is that it's hard to write docs about something we don't actually control.
It's not a TL but a ircd / services thing

**Comment by zotanmew** [comment]
hmm. (this was created out of frustration after i finally figured it out after an hour of digging through source code)
maybe hint the user towards the network documentation with whois as a fallback suggestion?

**Comment by brunnre8** [comment]
Well, all networks have a support channel for questions just like those.

oftc even has guides: https://www.oftc.net/NickServ/CertFP/#AddCertFPtoNS telling you that the fp is sent when you connect as 9art of the server greeting

**Comment by brunnre8** [comment]
Libera is here: https://libera.chat/guides/certfp

**Comment by zotanmew** [comment]
I see. I suppose we can close this then, thank you!

**Comment by brunnre8** [comment]
And don't get me wrong, I do sympathize with the mess... but I fail to see how we can write better docs than the actual service providers.
If you have an idea how to make the TL specific things clearer we'd certainly appreciate that.

**Comment by zotanmew** [comment]
maybe a sentence in the network configuration that directs users to check out the network's documentation? and maybe a "if nothing else works, try /whois yournick"
