### ISSUE TITLE
&& (and most likely others like that) should not be parsed as channel

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge#443]
At the moment, typing `&&` (such as messaging shell commands) will parse `&&` as a channel name, and therefore will be clickable and tab-able. It should not.

If someone takes this, extra credits given for a test suite that we can augment with these cases, and run as part of `npm test` :-)

**Comment by xPaw** [comment]
We still need to only make channels clickable if the type is supported by the server (I passed the support types to client after irc-fw, but it's never used). That would fix the issue on most networks that don't allow `&` chan types.

**Comment by astorije** [comment]
@xPaw, would this be fixed by #972?

**Comment by xPaw** [comment]
Not yet.
