### ISSUE TITLE
Context Menu for #channels

### ISSUE THREAD

**Issue by pcho** [thelounge/thelounge#4431]
### Feature Description

It would be nice to have #channel links behave like username on click. Showing additional options like: Join, See Invite List, Ban List, etc. That would prevent accidental clicks and give other options for user before entering a channel, in addition to that in modern IRCds it could display a description, website url or email.

**Comment by brunnre8** [comment]
Already done by https://github.com/thelounge/thelounge/pull/4376

That solves the primary issue, don't think we need banlist / invite list there. After all if you aren't joined there chances are you don't need it.
