### ISSUE TITLE
Character count to see how many characters are left before messages are seperated.

### ISSUE THREAD

**Issue by iluvatyr** [thelounge/thelounge#4432]
### Feature Description

When writing into the input field, I would like a feature that shows a character count on the right side of the input field and the max characters, before it gets separated into several messages.
It could look like the following:
![counter](https://user-images.githubusercontent.com/65125735/145865310-8b674db0-b57b-460c-a201-9577c9338e20.jpg)

**Comment by xnaas** [comment]
> [2021-06-02T01:54:20.916Z] <+bookworm> max is 500 from the IRC spec if I read the code comments properly... default of irc-framework is 350

Assuming thelounge uses that default of 350, that would be the 'max' to check against.

**Comment by brunnre8** [comment]
Rather than doing that, we could pop up a message box with something like "this message will be split into $n parts, please consider using a pastebin"

What do you think?
I mean during normal operating you probably don't have to care and then the counter is just noise, especially on mobile where space is limited

**Comment by xnaas** [comment]
I'm, personally, against something that interrupts user workflow (hitting send and getting blocked with a modal/pop-up is anti-user, imo). If that route was chosen, I'd say that doing it only on 3+ messages would at least make it fairly infrequent.

**Comment by brunnre8** [comment]
ah, not that kind of popup. Simply an additional text field above the input box that shows up when you reach a certain threshold. I'm with you, doing that for 3+ messages makes sense, splitting in two is really not that big of a deal

**Comment by dgw** [comment]
/me looks at #3331, which requested something very similar

**Comment by brunnre8** [comment]
ah indeed, so let's close this then
