### ISSUE TITLE
Connect button not working

### ISSUE THREAD

**Issue by BINGOLINGO-1** [thelounge/thelounge#4437]
When I pressed connect the button turned grey and I didn't join, it joins if I put in default info
![Screenshot_2021-12-30-17-57-18-788_org mozilla firefox](https://user-images.githubusercontent.com/82653560/147767988-12847b1b-9862-41ff-bfcc-0ed1df62ce64.jpg)

**Comment by brunnre8** [comment]
Logs? On the server side or in the developer console in your browser?

**Comment by BINGOLINGO-1** [comment]
It fixed itself, so it's prolly a one time

2021-12-30, kt 18:07, Reto ***@***.***> rašė:
