### ISSUE TITLE
Ping timeout on Public mode 

### ISSUE THREAD

**Issue by jisan11218** [thelounge/thelounge#4469]
The lounge version v4.3.0 public version. On Android & ios, users get Ping Timeout if they are idle for 30 seconds. On PC there is no Ping Timeout issue. How can I fix this problem? Please help

**Comment by brunnre8** [comment]
This is a bug tracker, please use #thelounge on irc.libera.chat for support.

**Comment by dgw** [comment]
@brunnre8 FWIW, the problem sounds like timer throttling, which is quite strict on mobile browsers these days. I don't know enough about modern JS/browsers to suggest a fix, but it seems unlikely that OP will be able to do anything to fix/mitigate this without code changes.
