### ISSUE TITLE
History search queries are not sanitized

### ISSUE THREAD

**Issue by sfan5** [thelounge/thelounge#4481]
The Lounge source (1ed4f57a / v4.3.0) (Node.js 17.3.1 on linux x64)

---

SQL [LIKE](https://mariadb.com/kb/en/like/) has two wildcard characters and these are not sanitized, consequently this works:
![Bildschirmfoto_2022-02-14_21-44-23](https://user-images.githubusercontent.com/1042418/153943743-f3731dbb-db4d-4352-b777-e32c8fc9a557.png)

**Comment by brunnre8** [comment]
Well, feature or bug? 😜

**Comment by sfan5** [comment]
I think it's worth marking this a feature for the sake of power users. It just need proper discoverability/documentation then.

**Comment by brunnre8** [comment]
Nah, it's a bug.
That we use a sql like query is an implementation detail that must be hidden from the end user.

I was just kidding.
I appreciate the bug btw, thanks!
