### ISSUE TITLE
Disable Firebase Cloud Messaging

### ISSUE THREAD

**Issue by 1RandomDev** [thelounge/thelounge#4486]
### Feature Description
I would like an option to completely disable FCM and all connections to Google. For me it's really important that non of my messages are sent to google.

Or is it already disabled if I don't register any devices for push notifications?

**Comment by dgw** [comment]
The WebPush component doesn't appear to do anything unless a client turns on the setting, which emits an event that triggers registration with the push service endpoint. Is that fine?

https://github.com/thelounge/thelounge/blob/4be9a282fafa182dc33f84bcf93cdcf6bda48d8b/src/server.js#L564-L584

**Comment by 1RandomDev** [comment]
Well if it doesn't send anything to google unless I click the button yes.

**Comment by MaxLeiter** [comment]
Yes, push notifications will only be sent if you have them explicitly enabled.
