### ISSUE TITLE
>4.3 no longer installs correctly with `npm install -g` (sqlite3)

### ISSUE THREAD

**Issue by sfan5** [thelounge/thelounge#4500]
- _Node version:_ 16.14
- _Operating system_: Ubuntu 20.04 LTS
- _The Lounge version:_ git 7cf95d3cbde8cf41957df93c8d4a3547bebd4cae

---

To reproduce this take an Ubuntu 20.04 system and perform the following:
```bash
wget 'https://nodejs.org/dist/v16.14.0/node-v16.14.0-linux-x64.tar.xz'
tar -xvf node-v16.14.0-linux-x64.tar.xz --strip-components=1 -C /usr/local
git clone https://github.com/thelounge/thelounge.git
cd thelounge
# (build steps are missing here, these don't matter for the demonstration)
npm pack .
cd ..
npm install -g --prefix $PWD/test ./thelounge/thelounge-4.3.0.tgz
```

Expected behaviour: The sqlite module is installed at `test/lib/node_modules/thelounge/node_modules/sqlite3`.

Actual behaviour: There is a broken symlink at `test/lib/node_modules/sqlite3`.
`lrwxrwxrwx 1 root root 42 Mar  2 18:12 test/lib/node_modules/sqlite3 -> ../../../.npm/_cacache/tmp/git-cloneYdcsZu`

Why does this matter? The [Debian](https://github.com/thelounge/thelounge-deb/blob/master/build-package) and [Arch](https://github.com/thelounge/thelounge-archlinux/blob/master/PKGBUILD) package both use `npm install -g`.

**This is a regression since commit c7e504eeab4f09ef673ce896417638632dfd1ed0.**

**Comment by brunnre8** [comment]
The packages have not yet been updated to work with the updated sqlite3

**Comment by sfan5** [comment]
Sure. But if this requires any changes the build process I'd like to know _which_.

**Comment by brunnre8** [comment]
sure. That was just to make everyone aware that the two linked packages aren't good templates

**Comment by brunnre8** [comment]
@JeDaYoshi Not sure what you mean, npm fucks up the sqlite dep for some reason, but simply deleting it means you then don't have the sqlite db stuff working, meaning no scrollback that survives a reboot.

**Comment by JeDaYoshi** [comment]
I mean that in my case, I noticed the `sqlite3` dependency was installed on the initial dep installation (well, as you'd expect it to) and added in the `.deb` package. So, the package installed a `/usr/lib/node_modules/sqlite3` and a `/usr/lib/node_modules/thelounge/node_modules/sqlite3`. `rm -rf`'ing those on the `build-package` script in `thelounge-deb`, and letting the dependencies install by the `postinst` hook (as you'd expect to, given the native nature of the modules for a package for all architectures) worked fine.

**Comment by brunnre8** [comment]
Not sure why or how npm manages to fuck it up, but I must say I've run out of patience.
If anyone has any ideas as to why npm does the symlink, I'd be very interested to hear them.

For packages I maintain, we'll simply switch to yarn for the installation.

```bash
yarn install --frozen-lockfile
export NODE_ENV_PRODUCTION
yarn build
yarn pack --filename thelounge.tar.gz
yarn global add --frozen-lockfile --prefix /usr --global-folder /opt/thelounge file:"$(pwd)/thelounge.tar.gz"
```
Should do.

**Comment by brunnre8** [comment]
Considering all the recent attacks from misguided developers on npm that willy nilly modify their popular packages to `rm -rf /*` or similar things, I suggest people only use yarn to install TL and hence (hopefully) use our lockfile.

The version lookup without that is clearly broken, recent examples:

* https://github.com/advisories/GHSA-97m3-w2cp-4xx6
* https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/ 

I'm closing this, however if someone really wants to make npm work and the change on our side is sensible I'd be happy to take it.
