### ISSUE TITLE
sqlite3 not working after upgrading to 4.3.1-rc.1

### ISSUE THREAD

**Issue by aminvakil** [thelounge/thelounge#4503]
- _Node version:_17.6.0
- _Browser version:_97.0.1
- _Device, operating system:_Arch Linux (both server and client)
- _The Lounge version:_ 4.3.1-rc.1

---
Just upgraded from 4.3.0 to 4.3.1-rc.1 and realized that all chat history of all channels and direct messages are gone.

I've changed two lines in config.js (this has been the same since I've installed thelounge): `bind: undefined` to `bind: aa:bb:cc:dd:ee:ff` (an IPv6) and set `reverseProxy` to `True`.

Please tell me if any further information is needed.

**Comment by brunnre8** [comment]
you didn't loose history as such...
How did you install the package?

Chances are that you didn't pick up sqlite3 properly but it's an optional dep so if that fails ot won't error out.
You should have gotten a warning during install and startup though

**Comment by brunnre8** [comment]
#4500 probably the same error

**Comment by aminvakil** [comment]
I'm maintaining it myself here: https://aur.archlinux.org/packages/thelounge-beta

Basically https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=thelounge-beta#n35.

I didn't know `sqlite` is a dep for thelounge, but it's installed on the server anyway (it's a dependency for pacman (archlinux package manager)).

You can also take a look at command output here: https://github.com/aminvakil/aur/runs/5404098018?check_suite_focus=true#step:11:89
