### ISSUE TITLE
General discussion thread

### ISSUE THREAD

**Issue by GreenLunar** [thelounge/thelounge#4511]
### Feature Description

Please open a General discussion subforum.

Not all issues are fit for chat platform (i.e. link to General support).

Thank you

**Comment by brunnre8** [comment]
Not sure what issues concerning TL aren't suited for IRC, support questions certainly are and specific issues / features can then be transferred to the issue tracker after some investigation if needed.

It's not a goal of TL to serve as a general forum for web related apps

**Comment by GreenLunar** [comment]
OK, I'll do so.

Some things are more difficult to convey on IM platforms and rather be on a static discussion board.

The issue is concerned to ticket #4510 

I'll contact your team soon, even though I want the participation of users as well.

Thank you.

**Comment by brunnre8** [comment]
Vote brigading will also not be tolerated on IRC... just saying.
The amount of feedback you so far received should serve as an indication as to how much of a problem that is in reality for people.

I have several desktop files for various web apps. None of which requires a new type.

**Comment by GreenLunar** [comment]
First of all, I have several desktop files for web apps and even plain links.

Second, I disagree.

In LineageOS, the default browser makes the experience as if each website (I didn't write webapp) is an app of its own, with favicon representing it.

Here, however, instead of using more resources and development time and compulation time to wrap a webapp into into an Electron app and call it done, we can provide and greately ease on webapp developers with a new desktop type, having a widget-less web browser window and the icon on the status bar wil the one of the desktop file.

It is a very good idea and will benefit all of us. I'm not doing it for nothing and I'm not making any profit out of it.  Though, I admit, the benefit here is time and accessibility which is no less than money.

Please, open a discussion sub forum and please let me persuade othes to vote and help to push this proposal I have.

Thank you.
