### ISSUE TITLE
Web Push notifications not working on Android, Desktop is OK.

### ISSUE THREAD

**Issue by brianwoo** [thelounge/thelounge#4515]
Node version: 16.14.0-4 (LTS)
Browser version: Brave 1.36.112 and Chrome 99.0.4844.58
Device, operating system: Pixel 6, Android 12 and OnePlusOne LineageOS 17.1
The Lounge version: 4.3.0

I have read that Web Push (VAPID) should now work on Android devices from (https://github.com/thelounge/thelounge/issues/1076), however, I cannot get the notification popup to work at all. Are there additional steps to follow to get VAPID to work?  Notification does not work on mobile but it does work on my desktop browser which is Brave as well.

**Comment by brunnre8** [comment]
This is an issue tracker and not a support forum.
Please use our IRC channel if you need help setting up TL.

Push works fine on Android.
