### ISSUE TITLE
Banned by Libera.chat immediately upon connecting to server preconfigured in live demo

### ISSUE THREAD

**Issue by alectrocute** [thelounge/thelounge#4518]
Maybe it’s due to the default channel name? I’ve never connected before to this IRC server.

![F10D3674-7C6E-4A86-806A-3BD0FAF0A027](https://user-images.githubusercontent.com/35377827/160420122-9c104a85-6eff-4bde-834a-dd9f89b2b76d.png)

**Comment by alectrocute** [comment]
> Thanks for the report. Some idiot was spamming from the demo server and apparently they banned the IP rather than the user.
> 
> I'll contact them and try to work things out.

I figured this would be the case. Thank you for your help! This is a wonderful project.

**Comment by brunnre8** [comment]
Hm, looks like we got unbanned?
At least it loads fine for me.
