### ISSUE TITLE
Not trim space on Network Settings > Server

### ISSUE THREAD

**Issue by EVOTk** [thelounge/thelounge#4521]
- _Browser version:_ Firefox 98.0.2 (64 bits)
- _Device, operating system:_ Windows 10
- _The Lounge version:_ v4.3.0

---

Hello,
Would it be possible to automatically erase the spaces before and after the Network Settings > Server field?
A bad copy/paste with a space before or after the server address makes the connection impossible.

Exemple : 
- ```irc.libera.chat``` Work
- ``` irc.libera.chat``` Not Work *
- ```irc.libera.chat ``` Not Work

_* Github trim the first space ^^_

Moreover the error is not explicit because removes this additional space

Thx

![2022-04-03 18_19_53-The Lounge](https://user-images.githubusercontent.com/45015615/161437794-9757127c-8979-4c3e-b081-d3a46c07eb16.png)
![2022-04-03 18_20_25-Libera Chat — The Lounge](https://user-images.githubusercontent.com/45015615/161437796-6e85fa41-2a2c-4f71-9493-b02bea803bb4.png)

**Comment by brunnre8** [comment]
It would make sense to do that, yes.
If you could test the commit referenced above that'd be great

**Comment by EVOTk** [comment]
Hello,
Thank you so much for your quick fix!
Unfortunately I don't have strong development skills. I have a simple install of thelougne in docker and I don't know how to test your fix :(

**Comment by MaxLeiter** [comment]
Thanks for the report @EVOTk! The fix has been merged and will be available in the next release. If you'd like it in the meantime, you can build from git.
