### ISSUE TITLE
Add option to force timezone (again)

### ISSUE THREAD

**Issue by B1773rm4n** [thelounge/thelounge#4525]
I was reading #2770  and #4083 already.

I'm running Firefox and there are no options to change the timezone.
It is not acceptable to use the OS timezone in the browser due to privacy reasons.
Also it's not acceptable to install a extension which has access to all data to all websites just for changing the timezone for TheLounge.

One easy fix would be to implement a env variable or a setting in which a timezone can be chosen. The timestamps are saved in epoch time anyway so it's just a matter of visualization.

Already asked on IRC but User xnaas was so nice to give this statement:
> 06:05 <xnaas> Shit out of luck 

What are the reasons against this feature?

**Comment by brunnre8** [comment]
The reasons are that this is an intrinsic browser feature that should just work.

At least as far as I am concerned I won't work around people who break their browser on purpose.
Self host TL and exempt it from the "privacy" features, you're running it after all so you should be able to trust it.
If your browser can't do the exception per host, figure it out with them.

**Comment by brunnre8** [comment]
it makes 0 sense to add options for something which should just work, and in fact does, while we consistently refuse options for actual *features* related to IRC where it would make sense and is simply a preference

**Comment by MaxLeiter** [comment]
Closing for reasons @bookworm shared above. You can see if your browser supports something like Firefox's "resist fingerprinting" that will spoof your timezone: https://support.mozilla.org/en-US/questions/1253204
