### ISSUE TITLE
Use the nickname as realname by default

### ISSUE THREAD

**Issue by emersion** [thelounge/thelounge#4527]
Right now The Lounge will use the string "The Lounge User" as realname if the user hasn't set one. Unfortunately this makes it difficult for other clients to figure out whether the realname is meaningful or not. Clients who want to display the realname need to resort to deny-lists to avoid showing the default realname.

The de-facto standard practice is to set the realname to the nickname if the user hasn't set a custom one. This allows other clients to easily figure out the "no custom realname" case without resorting to hacks.

Would you accept a patch to implement this in The Lounge? 

Apologies if this has already been discussed. I haven't found any past issue about it.

**Comment by brunnre8** [comment]
de-facto standard is a bit of a stretch isn't it?
ZNC does the same as TL in this case (https://github.com/znc/znc/issues/1830) weechat did an empty string assuming https://github.com/weechat/weechat/issues/774 is accurate. So which clients actually do it your way?

But considering that you do have a point and I'm generally not very fond of such vanity things (there's still ctcp version after all) yes, as far as I am concerned I'd be ok with your approach.

Question is, what do you expect to happen when the user changes the nick? Auto switch the realname as well?
Pretty sure that's not how it works in any client out there, pretty much all of them don't mess with the realname once it has been set, right?

**Comment by emersion** [comment]
> de-facto standard is a bit of a stretch isn't it?

Yes, "widely used" is maybe more accurate than "de-facto standard". weechat does follow the behavior explained above though. An empty string isn't a valid realname AFAIK. You can see for yourself by doing `/who #popularchannel`. In my experience realname==nickname is the most popular choice.

Another solution would be to use a fixed string ("Unknown" is a popular one). The downside is that a user who _really_ means to set their realname to "Unknown" will get their realname ignored by other clients. OTOH, many clients already ignore "Unknown".

> what do you expect to happen when the user changes the nick?

Clients seem to not change the realname indeed.

**Comment by brunnre8** [comment]
So which way would be your preferred choice?
Setting it to Unknown is of course much easier as far as edge cases are concerned, but I'd like to see this done the same everywhere, else your original problem wouldn't go away right?
Your client would still need to guess.

**Comment by emersion** [comment]
As an additional data point, jwheare reports that IRCCloud does the same as weechat: set the realname to the nickname by default. If a nickname changes the realname will not immediately change, it'll get updated next time the user reconnects.

We both agree that this is the most sensible behavior.

It's possible to enhance this behavior when the server supports [setname](https://ircv3.net/specs/extensions/setname).
