### ISSUE TITLE
Old logs not showing up in v4.3.1

### ISSUE THREAD

**Issue by dAtBigFish** [thelounge/thelounge#4532]
- _Node version:_ v16.14.2
- _Browser version:_ Firefox 99.0.1 (64-bit)
- _Device, operating system:_ Host@Ubuntu 20.04.4 LTS
- _The Lounge version:_ v4.3.1 

Logs are not showing up even though they exists and new messages are being written into it but they just aren't showing up  old stuff.
Running on Ubuntu 20.04.4 LTS installed via Swizzin.

---

**Comment by Troublesome123** [comment]
Same issue here.

**Comment by MaxLeiter** [comment]
Swizzin uses npm to install thelounge, which is not supported as of 4.3.1
