### ISSUE TITLE
Missing v4.3.1-2 from registry.npmjs.org

### ISSUE THREAD

**Issue by aminvakil** [thelounge/thelounge#4534]
https://github.com/thelounge/thelounge/releases/tag/v4.3.1-2

I've tried https://registry.npmjs.org/thelounge/-/thelounge-4.3.1-2.tgz .

Also 4.3.1-2 is not available in https://registry.npmjs.org/thelounge/ .

**Comment by brunnre8** [comment]
Yeah, that's not a proper release.
The tag got created by mistake (mea culpa)
