### ISSUE TITLE
Emoji list 

### ISSUE THREAD

**Issue by siniStar7boy** [thelounge/thelounge#4566]
### Feature Description
It would be extremely helpful to have an Emoji list for users who cannot remember the :emoji-name: 

IRCCloud has an emoji list, for example -- in the input/typing area where you can select the desired one and it is put into the message.

On IRC (Libera.Chat), this was requested by both @freakyy85 and myself.

**Comment by aab12345** [comment]
There is one -

https://github.com/thelounge/thelounge/blob/24316fc304d339d07ff15771fcde4c132cd9bb4c/client/js/helpers/simplemap.json

**Comment by dgw** [comment]
@aab12345 That's not accessible by a user via the GUI.

**Comment by freakyy85** [comment]
Yes it would be really nice to have this. :)

**Comment by xPaw** [comment]
Duplicate of #3958
