### ISSUE TITLE
VUE Error

### ISSUE THREAD

**Issue by eaeahm** [thelounge/thelounge#4568]
- _Node version:_16.15.0 LTS
- _Browser version:_Tested on multiple browsers, same issue
- _Device, operating system:_Tested on Win, macOS and Linux (Debian, *buntu, Arch) + Debian 11 (VPS) and Ubuntu 22.04 (VPS), same issue
- _The Lounge version:_4.3.1

---
Hello,
I keep getting VUE ERROR when I click the Mentions button after using TL for a while and I have to restart thelounge.service. Not sure what's going on or how to troubleshoot it, just want to see if anyone else is getting the same error.

I clear che znc buffer and the channel buffer/chat multiple times a day and after a while I see that error.

**Comment by brunnre8** [comment]
Logs? Client side in the dev console of your browser as well as server side from TL

**Comment by eaeahm** [comment]
I have to wait for the error again now but also I have to check what kind of logs TL is generating, how much of my personal stuff I have to clear from there etc. I keep IRC very separate from ...let's say, the real world/my real life.

**Comment by brunnre8** [comment]
Up to you, if we don't get any information we can't fix it though

**Comment by eaeahm** [comment]
Still waiting for the error to reappear, where would the log located be in the server?

**Comment by brunnre8** [comment]
stdout, so depends on how you start it.

**Comment by eaeahm** [comment]
I always use this way:
Add repos and install LTS from here: https://github.com/nodesource/distributions/blob/master/README.md and install the latest .deb manually, then I stop the process (systemctl stop thelounge.service) to edit my personal stuff and restart it with (systemctl restart thelounge.service). That's about it.

Also the main connection is to a ZNC on the same VPS.

Still waiting for the issue, didn't use IRC much today but it will appear again tonight or tomorrow.

**Comment by eaeahm** [comment]
I'll reopen one when I see it again, I am editing the theme so I restart the service multiple times a day and I'm not giving it a chance to appear right now.
