### ISSUE TITLE
vue.js:117 TypeError: Cannot read properties of null (reading 'channel') when clicking the Mentions button (@).

### ISSUE THREAD

**Issue by eaeahm** [thelounge/thelounge#4570]
- _Node version:_16.15.0
- _Browser version:_Chromium based
- _Device, operating system:_Debian 11 on VPS
- _The Lounge version:_4.3.1

---

Log:

:9000/#/chan-2:1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://VPSIP:9000/') with script ('https://VPSIP:9000/service-worker.js'): An SSL certificate error occurred when fetching the script.
webpush.js:47 DOMException: Failed to register a ServiceWorker for scope ('https://VPSIP:9000/') with script ('https://VPSIP:9000/service-worker.js'): An SSL certificate error occurred when fetching the script.
(anonymous) @ webpush.js:47
vue.js:117 TypeError: Cannot read properties of null (reading 'channel')
    at Mentions.vue:179:1
    at Array.filter (<anonymous>)
    at u.resolvedMessages (Mentions.vue:179:1)
    at vn.get (bundle.vendor.js?v=9303b22dc9:2:173625)
    at vn.evaluate (bundle.vendor.js?v=9303b22dc9:2:174765)
    at u.resolvedMessages (bundle.vendor.js?v=9303b22dc9:2:175530)
    at u.<anonymous> (Mentions.vue?679d:1:362)
    at u.t._render (bundle.vendor.js?v=9303b22dc9:2:181609)
    at u.r (bundle.vendor.js?v=9303b22dc9:2:211574)
    at vn.get (bundle.vendor.js?v=9303b22dc9:2:173625)
a.Z.config.errorHandler @ vue.js:117
DevTools failed to load source map: Could not load content for https://VPSIP:9000/js/bundle.vendor.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
vue.js:117 TypeError: Cannot read properties of null (reading 'channel')
    at Mentions.vue:179:1
    at Array.filter (<anonymous>)
    at u.resolvedMessages (Mentions.vue:179:1)
    at vn.get (bundle.vendor.js?v=9303b22dc9:2:173625)
    at vn.evaluate (bundle.vendor.js?v=9303b22dc9:2:174765)
    at u.resolvedMessages (bundle.vendor.js?v=9303b22dc9:2:175530)
    at u.<anonymous> (Mentions.vue?679d:1:362)
    at u.t._render (bundle.vendor.js?v=9303b22dc9:2:181609)
    at u.r (bundle.vendor.js?v=9303b22dc9:2:211574)
    at vn.get (bundle.vendor.js?v=9303b22dc9:2:173625)
a.Z.config.errorHandler @ vue.js:117
Ut @ bundle.vendor.js?v=9303b22dc9:2
Ht @ bundle.vendor.js?v=9303b22dc9:2
t._render @ bundle.vendor.js?v=9303b22dc9:2
r @ bundle.vendor.js?v=9303b22dc9:2
vn.get @ bundle.vendor.js?v=9303b22dc9:2
vn.run @ bundle.vendor.js?v=9303b22dc9:2
dn @ bundle.vendor.js?v=9303b22dc9:2
(anonymous) @ bundle.vendor.js?v=9303b22dc9:2
Zt @ bundle.vendor.js?v=9303b22dc9:2
Promise.then (async)
Yt @ bundle.vendor.js?v=9303b22dc9:2
ee @ bundle.vendor.js?v=9303b22dc9:2
(anonymous) @ bundle.vendor.js?v=9303b22dc9:2
vn.update @ bundle.vendor.js?v=9303b22dc9:2
ct.notify @ bundle.vendor.js?v=9303b22dc9:2
set @ bundle.vendor.js?v=9303b22dc9:2
mn.set @ bundle.vendor.js?v=9303b22dc9:2
togglePopup @ Mentions.vue:217
(anonymous) @ eventbus.js:45
emit @ eventbus.js:44
openMentions @ Chat.vue:231
qt @ bundle.vendor.js?v=9303b22dc9:2
n @ bundle.vendor.js?v=9303b22dc9:2
i._wrapper @ bundle.vendor.js?v=9303b22dc9:2

Screenshot of the error attache
![Screenshot 2022-05-11 223958](https://user-images.githubusercontent.com/84944160/167999980-b36186c9-9ade-4ba5-a515-1077e4992098.png)
d

**Comment by brunnre8** [comment]
>An SSL certificate error occurred when fetching the script.

Do you have an invalid cert?

**Comment by eaeahm** [comment]
I created a self signed one, this vps doesn't have a domain or anything.

**Comment by eaeahm** [comment]
Trying with just http and I get this:

DevTools failed to load source map: Could not load content for http://VPSIP:9000/js/bundle.vendor.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by brunnre8** [comment]
psh can't possibly work over http as the service worker won't install unless its localhost

**Comment by eaeahm** [comment]
Been using it in HTTP for a while and never got that problem once, I guess it doesn't work properly if the certs are self signed?
