### ISSUE TITLE
Automatically reconnect if Socks proxy disconnect

### ISSUE THREAD

**Issue by realitix** [thelounge/thelounge#4573]
Hello, I am using a Socks proxy and it works very well with The Lounge.
However, sometimes, my Socks proxy dies because of a network failure (for example).
When I restart the Socks proxy, The Lounge doesn't autoreconnect to the server, I have to restart The Lounge service.

I think the problem is the same for others proxy types too.

Would you be able to add a feature to autoreconnect (trying to reconnect every 30 sec for examples) ?

Thanks,

**Comment by xPaw** [comment]
This sounds like an issue in https://github.com/kiwiirc/irc-framework can you make this issue there, and provide a log of what the disconnect reason is (even better if you can get it with irc-framework debug enabled).
