### ISSUE TITLE
Implement "Jump to New Messages" functionality

### ISSUE THREAD

**Issue by brettgilio** [thelounge/thelounge#4576]
Just as TheLounge has a "Jump to Recent Messages" button, it would be nice if there was a "Jump to New Messages" button which points upward and would scrollback to the mark "New messages". It seems like it might be trivial to implement as there is a class marker for new messages: `unread-marker-text`. However, I am not a web developer so I could be wrong! 

Jump to recent messages is implemented @ https://github.com/thelounge/thelounge/blob/763047889d4a681e8b8f8404befa7c66e5395278/client/components/Chat.vue#L92-L101

I think this function could be reimplemented to a potential `jumpToNew` perhaps piggybacking off of https://github.com/thelounge/thelounge/blob/6dfd51bb5795b97e5341948729507ffb74055b63/client/components/Windows/SearchResults.vue#L236-L249

**Comment by brunnre8** [comment]
duplicate

**Comment by dgw** [comment]
To elaborate, duplicate _of_ #849

**Comment by brunnre8** [comment]
https://github.com/thelounge/thelounge/issues/4101 actually, but sure
