### ISSUE TITLE
Noscript addon breaks image previewer if videos are linked

### ISSUE THREAD

**Issue by tokariu** [thelounge/thelounge#4584]
- _Node version:_ v14.18.1
- _Browser version:_ FF v101.0
- _Device, operating system:_ W10
- _The Lounge version:_ v4.3.1

---

When people post images in the chat, usually you can click on them and an overlay div is opening showing the image in full size over the whole visible area of the window.
I guess since the last update of v4.3.1 it is showing the image overlay only in the narrow left channel-list area instead of the whole chat area.

Now for the cause of the issue:
it seems TheLounge is now trying to load external resources to make this work like it should. I have noscript-addon installed and it blocks `j-chaos.net`, see:
![loung](https://user-images.githubusercontent.com/7195846/171825020-ec5f3ffe-298b-4c68-b01c-fba0d107c35e.png)

when I temporarily allow `j-chaos.net` with noscript, TheLounge opens the images as expected. So it seems TheLounge is dependent on ressources of `j-chaos.net` to work properly. This should not be the case. Opening images in the Chat should not require the loading of external js(?) ressources to work.

please consider reworking this functionality without depending on external resources (if that really is the case).

**Comment by deltamualpha** [comment]
Do you have any lounge plugins installed? It seems... unlikely... that thelounge loads an external resource like that (there's no reference to that domain in the codebase on a quick search).

**Comment by tokariu** [comment]
> Do you have any lounge plugins installed? It seems... unlikely... that thelounge loads an external resource like that (there's no reference to that domain in the codebase on a quick search).

yeah right, after you mentioned that, I took a deeper look again.
I guessed wrong, it's not TheLounge loading external ressources. Someone in the chat posted way up in the backlog of the chat an URL which seems to mess up the image-viewer in TheLounge (probably when it tries to parse the link).

the URL was (slightly changed for privacy reasons): `https://somecast.j-chaos.net:8989/streamname`

if this URL-Link is present in the current chatlog, the image viewer of other image links from the same chat is not working (issue above). in other chatrooms with image links - without this suspicious url - the image viewer is working fine.

so I guess TheLounge is somewhere having a URL parsing issue here..

**Comment by xPaw** [comment]
1. noscript may also block media elements, not just actual scripts.
2. Lounge has `script-src self` which would prevent any third party scripts from loading if there was such an issue.

Sounds to me like noscript is hiding/breaking some element which causes html to shift. I just installed noscript and tried it on my site (steamdb.info) and it's causing all kinds of issues around a video element:

![image](https://user-images.githubusercontent.com/613331/172019391-1d2822ec-d68c-4671-9be0-ad527c415db6.png)

So this doesn't sound like a bug with TL.

**Comment by brunnre8** [comment]
Considering that our CSP blocks js interactions and that embedding the video is done per design and only if previews are enabled, I'm closing this as being not our bug.

**Comment by brunnre8** [comment]
Out of interest though... Looking at https://somecast.j-chaos.net:8989/streamname implies a stream, not an image. So which one is it now? Did it return an image content type or a video embbed?

**Comment by tokariu** [comment]
> Out of interest though... Looking at https://somecast.j-chaos.net:8989/streamname implies a stream, not an image. So which one is it now? Did it return an image content type or a video embbed?

the URL was posted in the chat. TheLounge did NOT do any preview of that URL (it was an icecast music stream afaik). maybe it tried to produce a preview of said URL but failed to do so (even if there is nothing to show). Never had an issue like that with TL before and it is only happening with this kind of URL.
