### ISSUE TITLE
OFTC doesn't authenticate with cert

### ISSUE THREAD

**Issue by c10l** [thelounge/thelounge#4604]
- _Node version:_ 16.14.2
- _Browser version:_ Firefox 102.0
- _Device, operating system:_ MacBook Air M1, macOS 12.5 Beta (same issue on non-beta though)
- _The Lounge version:_ 4.3.1

---

I followed OFTC's instructions on how to use a client cert for auth (https://www.oftc.net/NickServ/CertFP/#AddCertFPtoNS).

When I reconnect, most times The Lounge doesn't offer the cert and I end up with a random number suffix on my nick.

The only way to fix it is by manually authenticating with NickServ using my password. I tried re-registering the cert with NickServ but it tells me it's already added to my account.

**Comment by brunnre8** [comment]
Enable debug output for irc-framework in your server config, show a log of such a connection that fails to present the cert and paste it here, sanitize where necessary

**Comment by brunnre8** [comment]
even without debug enabled, it should be visible

```
11:59 -liquid.oftc.net- *** Looking up your hostname...
11:59 -liquid.oftc.net- *** Checking Ident
11:59 -liquid.oftc.net- *** Found your hostname
11:59 -liquid.oftc.net- *** No Ident response
11:59 -liquid.oftc.net- *** Connected securely via TLSv1.3 TLS_AES_256_GCM_SHA384-256
11:59 -liquid.oftc.net- *** Your client certificate fingerprint is 81A32C7E496CE60A2F0A375A978A96273A4C5C12
```

Or in other words, works on my machine™
Meaning you need to show the log from your end

**Comment by c10l** [comment]
Hi, thanks for looking. I have enabled the irc-framework debug logs but as my luck would have it, it's now working.

To be fair, it's an intermittent failure so I expect it to stop working in a few days if I try to reconnect. I'll leave debug on until that time.

Where are the logs stored though? I can only find logs for the channels I'm in, not network logs.

**Comment by brunnre8** [comment]
you don't want to keep debug enabled, you'll see every ping and pong

In your server buffer of the network

**Comment by c10l** [comment]
It's pretty silent on the app - pretty much the same as without `ircFramework` debug. If I also enable `raw` debug, then I get a lot of chatter.

I don't have the logs from prior failed connections but IIRC nickserv yells and The Lounge just yields and adds a random number suffix to my nick. No success auth following it, and I need to auth manually using my password.

**Comment by brunnre8** [comment]
>The Lounge just yields and adds a random number suffix to my nick

That doesn't mean that the cert wasn't presented... can be a ghost from an earlier unclean disconnect or nickserv booting you from the nick due to enforce being on etc 

What made you think that the cert wasn't presented exactly? What did Nickserv tell you?

**Comment by c10l** [comment]
I'm still going from memory as I can't find logs for those connections. Are these logs written to disk somewhere?

IIRC it didn't tell me much - except that that nick is registered and I had to either auth or change it. Then The Lounge would change the nick.

**Comment by c10l** [comment]
I have them enabled. Like I mentioned before, I have logs for every channel I'm on, but not connection/network logs.

**Comment by brunnre8** [comment]
I mean, TL happily displays the fingerprint
>-helix.oftc.net- *** Your client certificate fingerprint is 66471A97996CD5EBD1B72CF31FA8E7D42CBE571C

Tried asking the oftc people what could be going on?

**Comment by brunnre8** [comment]
So, I did ask.

>@ dwfreed> bookworm: our current services allow specifying a nick on your account when adding the cert; as long as you're using any nick on the account, the cert will identify you (so link your client's preferred alt nick), and then if there's a nick specified with the cert, services will automatically trigger a regain for that nick if it's not the nick you're using

Or in other words, you'd need to group every alt nick to your account that could ever be in use.  
Just the cert ain't enough (don't understand the reason, I'd just uniquely map a cert to an account but whatever)

TL doesn't make the alt nick configurable and I don't think we plan to do so.

In other words, just switch to normal pw auth for oftc until they manage to upgrade services so that they expose sasl external like every modern network nowdays.

**Comment by brunnre8** [comment]
(EWONTFIX for the lack of a better label, ENOTOURPROBLEM would be more suited in this case)
