### ISSUE TITLE
Add setting for users that you don't want highlights from

### ISSUE THREAD

**Issue by McInkay** [thelounge/thelounge#462]
Now that we have custom highlights, this is especially an issue. We should have a way to define users that don't highlight us at all.

Probably just as simple as a CSV textbox of users (same as the way custom highlights works) which is checked when we get a new message, and highlight removed if hte user is in that list.

**Comment by MaxLeiter** [comment]
Alternatively or additionally, we could add an ignore option to user context menus (and channels, I guess).

Personally I'd prefer this instead of a text box as the settings menu is cluttered as is imo, but if people really want one then it could just append to it automatically.

**Comment by YaManicKill** [comment]
I'm happy with adding the option to the user context menu, but I don't think it should be the only UI for it. We don't want the only way to remove a user from that list to be find their username and click on it. Whether that is a (more user friendly than a textbox) list of users in your highlight ignore list, or just the textbox that you can delete a user from, we need something like that.

**Comment by McInkay** [comment]
Think this is covered by #2197 now?

**Comment by astorije** [comment]
I think so!
