### ISSUE TITLE
trying to eliminate username, real name, and leave message from the login page

### ISSUE THREAD

**Issue by Amy-Ames** [thelounge/thelounge#4621]
Hi hi, I've used IRC to solve this once upon a time. But the method I stumbled on for editing bundle.js in 4.0 seems to break the lounge completely in the current version so my old way does not work.

6:26 PM → misterpickles joined (sid332138@user/misterpickles)
6:26 PM Channel mode is +ntz
6:26 PM <misterpickles> hi hi
6:28 PM <misterpickles> im sorry to have to ask again, MaxLeiter helped me with this once and yall pulled a log where the question was answered. ive used thelounge for a year or so , i solved this already , but im just being blunt i got out of the ICU a week ago and i have big time brain fog.
6:28 PM <misterpickles> im trying to eliminate username, real name, and leave message from the login page
6:28 PM <misterpickles> because they confuse our users
6:29 PM <misterpickles> i can delete the <connect-row>'s in firefox or chrome
6:29 PM <misterpickles> and have the login page just ask for a nickname and channel
6:30 PM <misterpickles> i did it in the vendor bundle last time which was kind of naughty
6:30 PM <misterpickles> i cracked this in an hour when i upgraded to 4.0 and here i sit, days later, stumped
6:33 PM <misterpickles> and i just cannot remember how i got rid of those two or three connect-rows

**Comment by Amy-Ames** [comment]
... we share one GitHub account, im not Amy lol

**Comment by brunnre8** [comment]
https://github.com/thelounge/thelounge/issues/3974

You already received the support how to work around it with CSS or patching the source in our IRC chan

**Comment by daaang** [comment]
Sorry to necro this, but does anybody have a record of the help received in IRC? I'm running thelounge in a container, and I'd rather not fork the project, patch the source code, and set up my own separate CD pipeline for containers with patched source code. If there's a way to inject CSS, I'm not finding documentation of it or examples in the github issues.

If it's not currently possible, and if it would be a welcome change to add some config to optionally hide these fields behind e.g. a `[ ] Show advanced fields` toggle, I'm happy to fork and make a PR—I just actually don't know whether it's already possible for me to fix this with custom CSS somehow.

**Comment by brunnre8** [comment]
you'd create a custom theme and set that as the default
