### ISSUE TITLE
css bugs and irc art compatibility

### ISSUE THREAD

**Issue by paigeadelethompson** [thelounge/thelounge#4625]
the nick field is all messed up in chrome: 
![Screenshot_20220904_081840](https://user-images.githubusercontent.com/47037454/188320864-60fc591d-b9ec-4f5e-989b-eab152527497.png)

first hand the cause would seem to be 
```
@media (min-width: 480px)
#chat .from {
    -webkit-mask-image: linear-gradient(270deg,#0000,#000 10px);
    mask-image: linear-gradient(270deg,#0000,#000 10px);
    padding-left: 10px;
```
disabling the `webkit-mask-image` property fixes it 

----- 

IRC art looks weird because the line height adds a gap between each line causing black stripes: 
![Screenshot_20220904_082053](https://user-images.githubusercontent.com/47037454/188320974-6e0f9e11-7f0d-4c09-857d-bd5b97351fa4.png)

```
#form, .messages .msg, .userlist {
    font-size: 14px;
    line-height: 1.4;
}
```

I find that the simplest and cleanest way to fix this is to add `margin-top: -4px` for the abyss theme, the amoled theme requires -8px:
![Screenshot_20220904_082525](https://user-images.githubusercontent.com/47037454/188321152-990ea5f9-3438-4015-9ff5-64f799eaa4f1.png)

I won't pretend to know the actual right way to fix that, that was just a way that works, this is also dependent on a monospace font, 

some of the colors are a bit off too: 

![Screenshot_20220904_082618](https://user-images.githubusercontent.com/47037454/188321199-9313e6b9-2e51-4795-8ef3-2908be9e8922.png)

![Screenshot_20220904_083228](https://user-images.githubusercontent.com/47037454/188321474-9a60b357-7ede-4ee7-8fc7-445c0a3bbb1c.png)

It looks like this happens whenever the fg and bg colors are the same: 
```
<span class="irc-fg5 irc-bg5">furretfurretfurretfurretfurretfu</span>
```

line breaks will occur in the middle of ascii pictures which is less than ideal:

![Screenshot_20220904_083548](https://user-images.githubusercontent.com/47037454/188321593-525a910d-37ec-401c-a92e-cd9ad42e3a33.png)

The page also slows down to a crawl after the buffer starts to fill up and it doesn't do any de-duplication on links for the preview 

- an option to disable preview for urls that contain color codes would be nice 
- a size limit for the scroll back buffer in the options would be nice 
- font choice in options would be nice (recommend meslo nerd font/mono) 
- maybe skip inserting a line break if previous message contains color codes and the amount of time since the last message is less than maybe 5 seconds.

**Comment by brunnre8** [comment]
Not a default theme, hence not our bug.
Some things may be valid, but mixing different issues into a single one makes it hard to handle and hence it's undesired to do that.
However none of the bullet points seem to be something I'd personal favor... Font config is already an option with custom CSS, so just use that, special casing anything related to ascii art gets my immediate NACK. Too brittle
