### ISSUE TITLE
Implement push notifications for Safari

### ISSUE THREAD

**Issue by ll024** [thelounge/thelounge#4626]
On the Settings page The Lounge mentions that Safari does not support web push notifications including a link to [the WebKit bug tracker](https://bugs.webkit.org/show_bug.cgi?id=182566). However, the bug tracker issue has been resolved since June 13th 2022, as PushManager support was included in Safari. 

Dev documentation can be found on [Apple’s website](https://developer.apple.com/documentation/usernotifications/sending_web_push_notifications_in_safari_and_other_browsers).

**Comment by brunnre8** [comment]
Other than removing the message there's nothing we need to do if Apple adheres to the webpush spec

And as we guard the message behind an unsupported check for webpush, it'll simply not show up once Apple rolls it out.

Don't think this is actionable from our side for now

**Comment by aab12345** [comment]
Just to add to this even though it's closed. Taken from:
https://www.apple.com/uk/ios/ios-16/features/#:~:text=Web%20push%20notifications,Coming%20in%202023.

Web push notifications - Adds support for opt‑in notifications on iOS. Coming in 2023.

It doesn't specifically say when, but it says it's coming.
