### ISSUE TITLE
iOS 16 now supports push notifications in browser

### ISSUE THREAD

**Issue by Kakise** [thelounge/thelounge#4627]
### Feature Description:
Adapt the existing notification system to make it available on safari. As of iOS 16, it supports push notifications.

https://bugs.webkit.org/show_bug.cgi?id=182566

**Comment by brunnre8** [comment]
We are aware.
It's behind a feature teat, as soon as your device supports it it'll magically start working if apple didn't mess up

**Comment by aab12345** [comment]
Just to add to this even though it's closed.  Taken from:
https://www.apple.com/uk/ios/ios-16/features/#:~:text=Web%20push%20notifications,Coming%20in%202023.

**Web push notifications - Adds support for opt‑in notifications on iOS. Coming in 2023.** 

It doesn't specifically say when, but it says it's coming.

**Comment by Moraxyc** [comment]
Now it’s coming

https://developer.apple.com/documentation/usernotifications/sending_web_push_notifications_in_web_apps_and_browsers
