### ISSUE TITLE
Add /ignore system

### ISSUE THREAD

**Issue by dgw** [thelounge/thelounge#464]
Having a flexible ignore system that allows specifying all or part of a hostmask and various options for what to ignore (highlights in channels, joins/parts/quits, all messages, PMs, etc.) would support #462 and well beyond.

I feel like I _always_ bring up Textual as an example, but I have stuck with it for a reason. This is what Textual's `/ignore` window looks like, with the various options. It's very configurable, and I much prefer it to the simple all-or-nothing approach most other clients seem to take. Obviously this is a longer term thing, and implementing HL ignores separately might happen on the way, but features like this would go a long way toward making The Lounge a true replacement for running a desktop client.

![Textual 5 /ignore window](https://cloud.githubusercontent.com/assets/164140/16600850/3a7d141e-42d7-11e6-8dbf-8c0689ba77c3.png)

**Comment by christer88** [comment]
Please make this support regex so we can ignore highlights in specific cases, e.g. ^(?!\[(hub|survival|city|creative)\]\[Mod\] <nick>).*<nick2>

**Comment by rgarrigue** [comment]
+1

I'm specificaly looking for a way to avoid the flood caused by bot spamming link like github's issues closed

**Comment by soja92** [comment]
Would like to see this implemented in any form. There is an announcebot spamming a channel I am in and with Lounge I have no way of ignoring it.

**Comment by MaxLeiter** [comment]
@soja92 https://github.com/thelounge/lounge/wiki/CSS-Modifications#hide-messages-based-on-nick

**Comment by divadsn** [comment]
Could be useful to hide message spam from bots in some IRC channels :)

**Comment by McInkay** [comment]
Just had a thought about this.

What might be a nice thing when we eventually implement it, is implementing the hiding of messages with a css class, rather than not removed from the dom, so that certain ones could be implemented by themes as muted or similar instead of completely hidden.

**Comment by xPaw** [comment]
@McInkay that won't stop push notifications and other things.

**Comment by McInkay** [comment]
@xPaw No, but they can be handled as well.

We send the message with an ignored attribute, the client then doesn't notify the user, and adds the message to the dom with the class for the ignored message.

As for push notifications, the server will get the settings and not send push notification if it's ignored for notifications.

**Comment by astorije** [comment]
In a similar fashion, I think the ignore/unignore should be retroactive (it doesn't tie this to CSS implementation, but that made me think about it since this is how we currently hide a few things).

So that if I ignore someone, their previous messages are hidden from me (use case: offensive stuff I really don't want to see), and if I unignore, I can see past messages again (use cases: check if user is still active, check something that was said before, etc.).

**Comment by Dracozny** [comment]
Inspircd has a /Silence command that handles the ignore of users at the server level. I'm not sure if that is available for other IRCDs but creating an alias to forward ignore commands to /server would potentially resolve the Push Notifications issue.

**Comment by xPaw** [comment]
There's /ignore in master now.

**Comment by c22** [comment]
Can this be reopened or should a new issue be opened? #2197 goes a long way on this but unless I am missing something we still don't have

> a flexible ignore system that allows specifying all or part of a hostmask and various options for what to ignore (highlights in channels, joins/parts/quits, all messages, PMs, etc.)

I would say we have rudimentary ignore support at the moment.

I'm specifically looking for a way to ignore CTCP messages from all users, it doesn't seem possible yet.

**Comment by McInkay** [comment]
Please open new tickets for individual improvements to the ignore system.

With generic tickets like this (where it says "etc") there is never a clear end goal, and so the initial one has to be just having an ignore system. Having issues that are open for years because there's not a clear end point is not good. So, please open other requests for what you want added to it. Thanks.
