### ISSUE TITLE
Implement BNC-style detaching

### ISSUE THREAD

**Issue by brettgilio** [thelounge/thelounge#4650]
While it is certainly possible to interface TheLounge with ZNC/Soju and other bouncers, it would be very nice if TheLounge supported this functionality on its own. Instead of calling it "detaching", we could possible implement something similar to [Telegram's "chat archive" ](https://telegram.org/blog/archive-and-new-design) but with the functionality of detaching. We could refer to it as an archive or a channel drawer, where channels will unarchive/undrawer/reattach themselves on a certain event (like a nick ping).

**Comment by brettgilio** [comment]
An addendum to this, the user JSON file would need to support an additional bool field per channel of "detached", or whatever vocabulary would be most appropriate.

**Comment by brunnre8** [comment]
Indeed, let's track it over there then.

duplicate
