### ISSUE TITLE
Longer ping timeout durations for TOR/I2P IRC servers

### ISSUE THREAD

**Issue by y2kboy23** [thelounge/thelounge#4657]
### Feature Description
IRC over hidden networks like tor and i2p naturally have higher latency due to the design of the networks. The Lounge will frequently disconnect due to ping timeouts on these networks. It would be nice to have a higher latency mode or a way to set a custom duration for these networks or when connecting to IRC servers over a VPN.

**Comment by brunnre8** [comment]
you have a latency higher than 2min?

Defaults are 
            ping_interval: 30,
            ping_timeout: 120,
Not sure we really want to add this as a setting honestly...
TL on purpose doesn't include tons of knobs people don't know what to do with.

And things like these would need to be set per network I guess... and that's the TL --> IRC side of things, IRC can happily boot you much before TL reached any timeout.

**Comment by brunnre8** [comment]
On the plus side for you, it's an easy patch that you could carry locally

**Comment by y2kboy23** [comment]
2 mins sounds sufficient.  My issue could be else where.  Completely agree with not too many knobs for end users.  Closing the  issue.

**Comment by RealYukiSan** [comment]
did you find what's the actual issue? I have similar problem, I can't connect to the I2P IRC server even though the Irc2P service is running (the indicator on the web page is green)

![image](https://github.com/user-attachments/assets/d6c1d269-835b-4a5f-ba51-4a3bedf6e219)

![image](https://github.com/user-attachments/assets/9e3dd374-5c9a-4695-8f53-3c3d8feb732b)

**Comment by RealYukiSan** [comment]
Ah, nevermind—my bad, I didn't realize that TL server is running on a separate machine.
