### ISSUE TITLE
Display IRC connection/channel information if JavaScripts/CSS are disabled

### ISSUE THREAD

**Issue by zzo38** [thelounge/thelounge#4658]
My suggestion is that even if JavaScripts and CSS are disabled, you should display the domain name, port number, and channel names of the IRC, so that you can use your own IRC client to connect to it in case someone links to the web client instead of the IRC, but wants to access the IRC instead.

**Comment by brunnre8** [comment]
This makes no sense.

TL isn't a bouncer that you can connect to, we are literally a pure js IRC client with always on features.

**Comment by zzo38** [comment]
Of course it is only useful if the default connection/channels are filled in and it is in public mode (although only some of the settings mentioned there are useful to be mentioned in this way). Otherwise, it is not useful.
