### ISSUE TITLE
Not staying connected after refresh

### ISSUE THREAD

**Issue by XXILTeun** [thelounge/thelounge#4675]
When i refresh the website i need to reconnect and i cant use the same username because thats already in use

**Comment by brunnre8** [comment]
What's your problem?

TL has no concept of user is already in use.

You mean the upstream IRC nick?
If so that's expected. GHOST the nick or whatever

**Comment by XXILTeun** [comment]
The lounge claimes that it is always connected even when offline but is there a way to stay logged in because when refresh my page i am not logged in anymore

**Comment by XXILTeun** [comment]
@brunnre8

**Comment by brunnre8** [comment]
The issue tracker is not meant as a support forum, please join us on libera in #thelounge
