### ISSUE TITLE
ts compilation litters .d.ts files into output dir

### ISSUE THREAD

**Issue by brunnre8** [thelounge/thelounge#4682]
Our TS compilation litters .d.ts + .tsbuildinfo files all over /dist/, which ought to only include the js output files.

It also compiles babel config files into it, which seems off too

@MaxLeiter any idea why it does that?

**Comment by brunnre8** [comment]
Looks like we can't disable this as we are using subprojects....

I'll solve it with the ignore file then, unless someone has a better idea

**Comment by MaxLeiter** [comment]
Fixed by #4707
