### ISSUE TITLE
Identd on Docker - how do I make it work?

### ISSUE THREAD

**Issue by Issam2204** [thelounge/thelounge#4720]
Hello, I'm using TheLounge with docker and I've mapped port 9001 on the container to 113 on the host:

```
    ports:
      - 9005:9000 #The Lounge web UI
      - 113:9001 #The Lounge idendt
```

I've also enabled the identd configuration and provided the correct port (9001) in the `config.js` file:

```
	identd: {
		enable: true,
		port: 9001,
	},
```

However, I see the following message on all IRC servers I try to connect to:

`*** Looking up your hostname...
*** Couldn't resolve your hostname; using your IP address instead`

In the documentation, it mentions modifying the `/etc/oidentd.conf` file, but not sure how should I approach this since I'm using docker.

Maybe important to mention that I'm using TheLounge behind VPN. Any help is appreciated!

**Comment by brunnre8** [comment]
This is an issue tracker, not a support forum.
Head over to our IRC chan #thelounge on libera.

**Comment by dgw** [comment]
"Couldn't resolve your hostname" relates to forward/reverse DNS, not ident.

**Comment by brunnre8** [comment]
@dgw that applies to you to

**Comment by dgw** [comment]
@brunnre8 blame github not updating the page while I was off googling before posting a reply

Consider this my one-time request for enabling discussions on this project, so people have somewhere other than issues to post questions & answers that aren't lost to the sands of chat logs.
