### ISSUE TITLE
Feature request: Ability to export/download scrollback/search results

### ISSUE THREAD

**Issue by myself248** [thelounge/thelounge#4729]
### Feature Description

I'm coming from a client which kept logs in plain text files, and it was occasionally super useful to just be able to grep them for things. TheLounge doesn't seem to have any equivalent functionality; the /search function only goes back a day despite having more if I hold PgUp (which is ultra slow btw), so I'd like a way to take matters back into my own hands.

I propose a /savescrollback command, which just takes everything sqlite has for the given channel (perhaps within a time range parameter), packs it up into a text file, and starts a web browser download action. I end up with a file on my local (client) disk that I can mangle as I see fit. 

This seems more sane than trying to do things on the server's filesystem which users may not have access to (I do, since I run my own instance, but it's buried inside docker and I'd just rather not). 

Optionally, it could be nice to pre-filter the lines that get included in the export, but that seems like it adds complexity for not a ton of benefit. 

Thank you for considering the idea!

**Comment by brunnre8** [comment]
I'd rather just make the UI better for our search.
The download functionality might be occasionally useful but what you really want is a functioning search, isn't it?

So let's do that instead

**Comment by myself248** [comment]
At this exact moment, I want to take a list of all URLs that've been mentioned in a given channel over the last few weeks, and send them to a friend, so even if search works, I'll be copying and pasting the results into a file. 

Exporting to my own tooling is more versatile than an internal search could ever be, and I think it's a very simple request that enables a bunch of user-side functions without having to implement all the complexity in the search function itself. 

But yes, better search would be nice too. And faster loading of more lines of scrollback to support eyeball-grepping, which is sometimes unfortunately needed when my brain can't remember the exact search term but "I'll know it when I see it".

**Comment by brunnre8** [comment]
scrollback loading is about as fast as your server can load things from disc and send it over the network... the only way to speed that up would be to only do the query once for all messages, and that's not something you'd do by repeatedly hitting the infinite scroll functionality.

**Comment by dgw** [comment]
Related: By default, The Lounge keeps both sqlite _and_ text logs, according to https://thelounge.chat/docs/configuration#messagestorage

These aren't directly downloadable from within the web client, but the plain text files _are_ available to be exported and analyzed by external tools, subject to setting up the correct filesystem access permissions.

**Comment by myself248** [comment]
> The Lounge keeps both sqlite and text logs,

oh heyyyyyyy. And it turns out that directory is mounted into docker in such a way that it's also accessible to the host. Well that was easy. (for me, because I host my own instance and I can just ssh into the host.) 

Would still be nice to improve search and/or provide a client-accessible download function, but my instant problem is well and truly solved. Thank you! 

I don't know whether to leave this issue open as an enhancement request, or close it as solved, but at least it's a breadcrumb for someone else possibly seeking similar functionality. Do as thou wilt.

**Comment by brunnre8** [comment]
Search will get improved in any case, pretty sure download function isn't exactly what UI we expect for TL.

Closing anyway as there's https://github.com/thelounge/thelounge/issues/1423
