### ISSUE TITLE
Connection closed unexpectedly: Error: certificate has expired

### ISSUE THREAD

**Issue by wolfdael** [thelounge/thelounge#4732]
- _Node version: unable to find
- _Browser version: latest up to date chrome
- _Device, operating system: latest windows 10
- _The Lounge version: 4.3.1 docker

I am getting the error in title no matter what I do. I even set "bind" in config and its still the same.

---

**Comment by brunnre8** [comment]
I mean, fix your cert if it's yours?
If not, tell it to whoever own the cert.

This is an issue tracker though, please hop into our IRC chan on libera for support.
