### ISSUE TITLE
Emoji Rendering Issues

### ISSUE THREAD

**Issue by xnaas** [thelounge/thelounge#4761]
- _Node version:_ N/A
- _Browser version:_ All
- _Device, operating system:_ All
- _The Lounge version:_ 4.4.1

---

The Lounge doesn't seem to properly render some emoji combinations, such as 🤝🏻.

<details><summary>screenshots across many platforms</summary>

![macOS](https://github.com/thelounge/thelounge/assets/8271327/f3453722-a723-4e5d-bffc-eb65f0b40864)

![WIndows 10](https://github.com/thelounge/thelounge/assets/8271327/01d102b4-fa7d-4747-a873-3f4a3b3ef58a)

![Gnome/Linux](https://github.com/thelounge/thelounge/assets/8271327/215cd5f7-4344-4022-ae4c-24068c710a5a)

![Windows 11](https://github.com/thelounge/thelounge/assets/8271327/2c083106-cccb-4550-84fc-296524f14a77)
</details>

The emoji render fine in the input box, so it's something The Lounge is doing, not a browser/OS issue:
<details><summary>screenshot of input field being normal</summary>

![input is fine](https://github.com/thelounge/thelounge/assets/8271327/4086679e-310d-43e9-a7d7-d122bfe17db5)
</details>

---

HTML on incorrect emoji sequence:

```html
<span class="emoji" role="img" aria-label="Emoji: handshake" title="Emoji: handshake">🤝</span>
<span class="emoji" role="img">🏻</span>
<span class="emoji" role="img" aria-label="Emoji: handshake" title="Emoji: handshake">🤝</span>
<span class="emoji" role="img">🏼</span>
<span class="emoji" role="img" aria-label="Emoji: handshake" title="Emoji: handshake">🤝</span>
<span class="emoji" role="img">🏽</span>
<span class="emoji" role="img" aria-label="Emoji: handshake" title="Emoji: handshake">🤝</span>
<span class="emoji" role="img">🏾</span>
<span class="emoji" role="img" aria-label="Emoji: handshake" title="Emoji: handshake">🤝</span>
<span class="emoji" role="img">🏿</span>
```

HTML on correct emoji sequence:

```html
<span class="emoji" role="img" aria-label="Emoji: person in suit levitating" title="Emoji: person in suit levitating">🕴🏻</span>
<span class="emoji" role="img" aria-label="Emoji: person in suit levitating" title="Emoji: person in suit levitating">🕴🏼</span>
<span class="emoji" role="img" aria-label="Emoji: person in suit levitating" title="Emoji: person in suit levitating">🕴🏽</span>
<span class="emoji" role="img" aria-label="Emoji: person in suit levitating" title="Emoji: person in suit levitating">🕴🏾</span>
<span class="emoji" role="img" aria-label="Emoji: person in suit levitating" title="Emoji: person in suit levitating">🕴🏿</span>
```

**Comment by brunnre8** [comment]
The fix only partially works, there's still some which display oddly

**Comment by brunnre8** [comment]
Although those also don't render for me here...
are you sure those combinations are valid?

🤝🏻🤝🏼🤝🏽🤝🏾🤝🏿
✍️🏻✍️🏼✍️🏽✍️🏾✍️🏿

**Comment by SnoopJ** [comment]
Unicode formalizes this in the [emoji standard](http://www.unicode.org/reports/tr51/#Diversity), the codepoints `1F3FB..1F3FF` are the `EMOJI MODIFIER FITZPATRICK TYPE 1-N` where N is one of `1, 2, 3, 4, 5, 6` corresponding to the same entry on the [Fitzpatrick scale](https://en.wikipedia.org/wiki/Fitzpatrick_scale) of human skin color.

The emoji that can be modified by these codepoints have the property `Emoji_Modifier_Base=Yes`, all of which are listed in [`emoji-data.txt`](https://unicode.org/Public/UCD/latest/ucd/emoji/emoji-data.txt) in the Unicode Character Database (UCD). There's a [complete list](https://unicode.org/emoji/charts/full-emoji-modifiers.html) on the Unicode website, but it loads very slowly for me, I did my spot-checks by looking at the text file. As far as I can tell, all of the codepoints discussed above have this property set.

Worth pointing out that it's **not** 'wrong' to render these modifier sequences the way The Lounge is representing them (it's explicitly called out in the standard as still notifying the reader of intent), but I believe it's considered a fallback behavior and the single-glyph form is the preferred representation.

**Comment by brunnre8** [comment]
cool, thanks for the explanation.

I'm in favor of closing this then, can't really fix it here anyway (would have to be done in emoji-regex)
