### ISSUE TITLE
The Lounge is very good!

### ISSUE THREAD

**Issue by larsenv** [thelounge/thelounge#4769]
WAY more easy to get up and running than ZNC, I don't have to dig for pings I missed, I get notifications on iOS even though it says on the website you can't. Within minutes I ditched Textual on my Mac and Igloo on iOS when I tried this out. Good job!

Is it possible to import logs from ZNC?

Thank you for making such a good IRC client.

**Comment by brunnre8** [comment]
It is not no, or at least not without mucking around in the DB manually.

Please do not use our issue tracker for support questions though, just hop in to our IRC chan on libera for those things
