### ISSUE TITLE
Error: Failed to write user log: Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by alfablac** [thelounge/thelounge#4775]
- _Node version:_ 20.5.1
- _Browser version:_ Chrome 105
- _Device, operating system:_ Linux
- _The Lounge version:_ Latest 

I'm getting this error while loading thelounge 

```
node_modules/thelounge/dist/server/plugins/messageStorage/text.js:94:19)
^C2023-08-25 11:33:03 [ERROR] Error: Failed to write user log: Error: EMFILE: too many open files
```

I'm only able to open it if I reduce the maxHistory variable

---

**Comment by brunnre8** [comment]
> if I reduce the maxHistory variable

this makes no sense, that doesn't open less file descriptors. What you are seeing is a race condition as you seem to be right at the edge

increase the number of fds allowed for your system, this isn't a TL issue. During normal operation with a few users we don't use an excessive amount
