### ISSUE TITLE
Hacked by the network

### ISSUE THREAD

**Issue by KyleSanderson** [thelounge/thelounge#4794]
-reflection.oftc.net- *** Looking up your hostname...
13:38:01 -reflection.oftc.net- *** Checking Ident
13:38:01 -reflection.oftc.net- *** No Ident response
13:38:02 -reflection.oftc.net- *** Couldn't look up your hostname
13:38:02 *** nick: Nickname is already in use. An attempt to use it will be made when this nick quits.
13:38:02 -reflection.oftc.net- *** Connected securely via TLSv1.3 TLS_AES_256_GCM_SHA384-256
13:38:02 Enabled capabilities: multi-prefix
13:38:02 You're now known as nick3

thelounge then seems to get married to nick3, and hard retains that forever.

**Comment by brunnre8** [comment]
Use our IRC chan for support
