### ISSUE TITLE
Configuration option to specify path where data is persisted

### ISSUE THREAD

**Issue by Sleepful** [thelounge/thelounge#4819]
### Feature Description

- Configuration option to specify path where data is persisted

would make it easier to anyone running in environments where the installation directories are ephemeral, like Docker or NixOs

**Comment by brunnre8** [comment]
https://github.com/thelounge/thelounge/issues/4366

Please check existing issue first, before opening up a new one

**Comment by Sleepful** [comment]
@brunnre8 too many open issues ;)

**Comment by Sleepful** [comment]
ty

**Comment by Sleepful** [comment]
Answering my own question, I can see that it uses a home directory defined in `server/command-line/utils.ts` https://github.com/thelounge/thelounge/blob/d15998d919414e41678e582ee65a316e71e6b2bb/server/command-line/utils.ts#L28

The home directory can be many things, from an ENV var to just a dir relative to installation `.thelounge`.

So there _is_ an option to specify the where the data is persisted, it's just not in the current configuration options.
