### ISSUE TITLE
OIDC Support

### ISSUE THREAD

**Issue by chsasank** [thelounge/thelounge#4847]
### Feature Description

There were many requests for OIDC and draft PRs with the most recent one here: https://github.com/thelounge/thelounge/pull/4676

The problem with this implementation IMO is that author didn't use gold standard of js auth: [passport js](https://www.passportjs.org/). I will be happy to give it yet another try with passport js if I am handheld a bit on the code base.

**Comment by brunnre8** [comment]
Don't think this needs to be a separate issue. There already is one open after all.

Either ask questions in IRC or open up a draft PR with your WIP
