### ISSUE TITLE
ZNC + crypt: my own messages show up encrypted

### ISSUE THREAD

**Issue by alexandergre** [thelounge/thelounge#4860]
Encountered the following issue when using ZNC with crypt plugin: whenever I send a message, is shows up encrypted in thelounge.

<img width="440" alt="image" src="https://github.com/thelounge/thelounge/assets/31637335/35de00c1-c068-4c6c-a3e3-9d3569083392">

**Comment by brunnre8** [comment]
Not a bug, that's caused by the echo-message cap.
Search the closed issues for the details.
