### ISSUE TITLE
Request to add a feature that performs unlimited reconnect when the connection is lost

### ISSUE THREAD

**Issue by KyokoMiki** [thelounge/thelounge#4874]
### Feature Description

From my user experience, situations like ECONNRESET, SQLITE_BUSY, etc. can all lead to disconnection that needs manual reconnect, and it is usually difficult to discover immediately. I think it is very necessary to add a 'keep-alive' mode. This mode should perform unlimited reconnection attempts after the connection is lost, just like what autobrr does.

**Comment by brunnre8** [comment]
the errors which are fatal and stop reconnection are partially handled in the irc-framework.

Guess this is already opened as https://github.com/thelounge/thelounge/issues/4842

SQLITE_BUSY is not something that can happen as we synchronize our accesses and TL owns the db while it runs.
But that has nothing to do with reconnecting, it'll simply drop the message on the floor
