### ISSUE TITLE
"Password" field in Network Settings is detected and populated by password manager

### ISSUE THREAD

**Issue by sevenrats** [thelounge/thelounge#4898]
which is super annoying honestly. every single time I edit a network I have to make sure I backspace the user password that gets autofilled into the network password field.

**Comment by brunnre8** [comment]
tell your pw manager not to do that without interaction then 🤷‍♂️ 

Not sure what you expect us to do here

**Comment by sevenrats** [comment]
its a "new password" style field so you would want to use some option like autocomplete="new-password" on the item itself. that way the browser will perform as the user expects instead of trying to apply their thelounge password as Network Password. Please reopen.

**Comment by sevenrats** [comment]
at a glance we could be setting autocomplete="off" or changing the name of the password field so that it isn't just "password".
for example
id="network-psk" name="networkpsk" autocomplete="off"
would probably fix it.
