### ISSUE TITLE
Notifications on mentions

### ISSUE THREAD

**Issue by SawkeeReemo** [thelounge/thelounge#4899]
### Feature Description
Very simply, I would love the option to notify on mentions only. I mute most channels because the notifications spam my phone. But I’d love a feature where you can get notified on mentions regardless of a channel or server being muted. Also, I would love this to be a per server or per channel option (whichever is possible)

**Comment by Jay2k1** [comment]
Uhm, did you accidentally enable this setting?
![image](https://github.com/user-attachments/assets/25914fd8-6434-4de0-984e-e43a5a348838)

Because by default you shouldn't get notifications for any message.

**Comment by brunnre8** [comment]
Not sure I follow... muting is there to *prevent* notifications.
It doesn't do anything else.
You *only* get notified when you are mentioned by default.

If you want notifications on mention, then simply don't mute.

**Comment by SawkeeReemo** [comment]
> Not sure I follow... muting is there to _prevent_ notifications. It doesn't do anything else. You _only_ get notified when you are mentioned by default.
> 
> If you want notifications on mention, then simply don't mute.

Really? I wonder if it’s because I had that “enable notifications on all messages” turned on. I don’t remember doing that. I also didn’t know notifications on mentions were the default. Gonna give that a try now. 
thanks!
