### ISSUE TITLE
Show the real username in the WHOIS output

### ISSUE THREAD

**Issue by SadieCat** [thelounge/thelounge#4900]
### Feature Description

Some servers (e.g. InspIRCd v4) support the concept of a real username, i.e. the username that was originally sent as distinct from their virtual username set by services. This is most commonly used to prevent ban evasion using services from users on shared hosts (e.g. IRCCloud).

This value is sent in `RPL_WHOISACTUALLY` and is already parsed by irc-framework into the `actual_username` field. Unfortunately unlike `actual_hostname` The Lounge does not currently show this in the WHOIS output. Would it be possible for you to add this?

**Comment by brunnre8** [comment]
Yes?

I don't think I'm connected to a server that sends those though, mind giving https://github.com/thelounge/thelounge/pull/4901 a try?
