### ISSUE TITLE
Option to have NOTICE messages display in current window

### ISSUE THREAD

**Issue by JReming85** [thelounge/thelounge#4902]
### Feature Description

One of my favorite features from AdIRC, is that it will show NOTICE messages send to me in the current channel window I am viewing so I dont have to keep switching to the Private Message window.

Any chance we can get a similar option for thelounge or maybe a plugin?

**Comment by dgw** [comment]
As far as I know, this is already TL's behavior _unless_ you have a PM buffer open for the nick sending you notices (in which case the notices go to the PM window).

**Comment by JReming85** [comment]
> As far as I know, this is already TL's behavior _unless_ you have a PM buffer open for the nick sending you notices (in which case the notices go to the PM window).

Omg, I thought I was going crazy.  Could have sworn it was doing it when I first started it and didnt realize what changed when it stopped.

That did the trick, thank you!
