### ISSUE TITLE
The Lounge  502:Bad Gateway Error on Raspberry Pi 5 with TP-Link Wi-Fi Extender

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [thelounge/thelounge#4909]
Subject: The Lounge  502:Bad Gateway Error on Raspberry Pi 5 with TP-Link Wi-Fi Extender

Dear Lounge Team,

Problem: I'm experiencing a "Bad Gateway" 502: Bad Gateway error when starting Lounge on my Raspberry Pi 5. This issue arises specifically when the Raspberry Pi is connected to the internet through a TP-Link Wi-Fi extender using a LAN (Ethernet) connection.
Expected behavior: Lounge should start successfully and function normally regardless of the network configuration.
Steps to Reproduce:
1. Install The Lounge on a Raspberry Pi 5.
2. Connect the Raspberry Pi to a TP-Link Wi-Fi extender using a LAN (Ethernet) cable.
3. Attempt to start The Lounge.
Additional Information:
* Other add-ons and services on the Raspberry Pi are functioning correctly.
* The issue is specific to The Lounge when using the TP-Link Wi-Fi extender.
* TP-Link model is : AX5400 WiFi 6 Range Extender with Ethernet Port 
* Link to buy This device in amazon is : https://a.co/d/03I1lC4
* I used to experience Same Bad Gateway error when using InfluxDB Add-ons too but now after my feedback even InfluxDB works great also all other adding works great.

Possible Solution:
* Enhancement: Consider implementing a feature or configuration option in Lounge to handle network configurations involving Wi-Fi extenders or other specific network topologies.
* Debugging: Provide more detailed error messages or logs to assist in troubleshooting network-related issues.

Thank you for your time and consideration. Please let me know if any other questions or concerns.

Kindest and Warmest Regards,
Sincerely, 
All the Best,
Pooya Mohammadhossein 
My Nickname : Ryan
Senior Computer Engineer and Senior Home Smart Expert

**Comment by brunnre8** [comment]
This is an issue tracker and not a support forum, head to our #thelounge channel on libera.

The error seems pretty clear and isn't from TL
