### ISSUE TITLE
List available install methods in README

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/thelounge#491]
We should have links to docker-lounge, arch-lounge, etc (and maybe list the necessary commands if they're not too lengthy)

**Comment by astorije** [comment]
I'm working on comprehensive install docs for the main website, which details how to install all these. The README of this repo should then contain a link to it to avoid duplicating the info. I'll change the README once I'm done with the website.
Ok to close this issue?

**Comment by xPaw** [comment]
Solved by new docs: https://thelounge.chat/docs/install-and-upgrade
