### ISSUE TITLE
fileUpload maxFileSize ignored.

### ISSUE THREAD

**Issue by scgehin** [thelounge/thelounge#4923]
- _Node version:_ v22.9.0
- _Browser version:_ Firefox 130.0.1 (Linux), Brave 1.70.119 (Android)
- _The Lounge version:_ v4.4.3

---
No matter what maxFileSize is set to (including -1), the upload limit appears to be 1MiB. File type does not matter. Smaller uploads work perfectly fine.

The error is:
> UPLOAD ABORTED: REQUEST ENTITY TOO LARGE (HTTP 413)

An example of the relevant part of the config:
```
fileUpload: {
    enable: true,
    maxFileSize: 524288,
    baseUrl: null,
},
```

**Comment by dgw** [comment]
Are you running TL behind a reverse proxy?

Nginx for example has a 1MB default maximum. https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by scgehin** [comment]
Ah, this was exactly the problem. Thank you.
