### ISSUE TITLE
CSS help: How to set different color for connected and disconnected network names?

### ISSUE THREAD

**Issue by dotcomUNDERGROUND** [thelounge/thelounge#4925]
Is it possible to set different color for connected and disconnected network names? Using custom CSS?

**Comment by dgw** [comment]
You can see some of the relevant CSS rules in the default client styles, e.g. https://github.com/thelounge/thelounge/blob/3d33ef8083ddd018c3159944c5d506666c662b05/client/css/style.css#L817-L820

Please take any follow-up on this topic to #thelounge at Libera.chat; this project prefers to keep its issue tracker strictly for actual issues and not support discussions.
