### ISSUE TITLE
Unified chat

### ISSUE THREAD

**Issue by RealYukiSan** [thelounge/thelounge#4931]
### Feature Description
Sometimes I feel bored and have nothing to do, and in that situation, I'm confused about which channel to choose to engage in some conversation. It would be nice if thelounge have some feature that unifies all channels and all networks together into one chat :3

**Comment by brunnre8** [comment]
Don't think this is in scope sorry

**Comment by RealYukiSan** [comment]
alright I'll use sqlite:
```
 select channel,DATETIME(ROUND(time / 1000)+25200, 'unixepoch') AS isodate,msg from messages where type is 'message' order by time desc limit 50;
```

or just `tail -F` command then

**Comment by brunnre8** [comment]
using sqlite this way in a loop will eventually drop messages on the floor

**Comment by RealYukiSan** [comment]
by "drop messages on the floor", did you mean there's potential data corrupt on the sql file even when I only do select operation and not attempt to modify/mutate the db?

**Comment by brunnre8** [comment]
In the normal write mode (assuming you didn't enable wal) sqlite can return EBUSY when you have some other query active. TL doesn't retry and will simply discard the message it tried to insert.

We serialize our accesses and assume we own the DB, which is sane given that it's internal application state

**Comment by RealYukiSan** [comment]
it sounds like if the network activity is intensive (many users chat at the same time) it's possible that some of the message will be discarded if EBUSY occurs without other process using the sql file?

**Comment by brunnre8** [comment]
TL serializes the accesses, heavy traffic is not a problem. Manually messing with the DB outside of TL is

**Comment by RealYukiSan** [comment]
You mention about wal, is it something that will solve the problem? just wondering
