### ISSUE TITLE
Can't load thelounge assets on the Android's Chrome web browser

### ISSUE THREAD

**Issue by RealYukiSan** [thelounge/thelounge#4933]
- _Node version:_  22.7.0
- _Browser version:_ Chrome 129.0.6668.81
- _Device, operating system:_ Android 14
- _The Lounge version:_ 4.4.3

![image](https://github.com/user-attachments/assets/38042eb0-8c35-4d42-913e-79c6e5224ae4)

I have thelounge hosted on my local network, and I can access it from the local IP, but it's throwing an error if I tried to access it through tailscale IP, Tested the same IP on the Android's Brave browser and it works without error, so I'll use this as a workaround when I'm not in my home, or another alternative would be access it from the ssh tunnel: `ssh -N -C -L 8080:127.0.0.1:9000 user@<redacted>` and it could work as well.

I'm not sure how to provide additional information to further debug the issue as it's occurs on android and I don't know how to open console tabs on the devtools

---

**Comment by brunnre8** [comment]
I use chrome on Android without a hitch, so not a TL bug.

You can connect devtools the usual way, follow the docs of chrome.
