### ISSUE TITLE
Wait some time before reconnecting

### ISSUE THREAD

**Issue by ikki4** [thelounge/thelounge#4944]
### Feature Description

Sometimes, on faulty networks, when we lose connection to the server, TheLounge immediately tried reconnecting. But it can't use the main nickname because the server hasn't acknowledged the disconnection yet, so TheLounge uses "nickname1", "nickname2", etc instead of the main nickname, but some servers have strict nickname rules, so **in certain servers those immediate reconnect attempts end up being pointless.** But I think that if we could configure TheLounge to wait x seconds/minutes before attempting to reconnect, this could mitigate this issue. I see that it tries to reconnect after 6 seconds, but it seems that 6 minutes is too short to avoid this issue.

![image](https://github.com/user-attachments/assets/f082e2d8-3173-4f3c-8ccb-68631820edcf)
![image](https://github.com/user-attachments/assets/cce61998-c1e5-438f-9138-ee4272ff094a)
![image](https://github.com/user-attachments/assets/252205d3-6ad9-4c48-9b53-f78a488941b1)

**Comment by brunnre8** [comment]
out of scope as very niche and for nick tracking there's other open issues
