### ISSUE TITLE
Store visibility status of sidebar menus in settings object

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#51]
For example:
1. Hide user list.
2. Restart the client.
3. User list is now visible, but if the visibility state was saved, it would stay hidden.

**Comment by astorije** [comment]
This is actually not too difficult to implement, so marking as up-for-grabs.

**Comment by McInkay** [comment]
This should probably not be in options (as it's not an option) but should be done similar to how #2195 is done, in another object.

**Comment by astorije** [comment]
I'm with @McInkay. Also if in options, we'd have to make sure that settings sync doesn't pick that up.
