### ISSUE TITLE
Sorting of channels / conversations in left sidebar

### ISSUE THREAD

**Issue by jancborchardt** [thelounge/thelounge#53]
Currently, newly added channels are just added to the bottom. This is quite strange, especially with private conversations inbetween.

Instead, in the first pass: All channels should be sorted first, and then private conversations. Sorted alphabetically.

In a second pass, we could sort the channels by the amount you use / message in them or something similar. That would make sorting more relevant.
For sure we can sort the private conversations to have the ones with the most recent message first. That’s how any mobile messenger like WhatsApp, Signal etc does it.

**Comment by xPaw** [comment]
Don't forget users can re-order the server list by dragging the channels.

**Comment by YaManicKill** [comment]
Yeah, I was just thinking that, too. I'm not sure that ordering it based on usage would be a good thing to do. Happy to start a new channel by putting it above the PMs though, that sounds like a sensible change.

**Comment by dgw** [comment]
I've found it very useful the way Textual does it: Channels are listed on top of PMs, and when a new one of either is added it goes to the bottom of that section. From there it can be dragged anywhere within that section (channels cannot be put in the middle of the PMs and vice versa).

**Comment by jancborchardt** [comment]
> Happy to start a new channel by putting it above the PMs though, that sounds like a sensible change.

@YaManicKill yup, definitely. The current mix is confusing. ;)


@xPaw @dgw For channels I am not sure what the best sorting method is. Alphabetical is fine for few channels, but then it quickly gets annoying. And manually dragging is just putting the work off to every single user. We can do better here.

For private messages, sorting by most recent up top is definitely a good way, as described above like others do it.

**Comment by nornagon** [comment]
For reference: Slack (which is admittedly solving a slightly different problem, but is useful as a point of reference anyway) addresses this issue by having 3 sections:

1. "Starred" channels go way up at the top, sorted alphabetically.
2. All the rest of your channels go next, sorted alphabetically.
3. All your PMs go last, also sorted alphabetically.

There's an option to hide channels (& PMs) that don't have any activity in them, which is useful if you're in a large number of channels.

There's also a fantastic quick-switcher that lets you jump to a channel or PM by hitting a shortcut (Cmd+T) and typing part of the name.

<img width="219" alt="slack" src="https://cloud.githubusercontent.com/assets/172800/18502008/42692b40-7a09-11e6-8f7b-dd406d329274.png">

<img width="515" alt="slack" src="https://cloud.githubusercontent.com/assets/172800/18502024/57ad2f92-7a09-11e6-8acd-431166d1b900.png">

**Comment by nicoulaj** [comment]
The fancy UI propositions are nice, but as a first step, even only having a "Sort channels" button at the bottom of the channels would do it for me. When you have hundreds of channels, sorting by hand is a hassle, so I often find myself just using "CTRL+F"...

**Comment by rgarrigue** [comment]
:+1: for a sort button !

**Comment by wiiaam** [comment]
Anybody working on this? Might give it a go some time next week.

Was thinking of adding an option in settings to sort alphabetically, and also leave it open for other sorting designs to be added, such as the most used channels design mentioned. Starred channels also sounds like a cool idea, so I might see if I can implement this if I have extra time.

Long time user, first time contributor, so some input on this would be greatly appreciated.

**Comment by YaManicKill** [comment]
> Was thinking of adding an option in settings to sort alphabetically, and also leave it open for other sorting designs to be added

In general, I like this, but we need to have a think where this will happen. I imagine it'll be a server-side option, because that's where the sorting happens (I think). But that makes it awkward to edit.

Also, a "manual" option would be good that would just pop it on at the bottom and you can manually reorder them and it'll never re-order.

We really need to get settings syncing :-\ that would make this a lot nicer.

**Comment by wiiaam** [comment]
Oh are settings stored locally? Never actually realized this, since I've never changed anything. I just assumed they were being pulled from the config file

**Comment by YaManicKill** [comment]
We have server-side user settings, server-side global settings, and client-side settings. Client-side settings are entirely local, and don't sync at all.

The ideal situation is where the server-side user settings and client-side settings are 1 (with options to override on local machines) so for things that happen on the server, the user can edit locally, and the clients can sync their settings.

There was a PR for this ( #275 ) but it never got merged. It got lost in time.

**Comment by astorije** [comment]
Alright, I'm going to give a try at that.
