### ISSUE TITLE
Demo both public and private mode

### ISSUE THREAD

**Issue by maxpoulin64** [thelounge/thelounge#531]
It came to my attention that a lot of people on the demo get confused as to what exactly is The Lounge. It would be great to have a private demo instance in addition to the public one, with a bunch of test logins people could use to see the persistance and play around with it.

I am willing to host it as necessary, as well as a short intermediate page explaining both modes and the different login credentials.

**Comment by xPaw** [comment]
We discussed providing a hosted The Lounge version on IRC before and this issue basically falls under that.

Demoing private mode would effectively mean we have to maintain a fully fledged The Lounge hosted instance which comes with extra maintenance burden (have to implement killing inactive users, etc).

**Comment by astorije** [comment]
@xPaw, what about something simpler that completely resets from scratch every 10 minutes or something?
I like the idea of demoing private mode a lot, even if it's an heavily limited version of it, I think it still showcases a lot. Better than nothing 🤷‍♂️
