### ISSUE TITLE
User list refreshes when scrolling, rendering it useless on high activity channels.

### ISSUE THREAD

**Issue by irrgit** [thelounge/thelounge#544]
Currently on thelounge 2.0.0-pre.4
The user list refreshes when users join so if you’re in the middle of scrolling to select a nickname to talk to it jumps and you always end up selecting the wrong nickname.

**Comment by astorije** [comment]
Yes, this is highly annoying and definitely acts as a bug.
PR welcome :-)

**Comment by dgw** [comment]
Might get fixed as a side effect of reducing the frequency with which the server sends the whole user list to the client, which I've volunteered to work on. We shall see!

**Comment by xPaw** [comment]
This was fixed when keyboard navigation was added.
