### ISSUE TITLE
When disconnected, network menu still shows "disconnect" option

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/thelounge#631]
When a network is disconnected, lounge tells you to use `/connect` to reconnect, so the menu should provide a connect option too instead of disconnect.

![2016-09-24 13 54 37](https://cloud.githubusercontent.com/assets/2070503/18809665/4454a098-8282-11e6-86d9-451aef0dfbb5.png)

**Comment by xPaw** [comment]
We don't really communicate server status to client UI yet.
