### ISSUE TITLE
Remove bootstrap

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#638]
As far as I can see, we only use it directly for the grid in settings/connect windows.

**Comment by williamboman** [comment]
Here's a list of things I found that breaks when removing the Bootstrap stylesheet:

- `* { box-sizing: border-box; }`
- `p` margins
- `a` text-decoration
- `body` line-height
- `.sr-only` labels
- `.row`, `.col-*` classes
- `.pull-left`, `.pull-right`
- `small` stylings inside `h1, h2, h3, ...`

**Comment by astorije** [comment]
Yeah I'm more and more leaning towards keeping Bootstrap but:

- Upgrading to v4
- Using their theming mechanism or whatnot to style our stuff better and consistently
- Not using the (modified?) copy in-repo

Bootstrap does something else that is often overlooked, it's the small tweaks to increase cross-browser support as much as they can.
It's also nice to be able to refer to a component documentation when doing something.
Just my 2c obviously, and explaining why my opinion on this is slowly changing.

**Comment by xPaw** [comment]
@astorije for that purpose we can bring in reboot.css (bootstrap's normalizer).

**Comment by astorije** [comment]
That addresses one small part of my comment though. I really don't want to reinvent the wheel, we have enough work as it is so if Bootstrap provides us with a good base to extend, we shouldn't run away from it 🤷‍♂️

**Comment by bardiharborow** [comment]
I'm team at Bootstrap, and a heavy Lounge user, so feel free to shout if you have any questions or need any assistance.

**Comment by xPaw** [comment]
@bardiharborow Hey. We don't really have any questions it just needs to be done at some point.

We only use normalize.css, some global styles (like links, headers) which should be merged into our own styles, and some of the grid (even then, very small subset of it).
