### ISSUE TITLE
Multiple mode changes appear on separate lines

### ISSUE THREAD

**Issue by dgw** [thelounge/thelounge#675]
If someone (e.g. ChanServ) sets mode `+ao nick nick`, for example, The Lounge displays those on separate lines:

```
ChanServ sets mode +a nick
ChanServ sets mode +o nick
```

Up to four users' modes may be changed in one line, so this could be spammy. At the very least, The Lounge should collapse multiple mode changes affecting the same user into one line.

**Comment by xPaw** [comment]
Also #84

**Comment by xPaw** [comment]
Do you still consider this to be a problem with message condensing?

**Comment by dgw** [comment]
Yes. These should be condensed to one line even if condensing is turned off, or when the condensed changes are expanded.
