### ISSUE TITLE
Have separate input box for channels and PM's

### ISSUE THREAD

**Issue by PolarizedIons** [thelounge/thelounge#706]
For example, if I type `Yea sure thing` in #channela, but before I finish, I get a pm and decide to reply to that first, when I switch to another channel (or in this case pm), the input field is reset. When I go back to #channela what I typed is put back into the input box.

**Comment by astorije** [comment]
I heavily support this idea!
I believe that this can be done fairly cleanly, do you want to give it a try?

**Comment by stepie22** [comment]
The issue is that I have exams coming up. I guess I could "study" for IT by working on this :P Will see though. Anyone can pick this up if they want to

**Comment by dgw** [comment]
I would go so far as to change this issue's title to "[Feature Request] Separate input field/history per-buffer". @astorije would you support each buffer's input field and history being completely independent? I'm used to that from e.g. Textual and (if memory serves; I haven't used in some months) KVIrc.

**Comment by astorije** [comment]
> The issue is that I have exams coming up. I guess I could "study" for IT by working on this :P

Hey exams come first! :D
Thanks for the offer though, but don't worry about it.

> @astorije would you support each buffer's input field and history being completely independent?

FWIW I was seeing this as a mandatory consequence of that change. It would be very confusing to have different inputs and (potentially) drafts in there but a global history.

In the end, it all comes down to how erming's library handles having multiple inputs on the page: does he maintain a global history or is it smarter than that...
This might need updating the lib (our version is a modified 1.3.1 while upstream is at 1.5.3...) and opening a PR there if necessary.

**Comment by dgw** [comment]
Without spelunking into the code, I'll just ask: Are you thinking of actually having a separate `input`/`textarea` per buffer in the DOM? Or emulating that by having one input box whose contents are managed by JS when the view changes?

The solution I had in mind was two dicts/associative arrays, one of `hiddenInputs` (only contains entries for buffers that are hidden but had unsent text entered) and one for `inputHistories`.

I could be talking over a solved problem because of not going through the code, but "one history per input" does make me wonder about having multiple inputs _in the DOM_…

**Comment by astorije** [comment]
I am indeed thinking of having multiple inputs. Right now, input is shared across all channels, I would much rather have one input per channel.

Having a single one and fuzzling with the text inside is very much-error prone, can lead to weird behavior, and may require awkward code to solve these.
For example, let's assume that when switching channels, text is being stored in a cache, replaced with value stored for that other channels (effectively one input for everything). This will have random issues when hitting Undo as this will be managed by the browser.

**Comment by dgw** [comment]
> For example, let's assume that when switching channels, text is being stored in a cache, replaced with value stored for that other channels (effectively one input for everything). This will have random issues when hitting Undo as this will be managed by the browser.

Ah, OK. I'm not really familiar with this sort of issue, but it sounds like you've worked with similar situations before and found that separate input elements, with whatever overhead that comes with DOM-wise, is better than futzing with JS content swapping. Fair enough; I'll go back to watching on the sidelines now. 😺
