### ISSUE TITLE
Add colons to unhandled messages first param

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/thelounge#797]
![image](https://i.imgur.com/Lxk8Png.png)

**Comment by xPaw** [comment]
`client.command_handler.addHandler("ERR_UNKNOWNCOMMAND", (cmd) => { /* emit error here */ });`

**Comment by astorije** [comment]
I must be missing something, but that's the reason for this, sorry?

**Comment by MaxLeiter** [comment]
dont understand your comment @astorije; it's a really easy fix that @xPaw commented

**Comment by xPaw** [comment]
@MaxLeiter I think he's missing an explaining what this issue wants.

**Comment by MaxLeiter** [comment]
ah, the error should probably be `ignore: unknown command`, rather than `ignore Unknown command`

**Comment by richrd** [comment]
How about switching it around to be `Unknown command: ignore`? That feels more natural to me.
