### ISSUE TITLE
Hide day markers if there's no messages (accounting for hidden stuff, too)

### ISSUE THREAD

**Issue by Pugabyte** [thelounge/thelounge#813]
![image](https://cloud.githubusercontent.com/assets/12417961/21291397/69bc4904-c4a3-11e6-9ac1-236605d4be03.png)

It believe it isn't hiding them because there are hidden join/quit messages which are turned off in my settings.

**Comment by PugaBear** [comment]
The newline marker should also be addressed in this situation 
![image](https://cloud.githubusercontent.com/assets/12417961/21724748/3df3c01a-d3fb-11e6-9aa3-05a2d8a30f05.png)

**Comment by YaManicKill** [comment]
Yeah, they are both because the joins/parts are hidden in css, not JS. We've had some discussions around that. It'll be done at some point.

**Comment by astorije** [comment]
This requires quite the undertaking. Do we really want to tag this with 2.3.0 considering we don't even have an attempt to do so at the moment?

**Comment by astorije** [comment]
Moving this out of v2.3.0 milestone per discussion with @xPaw as this alone is a lot of work we won't be able to tackle ourselves for this next release.

**Comment by xPaw** [comment]
@Pugabyte can you please test if this is still a problem on master?

**Comment by PolarizedIons** [comment]
The new message marker still appear for me with 'Hide all status messages' selected in the settings, and join/parting with another client. (on 2.5.0-rc.2). Unsure about the date marker, but I assume that would have the issue too
