### ISSUE TITLE
/whois on a person who is not online, results in a "No such server" error

### ISSUE THREAD

**Issue by PolarizedIons** [thelounge/thelounge#864]
I believe this may have been caused by pr #721 because that made a /whois send the nick twice, to get the idle time from the server the user is connected to. This responce is confusing to the user:

    /whois nonexistantuser
    [402] nonexistantuser No such server

Tested on master (d9cde04).

**Comment by astorije** [comment]
Alternative mentioned in #721 was to actually send `/whois nick nick` only when clicking on a nick, not when typing `/whois nick`. Note that this would have had the same consequence when clicking on a nick that quit.

I think the reasonable thing to do here is to treat a `No such server` as a `No such nick` when server == nick. Thoughts?

**Comment by PolarizedIons** [comment]
@astorije that sounds like a good idea, but might be a bit hard to do (from my short little investigation). The irc server sends back a  `ERR_NOSUCHSERVER (402)` instead of a `ERR_NOSUCHNICK (401)` so we don't really have enough information to know when to show a `No such nick` and when to show the real error (`No such server`) 
!()[http://i.imgur.com/JqocZSW.png]

**Comment by astorije** [comment]
Agreed @PolarizedIons, it might be harder than I thought. @xPaw, any idea?

**Comment by astorije** [comment]
I still don't know how to deal with that. @xPaw, what do you think?

**Comment by xPaw** [comment]
I don't think we can as of right now.

**Comment by astorije** [comment]
What would we need to be able to? Can irc-framework be augmented to help with this?

**Comment by richrd** [comment]
I just tested this. On my personal IRC server `InspIRCd-3.3.0-9d4dadba8` and on Quakenet I get the correct response. On freenode it says "No such server". I would say this is a Freenode bug and this should probably be closed.
![image](https://user-images.githubusercontent.com/3417292/71254922-21786a80-2335-11ea-87ca-49a537b2d6a7.png)

**Comment by xnaas** [comment]
Thanks for closing this.

Just for history's sake, I'll log this in here as well:

```
07:49:37 <xnaas> Looking at https://github.com/thelounge/thelounge/issues/864 -- it's ancient and a Freenode-specific issue (just tested on several IRC servers). Surely something like this could just be closed at this point, no? :P
07:51:07 <fnutt> Well... it's still an issue on Freenode though.
07:51:31 <xnaas> But that's on Freenode for not sending the right response. 
07:51:41 <xnaas> Not really thelounge's problem, imo. 
07:51:50 <fnutt> Sure sure. I agree.
07:52:06 <fnutt> Someone mind closing it, please?
07:55:41 <xnaas> Tested on several more servers. Seems to be very hit or miss on which send the right response, but regardless, I still think that's a server issue and not a TL issue. But that's just my opinion. :P
```
