### ISSUE TITLE
collapsible channel list

### ISSUE THREAD

**Issue by realies** [thelounge/thelounge#867]
I find it difficult to navigate when connected to multiple servers and channels. Perhaps collapsing the channel list into a server header would ease that.

> 13:25	realies	anyone up for collapsible server lists?
13:33	MiniDigger	+1
13:33	MiniDigger	make an issue realies
13:34	MiniDigger	when collapsed it should still show new messages and pings, but only on the server label
13:39	realies	MiniDigger, I was thinking that instead of messages amount to be displaying the amount of channels/private messages you've received since the last check

**Comment by MaxLeiter** [comment]
Dupe of #17

**Comment by astorije** [comment]
#17 is different. It is about collapsing the menu itself, while this issue is about collapsing individual networks among the channel list.

**Comment by realies** [comment]
What would be an acceptable layout change for this? Perhaps dynamically oriented arrow that appears upon hovering the server name?

**Comment by realies** [comment]
A dynamically oriented arrow bound to the collapsed state that appears upon hovering or next to the network name, or an collapse/expand option in the network context menu seems like a sensible layout approach for a visual trigger. The state change has to be communicated to and from the back-end, and it has to be propagated to the specific network in the networks section of the user's json file.

**Comment by MaxLeiter** [comment]
Duplicate of #17
