### ISSUE TITLE
`mode` command doesn't show current mode

### ISSUE THREAD

**Issue by drkitty** [thelounge/thelounge#885]
In other IRC clients (like irssi) and according to RFC 2812, sending `/mode <nickname>` with yourself as the target is supposed to show your current mode. Lounge 2.1.0 accepts that command without error, but it doesn't print anything. My guess is that it's just ignoring the server's response.

**Comment by drkitty** [comment]
This might be partly the fault of `irc-framework`. I looked at kiwiirc (which also uses `irc-framework`) and it doesn't show user modes, either, although it does show channel modes.

**Comment by MaxLeiter** [comment]
ping @prawnsalad

**Comment by prawnsalad** [comment]
@drkitty The current version of kiwiirc doesn't use irc-framework.

@MaxLeiter You pinged?

**Comment by MaxLeiter** [comment]
Was unaware kiwi IRC didn't use IRC-fw - so you think this is a Lounge or an IRC-fw issue?

**Comment by drkitty** [comment]
@prawnsalad My bad. I should have looked more closely.
@MaxLeiter I tested with debug mode on and looked at the source code a bit more. As far as I can tell, Lounge properly sends the MODE message and receives the 221 reply, but either the processing logic drops it on the floor or the frontend doesn't support it. I'm willing to keep looking at this, but I can't say I understand the architecture enough to fix it.

**Comment by MaxLeiter** [comment]
It's not implemented in irc-framework: https://github.com/kiwiirc/irc-framework/blob/55fac0cc9c2942f6d23c3a0958c806f3e1031656/src/commands/handlers/user.js#L213

**Comment by YaManicKill** [comment]
Just confirming this also doesn't work for stuff like showing the banlist on channels (/mode #channel +b). Not sure if it's the same issue or not.

**Comment by xPaw** [comment]
Not quite, afaik irc-fw hooks the ban list and sends it as a separate event that we don't handle.

**Comment by YaManicKill** [comment]
I created kiwiirc/irc-framework#102 for this, as it got lost.
