### ISSUE TITLE
set permissions for config.json

### ISSUE THREAD

**Issue by nhooyr** [thelounge/thelounge#900]
On nix, lounge is stored on a readonly file system. At https://github.com/thelounge/lounge/blob/b9047d98a2a8dfd4dd4e8c7e9654de7a69cf5e03/src/command-line/index.js#L23 the directory is created and chmodded to 700 but the file is not chmodded to 644, it is left as 444 so when I open it to edit, my editor says it is read only. Lounge should chmod it explicitly to 644.

**Comment by astorije** [comment]
What do you think of this, @maxpoulin64?

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
