### ISSUE TITLE
User list puts more space between header and section body than between sections

### ISSUE THREAD

**Issue by dgw** [thelounge/thelounge#909]
A visual annoyance that's been bothering me for a while now. Occurs on all four default themes shipped with 2.2.0 (Example, Crypto, Morning, and Zenburn).

The user list looks like this, roughly:

````
Owners
____

user1
user2

Administrators
____

user3

Operators
____

user4
user5
user6
<etc.>
````

This does not visually group the section headers with the content of each section correctly, IMO. The subtle line separating the heading from the rest of the section puts too much space in, and the headings visually group with the section before them instead of the section they describe.

I'd say putting the line between sections (instead of between the headers and their section bodies) would fix the apparent grouping. @astorije, I know you like to weigh in on UI stuff. Do you see what I'm talking about, or should I prepare a screenshot or two to illustrate? :)

**Comment by astorije** [comment]
Sounds reasonable to me!

**Comment by astorije** [comment]
@dgw, would you like to give a shot at this? That would be great! :)
