### ISSUE TITLE
accessibility/feature request: Add aria live region role to the list of messages

### ISSUE THREAD

**Issue by lilmike** [thelounge/thelounge#936]
Hi,
Just a quick feature request, if the aria live region role could be added to the messages from the channel you're currently in, that would be great, as then most screen readers that support the aria standard will automatically read incoming messages.
-Michael.

**Comment by chrys87** [comment]
that would be awsome :)

aria-relevant="additions"

is maybe what is needed in the messagebox

**Comment by astorije** [comment]
Hey @chrys87 and @lilmike! I would love for The Lounge to be more accessible!

These accessibility-related tickets could really use some external help, if someone wants to give it a shot.

**Comment by chrys87** [comment]
just let you guys know. 
byside of the problems we use it for our linux-a11y.org plattform. We want to bring impaired people together.
awsome software! keep going!

http://irc.linux-a11y.org

**Comment by xPaw** [comment]
@chrys87 Would you mind testing this change? I don't use a11y software, so I can't tell how well it works.

```diff
diff --git a/client/views/chat.tpl b/client/views/chat.tpl
index 9ccb639..28d27aa 100644
--- a/client/views/chat.tpl
+++ b/client/views/chat.tpl
@@ -17,7 +17,7 @@
                                Show older messages
                        </button>
                </div>
-               <div class="messages"></div>
+               <div class="messages" role="log" aria-live="polite" aria-relevant="additions"></div>
        </div>
        <aside class="sidebar">
                <div class="users"></div>
```

**Comment by chrys87** [comment]
Howdy,
Woe sweet :) sure i give a shot. I m currently not at home and will likely just arrive on monday but i will test it and give you feedback my frind.
Thanks for your hard work!
cheers chrys

**Comment by chrys87** [comment]
Howdy,

i have some trouble with testing.
i use a docker from here
https://github.com/thelounge/lounge/releases
(is that the offical dockerfile?)
for lazy testing ;) i just want to change this file in my docker container. but i recognize there is no folder "client/view". i can see any other folder from master in the folder "client" but not "view".
i use the version 2.2.1 (since 2.2.2 fails starting cause by an missing port variable -> i may report this on an separate place  )

can you tell me what happens here? and why this folder is missing there?

**Comment by MaxLeiter** [comment]
the folder is `views`, does that exist?

**Comment by chrys87** [comment]
Damn,
you are totaly right! sorry for the noise, i migrate the patch and test it on:
https://irc.linux-a11y.org/
and give you feedback than. Thanks! sorry again for the noise..

**Comment by xPaw** [comment]
@chrys87 You need to run `npm run build` after editing the file for changes to work.

**Comment by xPaw** [comment]
@chrys87 Have you had a chance to test this?

**Comment by chrys87** [comment]
Sorry not yet. 
a lot of stuff is going on in biz :).
i try to hurry up with testing.

**Comment by xPaw** [comment]
Hi @chrys87, are you still using Lounge and did you get a chance to try that change out?
