### ISSUE TITLE
Implement more user friendly IRC config defaults

### ISSUE THREAD

**Issue by bnvk** [thelounge/thelounge#962]
*Issue ported over from erming/shout#412*

A substantial usability problems with IRC for many non-technical users is the the levels of abstraction and possibilities of "multiple networks" each with "multiple channels" and the corresponding joining /  leaving of these. Currently Lounge implements the full IRC functionality- which is great, the goal is not to take this away but offer robust defaults that make things easier. Additionally this should support public as well as private instances. 

Here is a proposal towards modifying the config file to achieve the following goals:

- [ ] Lounge admin specifies global joining & leaving of Networks 
- [ ] Lounge admin specifies default Network that CANNOT be unjoined (specify in config)
- [ ] Lounge admin specifies global joining & leaving of Channels 
- [ ] Lounge admin specifies default Channels that CANNOT be unjoined (specify in config)

A proposed change to the `config.json` file to achieve global settings would be:

```
networkActions: false,
channelsActions: true 
```

And on the defaults would look like:

```
defaults: {
  "name": "Freenode",
  "host": "irc.freenode.org",
  "port": "6697",
  "tls": true,
  "username": "lil-b",
  "realname": "Lil B Man",
  "nick": "lil-b",
  "disconnect": false,
  "channels": [{
      "name": "#opensourcedesign",
      "quitable": false
    },{
      "name": "#lounge",
      "quitable": false
  }]
}
```

It would then be up to the theme to determine what to do with the settings in the config file! Some themes might ignore them, others might offer robust options to a user.

**Comment by bnvk** [comment]
Oh, pinging @ZacharyDuBois and @Xe who once expressed interest in helping with this :)

**Comment by ZacharyDuBois** [comment]
@bnvk I've added it to my list. I'll have to take a look as well when I get a chance. Right now I am just running a restricted KiwiIRC instance to get by. It isn't often I need a web client.

**Comment by Xe** [comment]
Please do not ping me about things like this. I have no interest in supporting this project.

**Comment by xPaw** [comment]
The restrictions you are suggesting is not something our client can control (e.g. there's many different ways to send a RAW irc commands).

The client can be locked to a single network by using `lockNetwork` config property. Default channels to join can also be set.
